
# ===== 계정 관리 (U-01~U-06) =====
DYN.update({
 'U-01': {
   'easy': '은행에서 <b>금고실 문이 현관 바로 앞에 있고, 지점장 이름만 대면 열리는 것</b>과 같습니다. root 원격 로그인을 허용하면 최고 권한 문이 인터넷이라는 현관 바로 앞에 놓인 셈입니다. 문 하나(일반 계정)를 더 거치게 하면 공격자는 두 겹을 뚫어야 합니다.',
   'attack_label': '공격자가 인터넷에서 root 계정 무차별 대입을 시도한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 SSH로 root 직접 로그인 시도'],
     ['prompt', 'attacker$ hydra -l root -P rockyou.txt ssh://victim.com'],
     ['bad', '[ATTEMPT] target 22 - login "root" - pass "admin123"'],
     ['bad', '[22][ssh] host: victim.com  login: root   password: toor'],
     ['bad', '>> 5번째 시도 만에 root 로그인 성공 — 곧바로 최고 권한 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 즉시 최고 권한', 'desc': 'root 직접 로그인이 열려 있어 비밀번호 한 번이 뚫리는 순간 시스템 전체가 넘어갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 공격을 안전한 설정에서 시도'],
     ['prompt', 'attacker$ hydra -l root -P rockyou.txt ssh://victim.com'],
     ['good', '[ATTEMPT] target 22 - login "root" - pass "admin123"'],
     ['good', '>> [ssh] host: victim.com   login: root   password: (거부됨)'],
     ['warn', '>> root 계정은 애초에 원격 직접 로그인 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — root 원격 로그인 금지', 'desc': 'PermitRootLogin no로 root 직접 접속이 불가하여 공격 표면이 한 겹 줄어듭니다.'},
 },
 'U-02': {
   'easy': '사무실 출입 비밀번호를 <b>4자리로 6개월째 안 바꾸는 것</b>과 같습니다. 짧고 오래 쓴 비밀번호는 복사해 둔 사람이 언제든 들어올 수 있죠. 90일마다 8자 이상으로 강제하면 훔친 번호의 수명이 짧아집니다.',
   'attack_label': '공격자가 오래된·단순한 비밀번호 목록으로 로그인을 시도한다',
   'attack_vuln': [
     ['cmt', '# 유출 추정 목록(3년 묵은 번호)으로 시도'],
     ['prompt', 'attacker$ ssh user01@victim.com'],
     ['', 'password: user2018'],
     ['bad', '>> PASS_MAX_DAYS=99999 — 3년간 변경 없음 확인'],
     ['bad', '>> Last login: 접속 성공 — 오래된 비밀번호 그대로 유효'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 낡은 비밀번호 통과', 'desc': '주기·복잡도 정책이 없어 몇 년 된 약한 비밀번호가 그대로 통과합니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 오래된 비밀번호로 시도'],
     ['prompt', 'attacker$ ssh user01@victim.com'],
     ['good', '>> 90일 주기 강제로 이미 변경된 비밀번호'],
     ['good', '>> Authentication failed (Permission denied)'],
     ['warn', '>> minlen=8 + 조합 강제로 사전 대입도 어려움'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 주기·복잡도 정책', 'desc': '90일 주기와 8자 이상 복잡도 강제로 오래된·단순한 비밀번호가 무효화됩니다.'},
 },
 'U-03': {
   'easy': '출입증을 몇 번 틀려도 <b>경비가 아무도 막지 않는 자동문</b>과 같습니다. 공격자는 밤새 번호를 하나씩 눌러 볼 수 있죠. 5번 틀리면 문을 잠그는 규칙이 있어야 합니다.',
   'attack_label': '공격자가 자동화 스크립트로 비밀번호를 계속 시도한다',
   'attack_vuln': [
     ['cmt', '# 무차별 대입 스크립트 실행 (잠금 정책 없음)'],
     ['prompt', 'attacker$ for p in $(cat dict.txt); do ssh user01@v $p; done'],
     ['', '시도 3,412회 ... 계속 진행 중'],
     ['bad', '>> 실패 제한 없음 — 시도 무제한 허용'],
     ['bad', '>> 시도 8,905회: password "qwer1234!" 로그인 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무한 대입', 'desc': '실패 임계값이 없어 공격자가 몇 번이든 시도하다 결국 비밀번호를 찾아냅니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 스크립트를 잠금 정책 하에서 실행'],
     ['prompt', 'attacker$ for p in $(cat dict.txt); do ssh user01@v $p; done'],
     ['good', '>> 5회 실패: 계정 잠금 (pam_faillock deny=5)'],
     ['good', '>> 이후 모든 시도 즉시 거부 — 해제는 관리자만'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 계정 자동 잠금', 'desc': '5회 실패 시 계정이 잠기고 600초 유지되어 무차별 대입이 원천 차단됩니다.'},
 },
 'U-04': {
   'easy': '모든 사원이 읽을 수 있는 <b>게시판에 비밀번호 전체 명단을 붙여 둔 것</b>과 같습니다. 원래 해시는 잠긴 서랍(shadow)에 있어야 하는데, passwd 파일에 박제되면 아무나 몰래 사본을 들고 가 두고두고 풀어봅니다.',
   'attack_label': '공격자가 일반 권한으로 해시 목록을 덤프해 오프라인으로 푼다',
   'attack_vuln': [
     ['cmt', '# 일반 사용자 권한으로 passwd 확인'],
     ['prompt', 'user01$ head -3 /etc/passwd'],
     ['bad', 'root:x4TgZ9mQ2...:0:0:root:/root:/bin/bash'],
     ['bad', '>> 해시가 통째로 노출 — 파일을 통째로 복사'],
     ['bad', '>> john the ripper: user02 = summer2024 (해독 완료)'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 전 계정 해시 유출', 'desc': '해시가 모든 사용자에게 읽혀 오프라인 무차별 대입으로 계정들이 하나씩 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 passwd 확인'],
     ['prompt', 'user01$ head -3 /etc/passwd'],
     ['good', 'root:x:0:0:root:/root:/bin/bash'],
     ['good', '>> x 표시 — 실제 해시는 /etc/shadow(400, root만)'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 해시 격리', 'desc': 'pwconv로 해시가 shadow로 분리되어 일반 사용자가 읽을 수 없습니다.'},
 },
 'U-05': {
   'easy': '사원증 번호가 <b>사장과 똑같은 아르바이트생</b>이 있는 상황입니다. 시스템은 번호(UID 0)만 보고 전원에게 사장 권한을 줍니다. 감사 로그에도 누가 사장인지 구분되지 않죠.',
   'attack_label': '공격자가 몰래 심어 둔 UID 0 계정으로 root 권한에 들어온다',
   'attack_vuln': [
     ['cmt', '# 침해 후 심어둔 백도어 계정 사용'],
     ['prompt', 'attacker$ ssh sysadm@victim.com'],
     ['', 'password: ********'],
     ['bad', '>> id: uid=0(root) gid=0(root) groups=0(root)'],
     ['bad', '>> 이름은 sysadm이지만 권한은 root와 동일 — 은신 유지'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 숨은 최고 권한', 'desc': 'UID 0 계정이 여럿이면 감사 로그에서 침입자 계정이 root처럼 위장됩니다.'},
   'attack_secure': [
     ['cmt', '# 점검: UID 0 계정 나열'],
     ['prompt', '# awk -F: "$3==0 {print $1}" /etc/passwd'],
     ['good', 'root'],
     ['warn', '>> UID 0은 root 단 하나 — 백도어 계정 존재하지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '점검 통과 — root 단일', 'desc': 'UID 0이 root 하나뿐이라 권한 위장·은신 경로가 없습니다.'},
 },
 'U-06': {
   'easy': '아무 직원이나 <b>사장실 열쇠 구멍에 번호를 계속 입력해 보는 것</b>을 막는 규칙입니다. su(사장실 입장)는 승인된 관리자 그룹(wheel)만 시도할 수 있어야 하고, 시도 기록도 남아야 합니다.',
   'attack_label': '일반 사용자 계정을 뚫은 공격자가 su로 root 전환을 시도한다',
   'attack_vuln': [
     ['cmt', '# 탈취한 일반 계정에서 root로 전환 시도'],
     ['prompt', 'user01$ su - root'],
     ['', 'Password: (대입 시도 1...) Password: (대입 시도 2...)'],
     ['bad', '>> su 사용 제한 없음 — 누구나 시도 가능'],
     ['bad', '>> 6번째 시도: 전환 성공 — root 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 권한 상승', 'desc': 'su가 전원에게 열려 있어 일반 계정만 뚫려도 root까지 올라탈 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 su 시도'],
     ['prompt', 'user01$ su - root'],
     ['good', '>> pam_wheel: user01은 wheel 그룹 아님 — 거부'],
     ['good', '>> 시도 기록이 /var/log/secure에 남아 탐지됨'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — wheel 그룹 제한', 'desc': 'su가 승인된 관리자(wheel)에게만 허용되고 시도 자체가 로그로 남습니다.'},
 },
})
