
# ===== D-01~D-26 보강 (기본계정·타임아웃·불필요권한·접근통제·감사/패치) =====
SPECS += [
D('D-01', '기본 계정 관리 (기본 계정 잠금·비밀번호 변경)', '👤', '상',
  'Oracle 설치 시 생성되는 기본 계정(SCOTT, OUTLN, XS$NULL 등)이 잠금 없이 남아 있으면 널리 알려진 기본 비밀번호로 바로 접속됩니다. 사용하지 않는 기본 계정은 잠그거나 삭제해야 합니다.',
  [('cmt', '-- 기본 계정 상태 확인'), ('prompt', 'SQL> '), ('', "SELECT username, account_status FROM dba_users WHERE username IN ('SCOTT','OUTLN','HR');"),
   ('bad', 'SCOTT   OPEN'), ('bad', 'OUTLN   OPEN'),
   ('warn', '→ 기본 계정이 잠금 없이 열려 있음 (취약)')],
  [('cmt', '-- 기본 계정 잠금·삭제'), ('prompt', 'SQL> '), ('', 'ALTER USER SCOTT ACCOUNT LOCK; DROP USER OUTLN CASCADE;'),
   ('good', 'User altered. / User dropped.'),
   ('good', '→ 미사용 기본 계정 제거 (양호)')],
  ['사용하지 않는 기본 계정은 <code>ACCOUNT LOCK</code> 또는 삭제합니다.',
   '유지하는 계정은 기본 비밀번호를 즉시 변경합니다.',
   '신규 설치 후 기본 계정 목록·상태를 점검표로 관리합니다.'],
  ['미사용 기본 계정이 잠금/삭제되었는가', '기본 비밀번호가 모두 변경되었는가'],
  '데이터베이스 > 기본 계정 관리'),

D('D-08', '세션 타임아웃 설정 (유휴 세션 종료)', '⌛', '중',
  'DB 세션이 오랫동안 방치되면 자리 비운 동안 계정 도용·화면 캡처·무단 쿼리의 기회가 됩니다. IDLE_TIME으로 유휴 세션을 자동 종료해야 합니다.',
  [('cmt', '-- 유휴 세션 제한 확인'), ('prompt', 'SQL> '), ('', "SELECT limit FROM dba_profiles WHERE resource_name='IDLE_TIME';"),
   ('bad', 'UNLIMITED'), ('warn', '→ 방치 세션이 무제한 유지 (취약)')],
  [('cmt', '-- 유휴 세션 자동 종료 설정'), ('prompt', 'SQL> '), ('', 'ALTER PROFILE DEFAULT LIMIT IDLE_TIME 15;  -- 15분'),
   ('good', 'Profile altered.'),
   ('good', '>> 15분 유휴 시 세션 자동 종료 (양호)')],
  ['프로파일에 <code>IDLE_TIME</code>(예: 15분)을 설정합니다.',
   '종료된 세션의 리소스 회수를 위해 <code>RESOURCE_LIMIT=TRUE</code>를 확인합니다.',
   '장기 배치 작업은 별도 프로파일로 예외 관리합니다.'],
  ['IDLE_TIME이 제한(예: 15분)되어 있는가', '예외 작업 프로파일이 문서화되어 있는가'],
  '데이터베이스 > 세션 타임아웃'),

D('D-10~12', '불필요한 계정·권한 제거 (PUBLIC 권한 회수)', '🧹', '상',
  '사용하지 않는 계정이 남아 있거나, 모든 사용자(PUBLIC)에 과도한 권한이 부여되면 최소 권한 원칙이 무너집니다. 미사용 계정 잠금과 PUBLIC 권한 회수가 필요합니다.',
  [('cmt', '-- PUBLIC 부여 권한·미사용 계정 확인'), ('prompt', 'SQL> '), ('', "SELECT table_name, privilege FROM dba_tab_privs WHERE grantee='PUBLIC' AND table_name LIKE 'UTL%';"),
   ('bad', 'UTL_FILE    EXECUTE'), ('bad', 'UTL_HTTP    EXECUTE'),
   ('bad', 'TEST_USER   (90일 미접속, OPEN)'),
   ('warn', '→ 전 계정에 강력 패키지 실행 권한 + 유령 계정 (취약)')],
  [('cmt', '-- PUBLIC 권한 회수·계정 잠금'), ('prompt', 'SQL> '), ('', 'REVOKE EXECUTE ON UTL_FILE FROM PUBLIC; REVOKE EXECUTE ON UTL_HTTP FROM PUBLIC;'),
   ('good', 'Revoke succeeded.  /  ALTER USER TEST_USER ACCOUNT LOCK;'),
   ('good', '→ 필요한 사용자에게만 권한 부여 (양호)')],
  ['<code>UTL_FILE</code>, <code>UTL_HTTP</code>, <code>UTL_TCP</code> 등 강력 패키지의 PUBLIC 권한을 회수합니다.',
   '90일 미접속 계정 등 미사용 계정은 잠금·삭제합니다.',
   '부여 권한은 Role로 묶어 최소한으로 관리합니다.'],
  ['PUBLIC에 과도한 권한이 없는가', '미사용 계정이 잠금/삭제되었는가', '권한 부여 이력이 관리되는가'],
  '데이터베이스 > 불필요한 계정·권한 제거', '06_db-d10-d12.html'),

D('D-18~19', 'DB 접근 통제·네트워크 암호화', '📡', '상',
  'DB가 모든 IP의 접속을 받고 통신이 평문이면, 내부망 스니핑으로 계정·데이터가 그대로 노출됩니다. 허용 호스트 제한(TCP.VALIDNODE_CHECKING)과 네이티브 암호화가 필요합니다.',
  [('cmt', '-- sqlnet 접근 제한·암호화 확인'), ('prompt', 'SQL> '), ('', 'cat $ORACLE_HOME/network/admin/sqlnet.ora'),
   ('bad', '(TCP.VALIDNODE_CHECKING 항목 없음 — 전 IP 허용)'),
   ('bad', '(암호화 설정 없음 — 평문 통신)'),
   ('warn', '→ 스니핑·외부 접속 노출 (취약)')],
  [('cmt', '-- 허용 호스트·암호화 설정'), ('prompt', 'SQL> '), ('', 'TCP.VALIDNODE_CHECKING=YES / TCP.INVITED_NODES=(app10, was20)'),
   ('good', 'SQLNET.ENCRYPTION_SERVER=REQUIRED / SQLNET.CRYPTO_CHECKSUM_SERVER=REQUIRED'),
   ('good', '→ 허용 호스트만 + 통신 암호화 (양호)')],
  ['<code>sqlnet.ora</code>에 <code>TCP.VALIDNODE_CHECKING=YES</code>와 허용 노드 목록을 설정합니다.',
   '<code>SQLNET.ENCRYPTION_SERVER=REQUIRED</code> 등 네이티브 암호화·무결성을 강제합니다.',
   '방화벽 정책과 함께 이중으로 WAS·관리망만 접속을 허용합니다.'],
  ['접속 가능 호스트가 제한되어 있는가', '통신 구간이 암호화되어 있는가'],
  '데이터베이스 > 접근 통제·네트워크 암호화', '06_db-d18-d19.html'),

D('D-25~26', '감사 로그 관리·보안 패치 적용', '🛠️', '상',
  '감사(Audit) 기능이 꺼져 있으면 사고 추적이 불가능하고, 최신 보안 패치(CPU/RU) 미적용 DB는 공개된 취약점으로 그대로 뚫립니다. 감사 정책과 정기 패치가 함께 운영되어야 합니다.',
  [('cmt', '-- 감사 기능·버전 확인'), ('prompt', 'SQL> '), ('', 'SHOW PARAMETER audit_trail'),
   ('bad', 'audit_trail  FALSE (감사 비활성)'),
   ('bad', 'BANNER: 19.3.0.0  (최신 RU 미적용 — 2년 경과)'),
   ('warn', '→ 침해 추적 불가 + 알려진 취약점 방치 (취약)')],
  [('cmt', '-- 감사 활성화·패치 적용'), ('prompt', 'SQL> '), ('', 'ALTER SYSTEM SET audit_trail=DB,EXTENDED SCOPE=SPFILE;'),
   ('good', '>> 권한 변경·로그인 실패 감사 기록 시작'),
   ('good', '>> 최신 Release Update 적용 완료 (분기 CPU 주기)'),
   ('good', '→ 추적 가능 + 알려진 구멍 제거 (양호)')],
  ['<code>audit_trail</code>을 활성화하고 로그인·권한 변경·민감 테이블 접근을 감사합니다.',
   '분기별 CPU/RU 패치를 변경관리 절차에 따라 적용합니다.',
   '감사 로그는 별도 저장소로 이관·보관하여 변조를 방지합니다.'],
  ['감사 기능이 활성화되어 있는가', '감사 로그가 안전하게 보관되는가', '최신 보안 패치가 적용되어 있는가'],
  '데이터베이스 > 감사 로그·패치 관리', '06_db-d25-d26.html'),
]
