
# ===== 계정 관리 (U-01~U-06) =====
SPECS += [
U('U-01', 'root 원격 접속 제한', '🚫', '상',
  'root 계정으로 telnet·ssh 등 원격에서 직접 로그인이 허용되면, 비밀번호 한 번만 뚫리면 곧바로 최고 권한을 내주게 됩니다. 일반 계정 로그인 후 sudo로 승격하는 구조로 관리해야 합니다.',
  [('cmt', '# root 원격 로그인 허용 여부 확인'), ('prompt', '# '), ('', 'grep -i permitrootlogin /etc/ssh/sshd_config'),
   ('bad', 'PermitRootLogin yes'), ('warn', '→ 원격에서 root 직접 로그인 허용 (취약)')],
  [('cmt', '# root 직접 로그인 차단 후 재시작'), ('prompt', '# '), ('', 'sed -i "s/PermitRootLogin yes/PermitRootLogin no/" /etc/ssh/sshd_config'),
   ('good', 'PermitRootLogin no'), ('good', '→ 개인 계정 + sudo로만 관리 (양호)')],
  ['<code>sshd_config</code>에 <code>PermitRootLogin no</code> 설정 후 sshd를 재시작합니다.',
   'telnet은 비활성화하고 SSH만 사용합니다.',
   '관리자 작업은 개인 계정 로그인 후 <code>sudo</code>로 수행하고 감사로그를 남깁니다.'],
  ['root의 원격 직접 로그인이 차단되어 있는가', 'telnet 등 평문 원격 서비스가 비활성화되었는가', '관리 작업이 sudo로 기록되는가'],
  '계정 관리 > root 원격접속 제한', '계정 관리'),

U('U-02', '비밀번호 관리정책 설정 (복잡도·주기)', '🔢', '중',
  '비밀번호 최대 사용기간과 복잡도(길이·숫자·특수문자 조합)가 설정되지 않으면 유추·무차별 대입에 오래 노출됩니다. login.defs와 pwquality로 정책을 강제해야 합니다.',
  [('cmt', '# 비밀번호 정책 확인'), ('prompt', '# '), ('', 'grep PASS_MAX_DAYS /etc/login.defs'),
   ('bad', 'PASS_MAX_DAYS  99999'), ('bad', 'pwquality: minlen=6 (기본값)'),
   ('warn', '→ 사실상 무기한·약한 비밀번호 허용 (취약)')],
  [('cmt', '# 주기·복잡도 설정'), ('prompt', '# '), ('', 'PASS_MAX_DAYS 90 / PASS_MIN_DAYS 7 / PASS_WARN_AGE 7'),
   ('good', '/etc/security/pwquality.conf: minlen=8 dcredit=-1 ucredit=-1 ocredit=-1'),
   ('good', '→ 90일 주기·8자 이상 복잡도 강제 (양호)')],
  ['<code>/etc/login.defs</code>에 최대 90일·최소 7일·만료 7일 전 경고를 설정합니다.',
   '<code>pwquality.conf</code>로 길이 8자 이상, 숫자·대문자·특수문자 조합을 강제합니다.',
   '기존 계정에도 정책이 적용되는지 <code>chage -l</code>로 확인합니다.'],
  ['비밀번호 최대 사용기간이 90일 이하로 설정되었는가', '복잡도(길이·조합)가 강제되는가'],
  '계정 관리 > 비밀번호 정책(복잡도·주기)', '계정 관리'),

U('U-03', '계정 잠금 임계값 설정', '⏳', '중',
  '로그인 실패 횟수 제한이 없으면 공격자가 무한히 비밀번호를 시도할 수 있습니다. 일정 횟수 실패 시 계정을 잠그고 해제 정책을 함께 운영해야 합니다.',
  [('cmt', '# 계정 잠금 정책 확인'), ('prompt', '# '), ('', 'grep pam_faillock /etc/pam.d/system-auth'),
   ('bad', '(출력 없음 — 잠금 설정 없음)'), ('warn', '→ 무차별 대입 무제한 시도 가능 (취약)')],
  [('cmt', '# 5회 실패 시 잠금 설정'), ('prompt', '# '), ('', 'auth required pam_faillock.so deny=5 unlock_time=600'),
   ('good', '>> faillog: user5  실패 5회 → 계정 잠금'),
   ('good', '→ 무차별 대입 5회에 자동 차단 (양호)')],
  ['<code>pam_faillock</code>(또는 pam_tally2)로 <code>deny=5</code>, <code>unlock_time</code>을 설정합니다.',
   'root 계정도 잠금 대상에 포함하는지 확인합니다.',
   '잠긴 계정은 보안 담당자 확인 후 <code>faillock --reset</code>으로 해제합니다.'],
  ['일정 실패 횟수(예: 5회) 초과 시 계정이 잠기는가', '잠금 해제 절차가 문서화되어 있는가'],
  '계정 관리 > 계정 잠금 임계값', '계정 관리'),

U('U-04', '비밀번호 파일 보호 (shadow 분리)', '🗝️', '상',
  '비밀번호 해시가 /etc/passwd에 그대로 들어 있으면 모든 사용자가 읽을 수 있어 오프라인 무차별 대입의 재료가 됩니다. 해시를 /etc/shadow로 분리·보호해야 합니다.',
  [('cmt', '# passwd에 해시가 남아 있는지 확인'), ('prompt', '# '), ('', 'head -2 /etc/passwd'),
   ('bad', 'root:x4TgZ9...:0:0:root:/root:/bin/bash'),
   ('warn', '→ 해시가 전 사용자에게 노출 (취약: pwunconv 상태)')],
  [('cmt', '# shadow로 분리·권한 강화'), ('prompt', '# '), ('', 'pwconv && ls -l /etc/shadow'),
   ('good', '-r-------- 1 root root 1024 /etc/shadow'),
   ('good', '→ 해시는 root만 접근 가능 (양호)')],
  ['<code>pwconv</code>로 해시를 <code>/etc/shadow</code>로 이관합니다.',
   '<code>chmod 400 /etc/shadow</code>로 root만 읽도록 제한합니다.',
   '주기적으로 <code>pwck</code>로 passwd·shadow 일관성을 점검합니다.'],
  ['해시가 /etc/shadow로 분리되었는가', '/etc/shadow 권한이 400 이하로 제한되었는가'],
  '계정 관리 > 비밀번호 파일 보호', '계정 관리'),

U('U-05', 'UID 0 계정 확인', '🪪', '상',
  'root와 UID가 같은(0) 계정이 여러 개면 각각이 모두 최고 권한이며 감사 구멍이 됩니다. UID 0은 root 단 하나여야 합니다.',
  [('cmt', '# UID 0 계정 조회'), ('prompt', '# '), ('', 'awk -F: "$3==0 {print $1}" /etc/passwd'),
   ('bad', 'root'), ('bad', 'toor  /  sysadm'),
   ('warn', '→ root 외 UID 0 계정 존재 (취약)')],
  [('cmt', '# 불법 UID 0 계정 정리'), ('prompt', '# '), ('', 'usermod -u 1500 toor && awk -F: "$3==0" /etc/passwd'),
   ('good', 'root'),
   ('good', '→ UID 0은 root만 존재 (양호)')],
  ['<code>awk -F: "$3==0" /etc/passwd</code>로 UID 0 계정을 주기적으로 점검합니다.',
   'root 외 UID 0 계정은 UID를 변경하거나 불필요 시 삭제합니다.',
   '백업 계정·벤더용 계정이 UID 0으로 만들어지지 않았는지 확인합니다.'],
  ['UID 0 계정이 root 하나뿐인가', '점검 결과가 감사 기록으로 남는가'],
  '계정 관리 > UID 0 계정 관리', '계정 관리'),

U('U-06', 'su 기능 제한 (wheel 그룹)', '🔐', '중',
  '모든 사용자가 su로 root 전환을 시도할 수 있으면 무차별 대입·권한 탈취의 표면이 넓어집니다. wheel 그룹 등 승인된 관리자만 su를 사용할 수 있게 제한해야 합니다.',
  [('cmt', '# su 사용 제한 확인'), ('prompt', '# '), ('', 'grep pam_wheel /etc/pam.d/su'),
   ('bad', '(주석 처리됨 — 누구나 su 시도 가능)'), ('warn', '→ 전 사용자 su 시도 허용 (취약)')],
  [('cmt', '# wheel 그룹만 su 허용'), ('prompt', '# '), ('', 'auth required pam_wheel.so use_uid'),
   ('good', 'usermod -aG wheel admin01'),
   ('good', '→ 승인된 관리자만 su 가능 (양호)')],
  ['<code>/etc/pam.d/su</code>에 <code>pam_wheel.so use_uid</code>를 활성화합니다.',
   '관리자 계정만 <code>wheel</code> 그룹에 등록합니다.',
   'su 사용 이력이 <code>/var/log/secure</code>에 기록되는지 확인합니다.'],
  ['su 사용이 wheel 그룹으로 제한되었는가', 'su 성공/실패 로그가 남는가'],
  '계정 관리 > su 사용 제한', '계정 관리'),

# ===== 파일 및 디렉터리 관리 (U-14~U-28) =====
U('U-14', 'root 홈 디렉토리 및 PATH 설정', '🏠', '중',
  'root 홈 디렉터리 권한이 느슨하면 .bashrc 등 시작 파일을 변조해 root 셸 명령을 가로챌 수 있습니다. 또한 PATH에 현재 디렉터리(.)가 있으면 악성 명령을 실행하게 됩니다.',
  [('cmt', '# root 홈 권한·PATH 확인'), ('prompt', '# '), ('', 'ls -ld /root && echo $PATH'),
   ('bad', 'drwxr-xr-x /root'),
   ('bad', 'PATH=.:/usr/bin:/bin  ← 현재 디렉터리 포함'),
   ('warn', '→ 시작 파일 변조·명령 가로채기 가능 (취약)')],
  [('cmt', '# 권한 강화·PATH 정리'), ('prompt', '# '), ('', 'chmod 700 /root'),
   ('good', 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'),
   ('good', '→ 홈 보호·경로에서 . 제거 (양호)')],
  ['<code>chmod 700 /root</code>으로 root 홈 디렉터리를 보호합니다.',
   'root와 사용자의 PATH에서 <code>.</code>(현재 디렉터리)를 제거합니다.',
   '<code>.bashrc</code>, <code>.bash_profile</code> 등 시작 파일 권한을 점검합니다.'],
  ['root 홈 디렉터리 권한이 700인가', 'PATH에 현재 디렉터리(.)가 없는가'],
  '파일 및 디렉터리 관리 > root 홈 디렉터리 및 PATH', '파일 및 디렉터리 관리'),

U('U-15', '파일·디렉터리 소유자 설정', '🧾', '하',
  '소유자·소유그룹이 없는(삭제된 계정의) 파일이 남아 있으면 권한 공백이 생기고 악용될 수 있습니다. 주기적으로 찾아 소유자를 지정하거나 제거해야 합니다.',
  [('cmt', '# 소유자 없는 파일 검색'), ('prompt', '# '), ('', 'find / -nouser -o -nogroup 2>/dev/null'),
   ('bad', '/var/spool/mail/ghost  (소유 계정 삭제됨)'),
   ('bad', '/opt/legacy/bin/tool  (그룹 없음)'),
   ('warn', '→ 소유자 없는 파일 방치 (취약)')],
  [('cmt', '# 소유자 재지정 또는 삭제'), ('prompt', '# '), ('', 'chown root:root /opt/legacy/bin/tool'),
   ('good', '>> find / -nouser -o -nogroup  → (출력 없음)'),
   ('good', '→ 모든 파일의 소유자 확인됨 (양호)')],
  ['퇴직·삭제 계정 소유 파일을 <code>find / -nouser -o -nogroup</code>으로 점검합니다.',
   '필요한 파일은 소유자를 재지정하고, 불필요한 파일은 삭제합니다.',
   '계정 삭제 절차에 소유 파일 정리 단계를 포함합니다.'],
  ['소유자/소유그룹 없는 파일이 없는가', '계정 삭제 시 파일 정리 절차가 운영되는가'],
  '파일 및 디렉터리 관리 > 소유자 없는 파일 제거', '파일 및 디렉터리 관리'),

U('U-16', '/etc/passwd 파일 권한 설정', '📄', '중',
  '/etc/passwd는 계정 목록·셸 정보를 담는 핵심 파일로, 일반 사용자가 수정할 수 있으면 공격자가 계정을 추가합니다. 644(root 소유)로 유지해야 합니다.',
  [('cmt', '# passwd 권한 확인'), ('prompt', '# '), ('', 'ls -l /etc/passwd'),
   ('bad', '-rw-rw-rw- 1 root root /etc/passwd'),
   ('warn', '→ 일반 사용자 수정 가능 (취약: 계정 추가 가능)')],
  [('cmt', '# 권한 조정'), ('prompt', '# '), ('', 'chmod 644 /etc/passwd'),
   ('good', '-rw-r--r-- 1 root root /etc/passwd'),
   ('good', '→ root만 수정, 전원 읽기 (양호)')],
  ['<code>chmod 644 /etc/passwd</code>, 소유자는 <code>root:root</code>로 유지합니다.',
   '무결성 점검 도구(AIDE 등)로 변경 이력을 모니터링합니다.'],
  ['/etc/passwd 권한이 644 이하인가', '소유자가 root인가', '무결성 점검 대상에 포함되었는가'],
  '파일 및 디렉터리 관리 > /etc/passwd 권한', '파일 및 디렉터리 관리'),

U('U-17', '시스템 시작 스크립트 권한 설정', '🚀', '중',
  '/etc/rc.d 등 부팅 스크립트를 일반 사용자가 수정할 수 있으면, 재부팅 시 원하는 명령이 root 권한으로 실행됩니다. root 소유 750 이하로 제한해야 합니다.',
  [('cmt', '# 시작 스크립트 권한 확인'), ('prompt', '# '), ('', 'ls -l /etc/rc.d/init.d | head -3'),
   ('bad', '-rwxrwxrwx 1 root root ... network'),
   ('warn', '→ 부팅 스크립트 변조 가능 (취약: 재부팅 시 악성코드 실행)')],
  [('cmt', '# 권한 조정'), ('prompt', '# '), ('', 'chmod -R 750 /etc/rc.d/init.d'),
   ('good', '-rwxr-x--- 1 root root ... network'),
   ('good', '→ root만 수정·실행 (양호)')],
  ['<code>/etc/rc.d</code> 하위를 root 소유 <code>750</code> 이하로 설정합니다.',
   'systemd 환경은 유닛 파일(<code>/etc/systemd/system</code>) 권한도 함께 점검합니다.',
   '변경 이력을 무결성 도구로 추적합니다.'],
  ['시작 스크립트가 root 소유 750 이하인가', '비정상 변경 감지 체계가 있는가'],
  '파일 및 디렉터리 관리 > 시작 스크립트 권한', '파일 및 디렉터리 관리'),

U('U-18', '/etc/shadow 파일 권한 설정', '🔒', '상',
  '/etc/shadow에는 비밀번호 해시가 들어 있습니다. 일반 사용자가 읽을 수 있으면 오프라인 무차별 대입으로 전 계정이 뚫립니다. 400(root만 읽기)이어야 합니다.',
  [('cmt', '# shadow 권한 확인'), ('prompt', '# '), ('', 'ls -l /etc/shadow'),
   ('bad', '-rw-r--r-- 1 root root /etc/shadow'),
   ('warn', '→ 해시 덤프 가능 (취약: 전 계정 오프라인 대입)')],
  [('cmt', '# 권한 조정'), ('prompt', '# '), ('', 'chmod 400 /etc/shadow'),
   ('good', '-r-------- 1 root root /etc/shadow'),
   ('good', '→ root만 읽기 가능 (양호)')],
  ['<code>chmod 400 /etc/shadow</code>로 root만 읽도록 제한합니다.',
   '백업 파일·스냅샷에도 동일 권한이 적용되는지 확인합니다.',
   '해시 알고리즘이 SHA-512 등 강한 방식인지 <code>/etc/login.defs</code>에서 확인합니다.'],
  ['/etc/shadow 권한이 400 이하인가', 'root 외 접근이 완전 차단되었는가'],
  '파일 및 디렉터리 관리 > /etc/shadow 권한', '파일 및 디렉터리 관리'),

U('U-19', '/etc/hosts 파일 권한 설정', '🌐', '중',
  '/etc/hosts는 도메인-IP 매핑으로 DNS보다 우선 적용됩니다. 일반 사용자가 수정하면 은행·관리 페이지를 가짜 서버로 보내는 로컬 피싱이 가능합니다. 644로 유지해야 합니다.',
  [('cmt', '# hosts 권한 확인'), ('prompt', '# '), ('', 'ls -l /etc/hosts'),
   ('bad', '-rw-rw-rw- 1 root root /etc/hosts'),
   ('warn', '→ 임의 수정 가능 (취약: 사이트 접속 가로채기)')],
  [('cmt', '# 권한 조정'), ('prompt', '# '), ('', 'chmod 644 /etc/hosts'),
   ('good', '-rw-r--r-- 1 root root /etc/hosts'),
   ('good', '→ root만 수정 (양호)')],
  ['<code>chmod 644 /etc/hosts</code>, 소유자 root로 유지합니다.',
   'hosts 내용에 의심스러운 매핑이 추가되지 않았는지 주기적으로 확인합니다.'],
  ['/etc/hosts 권한이 644 이하인가', '비정상 매핑 추가 여부를 점검하는가'],
  '파일 및 디렉터리 관리 > /etc/hosts 권한', '파일 및 디렉터리 관리'),

U('U-20', '/etc/inetd.conf 파일 권한 설정', '⚙️', '중',
  'inetd 설정 파일을 일반 사용자가 수정하면 악성 서비스를 등록해 재시작 후 실행할 수 있습니다. root 소유 640 이하로 제한합니다.',
  [('cmt', '# inetd.conf 권한 확인'), ('prompt', '# '), ('', 'ls -l /etc/inetd.conf /etc/xinetd.conf 2>/dev/null'),
   ('bad', '-rw-rw-rw- 1 root root /etc/inetd.conf'),
   ('warn', '→ 서비스 등록 변조 가능 (취약)')],
  [('cmt', '# 권한 조정'), ('prompt', '# '), ('', 'chmod 640 /etc/inetd.conf'),
   ('good', '-rw-r----- 1 root root /etc/inetd.conf'),
   ('good', '→ root 그룹만 읽기 (양호)')],
  ['inetd/xinetd 설정 파일을 root 소유 <code>640</code> 이하로 유지합니다.',
   'inetd를 사용하지 않는다면 서비스 자체를 제거합니다.',
   '설정 변경 시 이력을 남기고 주기적으로 비교합니다.'],
  ['설정 파일 권한이 640 이하인가', '불필요한 inetd 서비스가 제거되었는가'],
  '파일 및 디렉터리 관리 > inetd 설정 파일 권한', '파일 및 디렉터리 관리'),

U('U-21', '/etc/rsyslog.conf 파일 권한 설정', '📜', '중',
  '로그 설정 파일을 임의 수정하면 공격 흔적이 기록되지 않게 로그 경로를 바꾸거나 끊을 수 있습니다. root 소유 640 이하로 제한합니다.',
  [('cmt', '# rsyslog.conf 권한 확인'), ('prompt', '# '), ('', 'ls -l /etc/rsyslog.conf'),
   ('bad', '-rw-rw-rw- 1 root root /etc/rsyslog.conf'),
   ('warn', '→ 로그 경로 변조·흔적 삭제 유도 (취약)')],
  [('cmt', '# 권한 조정'), ('prompt', '# '), ('', 'chmod 640 /etc/rsyslog.conf'),
   ('good', '-rw-r----- 1 root root /etc/rsyslog.conf'),
   ('good', '→ 로그 설정 보호 (양호)')],
  ['<code>chmod 640 /etc/rsyslog.conf</code>로 제한합니다.',
   '원격 로그 서버로 실시간 전송하여 로그 삭제·변조에 대비합니다.',
   '로그 파일 자체 권한(640 이하)도 함께 점검합니다.'],
  ['설정 파일 권한이 640 이하인가', '원격 로그 이중화가 되어 있는가'],
  '파일 및 디렉터리 관리 > rsyslog 설정 파일 권한', '파일 및 디렉터리 관리'),

U('U-22', '/etc/services 파일 권한 설정', '🔌', '중',
  '포트-서비스 매핑(/etc/services)이 변조되면 서비스가 다른 포트로 돌거나 방화벽 판단이 흐트러집니다. 644(root 소유)로 유지합니다.',
  [('cmt', '# services 권한 확인'), ('prompt', '# '), ('', 'ls -l /etc/services'),
   ('bad', '-rw-rw-rw- 1 root root /etc/services'),
   ('warn', '→ 포트 매핑 변조 가능 (취약)')],
  [('cmt', '# 권한 조정'), ('prompt', '# '), ('', 'chmod 644 /etc/services'),
   ('good', '-rw-r--r-- 1 root root /etc/services'),
   ('good', '→ root만 수정 (양호)')],
  ['<code>chmod 644 /etc/services</code>, 소유자 root로 유지합니다.',
   '서비스·포트 변경은 변경관리 절차를 통해 수행합니다.'],
  ['/etc/services 권한이 644 이하인가', '비정상 포트 매핑이 없는가'],
  '파일 및 디렉터리 관리 > /etc/services 권한', '파일 및 디렉터리 관리'),

U('U-23', 'SUID, SGID, Sticky bit 점검', '⭐', '상',
  'SUID/SGID가 걸린 파일은 실행 순간 소유자 권한을 얻습니다. 불필요한 파일에 남아 있으면 권한 상승의 사다리가 되므로 최소화하고 목록 관리해야 합니다.',
  [('cmt', '# SUID/SGID 파일 검색'), ('prompt', '# '), ('', 'find / -perm -4000 -type f 2>/dev/null'),
   ('bad', '/usr/bin/old-backup  (root SUID, 사용 안 함)'),
   ('bad', '/tmp/collector      (일반 사용자가 만든 SUID 스크립트)'),
   ('warn', '→ 불필요·비인가 SUID 존재 (취약)')],
  [('cmt', '# 불필요 비트 제거·목록 관리'), ('prompt', '# '), ('', 'chmod u-s /usr/bin/old-backup && rm /tmp/collector'),
   ('good', '>> SUID 목록이 승인 목록과 일치'),
   ('good', '→ 권한 상승 경로 최소화 (양호)')],
  ['<code>find / -perm -4000</code>(SGID: -2000)로 주기적으로 점검합니다.',
   '승인된 SUID/SGID 목록을 문서화하고 차이 발생 시 알림을 둡니다.',
   '공유 디렉터리에는 Sticky bit(<code>chmod +t</code>)를 적용해 타인 파일 삭제를 막습니다.'],
  ['SUID/SGID 파일이 승인 목록과 일치하는가', '새로 생긴 비트를 탐지하는 점검 주기가 있는가'],
  '파일 및 디렉터리 관리 > SUID/SGID/Sticky bit 점검', '파일 및 디렉터리 관리'),

U('U-24', '환경변수 파일 권한 설정', '📉', '중',
  '.bash_profile, .profile 등 환경변수 파일을 다른 사용자가 수정하면, 로그인 시 공격자의 명령(PATH 주입·alias 위장)이 실행됩니다. 소유자만 쓸 수 있게 제한합니다.',
  [('cmt', '# 환경변수 파일 권한 확인'), ('prompt', '# '), ('', 'ls -la ~user01/.bash_profile'),
   ('bad', '-rw-rw-rw- 1 user01 user01 .bash_profile'),
   ('warn', '→ 타인 수정 가능 (취약: 로그인 시 악성 명령 실행)')],
  [('cmt', '# 권한 조정'), ('prompt', '# '), ('', 'chmod 600 ~user01/.bash_profile'),
   ('good', '-rw------- 1 user01 user01 .bash_profile'),
   ('good', '→ 본인만 수정 (양호)')],
  ['홈의 시작 파일(<code>.bash_profile</code>, <code>.bashrc</code> 등)을 <code>600</code>으로 제한합니다.',
   'PATH에 <code>.</code>가 없는지, 의심스러운 alias가 없는지 확인합니다.',
   '신규 계정 생성 시 안전한 기본 스켈레톤(<code>/etc/skel</code>)을 배포합니다.'],
  ['환경변수 파일이 소유자만 쓸 수 있는가', 'PATH·alias에 위장 명령이 없는가'],
  '파일 및 디렉터리 관리 > 환경변수 파일 권한', '파일 및 디렉터리 관리'),

U('U-25', 'world writable 파일 점검', '✍️', '상',
  '누구나 쓸 수 있는(o+w) 파일은 공격자가 악성 스크립트로 교체하거나 내용을 바꿔치기할 수 있습니다. /tmp 등 예외를 제외하고 제거해야 합니다.',
  [('cmt', "# world writable 파일 검색"), ('prompt', '# '), ('', 'find / -type f -perm -2 -not -path "/tmp/*" 2>/dev/null'),
   ('bad', '/usr/local/bin/report.sh  (777)'),
   ('bad', '/home/share/plan.docx  (777)'),
   ('warn', '→ 무단 기입 가능 파일 다수 (취약)')],
  [('cmt', '# 쓰기 비트 제거'), ('prompt', '# '), ('', 'chmod o-w /usr/local/bin/report.sh'),
   ('good', '>> find / -perm -2  → /tmp 제외 없음'),
   ('good', '→ 무단 기입 경로 제거 (양호)')],
  ['<code>find / -type f -perm -2</code>로 주기적으로 점검하고 <code>chmod o-w</code>로 제거합니다.',
   '공유가 필요하면 쓰기 대신 그룹 권한(770)이나 공유 디렉터리+Sticky bit를 사용합니다.',
   '예외 목록(/tmp 등)을 문서화하여 관리합니다.'],
  ['world writable 파일이 예외 목록 외 없는가', '공유 필요 파일이 그룹 권한으로 대체되었는가'],
  '파일 및 디렉터리 관리 > world writable 파일 제거', '파일 및 디렉터리 관리'),

U('U-26', '/dev 디바이스 파일 점검', '💽', '상',
  '/dev의 특수 디바이스 파일(디스크·메모리 접근)을 일반 사용자가 소유하거나 읽을 수 있으면 원격으로 디스크 내용을 통째로 훔칠 수 있습니다. root 소유로 제한해야 합니다.',
  [('cmt', '# 일반 사용자 소유 디바이스 확인'), ('prompt', '# '), ('', 'find /dev -type f -user user01 2>/dev/null; ls -l /dev/sda'),
   ('bad', 'brw-rw-rw- 1 root disk /dev/sda'),
   ('warn', '→ 전원 읽기 가능 (취약: 디스크 통째 탈취)')],
  [('cmt', '# 권한 조정'), ('prompt', '# '), ('', 'chmod 660 /dev/sda'),
   ('good', 'brw-rw---- 1 root disk /dev/sda'),
   ('good', '→ root·disk 그룹만 접근 (양호)')],
  ['주요 디바이스(<code>/dev/sda</code>, <code>/dev/mem</code> 등)는 root 소유 660 이하로 유지합니다.',
   '일반 사용자 소유 디바이스 파일은 존재하지 않아야 합니다.',
   'USB 등 이동식 장치 마운트 정책과 함께 관리합니다.'],
  ['일반 사용자 소유 디바이스가 없는가', '주요 디바이스 권한이 660 이하인가'],
  '파일 및 디렉터리 관리 > /dev 디바이스 점검', '파일 및 디렉터리 관리'),

U('U-27', '.rhosts 사용 금지', '🚷', '상',
  '.rhosts는 "이 호스트의 이 사용자는 인증 없이 통과"라는 백문이 없는 신뢰 목록입니다. 한 대만 뚫리면 연쇄로 rlogin/rcp가 열리므로 사용을 금지해야 합니다.',
  [('cmt', '# .rhosts 파일 존재 확인'), ('prompt', '# '), ('', 'find / -name .rhosts 2>/dev/null; cat /root/.rhosts'),
   ('bad', '+ +'),
   ('warn', '→ 누구든 인증 없이 r 계열 접속 허용 (취약)')],
  [('cmt', '# 파일 제거·생성 차단'), ('prompt', '# '), ('', 'rm -f /root/.rhosts'),
   ('good', '>> find / -name .rhosts  → (출력 없음)'),
   ('good', '→ 신뢰 목록 제거, SSH만 허용 (양호)')],
  ['모든 홈 디렉터리에서 <code>.rhosts</code>, <code>hosts.equiv</code>를 제거합니다.',
   'r 계열 서비스(U-36)를 비활성화 하여 사용 자체를 차단합니다.',
   '정기 점검 스크립트로 재생성을 탐지합니다.'],
  ['.rhosts/hosts.equiv가 존재하지 않는가', 'r 계열 서비스가 비활성화되었는가'],
  '파일 및 디렉터리 관리 > .rhosts 사용 금지', '파일 및 디렉터리 관리'),

U('U-28', '접속 IP 및 포트 제한 (TCP Wrapper)', '🧱', '중',
  'hosts.allow/deny가 비어 있으면 서비스 포트에 누구나 접근을 시도할 수 있습니다. 허용할 IP·서비스만 명시하고 나머지는 거부해야 합니다.',
  [('cmt', '# TCP Wrapper 설정 확인'), ('prompt', '# '), ('', 'cat /etc/hosts.allow /etc/hosts.deny'),
   ('bad', '(모두 비어 있음 — 제한 없음)'),
   ('warn', '→ 임의 IP에서 서비스 접근 시도 가능 (취약)')],
  [('cmt', '# 허용 목록·기본 거부 설정'), ('prompt', '# '), ('', 'sshd: 10.0.10.  ← /etc/hosts.allow'),
   ('good', 'ALL: ALL  ← /etc/hosts.deny (기본 거부)'),
   ('good', '→ 관리망만 접속 허용 (양호)')],
  ['<code>/etc/hosts.allow</code>에 허용 서비스·IP를 최소로 명시합니다.',
   '<code>/etc/hosts.deny</code>에 <code>ALL: ALL</code>로 기본 거부를 설정합니다.',
   '방화벽과 함께 이중으로 관리망 접근을 제한합니다.'],
  ['허용 IP가 최소한으로 명시되었는가', '기본 거부(deny) 정책이 설정되었는가'],
  '파일 및 디렉터리 관리 > 접속 IP·포트 제한(TCP Wrapper)', '파일 및 디렉터리 관리'),
]
