# -*- coding: utf-8 -*-
"""전자금융 보안 특화 시뮬 10종 콘텐츠 명세 (금융보안원 제2026-1호 항목 개념 재구성)."""

SPECS = [
{
 'file':'07_fin-transaction-integrity.html',
 'title':'거래정보 무결성 검증 (전문 변조)',
 'icon':'🧾', 'target':'Core Banking 이체 API', 'risk':'5', 'item_code':'WEB-SER 거래정보 검증',
 'attack_panel_title':'계좌 이체 요청',
 'scenario_html':'사용자가 입력한 거래정보(이체금액·수취계좌)가 단말에서 서버로 전송될 때 <b>무결성 검증(서명/HMAC)</b> 없이 처리되면, 프록시로 가로채 <b>이체금액을 변조</b>해도 서버가 그대로 승인합니다.',
 'attack_name':'이체 전문(Amount) 변조', 'attack_sub':'amount 10,000 → 50,000,000 변조 후 재전송',
 'normal_req':'{\n  "from": "110-392-102931",\n  "to":   "220-771-559010",\n  "amount": 10000,\n  "memo": "월세"\n}',
 'attack_req':'{\n  "from": "110-392-102931",\n  "to":   "999-000-HACKER",   // 공격자 계좌\n  "amount": 50000000,         // 금액 변조\n  "memo": "월세"\n}',
 'vuln_logs_js':"addLog('[PROXY] 이체 전문 가로채기 → amount/to 변조','warn'); addLog('[WAS] 거래정보 무결성(서명) 검증 절차 없음','error'); addLog('[DB] 50,000,000원 출금 승인 → 공격자 계좌 입금','error');",
 'breach_html':'<strong>🚨 거래 변조 성공</strong><br>무결성 검증이 없어 변조된 금액(50,000,000원)과 수취계좌가 그대로 승인되었습니다.<table class="data-table"><tr><th>항목</th><th>원거래</th><th>변조 후</th></tr><tr><td>수취계좌</td><td>220-771-559010</td><td style="color:#b71c1c">999-000-HACKER</td></tr><tr><td>금액</td><td class="amount">10,000</td><td class="amount" style="color:#b71c1c">50,000,000</td></tr></table>',
 'violations':['전자금융감독규정 제34조: 거래정보의 무결성 확보 미흡',
               '평가기준 WEB/MOB/HTS-SER [전자금융] 거래정보 무결성 검증(위험도 5)',
               '예비거래↔본거래 거래정보 일치 검증 부재'],
 'defense_intro':'서버는 클라이언트 입력 금액을 신뢰하지 말고, 거래정보에 대한 <strong>전자서명/HMAC 무결성 검증</strong>과 예비거래 대조를 수행해야 합니다. 아래 검증 로직을 안전하게 보완하세요.',
 'vuln_code':'// [취약] 클라이언트가 보낸 금액을 그대로 신뢰\npublic void transfer(TxnRequest req) {\n    // 무결성 검증 없음\n    account.withdraw(req.getFrom(), req.getAmount());\n    account.deposit(req.getTo(), req.getAmount());\n}',
 'secure_hint':'// [안전] 거래정보 무결성 검증 + 예비거래 대조\npublic void transfer(TxnRequest req) {\n    // 1) 전문 위변조 방지: 서버 보관 키로 HMAC 재계산 후 비교\n    String mac = hmacSHA256(serverKey, req.canonical());\n    if (!constantTimeEquals(mac, req.getSignature()))\n        throw new SecurityException("거래정보 무결성 검증 실패");\n    // 2) 예비거래(준비단계) 금액/수취계좌와 본거래 일치 확인\n    PreparedTxn p = txnStore.get(req.getTxnId());\n    if (p.getAmount() != req.getAmount() || !p.getTo().equals(req.getTo()))\n        throw new SecurityException("예비거래 정보 불일치");\n    account.withdraw(req.getFrom(), req.getAmount());\n    account.deposit(req.getTo(), req.getAmount());\n}',
 'checks':[['hmac','HMAC','signature','getSignature'],['예비거래','getTxnId','PreparedTxn','일치']],
 'success_msg':'HMAC 무결성 검증과 예비거래 대조로 전문 변조가 차단됩니다.',
 'fail_msg':'서버 측 무결성 검증(HMAC/서명)과 예비거래 금액 대조가 필요합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>운영 관리 &gt; 공개서버 보안 &gt; <b>거래정보 무결성 검증</b><h4>2. 위험 분석</h4><ul><li>이체금액·수취계좌 변조로 직접적 금전 피해</li><li>유료 인증서 발급비용 변조 등 파생 악용</li></ul><h4>3. 조치 방법</h4><ul><li>거래정보에 대한 <b>전자서명/HMAC</b> 적용 및 서버 검증</li><li>예비거래와 본거래 거래정보 <b>일치 여부</b> 확인</li><li>금액 등 핵심 값은 서버 보관 값을 기준으로 처리</li></ul>',
},
{
 'file':'07_fin-replay.html',
 'title':'거래정보 재사용 방지 (리플레이)',
 'icon':'🔁', 'target':'간편결제 승인 API', 'risk':'5', 'item_code':'WEB-SER 거래정보 재사용 방지',
 'attack_panel_title':'결제 승인 요청',
 'scenario_html':'정상 결제 전문에 <b>일회성 토큰(nonce)·타임스탬프</b>가 없으면, 가로챈 <b>결제 전문을 그대로 재전송</b>하여 동일 결제를 무한 반복(중복 출금)할 수 있습니다.',
 'attack_name':'결제 전문 재전송(Replay)', 'attack_sub':'캡처한 승인 전문을 N회 재전송',
 'normal_req':'POST /pay/approve\n{\n  "orderId": "ORD-20260620-001",\n  "amount": 35000,\n  "token": "otp-7741"\n}',
 'attack_req':'POST /pay/approve   (캡처본 그대로 재전송 x10)\n{\n  "orderId": "ORD-20260620-001",\n  "amount": 35000,\n  "token": "otp-7741"   // 이미 사용된 값 재사용\n}',
 'vuln_logs_js':"addLog('[PROXY] 결제 승인 전문 캡처','warn'); addLog('[REPLAY] 동일 전문 10회 재전송','warn'); addLog('[WAS] nonce/사용이력 검증 없음 → 10건 모두 승인','error'); addLog('[DB] 350,000원 중복 출금 발생','error');",
 'breach_html':'<strong>🚨 리플레이 성공</strong><br>일회성 검증이 없어 동일 결제가 <b>10회 중복 승인</b>되었습니다.<table class="data-table"><tr><th>시도</th><th>token</th><th>결과</th></tr><tr><td>1~10회</td><td>otp-7741 (동일)</td><td style="color:#b71c1c">전부 승인 / 35,000×10</td></tr></table>',
 'violations':['평가기준 [전자금융] 거래정보 재사용 방지(위험도 5)',
               '이용자 인증정보 재사용 방지(전자서명/OTP 일회성) 위반',
               '전자금융감독규정 제34조 해킹 방지대책 미흡'],
 'defense_intro':'서버는 거래마다 <strong>일회성 nonce</strong>를 발급·소비하고, <strong>사용 이력/타임스탬프</strong>로 재전송을 거부해야 합니다. 검증 로직을 보완하세요.',
 'vuln_code':'// [취약] 동일 전문 재전송을 막지 못함\npublic void approve(PayReq req) {\n    otp.verify(req.getToken());   // 값 검증만, 일회성 보장 X\n    ledger.charge(req.getOrderId(), req.getAmount());\n}',
 'secure_hint':'// [안전] nonce 일회성 소비 + 중복 거래 차단\nprivate final Set<String> usedNonce = ConcurrentHashMap.newKeySet();\npublic void approve(PayReq req) {\n    // 1) 일회성 nonce: 이미 사용되었으면 거부\n    if (!usedNonce.add(req.getNonce()))\n        throw new SecurityException("재사용된 거래 요청(replay)");\n    // 2) 타임스탬프 유효시간(예: 60초) 검증\n    if (Math.abs(now() - req.getTimestamp()) > 60_000)\n        throw new SecurityException("거래 유효시간 초과");\n    // 3) 주문 중복 승인 방지\n    if (ledger.isApproved(req.getOrderId()))\n        throw new SecurityException("이미 처리된 주문");\n    ledger.charge(req.getOrderId(), req.getAmount());\n}',
 'checks':[['usedNonce','nonce','getNonce'],['timestamp','getTimestamp','유효시간','isApproved']],
 'success_msg':'일회성 nonce 소비와 유효시간·중복승인 검증으로 재전송이 차단됩니다.',
 'fail_msg':'nonce 일회성 소비와 타임스탬프/중복 승인 검증을 추가해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>거래정보 검증 &gt; <b>거래정보 재사용 방지</b><h4>2. 위험 분석</h4><ul><li>이체/결제 전문 재전송으로 중복 출금</li><li>OTP·전자서명 등 일회성 값 재사용</li></ul><h4>3. 조치 방법</h4><ul><li>거래별 <b>nonce(일회성 토큰)</b> 발급·소비</li><li>요청 <b>타임스탬프 유효시간</b> 제한</li><li>주문/거래 ID <b>멱등성(idempotency)</b> 보장</li></ul>',
},
{
 'file':'07_fin-idor-account.html',
 'title':'거래 시 소유주 검증 (금융 IDOR)',
 'icon':'🪪', 'target':'계좌 조회/이체 서비스', 'risk':'5', 'item_code':'WEB-SER 부적절한 이용자 인가',
 'attack_panel_title':'계좌 거래내역 조회',
 'scenario_html':'로그인한 이용자가 요청한 <b>계좌번호 파라미터</b>의 소유주가 본인인지 서버가 확인하지 않으면, 파라미터만 바꿔 <b>타인의 계좌·거래내역</b>을 조회/이체할 수 있습니다(금융형 IDOR).',
 'attack_name':'소유주 검증 우회(IDOR)', 'attack_sub':'본인 계좌 → 타인 계좌번호로 변조',
 'normal_req':'GET /api/account/transactions\nsessionUser = user_1023\n{\n  "account": "110-392-102931"   // 본인 계좌\n}',
 'attack_req':'GET /api/account/transactions\nsessionUser = user_1023\n{\n  "account": "110-441-203912"   // (주)삼성전자 계좌 변조\n}',
 'vuln_logs_js':"addLog('[REQUEST] account=110-441-203912 (타인)','warn'); addLog('[WAS] 세션 이용자와 계좌 소유주 매핑 검증 없음','error'); addLog('[DB] 타인 거래내역 540억 계좌 반환','error');",
 'breach_html':'<strong>🚨 타인 계좌 정보 노출</strong><br>소유주 검증 부재로 다른 이용자의 계좌 거래내역이 조회되었습니다.<table class="data-table"><tr><th>계좌</th><th>예금주</th><th>잔액</th></tr><tr><td>110-441-203912</td><td>(주)삼성전자</td><td class="amount" style="color:#b71c1c">54,000,000,000</td></tr></table>',
 'violations':['평가기준 [전자금융] 거래 시 소유주 검증(위험도 5)',
               '부적절한 이용자 인가(IN) / 불충분한 권한 검증',
               '개인정보보호법 제29조 안전조치 의무 위반'],
 'defense_intro':'서버는 모든 거래에서 <strong>세션 이용자와 대상 계좌의 소유 관계</strong>를 확인해야 합니다. 파라미터를 신뢰하지 않도록 인가 로직을 보완하세요.',
 'vuln_code':'// [취약] 계좌번호 파라미터를 그대로 신뢰\npublic List<Txn> history(HttpSession s, String account) {\n    // 소유주 확인 없음\n    return txnRepo.findByAccount(account);\n}',
 'secure_hint':'// [안전] 세션 이용자와 계좌 소유주 매핑 검증\npublic List<Txn> history(HttpSession s, String account) {\n    String userId = (String) s.getAttribute("userId");\n    // 요청 계좌가 현재 로그인 이용자 소유인지 확인\n    if (!accountRepo.isOwner(userId, account))\n        throw new AccessDeniedException("권한 없는 계좌 접근");\n    return txnRepo.findByAccount(account);\n}',
 'checks':[['isOwner','소유','getAttribute'],['AccessDenied','권한','throw']],
 'success_msg':'세션 이용자–계좌 소유주 매핑 검증으로 IDOR이 차단됩니다.',
 'fail_msg':'세션 이용자가 해당 계좌의 소유주인지 서버에서 검증해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>이용자 인증/인가 &gt; <b>거래 시 소유주 검증</b><h4>2. 위험 분석</h4><ul><li>파라미터 변조로 타인 계좌·카드·계약 조회/이체</li><li>대량 자동조회 시 정보 유출 확대</li></ul><h4>3. 조치 방법</h4><ul><li>모든 거래에서 <b>세션 주체–자원 소유관계</b> 검증</li><li>직접 식별자 대신 <b>간접 참조(매핑 테이블)</b> 사용</li><li>권한 검증을 <b>서버 측</b>에서 일관 적용</li></ul>',
},
{
 'file':'07_fin-txn-auth.html',
 'title':'거래 인증수단 검증 (OTP/보안카드 우회)',
 'icon':'🔐', 'target':'이체 2차 인증', 'risk':'5', 'item_code':'WEB-FIN 거래 인증',
 'attack_panel_title':'이체 2차 인증',
 'scenario_html':'이체 시 OTP·보안카드 등 <b>거래 인증</b>이 서버에서 강제되지 않고 클라이언트 응답(success=true)만으로 처리되면, 인증 단계를 <b>로직 변조로 우회</b>할 수 있습니다.',
 'attack_name':'2차 인증 우회', 'attack_sub':'authResult를 강제로 success로 변조',
 'normal_req':'POST /transfer/confirm\n{\n  "txnId": "T-90021",\n  "otp": "(미입력)",\n  "authResult": "PENDING"\n}',
 'attack_req':'POST /transfer/confirm\n{\n  "txnId": "T-90021",\n  "otp": "000000",\n  "authResult": "SUCCESS"   // 클라이언트 응답 변조\n}',
 'vuln_logs_js':"addLog('[PROXY] authResult=PENDING → SUCCESS 변조','warn'); addLog('[WAS] 서버측 OTP 검증 없이 클라이언트 결과 신뢰','error'); addLog('[DB] 2차 인증 생략 → 이체 승인','error');",
 'breach_html':'<strong>🚨 거래 인증 우회</strong><br>서버가 OTP를 직접 검증하지 않아, 변조된 인증결과(SUCCESS)만으로 이체가 승인되었습니다.',
 'violations':['평가기준 [전자금융] 거래 인증수단 검증(위험도 5)',
               '불충분한 인증 / 폐기된 인증수단 사용 통제 미흡',
               '전자금융감독규정 제37조 추가인증 의무 위반'],
 'defense_intro':'인증 판단은 반드시 <strong>서버에서</strong> 수행하고, 클라이언트가 보낸 인증결과를 신뢰하면 안 됩니다. OTP 유효성·유효시간·폐기여부를 서버에서 검증하세요.',
 'vuln_code':'// [취약] 클라이언트 authResult를 신뢰\npublic void confirm(TxnReq req) {\n    if ("SUCCESS".equals(req.getAuthResult())) {\n        transfer.execute(req.getTxnId());\n    }\n}',
 'secure_hint':'// [안전] 서버측 OTP 검증 (유효성+유효시간+폐기여부)\npublic void confirm(TxnReq req) {\n    OtpToken t = otpStore.get(req.getTxnId());\n    if (t == null || t.isRevoked() || t.isExpired())\n        throw new SecurityException("유효하지 않은 인증수단");\n    if (!otpService.verify(req.getTxnId(), req.getOtp()))\n        throw new SecurityException("OTP 검증 실패");\n    transfer.execute(req.getTxnId());\n}',
 'checks':[['otpService.verify','otpStore','verify('],['isExpired','isRevoked','유효시간','폐기']],
 'success_msg':'서버측 OTP 검증·유효시간·폐기여부 확인으로 인증 우회가 차단됩니다.',
 'fail_msg':'클라이언트 결과 대신 서버에서 OTP 유효성/유효시간/폐기여부를 검증해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>거래 인증 &gt; <b>거래 인증수단 검증</b><h4>2. 위험 분석</h4><ul><li>잘못된/폐기된 인증정보로 정상 거래 가능</li><li>인증 유효시간 미제한으로 탈취 인증정보 재사용</li></ul><h4>3. 조치 방법</h4><ul><li>인증 검증은 <b>서버 사이드</b>에서 수행</li><li>OTP/보안카드 <b>유효시간·폐기여부</b> 확인</li><li>클라이언트 스크립트로 인증 처리 금지</li></ul>',
},
{
 'file':'07_fin-fixed-authcode.html',
 'title':'고정·유추가능 인증코드 (SMS/ARS)',
 'icon':'📩', 'target':'본인확인 인증코드', 'risk':'5', 'item_code':'WEB-SER 고정된 인증정보 이용 방지',
 'attack_panel_title':'SMS 인증코드 확인',
 'scenario_html':'SMS/ARS 인증코드가 매번 <b>동일하거나 규칙적</b>이면, 한 번 관측한 값으로 타인의 본인확인을 <b>예측·우회</b>할 수 있습니다.',
 'attack_name':'고정 인증코드 예측', 'attack_sub':'관측한 코드(000000 고정) 재사용',
 'normal_req':'POST /verify/sms\n{\n  "phone": "010-1234-5678",\n  "code": "(서버 발송 코드)"\n}',
 'attack_req':'POST /verify/sms\n{\n  "phone": "010-9999-0000",   // 타인 번호\n  "code": "000000"            // 항상 고정값\n}',
 'vuln_logs_js':"addLog('[OBSERVE] 발송 코드가 항상 000000 (고정)','warn'); addLog('[WAS] 가변 난수 미사용 + 시도횟수 제한 없음','error'); addLog('[DB] 타인 본인확인 통과','error');",
 'breach_html':'<strong>🚨 본인확인 우회</strong><br>인증코드가 고정값이라 타인 번호에 대한 본인확인이 통과되었습니다.',
 'violations':['평가기준 고정된 인증정보 이용 방지 / 유추 가능한 인증정보(위험도 5)',
               '적절하지 않은 난수 값 사용(보안기능)',
               '반복 인증시도 제한 기능 부재'],
 'defense_intro':'인증코드는 <strong>암호학적 난수(가변)</strong>로 생성하고, <strong>유효시간·시도횟수 제한</strong>을 적용해야 합니다.',
 'vuln_code':'// [취약] 고정/약한 난수 인증코드\nString code = "000000";              // 항상 동일\n// 또는 new Random().nextInt(); (예측 가능)\nsmsService.send(phone, code);',
 'secure_hint':'// [안전] 암호학적 난수 + 유효시간 + 시도제한\nSecureRandom rnd = new SecureRandom();\nString code = String.format("%06d", rnd.nextInt(1_000_000));\nverifyStore.put(phone, code, Duration.ofMinutes(3)); // 유효시간\nrateLimiter.check(phone);             // 시도횟수 제한\nsmsService.send(phone, code);',
 'checks':[['SecureRandom'],['유효시간','Duration','rateLimiter','시도','ofMinutes']],
 'success_msg':'SecureRandom 가변 코드 + 유효시간/시도제한으로 예측·재사용이 차단됩니다.',
 'fail_msg':'SecureRandom 기반 가변 코드와 유효시간·시도횟수 제한이 필요합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>이용자 인증 &gt; <b>고정된 인증정보 이용 방지</b><h4>2. 위험 분석</h4><ul><li>고정·규칙적 코드로 타인 본인확인 우회</li><li>무차별 대입으로 인증코드 추측</li></ul><h4>3. 조치 방법</h4><ul><li><b>SecureRandom</b> 등 안전한 난수로 매번 생성</li><li>코드 <b>유효시간</b> 및 <b>시도횟수</b> 제한</li><li>주민번호·전화번호 등 유추 가능 정보 사용 금지</li></ul>',
},
{
 'file':'07_fin-device-rooting.html',
 'title':'루팅·탈옥 단말 탐지',
 'icon':'📱', 'target':'모바일뱅킹 앱', 'risk':'5', 'item_code':'MOB-FIN OS 변조 탐지',
 'attack_panel_title':'모바일 앱 구동 점검',
 'scenario_html':'OS가 변조(루팅/탈옥)된 단말에서는 보안프로그램 무력화·메모리 조작 위협이 커집니다. 앱이 <b>루팅 탐지</b> 없이 구동되면 변조 단말에서 그대로 금융거래가 가능합니다.',
 'attack_name':'루팅 단말에서 앱 실행', 'attack_sub':'su/Magisk 환경에서 거래 시도',
 'normal_req':'{\n  "device": "Galaxy S24",\n  "rooted": false,\n  "integrity": "PASS"\n}',
 'attack_req':'{\n  "device": "Galaxy S24 (Magisk)",\n  "rooted": true,            // 루팅됨\n  "su_binary": "/system/xbin/su",\n  "integrity": "PASS"        // 무결성 응답 변조\n}',
 'vuln_logs_js':"addLog('[APP] 루팅 탐지 로직 없음','error'); addLog('[ENV] su 바이너리/Magisk 감지되나 차단 안함','warn'); addLog('[TXN] 변조 단말에서 이체 정상 진행','error');",
 'breach_html':'<strong>🚨 변조 단말 거래 허용</strong><br>루팅 탐지가 없어 OS 변조 단말에서 금융거래가 그대로 수행되었습니다. 보안프로그램 무력화·키로깅 위험이 큽니다.',
 'violations':['평가기준 [전자금융] OS 변조 탐지 기능 적용(위험도 5)',
               '악성코드 방지 / 보안프로그램 동작 미흡',
               '단말 보안 통제 부재'],
 'defense_intro':'앱은 구동 시 <strong>루팅/탈옥·후킹·에뮬레이터</strong>를 다중 신호로 탐지하고, 변조 단말에서는 거래를 차단/제한해야 합니다. (서버에서도 무결성 응답을 재검증)',
 'vuln_code':'// [취약] 루팅 여부를 점검하지 않음\nfun onAppStart() {\n    startBankingSession()   // 무조건 진행\n}',
 'secure_hint':'// [안전] 다중 신호 루팅/무결성 탐지 후 차단\nfun onAppStart() {\n    if (RootDetection.isRooted()        // su, Magisk, 빌드태그 등\n        || RootDetection.isHooked()     // Frida/Xposed\n        || RootDetection.isEmulator()) {\n        blockAndExit("변조된 단말에서는 이용할 수 없습니다")\n        return\n    }\n    // 서버에서 Play Integrity / 무결성 토큰 재검증\n    if (!server.verifyDeviceIntegrity(attestationToken())) {\n        blockAndExit("단말 무결성 검증 실패"); return\n    }\n    startBankingSession()\n}',
 'checks':[['isRooted','RootDetection','루팅'],['verifyDeviceIntegrity','Integrity','무결성','isHooked']],
 'success_msg':'루팅/후킹 탐지 + 서버측 무결성 재검증으로 변조 단말 거래가 차단됩니다.',
 'fail_msg':'루팅/탈옥 탐지와 서버측 단말 무결성 재검증을 추가해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>단말 보안 &gt; <b>OS 변조(루팅/탈옥) 탐지</b><h4>2. 위험 분석</h4><ul><li>보안프로그램 무력화, 메모리·입력값 탈취</li><li>악성코드·키로거 동작 환경</li></ul><h4>3. 조치 방법</h4><ul><li>루팅/탈옥·후킹·에뮬레이터 <b>다중 탐지</b></li><li>변조 단말 거래 <b>차단/제한</b></li><li>클라이언트 응답을 <b>서버에서 재검증</b>(무결성 토큰)</li></ul>',
},
{
 'file':'07_fin-app-integrity.html',
 'title':'앱 위·변조 및 안티디버깅',
 'icon':'🧩', 'target':'모바일/HTS 실행파일', 'risk':'5', 'item_code':'MOB/HTS-FIN 프로그램 무결성',
 'attack_panel_title':'앱 무결성 점검',
 'scenario_html':'설치파일(APK/IPA)이나 실행 라이브러리가 <b>위·변조 검증·난독화·안티디버깅</b> 없이 배포되면, 디컴파일로 로직을 분석하거나 변조 후 재서명하여 악성코드를 삽입·재배포할 수 있습니다.',
 'attack_name':'APK 변조 후 재서명', 'attack_sub':'디컴파일→로직 패치→재서명 설치',
 'normal_req':'{\n  "apk_signature": "원 배포사 서명",\n  "debuggable": false,\n  "obfuscated": true\n}',
 'attack_req':'{\n  "apk_signature": "공격자 재서명",   // 변조\n  "debuggable": true,               // 디버깅 가능\n  "obfuscated": false               // 평문 로직 노출\n}',
 'vuln_logs_js':"addLog('[REPACK] 디컴파일→이체로직 패치→재서명','warn'); addLog('[APP] 무결성/서명 검증 없음','error'); addLog('[DBG] gdb/Frida 부착 가능 (안티디버깅 부재)','error');",
 'breach_html':'<strong>🚨 변조 앱 정상 실행</strong><br>무결성·서명 검증과 난독화/안티디버깅이 없어, 변조·재서명된 앱이 그대로 실행되고 핵심 로직이 노출됩니다.',
 'violations':['평가기준 [전자금융] 프로그램 무결성 검증(위험도 5)',
               '소스코드 난독화 미적용 / 디버깅 탐지 미적용',
               '무결성 검사 없는 코드 다운로드(보안기능)'],
 'defense_intro':'앱은 <strong>서명·체크섬 기반 무결성 검증</strong>, <strong>코드 난독화</strong>, <strong>안티디버깅</strong>을 적용해야 합니다. 실행 시 무결성 검사를 보완하세요.',
 'vuln_code':'// [취약] 무결성/디버깅 점검 없음\nfun onStart() {\n    runApp()\n}',
 'secure_hint':'// [안전] 서명/체크섬 무결성 + 안티디버깅\nfun onStart() {\n    if (!Integrity.verifySignature(expectedCertHash)   // 재서명 탐지\n        || !Integrity.verifyChecksum(expectedDexHash)) {\n        blockAndExit("앱 무결성 검증 실패"); return\n    }\n    if (AntiDebug.isDebuggerAttached()                 // gdb/Frida\n        || AntiDebug.isTracerPidSet()) {\n        blockAndExit("디버깅 환경 탐지"); return\n    }\n    runApp()  // + 빌드 시 R8/ProGuard 난독화 적용\n}',
 'checks':[['verifySignature','verifyChecksum','Integrity.verify'],['AntiDebug','isDebugger','isTracer']],
 'success_msg':'서명/체크섬 무결성 + 안티디버깅 적용으로 위·변조 앱 실행이 차단됩니다.',
 'fail_msg':'서명/체크섬 무결성 검증과 안티디버깅(디버거 탐지)을 추가해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>단말 보안 &gt; <b>프로그램 무결성 검증·난독화·안티디버깅</b><h4>2. 위험 분석</h4><ul><li>변조 앱 재배포로 악성코드 유포</li><li>디컴파일로 중요 로직·키 노출</li></ul><h4>3. 조치 방법</h4><ul><li>설치파일 <b>서명/체크섬 무결성</b> 검증</li><li>소스코드 <b>난독화</b>(R8/ProGuard 등)</li><li><b>안티디버깅</b>·메모리 보호 적용</li></ul>',
},
{
 'file':'07_fin-hts-param.html',
 'title':'HTS 실행 파라미터 재사용',
 'icon':'💹', 'target':'HTS 데스크톱 클라이언트', 'risk':'5', 'item_code':'HTS-FIN 실행 파라미터 재사용 방지',
 'attack_panel_title':'HTS 구동 파라미터',
 'scenario_html':'HTS가 웹 연동 로그인 후 <b>실행 파라미터(세션키 등)로 데스크톱 클라이언트를 구동</b>할 때, 그 파라미터가 <b>재사용 가능</b>하면 노출된 값으로 별도 인증 없이 <b>타인 HTS 계정에 로그인</b>할 수 있습니다. 명령줄에 중요정보가 평문 노출되기도 합니다.</b>',
 'attack_name':'실행 파라미터 재사용', 'attack_sub':'명령줄에서 추출한 sessionKey 재구동',
 'normal_req':'hts.exe --user=user_1023 --sessionKey=AB12CD (1회용)',
 'attack_req':'# 프로세스 명령줄에서 평문 추출 후 재사용\nhts.exe --user=user_1023 --sessionKey=AB12CD   // 동일 키 재구동',
 'vuln_logs_js':"addLog('[PROC] 명령줄에 sessionKey 평문 노출','warn'); addLog('[HTS] 파라미터 일회성/바인딩 검증 없음','error'); addLog('[AUTH] 추가 인증 없이 타인 HTS 로그인 성공','error');",
 'breach_html':'<strong>🚨 무인증 HTS 접속</strong><br>실행 파라미터가 일회성이 아니어서, 명령줄에서 추출한 sessionKey로 별도 인증 없이 타인 HTS에 접속되었습니다.',
 'violations':['평가기준 [전자금융] HTS 구동시 실행 파라미터 재사용 방지(위험도 5)',
               '명령줄 내 중요정보 평문 노출 방지 위반',
               '불충분한 세션 관리'],
 'defense_intro':'실행 파라미터는 <strong>일회성·단말/세션 바인딩·짧은 유효시간</strong>이어야 하며, 명령줄 평문 노출을 피하고 서버에서 재사용을 거부해야 합니다.',
 'vuln_code':'// [취약] 재사용 가능한 실행 파라미터\npublic boolean launchHts(String user, String sessionKey) {\n    return sessionStore.exists(sessionKey);  // 값만 확인\n}',
 'secure_hint':'// [안전] 일회성 + 바인딩 + 유효시간 + 즉시 소비\npublic boolean launchHts(String user, String sessionKey, String deviceId) {\n    LaunchTicket t = ticketStore.consume(sessionKey); // 1회용 소비\n    if (t == null || t.isExpired())            // 짧은 유효시간\n        throw new SecurityException("만료/재사용된 실행 파라미터");\n    if (!t.getUser().equals(user) || !t.getDeviceId().equals(deviceId))\n        throw new SecurityException("단말/이용자 바인딩 불일치");\n    return true; // 명령줄 평문 대신 보안 채널로 전달\n}',
 'checks':[['consume','일회성','1회','ticketStore'],['isExpired','deviceId','바인딩','유효시간']],
 'success_msg':'일회성 소비·단말 바인딩·유효시간으로 파라미터 재사용이 차단됩니다.',
 'fail_msg':'실행 파라미터의 일회성 소비, 단말/이용자 바인딩, 유효시간 검증이 필요합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>단말 보안 &gt; <b>HTS 실행 파라미터 재사용 방지</b><h4>2. 위험 분석</h4><ul><li>노출 파라미터로 무인증 타인 계정 로그인</li><li>명령줄 평문 중요정보 노출</li></ul><h4>3. 조치 방법</h4><ul><li>실행 파라미터 <b>일회성·유효시간</b> 적용</li><li><b>단말/세션 바인딩</b> 및 서버 재사용 거부</li><li>명령줄 평문 노출 금지(보안 채널 전달)</li></ul>',
},
{
 'file':'07_fin-predictable-reset.html',
 'title':'초기화 비밀번호 규칙성',
 'icon':'🔑', 'target':'비밀번호 찾기/초기화', 'risk':'5', 'item_code':'WEB-SER 유추가능 초기화 비밀번호',
 'attack_panel_title':'비밀번호 초기화',
 'scenario_html':'비밀번호 찾기로 <b>초기화된 비밀번호</b>가 생년월일·전화번호·고정패턴 등 <b>규칙적</b>으로 발급되면, 공격자가 타인의 초기 비밀번호를 <b>추측</b>하여 계정을 탈취할 수 있습니다.',
 'attack_name':'초기 비밀번호 추측', 'attack_sub':'규칙(이름+생년)로 초기값 예측',
 'normal_req':'POST /password/reset\n{\n  "userId": "victim01"\n}',
 'attack_req':'POST /password/reset\n{\n  "userId": "victim01"\n}\n# 발급 규칙: 이름이니셜+생년월일 = "hgd1990" (예측됨)',
 'vuln_logs_js':"addLog('[RESET] 초기 비밀번호 = 이름+생년월일 규칙','warn'); addLog('[WAS] 난수성 없음 + 강제 변경 미요구','error'); addLog('[LOGIN] 추측한 초기값으로 로그인 성공','error');",
 'breach_html':'<strong>🚨 계정 탈취</strong><br>초기화 비밀번호가 규칙적이라 추측만으로 타인 계정에 로그인되었습니다.',
 'violations':['평가기준 유추 가능한 초기화 비밀번호 이용 방지(위험도 5)',
               '취약한 비밀번호 복구 / 적절하지 않은 난수 값',
               '본인확인 절차·강제 변경 미흡'],
 'defense_intro':'초기화 비밀번호는 <strong>암호학적 난수(임시·일회성)</strong>로 발급하고, <strong>본인확인 후 보안 채널 전달 + 최초 로그인 시 강제 변경</strong>을 적용하세요.',
 'vuln_code':'// [취약] 규칙적 초기 비밀번호\nString temp = nameInitials + birth;   // 예: hgd1990\nuser.setPassword(hash(temp));',
 'secure_hint':'// [안전] 난수 임시 비밀번호 + 강제 변경\nSecureRandom rnd = new SecureRandom();\nString temp = randomPassword(rnd, 12);   // 예측 불가 일회성\nuser.setPassword(hash(temp));\nuser.setMustChangePassword(true);        // 최초 로그인 시 강제 변경\nsecureChannel.deliver(user, temp);       // 본인확인 후 안전 전달',
 'checks':[['SecureRandom','randomPassword'],['MustChange','강제','mustChange','setMustChangePassword']],
 'success_msg':'난수 임시 비밀번호 + 강제 변경으로 초기 비밀번호 추측이 차단됩니다.',
 'fail_msg':'SecureRandom 임시 비밀번호와 최초 로그인 강제 변경이 필요합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>이용자 인증 &gt; <b>유추 가능한 초기화 비밀번호 이용 방지</b><h4>2. 위험 분석</h4><ul><li>규칙적 초기 비밀번호 추측으로 계정 탈취</li><li>복구 메커니즘 악용</li></ul><h4>3. 조치 방법</h4><ul><li>초기 비밀번호 <b>난수·일회성</b> 발급</li><li>최초 로그인 시 <b>강제 변경</b></li><li>본인확인 후 <b>안전한 채널</b>로 전달</li></ul>',
},
{
 'file':'07_fin-guessable-cred.html',
 'title':'유추 가능한 인증정보 (복잡도)',
 'icon':'🧠', 'target':'비밀번호 등록/변경', 'risk':'5', 'item_code':'WEB-SER 유추가능 인증정보 방지',
 'attack_panel_title':'비밀번호 등록',
 'scenario_html':'비밀번호 등록/변경 시 <b>복잡도·연속/반복/개인정보 포함</b> 검증이 없으면 “111111”, “password”, 전화번호 같은 <b>유추 가능한 비밀번호</b>가 허용되어 무차별 대입에 쉽게 뚫립니다.',
 'attack_name':'약한 비밀번호 등록/대입', 'attack_sub':'연속·반복·개인정보 비밀번호 허용',
 'normal_req':'POST /password/change\n{\n  "userId": "user_1023",\n  "newPw": "(복잡도 충족 값)"\n}',
 'attack_req':'POST /password/change\n{\n  "userId": "user_1023",\n  "newPw": "010-1234-5678"   // 전화번호=비밀번호\n}',
 'vuln_logs_js':"addLog('[REGISTER] newPw=전화번호/연속숫자 허용','warn'); addLog('[WAS] 복잡도·금칙어·개인정보 포함 검증 없음','error'); addLog('[BRUTE] 사전 대입 12회 내 탈취','error');",
 'breach_html':'<strong>🚨 약한 비밀번호 허용</strong><br>복잡도 검증이 없어 전화번호·연속숫자 같은 유추 가능한 비밀번호가 등록되고, 무차별 대입으로 즉시 탈취됩니다.',
 'violations':['평가기준 유추 가능한 인증정보 이용 방지(위험도 5)',
               '취약한 비밀번호 허용(보안기능) / 반복 인증시도 제한 부재',
               '비밀번호 복잡도: 2종 10자리·3종 8자리 이상 미적용'],
 'defense_intro':'비밀번호는 <strong>복잡도(2종 10자리/3종 8자리 이상)</strong>, <strong>연속·반복·개인정보·금칙어</strong> 검증을 통과해야 합니다. 정책 로직을 보완하세요.',
 'vuln_code':'// [취약] 길이만 확인\nboolean valid(String pw) {\n    return pw.length() >= 6;\n}',
 'secure_hint':'// [안전] 복잡도 + 패턴/개인정보/금칙어 검증\nboolean valid(String pw, User u) {\n    int kinds = charKinds(pw); // 대문자/소문자/숫자/특수 종류 수\n    boolean lenOk = (kinds >= 3 && pw.length() >= 8)\n                 || (kinds >= 2 && pw.length() >= 10); // 복잡도 정책\n    if (!lenOk) return false;\n    if (hasSequential(pw) || hasRepeated(pw)) return false; // 연속/반복\n    if (containsPersonalInfo(pw, u)) return false;          // 개인정보\n    if (BLACKLIST.contains(pw)) return false;               // 금칙어\n    return true;\n}',
 'checks':[['kinds','복잡도','charKinds','length() >= 8','length() >= 10'],['hasSequential','hasRepeated','containsPersonalInfo','BLACKLIST','연속','금칙어']],
 'success_msg':'복잡도+연속/반복/개인정보/금칙어 검증으로 약한 비밀번호가 차단됩니다.',
 'fail_msg':'복잡도(2종10/3종8) 및 연속·반복·개인정보·금칙어 검증을 추가해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>이용자 인증 &gt; <b>유추 가능한 인증정보 이용 방지</b><h4>2. 위험 분석</h4><ul><li>약한 비밀번호로 무차별 대입 성공률 급증</li><li>개인정보·연속/반복 패턴 비밀번호</li></ul><h4>3. 조치 방법</h4><ul><li>복잡도 <b>2종 10자리 / 3종 8자리</b> 이상</li><li>연속·반복·개인정보·금칙어 <b>차단</b></li><li>로그인 <b>시도횟수 제한</b> 병행</li></ul>',
},
]
