# -*- coding: utf-8 -*-
DYN = {
 'W-01': {
   'easy': '관리자 계정 이름이 항상 <b>Administrator</b>면, 도둑이 모든 집의 안방 위치를 미리 아는 것과 같습니다. 공격자는 이름을 추측할 필요 없이 비밀번호만 때려 맞추면 됩니다. 이름을 바꾸면 표적부터 흐려집니다.',
   'attack_label': '공격자가 알려진 Administrator 이름으로 비밀번호를 대입한다',
   'attack_vuln': [
     ['cmt', '# 공격자는 관리자명이 Administrator라고 가정'],
     ['prompt', 'attacker$ hydra -l Administrator -P rockyou.txt smb://victim'],
     ['', '...비밀번호 사전 대입 진행...'],
     ['bad', '>> 로그인 성공: Administrator (SID 끝 -500)'],
     ['bad', '>> 관리자 권한 장악 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 관리자 탈취','desc':'계정명이 알려져 있어 비밀번호 대입만으로 관리자가 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일 공격을 안전한 설정에서'],
     ['prompt', 'attacker$ hydra -l Administrator -P rockyou.txt smb://victim'],
     ['good', '>> Administrator 라는 계정이 존재하지 않음'],
     ['warn', '>> 실제 관리자명을 모르면 대입 자체가 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 표적 상실','desc':'관리자명이 바뀌어 공격자가 대상 계정을 특정하지 못합니다.'},
 },
 'W-02': {
   'easy': 'Guest 계정은 <b>잠그지 않은 손님용 쪽문</b>입니다. 비밀번호 없이 누구나 들어와 집 안을 둘러볼 수 있죠. 켜져 있으면 공격자가 인증 없이 첫 발을 들입니다.',
   'attack_label': '공격자가 비밀번호 없는 Guest로 로그인한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 Guest 계정으로 접속 시도'],
     ['prompt', 'attacker$ smbclient -U Guest% //victim/share'],
     ['', '...빈 비밀번호로 인증...'],
     ['bad', '>> 로그인 성공: Guest (암호 불필요)'],
     ['bad', '>> 공유 파일 열람으로 정보 수집 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 익명 침입','desc':'Guest가 켜져 있어 인증 없이 내부 자원에 접근합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 Guest 로그인 시도'],
     ['prompt', 'attacker$ smbclient -U Guest% //victim/share'],
     ['good', '>> NT_STATUS_ACCOUNT_DISABLED'],
     ['warn', '>> Guest 비활성화로 진입 경로 차단'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — Guest 비활성','desc':'Guest가 꺼져 있어 익명 진입 시도가 거부됩니다.'},
 },
 'W-03': {
   'easy': '쓰지 않는 옛 계정은 <b>잊어버린 여벌 열쇠</b>와 같습니다. 주인은 잊었지만 도둑이 주우면 그대로 문이 열리죠. 퇴직자나 테스트 계정이 살아 있으면 감시 없는 뒷문이 됩니다.',
   'attack_label': '공격자가 방치된 test 계정의 약한 암호를 뚫는다',
   'attack_vuln': [
     ['cmt', '# 공격자가 미사용 계정을 노림'],
     ['prompt', 'attacker$ crackmapexec smb victim -u test -p Test1234'],
     ['', '...관리되지 않던 계정 대입...'],
     ['bad', '>> 로그인 성공: test (오래된 약한 암호)'],
     ['bad', '>> 감시 사각지대 계정으로 잠입 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 유령 계정 악용','desc':'방치된 계정의 약한 암호가 그대로 침투 통로가 됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 test 계정 대입 시도'],
     ['prompt', 'attacker$ crackmapexec smb victim -u test -p Test1234'],
     ['good', '>> 계정 test 가 존재하지 않음'],
     ['warn', '>> 미사용 계정 제거로 진입로 사라짐'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 계정 정리','desc':'불필요 계정을 제거해 공격자가 노릴 대상이 없습니다.'},
 },
 'W-04': {
   'easy': '잠금 정책이 없으면 도둑이 <b>비밀번호 자물쇠를 무한정 돌려볼 수</b> 있습니다. 0000부터 9999까지 천천히 다 시도하면 언젠가 열리죠. 몇 번 틀리면 잠기게 하면 이 게임이 끝납니다.',
   'attack_label': '공격자가 잠금 없는 계정에 온라인 무차별 대입을 한다',
   'attack_vuln': [
     ['cmt', '# 실패해도 잠기지 않으니 계속 대입'],
     ['prompt', 'attacker$ hydra -l svc_adm -P 10million.txt rdp://victim'],
     ['', '...수만 번 시도, 잠금 없음...'],
     ['bad', '>> 비밀번호 발견: Summer2024!'],
     ['bad', '>> 무차별 대입으로 계정 탈취 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 무차별 대입','desc':'잠금이 없어 무제한 시도 끝에 비밀번호가 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 대량 대입 시도'],
     ['prompt', 'attacker$ hydra -l svc_adm -P 10million.txt rdp://victim'],
     ['good', '>> 5회 실패 후 계정 잠김 (60분)'],
     ['warn', '>> 더 이상 시도 불가, 대입 무력화'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 계정 잠금','desc':'5회 실패 시 잠겨 무차별 대입을 멈추게 합니다.'},
 },
 'W-05': {
   'easy': '되돌릴 수 있는 암호화는 비밀번호를 <b>연필로 쓴 글씨</b>로 보관하는 것과 같습니다. 지우개(복호화 키)만 있으면 원문이 그대로 드러나죠. 암호는 되돌릴 수 없게 보관해야 안전합니다.',
   'attack_label': '공격자가 저장된 암호를 평문으로 복원한다',
   'attack_vuln': [
     ['cmt', '# 되돌릴 수 있는 암호화로 저장된 자격증명'],
     ['prompt', 'attacker$ 도메인 비밀 복호화 도구 실행'],
     ['', '...ClearTextPassword 정책이 켜진 상태...'],
     ['bad', '>> 복원된 평문: P@ssw0rd! (원문 그대로)'],
     ['bad', '>> 비밀번호 평문 확보 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 평문 복원','desc':'복구 가능 저장이라 비밀번호가 원문으로 되살아납니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 평문 복원 시도'],
     ['prompt', 'attacker$ 도메인 비밀 복호화 도구 실행'],
     ['good', '>> 단방향 해시만 존재, 원문 복원 불가'],
     ['warn', '>> 평문 추출 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 단방향 저장','desc':'되돌릴 수 없게 저장해 원문 복원이 불가능합니다.'},
 },
 'W-06': {
   'easy': '복잡성 정책이 없으면 사용자가 <b>1234 같은 단순 암호</b>를 그대로 씁니다. 이런 암호는 사전에 다 들어 있어 한순간에 깨지죠. 대소문자·숫자·기호를 섞게 강제하면 추측이 어려워집니다.',
   'attack_label': '공격자가 사전 단어로 단순 암호를 맞춘다',
   'attack_vuln': [
     ['cmt', '# 복잡성 미적용으로 단순 암호 허용'],
     ['prompt', 'attacker$ hydra -l user -P common-words.txt smb://victim'],
     ['', '...흔한 단어 위주 대입...'],
     ['bad', '>> 비밀번호 발견: password (단순 단어)'],
     ['bad', '>> 사전 공격으로 즉시 탈취'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 사전 공격','desc':'단순 암호가 허용되어 흔한 단어로 바로 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 단순 단어 대입'],
     ['prompt', 'attacker$ hydra -l user -P common-words.txt smb://victim'],
     ['good', '>> 단순 단어 암호는 정책상 설정 불가'],
     ['warn', '>> 사전 단어가 전부 빗나감'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 복잡성 강제','desc':'복잡한 암호만 허용되어 사전 공격이 통하지 않습니다.'},
 },
 'W-07': {
   'easy': '짧은 암호는 <b>자릿수가 적은 자전거 자물쇠</b>와 같습니다. 4자리는 1만 가지뿐이라 금방 다 돌려보죠. 길이를 늘리면 경우의 수가 폭발해 깨기 어려워집니다.',
   'attack_label': '공격자가 짧은 암호 전수 대입(무차별)을 한다',
   'attack_vuln': [
     ['cmt', '# 최소 길이 0, 짧은 암호 허용'],
     ['prompt', 'attacker$ hashcat -a 3 hash.txt ?a?a?a?a (4자리 전수)'],
     ['', '...4자리 모든 조합 빠르게 탐색...'],
     ['bad', '>> 짧은 암호 ab1! 수초 만에 크랙'],
     ['bad', '>> 전수 대입으로 암호 복구 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 전수 대입','desc':'암호가 짧아 모든 조합을 빠르게 다 시도해 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 전수 대입 시도'],
     ['prompt', 'attacker$ hashcat -a 3 hash.txt (8자 이상 조합)'],
     ['good', '>> 경우의 수 폭증, 수백 년 소요 추정'],
     ['warn', '>> 현실적으로 크랙 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 충분한 길이','desc':'8자 이상이면 조합이 폭증해 전수 대입이 무의미해집니다.'},
 },
 'W-08': {
   'easy': '암호를 영영 안 바꾸면, 한 번 유출된 비밀번호가 <b>평생 유효한 출입증</b>이 됩니다. 정기적으로 바꾸면 옛날에 새어 나간 암호는 폐기되죠. 만료 기간이 방어선입니다.',
   'attack_label': '공격자가 과거 유출된 암호를 계속 재사용한다',
   'attack_vuln': [
     ['cmt', '# 2년 전 유출된 암호, 만료 없음'],
     ['prompt', 'attacker$ crackmapexec smb victim -u admin -p Old#Leak2022'],
     ['', '...오래된 유출 암호 그대로 입력...'],
     ['bad', '>> 로그인 성공: 암호가 아직 유효'],
     ['bad', '>> 묵은 유출 자격증명으로 침투 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 묵은 암호 재사용','desc':'암호가 만료되지 않아 과거 유출본이 계속 통합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 유출 암호 재사용 시도'],
     ['prompt', 'attacker$ crackmapexec smb victim -u admin -p Old#Leak2022'],
     ['good', '>> 90일 주기로 변경되어 이미 폐기됨'],
     ['warn', '>> 옛 암호로는 인증 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 주기적 변경','desc':'암호가 정기 만료되어 과거 유출본이 무효가 됩니다.'},
 },
 'W-09': {
   'easy': '공유에 Everyone 모든 권한은 <b>창고 문을 활짝 열고 모두 환영</b> 푯말을 붙인 격입니다. 누구나 들어와 물건을 가져가고 바꿔치기까지 하죠. 필요한 사람에게만 열어야 합니다.',
   'attack_label': '공격자가 Everyone 공유에 접속해 파일을 변조한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 Data 공유에 접속'],
     ['prompt', 'attacker$ smbclient //victim/Data -N'],
     ['', '...Everyone 전체 권한으로 접근...'],
     ['bad', '>> 파일 다운로드/수정/삭제 모두 가능'],
     ['bad', '>> 업무 파일 변조·탈취 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 공유 무단 접근','desc':'Everyone 전체 권한이라 누구나 파일을 읽고 바꿉니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 공유 접속 시도'],
     ['prompt', 'attacker$ smbclient //victim/Data -N'],
     ['good', '>> NT_STATUS_ACCESS_DENIED'],
     ['warn', '>> 허가된 그룹만 읽기 가능, 접근 거부'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 최소 권한','desc':'Everyone을 제거해 권한 없는 접근이 거부됩니다.'},
 },
 'W-10': {
   'easy': '관리용 기본 공유(C드라이브 관리 공유 등)는 <b>건물 전체로 통하는 관리인 통로</b>입니다. 관리인 열쇠를 손에 넣은 침입자는 이 통로로 옆방 옆방을 다 넘나들죠. 불필요하면 막아야 합니다.',
   'attack_label': '공격자가 C$ 관리 공유로 측면 이동한다',
   'attack_vuln': [
     ['cmt', '# 탈취한 자격증명으로 관리 공유 접속'],
     ['prompt', 'attacker$ victim 호스트의 C$ 관리 공유에 접속'],
     ['', '...자동 생성된 C드라이브 관리 공유...'],
     ['bad', '>> C드라이브 전체 파일 시스템 노출'],
     ['bad', '>> 측면 이동으로 내부 확산 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 측면 이동','desc':'기본 관리 공유로 시스템 전체에 원격 접근합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 C$ 관리 공유 접속 시도'],
     ['prompt', 'attacker$ victim 호스트의 C$ 관리 공유에 접속'],
     ['good', '>> 공유를 찾을 수 없음 (자동 공유 해제)'],
     ['warn', '>> 관리 공유 경로 차단'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 기본 공유 제거','desc':'자동 관리 공유를 꺼서 측면 이동 통로를 없앱니다.'},
 },
 'W-11': {
   'easy': '안 쓰는 서비스를 켜 두는 건 <b>안 쓰는 문을 계속 열어 두는 것</b>과 같습니다. 문이 많을수록 도둑이 노릴 곳도 많아지죠. Telnet 같은 위험 서비스는 특히 평문으로 비밀번호를 흘립니다.',
   'attack_label': '공격자가 켜진 Telnet으로 평문 접속·도청한다',
   'attack_vuln': [
     ['cmt', '# 불필요하게 켜진 Telnet 노림'],
     ['prompt', 'attacker$ telnet victim 23'],
     ['', '...평문 인증 서비스에 접속...'],
     ['bad', '>> 로그인 입력이 평문으로 오감, 도청 가능'],
     ['bad', '>> 위험 서비스 통해 접근 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 위험 서비스 악용','desc':'불필요한 Telnet이 켜져 있어 평문 접근이 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 Telnet 접속 시도'],
     ['prompt', 'attacker$ telnet victim 23'],
     ['good', '>> Connection refused (서비스 중지)'],
     ['warn', '>> 공격 표면이 줄어 접근 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 서비스 제거','desc':'불필요 서비스를 꺼서 노릴 문 자체를 없앱니다.'},
 },
 'W-12': {
   'easy': '디렉터리 리스팅은 <b>도서관 서가를 통째로 공개</b>하는 것과 같습니다. 방문자가 모든 책 제목을 훑어보다 숨겨둔 비밀 노트(백업 파일)까지 발견하죠. 목록을 가려야 합니다.',
   'attack_label': '공격자가 디렉터리 목록에서 백업 파일을 찾는다',
   'attack_vuln': [
     ['cmt', '# 디렉터리 검색 켜진 IIS 탐색'],
     ['prompt', 'attacker$ curl http://victim/uploads/'],
     ['', '...폴더 내 파일 목록이 그대로 출력...'],
     ['bad', '>> backup.zip, web.config.bak 노출'],
     ['bad', '>> 백업 파일 받아 설정·소스 유출 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 정보 노출','desc':'파일 목록이 드러나 숨은 백업까지 다운로드됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 디렉터리 탐색 시도'],
     ['prompt', 'attacker$ curl http://victim/uploads/'],
     ['good', '>> 403 Forbidden (목록 비표시)'],
     ['warn', '>> 파일 이름을 알 수 없어 수집 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 목록 비공개','desc':'디렉터리 검색을 꺼서 숨은 파일이 노출되지 않습니다.'},
 },
 'W-13': {
   'easy': 'NLA 없는 RDP를 전체 개방하면 <b>현관을 인증 없이 두드릴 수</b> 있게 둔 셈입니다. 누구나 로그인 창까지 와서 비밀번호를 무한정 두드리죠. NLA는 문 앞에서 신분증부터 검사합니다.',
   'attack_label': '공격자가 개방된 RDP에 무차별 대입한다',
   'attack_vuln': [
     ['cmt', '# NLA 없이 전체 개방된 RDP'],
     ['prompt', 'attacker$ hydra -l admin -P pass.txt rdp://victim:3389'],
     ['', '...인증 전 단계까지 도달해 대입...'],
     ['bad', '>> 비밀번호 적중, RDP 세션 획득'],
     ['bad', '>> 원격 데스크톱 장악 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — RDP 탈취','desc':'NLA 미적용·전체 개방이라 대입으로 원격 접속을 뺏깁니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 RDP 대입 시도'],
     ['prompt', 'attacker$ hydra -l admin -P pass.txt rdp://victim:3389'],
     ['good', '>> 허용 IP 아님 + NLA 사전 인증 요구'],
     ['warn', '>> 연결 거부, 대입 단계 진입 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — NLA·IP 제한','desc':'NLA와 IP 제한으로 대입 시도 자체가 막힙니다.'},
 },
 'W-14': {
   'easy': 'SNMP의 기본 community(public/private)는 <b>누구나 아는 공용 비밀번호</b>입니다. 이 단어 하나면 장비 내부 정보를 줄줄 읽고 설정까지 바꾸죠. 추측 어려운 값으로 바꿔야 합니다.',
   'attack_label': '공격자가 기본 community로 시스템 정보를 캔다',
   'attack_vuln': [
     ['cmt', '# 기본 community public 추측'],
     ['prompt', 'attacker$ snmpwalk -c public -v2c victim'],
     ['', '...기본값 그대로 인증 통과...'],
     ['bad', '>> 호스트명, 사용자, 네트워크 정보 노출'],
     ['bad', '>> 기본 community로 정보 수집 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — SNMP 정보 노출','desc':'기본 community라 시스템 내부 정보가 그대로 읽힙니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 public 으로 조회 시도'],
     ['prompt', 'attacker$ snmpwalk -c public -v2c victim'],
     ['good', '>> Timeout: 기본 community 거부'],
     ['warn', '>> 허용 호스트도 아니라 응답 없음'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — community 강화','desc':'기본값을 제거하고 호스트를 제한해 조회가 막힙니다.'},
 },
 'W-15': {
   'easy': 'DNS 영역 전송을 누구에게나 허용하면 <b>회사 전화번호부 전체를 복사해 가게</b> 두는 것과 같습니다. 공격자는 모든 서버·호스트 이름을 한 번에 받아 표적 지도를 그리죠.',
   'attack_label': '공격자가 영역 전송으로 전체 DNS 정보를 받아간다',
   'attack_vuln': [
     ['cmt', '# 누구나 영역 전송 가능한 DNS'],
     ['prompt', 'attacker$ dig axfr victim.com @victim-dns'],
     ['', '...전체 영역 레코드 전송 요청...'],
     ['bad', '>> 모든 호스트·서버 레코드 통째 수신'],
     ['bad', '>> 내부 자산 지도 확보 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 영역 전송 유출','desc':'전송 제한이 없어 도메인 전체 구성이 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 영역 전송 요청'],
     ['prompt', 'attacker$ dig axfr victim.com @victim-dns'],
     ['good', '>> Transfer failed (지정 서버만 허용)'],
     ['warn', '>> 인가된 보조 서버 외에는 거부'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 전송 제한','desc':'지정 서버로만 전송을 제한해 정보 수집을 막습니다.'},
 },
 'W-16': {
   'easy': '미적용 패치는 <b>이미 공개된 자물쇠 결함을 그대로 둔 문</b>입니다. 공격자는 인터넷에 공개된 공격 코드를 그대로 받아 실행하면 끝이죠. 패치는 알려진 구멍을 메웁니다.',
   'attack_label': '공격자가 공개된 취약점 익스플로잇을 실행한다',
   'attack_vuln': [
     ['cmt', '# 18개월 미패치 시스템 노림'],
     ['prompt', 'attacker$ msfconsole 으로 알려진 RCE 익스플로잇 실행'],
     ['', '...공개된 취약점 코드 적용...'],
     ['bad', '>> 원격 코드 실행 성공, SYSTEM 권한 획득'],
     ['bad', '>> 알려진 취약점으로 완전 장악'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 익스플로잇','desc':'미패치 취약점이라 공개 공격 코드만으로 장악됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 알려진 익스플로잇 실행'],
     ['prompt', 'attacker$ msfconsole 으로 동일 익스플로잇 실행'],
     ['good', '>> 대상 패치 적용됨, 취약점 닫힘'],
     ['warn', '>> 익스플로잇 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 패치 적용','desc':'최신 패치로 알려진 취약점이 막혀 공격이 실패합니다.'},
 },
 'W-17': {
   'easy': '감사 정책이 없으면 건물에 <b>CCTV가 한 대도 없는</b> 것과 같습니다. 누가 언제 드나들었는지 기록이 없어 사고가 나도 추적이 불가능하죠. 감사 로그가 보안의 눈입니다.',
   'attack_label': '공격자가 로그를 남기지 않고 침투·활동한다',
   'attack_vuln': [
     ['cmt', '# 감사 미설정으로 흔적이 안 남음'],
     ['prompt', 'attacker$ 로그온 실패/성공 반복 후 침투'],
     ['', '...어떤 보안 이벤트도 기록되지 않음...'],
     ['bad', '>> 침입·권한 사용 기록이 전혀 없음'],
     ['bad', '>> 추적 불가 상태로 활동 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 무흔적 침투','desc':'감사가 꺼져 있어 공격 활동이 기록되지 않습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 침투 시도'],
     ['prompt', 'attacker$ 로그온 실패/성공 반복 후 침투'],
     ['good', '>> 실패/성공 이벤트가 보안 로그에 기록'],
     ['warn', '>> SIEM 경보 발생, 탐지·추적됨'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 감사 기록','desc':'주요 이벤트가 기록되어 침입이 탐지·추적됩니다.'},
 },
 'W-18': {
   'easy': '원격 레지스트리 경로를 넓게 열어 두면, <b>집 설계도 캐비닛을 외부에서 열람</b>하게 두는 셈입니다. 공격자는 내부 구성과 설정을 원격으로 읽고 변조하죠. 경로를 최소화해야 합니다.',
   'attack_label': '공격자가 원격 레지스트리로 설정을 읽어낸다',
   'attack_vuln': [
     ['cmt', '# 원격 레지스트리 광범위 허용'],
     ['prompt', 'attacker$ reg connect 으로 원격 레지스트리 접속'],
     ['', '...허용 경로가 넓어 다수 키 열람...'],
     ['bad', '>> 시스템 구성·자격 관련 키 노출'],
     ['bad', '>> 원격 레지스트리 정보 수집 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 원격 열람','desc':'허용 경로가 넓어 원격으로 설정 정보가 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 원격 레지스트리 접속'],
     ['prompt', 'attacker$ reg connect 으로 원격 레지스트리 접속'],
     ['good', '>> RemoteRegistry 중지, 연결 거부'],
     ['warn', '>> 허용 경로 최소화로 열람 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 경로 최소화','desc':'원격 접근을 막고 경로를 줄여 열람을 차단합니다.'},
 },
 'W-19': {
   'easy': '로그 용량이 작고 덮어쓰기로 두면, <b>오래된 CCTV 영상이 몇 시간 만에 지워지는</b> 것과 같습니다. 정작 사고를 분석하려 할 때 결정적 장면이 이미 사라져 있죠.',
   'attack_label': '공격자가 로그를 밀어내 침입 흔적을 지운다',
   'attack_vuln': [
     ['cmt', '# 작은 로그+덮어쓰기 설정 악용'],
     ['prompt', 'attacker$ 대량 이벤트를 발생시켜 로그 가득 채움'],
     ['', '...512KB 로그가 금세 가득 차 덮어씀...'],
     ['bad', '>> 침입 시점의 로그가 밀려 사라짐'],
     ['bad', '>> 흔적 소실로 분석 회피 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 흔적 소실','desc':'로그가 작아 덮어쓰기로 침입 기록이 사라집니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 로그 채우기 시도'],
     ['prompt', 'attacker$ 대량 이벤트를 발생시켜 로그 채움'],
     ['good', '>> 200MB 보관+중앙 전송으로 원본 유지'],
     ['warn', '>> 흔적이 보존되어 분석 가능'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 로그 보존','desc':'충분한 용량과 중앙 전송으로 흔적이 보존됩니다.'},
 },
 'W-20': {
   'easy': '자리 비움 시 화면이 안 잠기면, <b>책상에 열쇠 꽂힌 채 자리를 비우는</b> 것과 같습니다. 잠깐 지나가던 사람이 그대로 앉아 일을 벌이죠. 자동 잠금이 물리적 방어선입니다.',
   'attack_label': '물리 접근자가 잠기지 않은 세션을 탈취한다',
   'attack_vuln': [
     ['cmt', '# 관리자가 자리를 비운 사이'],
     ['prompt', 'attacker$ 잠기지 않은 콘솔 앞에 앉음'],
     ['', '...화면 자동 잠금 미설정...'],
     ['bad', '>> 로그인된 관리자 세션 그대로 사용'],
     ['bad', '>> 세션 탈취로 명령 실행 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 세션 탈취','desc':'화면이 안 잠겨 물리 접근자가 세션을 가로챕니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 콘솔 앞에 앉음'],
     ['prompt', 'attacker$ 자리 비운 콘솔 앞에 앉음'],
     ['good', '>> 10분 후 잠김, 암호 입력 요구'],
     ['warn', '>> 암호 없이는 세션 사용 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 자동 잠금','desc':'일정 시간 후 잠겨 물리 세션 탈취를 막습니다.'},
 },
 'W-21': {
   'easy': '로그온 없이 종료를 허용하면, <b>누구나 건물 메인 전원을 끌 수</b> 있게 둔 셈입니다. 비인가자가 로그인 화면에서 종료 버튼만 눌러 서비스를 멈추죠.',
   'attack_label': '비인가자가 로그인 화면에서 시스템을 종료한다',
   'attack_vuln': [
     ['cmt', '# 로그온 없는 종료 허용'],
     ['prompt', 'attacker$ 로그인 화면의 전원 메뉴 클릭'],
     ['', '...인증 없이 종료 버튼 노출...'],
     ['bad', '>> 시스템 종료 실행됨'],
     ['bad', '>> 비인가 종료로 서비스 중단(DoS) 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 서비스 중단','desc':'인증 없이 종료가 가능해 서비스가 강제로 멈춥니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 종료 시도'],
     ['prompt', 'attacker$ 로그인 화면에서 종료 시도'],
     ['good', '>> 종료 옵션이 표시되지 않음'],
     ['warn', '>> 인증된 사용자만 종료 가능'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 종료 제한','desc':'로그온 없는 종료를 막아 무단 중단을 방지합니다.'},
 },
 'W-22': {
   'easy': '익명 SID/이름 변환을 허용하면, <b>이름표 없이도 사번을 대면 누구 직원인지 알려주는</b> 안내데스크와 같습니다. 공격자는 이걸로 실제 계정 이름들을 줄줄이 알아내죠.',
   'attack_label': '공격자가 익명으로 SID를 계정명으로 변환·열거한다',
   'attack_vuln': [
     ['cmt', '# 익명 SID/이름 변환 허용'],
     ['prompt', 'attacker$ rpcclient -U "" -N victim'],
     ['', '...lookupsids 로 SID를 이름으로 변환...'],
     ['bad', '>> svc_adm07, backup_op 등 계정명 확인'],
     ['bad', '>> 관리자 SID(-500)로 실제 관리자명 노출'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 계정 열거','desc':'익명 변환이 허용되어 실제 계정 이름이 드러납니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 익명 변환 시도'],
     ['prompt', 'attacker$ rpcclient -U "" -N victim'],
     ['good', '>> NT_STATUS_ACCESS_DENIED'],
     ['warn', '>> 익명 변환 차단으로 이름 노출 없음'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 익명 변환 금지','desc':'익명 SID 변환을 막아 계정 열거를 차단합니다.'},
 },
 'W-23': {
   'easy': '익명 사용자에게 Everyone 권한을 주면, <b>"모두 출입 가능" 명단에 익명 손님까지 끼워 넣는</b> 격입니다. 신분을 밝히지 않은 사람도 공유와 자원에 손을 대게 되죠.',
   'attack_label': '익명 접근자가 Everyone 권한으로 자원에 접근한다',
   'attack_vuln': [
     ['cmt', '# 익명에 Everyone 권한 포함'],
     ['prompt', 'attacker$ smbclient //victim/Share -U "" -N'],
     ['', '...익명 세션이 Everyone 권한 획득...'],
     ['bad', '>> Everyone 허용 자원에 익명 접근 성공'],
     ['bad', '>> 인증 없이 공유 리소스 열람 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 익명 권한 획득','desc':'익명이 Everyone에 포함되어 자원에 접근합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 익명 접근 시도'],
     ['prompt', 'attacker$ smbclient //victim/Share -U "" -N'],
     ['good', '>> 익명은 Everyone에서 제외됨'],
     ['warn', '>> 접근 거부, 자원 열람 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 익명 제외','desc':'익명을 Everyone에서 빼 무단 접근을 막습니다.'},
 },
 'W-24': {
   'easy': '약한 NTLM(LM/NTLMv1)은 <b>쉽게 복제되는 구형 자물쇠</b>입니다. 공격자가 통신에서 인증 값을 한 번 가로채면, 깨거나 그대로 중계해 남의 자물쇠를 열죠. NTLMv2만 허용해야 합니다.',
   'attack_label': '공격자가 가로챈 NTLM 해시를 크랙·중계한다',
   'attack_vuln': [
     ['cmt', '# 약한 인증으로 해시 가로채기'],
     ['prompt', 'attacker$ responder 로 NTLMv1 해시 캡처'],
     ['', '...LM/NTLMv1 응답을 수집...'],
     ['bad', '>> 가로챈 해시를 즉시 크랙, 암호 복원'],
     ['bad', '>> 다른 서버로 중계(relay)해 접속 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 해시 크랙·중계','desc':'약한 NTLM이라 가로챈 해시를 깨거나 중계해 침투합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 해시 캡처 시도'],
     ['prompt', 'attacker$ responder 로 인증 응답 캡처'],
     ['good', '>> NTLMv2 응답만 존재, 즉시 크랙 불가'],
     ['warn', '>> 서명 강제로 중계 공격도 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — NTLMv2 강제','desc':'강한 인증만 허용해 크랙·중계가 통하지 않습니다.'},
 },
 'W-25': {
   'easy': 'SAM 익명 열거를 막지 않으면, <b>신분 확인 없이도 직원 명부와 창고 목록을 보여주는</b> 안내소가 됩니다. 공격자는 로그인도 없이 계정·공유 목록을 손에 넣어 다음 공격을 준비하죠.',
   'attack_label': '공격자가 익명 세션으로 계정·공유 목록을 열거한다',
   'attack_vuln': [
     ['cmt', '# RestrictAnonymous 미설정'],
     ['prompt', 'attacker$ enum4linux -a victim'],
     ['', '...익명 세션으로 SAM 열거...'],
     ['bad', '>> 사용자 목록·그룹·공유 전부 노출'],
     ['bad', '>> 표적 계정·자원 목록 확보 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 익명 열거','desc':'익명 열거가 허용되어 계정·공유 목록이 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 익명 열거 시도'],
     ['prompt', 'attacker$ enum4linux -a victim'],
     ['good', '>> 익명 세션 접근 거부, 목록 비공개'],
     ['warn', '>> 계정·공유 열거 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 익명 열거 제한','desc':'익명 열거를 막아 사전 정찰을 차단합니다.'},
 },
 'W-26': {
   'easy': '자동 로그온은 편하지만, 비밀번호를 <b>현관 매트 밑에 적어 두는</b> 것과 같습니다. 레지스트리에 평문으로 적힌 암호를 누구든 읽을 수 있고, 부팅만 하면 바로 로그인되죠.',
   'attack_label': '공격자가 레지스트리에서 평문 암호를 읽어낸다',
   'attack_vuln': [
     ['cmt', '# 자동 로그온 켜진 상태'],
     ['prompt', 'attacker$ 레지스트리 Winlogon 키의 DefaultPassword 조회'],
     ['', '...AutoAdminLogon=1 로 평문 저장됨...'],
     ['bad', '>> DefaultPassword: P@ssw0rd! (평문 노출)'],
     ['bad', '>> 관리자 암호 평문 확보 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 평문 암호 노출','desc':'자동 로그온이라 레지스트리에서 암호가 그대로 읽힙니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 DefaultPassword 조회'],
     ['prompt', 'attacker$ 레지스트리 Winlogon 키의 DefaultPassword 조회'],
     ['good', '>> AutoAdminLogon=0, DefaultPassword 없음'],
     ['warn', '>> 평문 암호가 저장돼 있지 않아 추출 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 자동 로그온 해제','desc':'자동 로그온을 끄고 평문 암호를 제거해 노출을 막습니다.'},
 },
 'W-27': {
   'easy': '백신이 없거나 시그니처가 낡으면, <b>유행 중인 감기 예방주사를 안 맞은</b> 것과 같습니다. 흔한 악성코드·랜섬웨어가 걸러지지 않고 그대로 실행되죠. 실시간 보호와 최신 갱신이 핵심입니다.',
   'attack_label': '공격자가 알려진 악성코드를 무방비로 실행시킨다',
   'attack_vuln': [
     ['cmt', '# 실시간 보호 꺼짐, 시그니처 60일'],
     ['prompt', 'attacker$ 알려진 랜섬웨어 페이로드 투입'],
     ['', '...탐지 엔진이 동작하지 않음...'],
     ['bad', '>> 악성코드 실행됨, 파일 암호화 시작'],
     ['bad', '>> 무방비 상태로 감염 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 악성코드 감염','desc':'보호가 꺼져 있어 알려진 악성코드도 그대로 실행됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 악성 페이로드 투입'],
     ['prompt', 'attacker$ 알려진 랜섬웨어 페이로드 투입'],
     ['good', '>> 실시간 보호가 즉시 탐지·격리'],
     ['warn', '>> 실행 차단, 감염 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 실시간 보호','desc':'최신 백신이 악성코드를 탐지·격리해 감염을 막습니다.'},
 },
 'W-28': {
   'easy': '시각이 동기화되지 않으면, 여러 CCTV의 <b>시계가 제각각</b>인 것과 같습니다. 사고 영상을 모아도 순서가 뒤죽박죽이라 무슨 일이 먼저 났는지 알 수 없죠. NTP가 모든 시계를 맞춰 줍니다.',
   'attack_label': '공격자가 시각 불일치를 틈타 사고 분석을 방해한다',
   'attack_vuln': [
     ['cmt', '# 시각 미동기화, 서버마다 시간 어긋남'],
     ['prompt', 'attacker$ 여러 서버를 거치며 침투'],
     ['', '...각 로그의 타임스탬프가 제각각...'],
     ['bad', '>> 로그 시각이 어긋나 공격 순서 재구성 불가'],
     ['bad', '>> 상관분석 방해로 추적 회피 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 분석 방해','desc':'시각이 어긋나 로그 상관분석과 추적이 어려워집니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 침투, 시각은 동기화됨'],
     ['prompt', 'attacker$ 여러 서버를 거치며 침투'],
     ['good', '>> 모든 로그 타임스탬프가 일관됨'],
     ['warn', '>> 시간순 상관분석으로 경로 추적 성공'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 시각 동기화','desc':'NTP로 시각을 맞춰 정확한 사고 분석과 추적이 가능합니다.'},
 },
}
