# -*- coding: utf-8 -*-
DYN = {
 'U-34': {
   'easy': 'Finger 서비스는 회사 <b>전 직원 명단</b>을 현관에 붙여 둔 것과 같습니다. 누가 언제 출근했는지, 자리는 어디인지 외부인이 다 볼 수 있죠. 공격자는 이 명단으로 공격할 계정을 손쉽게 고릅니다.',
   'attack_label': '공격자가 원격에서 시스템 사용자 목록을 캐낸다',
   'attack_vuln': [
     ['cmt', '# 공격자가 finger로 서버 사용자 정보를 조회'],
     ['prompt', 'attacker$ finger @victim.com'],
     ['', 'Login    Name       TTY   Idle  Login Time'],
     ['bad', '>> admin    Administrator  pts/0   1d  Jun 19'],
     ['bad', '>> oracle   DB Operator    -       -   계정 명단 확보'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 계정 명단 유출', 'desc': 'Finger가 켜져 있어 로그인명과 활동 정보가 인증 없이 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 공격을 안전한 설정에서 시도'],
     ['prompt', 'attacker$ finger @victim.com'],
     ['good', '>> connect: Connection refused'],
     ['warn', '>> 사용자 목록을 얻을 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 조회 거부', 'desc': 'Finger를 비활성화하여 외부에서 사용자 정보를 조회할 수 없습니다.'},
 },
 'U-35': {
   'easy': '익명 FTP는 <b>잠그지 않은 창고 문</b>과 같습니다. 이름도 묻지 않고 아무나 들어와 물건을 가져가거나 쓰레기를 버릴 수 있죠. 공격자는 자료를 빼가거나 악성파일을 올려 둡니다.',
   'attack_label': '공격자가 인증 없이 FTP로 파일을 빼가거나 올린다',
   'attack_vuln': [
     ['cmt', '# 공격자가 anonymous 계정으로 로그인'],
     ['prompt', 'attacker$ ftp victim.com'],
     ['', 'Name: anonymous   Password: (아무거나)'],
     ['bad', '>> 230 Login successful.'],
     ['bad', '>> get backup.sql / put shell.php  자료 탈취+업로드'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무인증 파일 접근', 'desc': '익명 접속이 허용되어 누구나 파일을 내려받고 올릴 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 anonymous 로그인을 시도'],
     ['prompt', 'attacker$ ftp victim.com'],
     ['good', '>> 530 Login incorrect.'],
     ['warn', '>> 익명 접속이 거부되어 진입 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 익명 차단', 'desc': 'anonymous_enable=NO로 인증 없는 접속을 막아 파일에 접근할 수 없습니다.'},
 },
 'U-36': {
   'easy': 'r 계열 서비스는 <b>옆집이라고 말하면 그냥 들여보내는 경비</b>와 같습니다. 신분 확인 없이 신뢰만으로 문을 열어 주고, 대화 내용도 평문이라 엿들리죠. 공격자는 신뢰 관계를 흉내 내 그대로 들어옵니다.',
   'attack_label': '공격자가 신뢰관계를 악용해 비밀번호 없이 접속한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 rlogin으로 신뢰 기반 접속 시도'],
     ['prompt', 'attacker$ rlogin victim.com -l root'],
     ['', '.rhosts 신뢰 항목 확인 중 ...'],
     ['bad', '>> Last login: ... 비밀번호 없이 통과'],
     ['bad', '>> victim# root 쉘 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 인증 우회', 'desc': 'r 서비스의 신뢰기반 인증으로 비밀번호 없이 접속이 허용됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 rlogin 접속을 시도'],
     ['prompt', 'attacker$ rlogin victim.com -l root'],
     ['good', '>> connect: Connection refused'],
     ['warn', '>> SSH만 열려 있어 신뢰 악용 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 서비스 비활성', 'desc': 'r 서비스를 끄고 SSH로 대체하여 신뢰기반 우회가 통하지 않습니다.'},
 },
 'U-37': {
   'easy': 'cron 접근제어가 없으면 <b>누구나 회사 자동화 스위치를 만질 수 있는</b> 상태입니다. 일반 직원이 한밤중에 몰래 실행될 작업을 심어 둘 수 있죠. 공격자는 이를 이용해 관리자 권한을 노립니다.',
   'attack_label': '일반 사용자가 예약작업으로 권한 상승을 노린다',
   'attack_vuln': [
     ['cmt', '# 권한 없는 사용자가 cron에 작업 등록'],
     ['prompt', 'user$ crontab -e   (제한 없음)'],
     ['', '* * * * * cp /bin/sh /tmp/s; chmod 4755 /tmp/s'],
     ['bad', '>> 작업이 정상 등록됨 (no restriction)'],
     ['bad', '>> /tmp/s 실행 → root 권한 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 권한 상승', 'desc': 'cron 사용이 통제되지 않아 일반 사용자가 악성 예약작업을 심을 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 일반 사용자가 cron 등록 시도'],
     ['prompt', 'user$ crontab -e'],
     ['good', '>> You are not allowed to use this program'],
     ['warn', '>> cron.allow에 없어 작업 등록 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 사용 제한', 'desc': 'cron.allow로 허용 계정만 등록 가능해 일반 사용자는 작업을 만들 수 없습니다.'},
 },
 'U-38': {
   'easy': 'echo/chargen 같은 단순 서비스는 <b>아무 말이나 외치면 똑같이 메아리쳐 주는 확성기</b>와 같습니다. 공격자가 남의 주소를 사칭해 외치면 메아리가 피해자에게 쏟아지죠. 트래픽을 증폭해 마비시키는 데 악용됩니다.',
   'attack_label': '공격자가 단순 서비스로 증폭 DoS를 일으킨다',
   'attack_vuln': [
     ['cmt', '# 공격자가 피해자 IP를 사칭해 chargen 자극'],
     ['prompt', 'attacker$ hping3 --udp -p 19 -a victim srv'],
     ['', 'chargen(19)이 끝없는 문자열을 응답 생성'],
     ['bad', '>> 응답 폭주가 victim에게 반사됨'],
     ['bad', '>> 대역폭 포화 → 서비스 마비'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 증폭 DoS', 'desc': '단순 서비스가 열려 있어 반사·증폭 공격의 발판이 됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 chargen 포트를 자극 시도'],
     ['prompt', 'attacker$ hping3 --udp -p 19 -a victim srv'],
     ['good', '>> ICMP port unreachable (응답 없음)'],
     ['warn', '>> 증폭에 쓸 서비스가 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 서비스 제거', 'desc': 'echo/discard/daytime/chargen을 비활성화하여 증폭 발판이 사라집니다.'},
 },
 'U-39': {
   'easy': 'NFS를 열어 두는 것은 <b>회사 공용 폴더를 인터넷에 그대로 붙여 둔</b> 것과 같습니다. 누가 마운트할 수 있는지 따지지 않으면 외부인이 통째로 가져갈 수 있죠. 공격자는 원격에서 디스크를 통째로 들여다봅니다.',
   'attack_label': '공격자가 원격에서 NFS 공유를 통째로 마운트한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 export된 공유 목록을 조회'],
     ['prompt', 'attacker$ showmount -e victim.com'],
     ['', 'Export list for victim.com:'],
     ['bad', '>> /data *  (모두에게 공개)'],
     ['bad', '>> mount victim:/data /mnt → 파일 전부 열람'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 원격 마운트', 'desc': '불필요한 NFS가 구동되어 외부에서 파일시스템을 마운트할 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 export 목록을 조회 시도'],
     ['prompt', 'attacker$ showmount -e victim.com'],
     ['good', '>> clnt_create: RPC: Program not registered'],
     ['warn', '>> 마운트할 공유를 찾을 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 데몬 중지', 'desc': 'NFS 데몬을 중지하여 원격 마운트 자체가 불가능합니다.'},
 },
 'U-40': {
   'easy': 'NFS를 everyone에게 여는 것은 <b>창고 열쇠를 복사해 길거리에 뿌리는</b> 것과 같습니다. 특정 사람만 받게 하지 않으면 아무나 들어와 물건을 바꿔치기하죠. 공격자는 root 권한까지 흉내 내 파일을 조작합니다.',
   'attack_label': '공격자가 공개 공유를 마운트해 데이터를 변조한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 * 공유를 자기 PC에 마운트'],
     ['prompt', 'attacker$ mount -t nfs victim:/data /mnt'],
     ['', '/data가 *(rw,no_root_squash)로 공개됨'],
     ['bad', '>> root 권한으로 파일 쓰기 가능'],
     ['bad', '>> 중요 파일 변조 + 백도어 삽입 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 데이터 변조', 'desc': 'everyone(*) + no_root_squash로 누구나 root 권한 쓰기가 가능합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 공유 마운트를 시도'],
     ['prompt', 'attacker$ mount -t nfs victim:/data /mnt'],
     ['good', '>> access denied by server'],
     ['warn', '>> 허용 호스트가 아니라 마운트 거부'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 접근통제', 'desc': '허용 호스트만 ro+root_squash로 제한해 외부 변조가 차단됩니다.'},
 },
 'U-41': {
   'easy': 'automountd는 <b>알아서 문을 여닫는 자동문</b>인데, 고장난 센서가 많아 엉뚱한 사람도 통과시키곤 합니다. 알려진 결함이 많아 공격자가 이를 비집고 권한을 높이죠. 안 쓰면 떼어내는 게 안전합니다.',
   'attack_label': '공격자가 automountd 취약점으로 권한을 높인다',
   'attack_vuln': [
     ['cmt', '# 공격자가 automountd RPC 취약점을 노림'],
     ['prompt', 'attacker$ rpcinfo -p victim | grep automount'],
     ['', '100099  3  udp  ...  automountd 등록 확인'],
     ['bad', '>> 알려진 RPC 취약점으로 명령 주입'],
     ['bad', '>> root 권한 코드 실행 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 권한 상승', 'desc': 'automountd가 구동 중이라 알려진 RPC 취약점으로 공격당합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 automountd 등록을 조회 시도'],
     ['prompt', 'attacker$ rpcinfo -p victim | grep automount'],
     ['good', '>> (출력 없음)'],
     ['warn', '>> 공격할 데몬이 존재하지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 데몬 제거', 'desc': 'autofs를 비활성화하여 취약한 RPC 진입점이 사라집니다.'},
 },
 'U-42': {
   'easy': '불필요한 RPC 서비스는 <b>안 쓰는데도 열려 있는 뒷문들</b>입니다. 문이 많을수록 그중 하나는 자물쇠가 고장나 있기 마련이죠. 공격자는 결함이 알려진 뒷문을 찾아 비집고 들어옵니다.',
   'attack_label': '공격자가 취약 RPC 데몬으로 원격 코드를 실행한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 등록된 RPC 서비스를 스캔'],
     ['prompt', 'attacker$ rpcinfo -p victim.com'],
     ['', '100083 ... rpc.ttdbserverd 노출'],
     ['bad', '>> ttdbserverd 버퍼 오버플로우 익스플로잇'],
     ['bad', '>> 원격 코드 실행으로 시스템 장악'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 원격 코드 실행', 'desc': '취약한 RPC 서비스가 살아 있어 알려진 익스플로잇에 그대로 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 RPC 서비스를 스캔 시도'],
     ['prompt', 'attacker$ rpcinfo -p victim.com'],
     ['good', '>> 취약 서비스 미등록 (필수 항목만)'],
     ['warn', '>> 공격 대상 데몬이 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — RPC 최소화', 'desc': '불필요한 RPC를 비활성화해 알려진 취약점의 표적이 사라집니다.'},
 },
 'U-43': {
   'easy': 'NIS는 <b>전 직원 비밀번호 장부를 우편엽서로 돌려 보는</b> 방식입니다. 오가는 도중 누구나 펼쳐 볼 수 있어 계정 정보가 새죠. 공격자는 통신을 엿듣기만 해도 인증정보를 손에 넣습니다.',
   'attack_label': '공격자가 NIS 맵에서 계정·암호 정보를 빼낸다',
   'attack_vuln': [
     ['cmt', '# 공격자가 NIS 도메인의 passwd 맵을 덤프'],
     ['prompt', 'attacker$ ypcat -d corp -h victim passwd'],
     ['', 'NIS 서버가 맵 정보를 평문 응답'],
     ['bad', '>> root:x:0:0... / user:HASH... 계정 노출'],
     ['bad', '>> 해시 크랙으로 다수 계정 탈취'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 계정정보 유출', 'desc': 'NIS가 맵 정보를 평문으로 제공해 전체 계정이 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 passwd 맵 덤프를 시도'],
     ['prompt', 'attacker$ ypcat -d corp -h victim passwd'],
     ['good', '>> Cant bind to server (NIS 미구동)'],
     ['warn', '>> 맵 정보를 얻을 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — NIS 비활성', 'desc': 'NIS를 끄고 LDAPS로 대체하여 평문 계정정보 유출이 차단됩니다.'},
 },
 'U-44': {
   'easy': 'tftp는 <b>이름도 안 묻고 택배를 내주는 무인 보관함</b>과 같습니다. 아무나 와서 안의 파일을 가져갈 수 있죠. 공격자는 설정파일이나 부팅 이미지를 손쉽게 빼냅니다.',
   'attack_label': '공격자가 인증 없이 tftp로 시스템 파일을 가져간다',
   'attack_vuln': [
     ['cmt', '# 공격자가 tftp로 설정파일을 요청'],
     ['prompt', 'attacker$ tftp victim.com -c get /etc/passwd'],
     ['', '인증 절차 없이 파일 전송 시작'],
     ['bad', '>> Received 1843 bytes'],
     ['bad', '>> /etc/passwd 등 민감 파일 탈취 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무인증 파일 탈취', 'desc': 'tftp가 인증 없이 파일을 내주어 민감 파일이 그대로 유출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 tftp로 파일을 요청'],
     ['prompt', 'attacker$ tftp victim.com -c get /etc/passwd'],
     ['good', '>> Transfer timed out (서비스 없음)'],
     ['warn', '>> 파일을 가져올 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 서비스 비활성', 'desc': 'tftp/talk/ntalk를 비활성화해 무인증 파일 전송이 불가능합니다.'},
 },
 'U-45': {
   'easy': '구버전 Sendmail은 <b>도둑이 여는 법을 다 아는 옛날 자물쇠</b>입니다. 공개된 약점이 많아 누구나 손쉽게 따죠. 공격자는 버전만 확인하면 맞는 공격을 골라 씁니다.',
   'attack_label': '공격자가 구버전 메일서버의 알려진 취약점을 친다',
   'attack_vuln': [
     ['cmt', '# 공격자가 SMTP 배너로 버전을 확인'],
     ['prompt', 'attacker$ telnet victim.com 25'],
     ['', '220 victim ESMTP Sendmail 8.12.8'],
     ['bad', '>> 8.12.x 대상 공개 익스플로잇 적용'],
     ['bad', '>> 원격 코드 실행으로 메일서버 장악'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 알려진 취약점 악용', 'desc': '구버전 Sendmail이라 공개된 취약점으로 원격 장악이 가능합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 버전을 확인 후 공격 시도'],
     ['prompt', 'attacker$ telnet victim.com 25'],
     ['good', '>> 220 ESMTP Sendmail 8.17.x'],
     ['warn', '>> 최신판이라 알려진 익스플로잇이 통하지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 최신 패치', 'desc': '최신 보안 버전을 유지해 알려진 취약점 공격이 막힙니다.'},
 },
 'U-46': {
   'easy': 'Sendmail 큐 실행을 누구나 할 수 있으면 <b>우체국 뒷방을 일반 손님이 드나드는</b> 격입니다. 남의 메일 처리에 끼어들어 정보를 엿볼 수 있죠. restrictqrun으로 직원만 들어가게 해야 합니다.',
   'attack_label': '일반 사용자가 메일 큐를 조작해 정보를 엿본다',
   'attack_vuln': [
     ['cmt', '# 권한 없는 사용자가 메일 큐를 강제 처리'],
     ['prompt', 'user$ sendmail -q -v'],
     ['', 'restrictqrun 미설정 → 실행 허용'],
     ['bad', '>> 큐에 쌓인 타인 메일의 발신/수신자 노출'],
     ['bad', '>> 메일 흐름 정보 수집 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 큐 정보 노출', 'desc': 'restrictqrun이 없어 일반 사용자가 큐를 실행하고 메일 정보를 봅니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 큐 강제 처리를 시도'],
     ['prompt', 'user$ sendmail -q -v'],
     ['good', '>> You do not have permission to process the queue'],
     ['warn', '>> 일반 사용자는 큐를 실행할 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 실행 제한', 'desc': 'restrictqrun으로 큐 실행을 제한해 일반 사용자의 오용이 막힙니다.'},
 },
 'U-47': {
   'easy': '오픈 릴레이는 <b>주인 없이 아무 편지나 대신 부쳐 주는 우체통</b>입니다. 스팸 발송자가 자기 흔적은 숨기고 우리 우체통을 빌려 쓰죠. 결국 우리 서버가 스팸 발송지로 차단당합니다.',
   'attack_label': '공격자가 메일서버를 경유해 스팸을 대량 발송한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 외부->외부 메일 릴레이를 시도'],
     ['prompt', 'attacker$ swaks --server victim -t target@out.com'],
     ['', 'MAIL FROM:spam@evil.com  RCPT TO:target@out.com'],
     ['bad', '>> 250 Message accepted for delivery'],
     ['bad', '>> 우리 서버 경유로 스팸 대량 발송 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 오픈 릴레이 악용', 'desc': '릴레이가 모두 허용되어 외부 스팸의 발송 경유지로 악용됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 외부->외부 릴레이를 시도'],
     ['prompt', 'attacker$ swaks --server victim -t target@out.com'],
     ['good', '>> 550 Relaying denied'],
     ['warn', '>> 허용 네트워크가 아니라 발송 거부'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 릴레이 제한', 'desc': 'access DB로 허용 네트워크만 릴레이해 스팸 경유가 차단됩니다.'},
 },
 'U-49': {
   'easy': '구버전 BIND는 <b>오래되어 잘못된 주소도 그냥 믿는 안내데스크</b>입니다. 공격자가 가짜 주소를 슬쩍 끼워 넣으면 손님을 엉뚱한 곳으로 보내죠. 캐시 변조나 원격 공격에 그대로 당합니다.',
   'attack_label': '공격자가 구버전 DNS의 캐시 포이즈닝을 노린다',
   'attack_vuln': [
     ['cmt', '# 공격자가 DNS 버전을 확인'],
     ['prompt', 'attacker$ dig @victim version.bind chaos txt'],
     ['', 'version.bind. ... 9.4.1'],
     ['bad', '>> 9.4.x 캐시 포이즈닝 취약점 악용'],
     ['bad', '>> 가짜 응답 주입으로 사용자 트래픽 가로채기'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 캐시 포이즈닝', 'desc': '구버전 BIND라 알려진 취약점으로 DNS 응답이 위조됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 버전 확인 후 공격 시도'],
     ['prompt', 'attacker$ dig @victim version.bind chaos txt'],
     ['good', '>> (버전 숨김 / 최신 9.18.x)'],
     ['warn', '>> 알려진 취약점이 통하지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 최신 패치', 'desc': '최신 BIND 유지와 버전 은닉으로 캐시 포이즈닝이 차단됩니다.'},
 },
 'U-50': {
   'easy': 'Zone Transfer를 열어 두면 <b>회사 전체 좌석 배치도를 통째로 복사해 주는</b> 셈입니다. 어떤 서버가 어디 있는지 지도가 통째로 넘어가죠. 공격자는 이 지도로 다음 표적을 정합니다.',
   'attack_label': '공격자가 전체 도메인 정보를 통째로 가져간다',
   'attack_vuln': [
     ['cmt', '# 공격자가 zone transfer(axfr)를 요청'],
     ['prompt', 'attacker$ dig @victim corp.com axfr'],
     ['', '서버가 전체 zone 레코드를 전송'],
     ['bad', '>> www / mail / db / vpn 모든 호스트-IP 노출'],
     ['bad', '>> 내부 구조 지도 확보 → 표적 선정'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 도메인 정보 유출', 'desc': 'allow-transfer 제한이 없어 누구나 전체 zone을 가져갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 axfr 전송을 요청'],
     ['prompt', 'attacker$ dig @victim corp.com axfr'],
     ['good', '>> Transfer failed (refused)'],
     ['warn', '>> 인가된 보조 DNS가 아니라 전송 거부'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 전송 제한', 'desc': 'allow-transfer로 보조 DNS만 허용해 외부 axfr이 거부됩니다.'},
 },
 'U-59': {
   'easy': '불필요한 SNMP는 <b>꺼 두는 걸 깜빡한 상태 표시 모니터</b>와 같습니다. 장비의 속사정이 외부 복도에 그대로 비치죠. 안 쓰는데 켜 두면 공격자에게 정찰 정보를 공짜로 줍니다.',
   'attack_label': '공격자가 SNMP로 시스템 내부 정보를 정찰한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 SNMP 포트 구동 여부를 스캔'],
     ['prompt', 'attacker$ nmap -sU -p 161 victim.com'],
     ['', '161/udp open  snmp'],
     ['bad', '>> snmpwalk로 OS/프로세스/인터페이스 조회'],
     ['bad', '>> 시스템 내부 정보 정찰 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 정보 정찰', 'desc': '불필요한 SNMP가 켜져 있어 시스템 정보가 외부에 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 SNMP 포트를 스캔'],
     ['prompt', 'attacker$ nmap -sU -p 161 victim.com'],
     ['good', '>> 161/udp closed'],
     ['warn', '>> 조회할 SNMP 서비스가 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 서비스 중지', 'desc': 'SNMP를 비활성화하여 외부에서 시스템 정보를 조회할 수 없습니다.'},
 },
 'U-61': {
   'easy': 'community string이 public이면 <b>금고 비밀번호를 0000으로 둔</b> 것과 같습니다. 누구나 기본값을 알기에 그냥 열어 보죠. 공격자는 정보를 읽고, private까지 기본값이면 설정을 바꿔 버립니다.',
   'attack_label': '공격자가 기본 커뮤니티로 정보를 읽고 변조한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 기본 community string으로 조회'],
     ['prompt', 'attacker$ snmpwalk -v2c -c public victim'],
     ['', 'public이 그대로 통과됨'],
     ['bad', '>> 계정/라우팅/프로세스 등 전체 정보 열람'],
     ['bad', '>> -c private 쓰기로 설정 변조까지 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 정보 열람·변조', 'desc': '기본 community(public/private)라 누구나 정보를 읽고 변경합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 기본 커뮤니티로 조회 시도'],
     ['prompt', 'attacker$ snmpwalk -v2c -c public victim'],
     ['good', '>> Timeout: No Response (인증 실패)'],
     ['warn', '>> 추측 불가 값+소스 제한으로 접근 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 강한 인증', 'desc': '복잡한 community와 소스 제한(또는 SNMPv3)으로 무단 접근이 막힙니다.'},
 },
}
