# -*- coding: utf-8 -*-
"""제어시스템(ICS/SCADA) 동적 공격 데모 — 비유 + 상태별 결과."""
DYN = {
 'ICS-01': {
   'easy': 'PLC/HMI의 기본 비밀번호는 <b>출고 때 붙은 표준 자물쇠</b>입니다. 누구나 매뉴얼만 보면 여는 똑같은 열쇠를 가지고 있죠. 비밀번호를 바꾸는 건 <b>내 자물쇠로 교체</b>하는 것입니다.',
   'attack_label': '제조사 매뉴얼의 기본 계정으로 HMI에 로그인한다',
   'attack_vuln': [
     ['cmt', '# 장비 모델명을 검색해 기본 계정을 알아냄'],
     ['prompt', 'attacker$ HMI 로그인 admin / admin'],
     ['bad', '>> 로그인 성공 (기본 계정 그대로)'],
     ['bad', '>> 운전 화면 진입 — 펌프 제어 가능'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 제어 권한 탈취','desc':'매뉴얼에 적힌 기본 계정으로 누구나 들어옵니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 기본 계정으로 시도'],
     ['prompt', 'attacker$ HMI 로그인 admin / admin'],
     ['good', '>> 로그인 실패 (기본 비밀번호 변경됨)'],
     ['warn', '>> guest 계정도 삭제됨 — 진입 경로 없음'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 기본값 제거','desc':'기본 계정을 바꾸고 지워 표준 열쇠가 통하지 않습니다.'},
 },
 'ICS-02': {
   'easy': 'IT/OT 망 분리는 <b>사무실과 발전 설비 사이의 방화벽 문</b>입니다. 문이 없으면 사무실 PC에 붙은 불(랜섬웨어)이 곧장 설비로 번집니다. 망을 나누면 불이 사무실에서 멈춥니다.',
   'attack_label': '사무망 PC를 감염시킨 뒤 제어망으로 확산시킨다',
   'attack_vuln': [
     ['cmt', '# 직원 PC가 피싱 메일로 감염됨'],
     ['prompt', 'office-pc$ 랜섬웨어가 옆 대역 스캔'],
     ['bad', '>> 10.20.0.11 (PLC) 직접 도달 가능'],
     ['bad', '>> 제어망 설비까지 암호화 — 가동 중단'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 제어망 확산','desc':'망이 붙어 있어 사무망 감염이 그대로 설비로 번집니다.'},
   'attack_secure': [
     ['cmt', '# 같은 PC가 감염된 뒤 제어망 탐색'],
     ['prompt', 'office-pc$ 랜섬웨어가 OT 대역 스캔'],
     ['good', '>> 방화벽: IT→OT 차단 (도달 불가)'],
     ['warn', '>> 감염이 사무망에서 멈춤'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 망 분리','desc':'존/방화벽으로 나뉘어 감염이 제어망에 닿지 못합니다.'},
 },
 'ICS-03': {
   'easy': 'Modbus 같은 산업 프로토콜은 <b>발신자 확인 없는 무전기</b>와 같습니다. 같은 채널에 끼어들면 누가 말하든 설비는 그대로 따릅니다. 경로를 통제하면 등록된 무전기만 명령할 수 있습니다.',
   'attack_label': '제어망에 끼어들어 위조 제어 명령을 전송한다',
   'attack_vuln': [
     ['cmt', '# 제어망에 침투해 명령을 위조'],
     ['prompt', 'attacker$ modbus write coil=1 ON → PLC'],
     ['bad', '>> PLC: 인증 없이 명령 수락'],
     ['bad', '>> 밸브 강제 개방 — 공정 이상'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 위조 명령 실행','desc':'인증이 없어 망에 들어온 누구의 명령이든 따릅니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 위조 명령 전송'],
     ['prompt', 'attacker$ modbus write coil=1 ON → PLC'],
     ['good', '>> 게이트웨이: 미등록 출발지 거부'],
     ['warn', '>> IDS가 비정상 명령 경보 발생'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 경로/명령 통제','desc':'출발지 화이트리스트와 탐지로 위조 명령을 막습니다.'},
 },
 'ICS-04': {
   'easy': '상시 열린 원격 유지보수 통로는 <b>늘 열어둔 뒷문</b>입니다. 벤더가 가끔 쓰지만, 그 사이 누구나 드나들 수 있죠. 작업할 때만 승인받아 잠깐 여는 게 안전합니다.',
   'attack_label': '상시 개방된 벤더 원격 통로로 제어망에 들어온다',
   'attack_vuln': [
     ['cmt', '# 벤더 원격 통로가 24시간 열려 있음'],
     ['prompt', 'attacker$ vpn connect vendor-gw'],
     ['bad', '>> MFA 없음 — 약한 계정으로 접속'],
     ['bad', '>> 제어망 직접 진입 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 원격 진입','desc':'항상 열린 통로라 외부에서 바로 들어옵니다.'},
   'attack_secure': [
     ['cmt', '# 같은 통로로 접속 시도'],
     ['prompt', 'attacker$ vpn connect vendor-gw'],
     ['good', '>> 평소 차단 — 승인된 세션 없음'],
     ['warn', '>> MFA+자동만료로 진입 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 승인 기반 개방','desc':'작업 시에만 승인·MFA로 잠깐 열려 평소엔 닫혀 있습니다.'},
 },
 'ICS-05': {
   'easy': '지원종료된 노후 OS는 <b>부품이 끊긴 낡은 금고</b>입니다. 약점이 공개돼도 고칠 패치가 없죠. 업그레이드하거나, 못 하면 금고를 따로 격리해 지켜야 합니다.',
   'attack_label': '엔지니어링 PC의 지원종료 OS 취약점을 공격한다',
   'attack_vuln': [
     ['cmt', '# HMI가 지원종료 Windows + 미패치'],
     ['prompt', 'attacker$ exploit 알려진 취약점'],
     ['bad', '>> 패치 없음 — 원격 코드 실행'],
     ['bad', '>> 엔지니어링 PC 장악'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 알려진 취약점','desc':'패치가 없어 공개된 약점으로 쉽게 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 같은 취약점으로 공격 시도'],
     ['prompt', 'attacker$ exploit 알려진 취약점'],
     ['good', '>> 패치 적용됨 — 익스플로잇 실패'],
     ['warn', '>> 격리+화이트리스트로 실행 차단'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 패치/보완통제','desc':'패치하거나 격리·화이트리스트로 막습니다.'},
 },
 'ICS-06': {
   'easy': '폐쇄망에서 USB는 <b>외부와 통하는 유일한 다리</b>입니다. 그 다리로 악성코드가 건너옵니다. 다리를 막고, 꼭 건너야 할 짐은 검색대를 통과시켜야 합니다.',
   'attack_label': '악성코드가 담긴 USB를 제어 단말에 꽂는다',
   'attack_vuln': [
     ['cmt', '# 협력업체 USB에 악성코드 잠복'],
     ['prompt', 'attacker$ insert usb → HMI'],
     ['bad', '>> 자동실행으로 악성코드 동작'],
     ['bad', '>> 폐쇄망 우회 감염 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 매체 경유 감염','desc':'USB 통제가 없어 폐쇄망이 우회로 감염됩니다.'},
   'attack_secure': [
     ['cmt', '# 같은 USB를 단말에 삽입'],
     ['prompt', 'attacker$ insert usb → HMI'],
     ['good', '>> 미등록 매체 차단 — 인식 거부'],
     ['warn', '>> 검사 키오스크 통과 전 사용 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 매체 통제','desc':'등록 매체만 허용하고 검사 후 사용해 막습니다.'},
 },
 'ICS-07': {
   'easy': 'PLC 로직 무결성 검증은 <b>설계도 원본과 대조</b>하는 것입니다. 누가 도면을 몰래 고쳐도 원본과 비교하면 드러나죠. 검증이 없으면 바뀐 줄도 모르고 설비가 오작동합니다.',
   'attack_label': '운영 중 PLC 제어 로직을 몰래 바꿔치기한다',
   'attack_vuln': [
     ['cmt', '# 변경 검증 수단이 없음'],
     ['prompt', 'attacker$ download modified_logic.plc'],
     ['bad', '>> 무결성 검증 없이 그대로 반영'],
     ['bad', '>> 설비가 잘못된 로직으로 동작'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 로직 변조','desc':'기준값 비교가 없어 변경을 알아채지 못합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 로직 변경 시도'],
     ['prompt', 'attacker$ download modified_logic.plc'],
     ['good', '>> 체크섬 불일치 — 변경 탐지'],
     ['warn', '>> 승인 이력 없는 변경 거부'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 무결성 검증','desc':'서명/체크섬과 변경통제로 무단 변경을 잡아냅니다.'},
 },
 'ICS-08': {
   'easy': '제어망 로깅은 <b>공장 곳곳의 CCTV</b>입니다. CCTV가 없으면 사고가 나도 누가 무엇을 했는지 알 수 없죠. 로그가 있으면 조기에 알아채고 원인도 되짚을 수 있습니다.',
   'attack_label': '제어망에 침입한 흔적을 추적해 본다',
   'attack_vuln': [
     ['cmt', '# 침해 사고 발생 후 조사'],
     ['prompt', 'ics$ show logs'],
     ['bad', '>> 로그 없음 / 보관 안 됨'],
     ['bad', '>> 침입 시점·경로 파악 불가'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'탐지 실패 — 깜깜이','desc':'로그가 없어 침해를 인지·추적할 수 없습니다.'},
   'attack_secure': [
     ['cmt', '# 같은 사고를 조사'],
     ['prompt', 'siem$ search ot-logs'],
     ['good', '>> 이상 행위 발생 시 즉시 경보'],
     ['warn', '>> 침입 시점·경로 추적 가능'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'조기 탐지 — 가시성 확보','desc':'중앙 로그·이상 탐지로 빨리 알고 추적합니다.'},
 },
 'ICS-09': {
   'easy': '불필요한 열린 포트는 <b>잠그지 않은 여분의 출입문</b>입니다. 안 쓰는 문이 많을수록 도둑이 노릴 곳도 많죠. 안 쓰는 문은 닫아 공격할 곳을 줄여야 합니다.',
   'attack_label': '열린 포트를 스캔해 취약 서비스로 침투한다',
   'attack_vuln': [
     ['cmt', '# 제어 장비의 열린 포트 스캔'],
     ['prompt', 'attacker$ nmap plc-01'],
     ['bad', '>> telnet/ftp/web 등 다수 개방'],
     ['bad', '>> 취약한 telnet으로 침투'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 넓은 공격면','desc':'쓰지 않는 서비스가 침투 경로가 됩니다.'},
   'attack_secure': [
     ['cmt', '# 같은 장비를 스캔'],
     ['prompt', 'attacker$ nmap plc-01'],
     ['good', '>> 운영 필수 포트만 응답'],
     ['warn', '>> telnet/ftp 비활성 — 진입로 없음'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 최소 서비스','desc':'불필요 서비스를 닫아 노릴 곳을 줄였습니다.'},
 },
 'ICS-10': {
   'easy': '제어망에 붙은 약한 Wi-Fi는 <b>담장 밖까지 새는 전파 통로</b>입니다. 침입자가 주차장에서도 들어올 수 있죠. 무선은 없애거나, 꼭 쓰면 강하게 잠그고 따로 떼어 둬야 합니다.',
   'attack_label': '약한 무선을 뚫고 제어망에 접근한다',
   'attack_vuln': [
     ['cmt', '# 건물 밖에서 무선 탐색'],
     ['prompt', 'attacker$ crack WPA2-PSK (공유키)'],
     ['bad', '>> 공유 비밀번호 획득'],
     ['bad', '>> 제어망 직결 — 원격 접근 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 무선 침투','desc':'약한 공유키 무선이 제어망과 직결돼 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 같은 무선에 접근 시도'],
     ['prompt', 'attacker$ connect 제어망 AP'],
     ['good', '>> WPA3-Enterprise 개별 인증 요구'],
     ['warn', '>> 별도 VLAN 격리 — 제어망 도달 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 무선 강화/격리','desc':'개별 인증과 망 분리로 무단 접근을 막습니다.'},
 },
 'ICS-11': {
   'easy': '백업은 <b>비상시 펼치는 예비 설계도</b>입니다. 사고나 랜섬웨어로 설비가 멈춰도 예비 설계도가 있으면 빨리 되살리죠. 없으면 처음부터 다시 만들어야 합니다.',
   'attack_label': '랜섬웨어 피해 후 설비를 복구해 본다',
   'attack_vuln': [
     ['cmt', '# 랜섬웨어로 PLC 설정 손상'],
     ['prompt', 'ics$ restore plc-config'],
     ['bad', '>> 백업 없음 — 복구 불가'],
     ['bad', '>> 장기 가동 중단'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'복구 실패 — 장기 중단','desc':'백업이 없어 사고 후 되돌릴 수 없습니다.'},
   'attack_secure': [
     ['cmt', '# 같은 피해 후 복구'],
     ['prompt', 'ics$ restore --from offline-backup'],
     ['good', '>> 최신 백업으로 설정 복원'],
     ['warn', '>> 복구 시험 검증 완료 — 빠른 재가동'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'신속 복구 — 백업 체계','desc':'격리 보관 백업과 복구 훈련으로 빠르게 되살립니다.'},
 },
 'ICS-12': {
   'easy': '물리 접근 통제는 <b>제어실 출입문의 잠금과 CCTV</b>입니다. 아무나 들어와 노트북을 꽂으면 원격 방어가 무의미하죠. 문을 잠그고 빈 포트를 막아야 합니다.',
   'attack_label': '제어실에 들어가 현장 단말에 직접 접속한다',
   'attack_vuln': [
     ['cmt', '# 통제 없는 제어실에 잠입'],
     ['prompt', 'attacker$ 노트북을 빈 포트에 연결'],
     ['bad', '>> 잠금/감시 없음 — 제어망 진입'],
     ['bad', '>> HMI 직접 조작'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 물리 침입','desc':'출입·포트 통제가 없어 현장에서 바로 조작합니다.'},
   'attack_secure': [
     ['cmt', '# 같은 방식으로 잠입 시도'],
     ['prompt', 'attacker$ 노트북을 빈 포트에 연결'],
     ['good', '>> 출입통제+CCTV로 진입 차단'],
     ['warn', '>> 미사용 포트 비활성 — 연결 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 물리 통제','desc':'출입통제와 포트 비활성으로 현장 접근을 막습니다.'},
 },
 'ICS-13': {
   'easy': '화이트리스트는 <b>출입 허가 명단</b>입니다. 명단에 없는 프로그램은 아예 실행되지 않죠. 백신을 못 쓰는 제어 단말에서 미인가 악성코드를 막는 효과적인 방법입니다.',
   'attack_label': '제어 단말에서 미인가 실행파일을 동작시킨다',
   'attack_vuln': [
     ['cmt', '# HMI에 악성 실행파일 반입'],
     ['prompt', 'attacker$ run unknown.exe'],
     ['bad', '>> 실행 제어 없음 — 그대로 실행'],
     ['bad', '>> 악성코드 상주 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 임의 실행','desc':'실행 통제가 없어 미인가 코드가 동작합니다.'},
   'attack_secure': [
     ['cmt', '# 같은 파일 실행 시도'],
     ['prompt', 'attacker$ run unknown.exe'],
     ['good', '>> 허용 목록에 없음 — 실행 차단'],
     ['warn', '>> 인가된 프로그램만 동작'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 화이트리스트','desc':'허가된 프로그램만 실행되어 악성코드를 막습니다.'},
 },
 'ICS-14': {
   'easy': 'PLC 쓰기보호(Run 모드)는 <b>편집 잠금이 걸린 문서</b>입니다. 평소엔 읽기만 되고, 고치려면 잠금을 풀어야 하죠. 운영 중 잠가두면 가동 중 로직을 함부로 못 바꿉니다.',
   'attack_label': '가동 중인 PLC의 제어 로직을 덮어쓴다',
   'attack_vuln': [
     ['cmt', '# PLC가 상시 프로그래밍 가능 상태'],
     ['prompt', 'attacker$ plc set-mode PROGRAM ; write'],
     ['bad', '>> 키스위치/보호 없음 — 변경 허용'],
     ['bad', '>> 가동 중 로직 변조 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 운영 중 변조','desc':'쓰기보호가 없어 가동 중에도 로직이 바뀝니다.'},
   'attack_secure': [
     ['cmt', '# 같은 방식으로 변경 시도'],
     ['prompt', 'attacker$ plc set-mode PROGRAM'],
     ['good', '>> 키스위치 RUN(쓰기보호) — 전환 거부'],
     ['warn', '>> 모드 변경 시도가 로그에 기록됨'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 쓰기보호','desc':'운영 중 Run 모드로 잠겨 무단 변경을 막습니다.'},
 },
}
