# -*- coding: utf-8 -*-
DYN = {
 'D-05': {
   'easy': '도둑이 예전에 한 번 알아냈던 <b>집 비밀번호</b>를, 당신이 시간이 지나 다시 그 번호로 바꾸면 도둑은 또 들어옵니다. "최근에 쓰던 번호는 다시 못 쓰게" 막아두면, 과거에 새어 나간 비밀번호가 더는 통하지 않습니다. 그것이 <b>패스워드 재사용 금지</b>입니다.',
   'attack_label': '공격자가 과거에 유출된 비밀번호로 재로그인을 시도한다',
   'attack_vuln': [
     ['cmt', '# 1년 전 유출 목록에서 SYSTEM 옛 비밀번호 확보'],
     ['prompt', 'attacker$ sqlplus SYSTEM/OldPass2023@10.0.0.5'],
     ['', 'PASSWORD_REUSE_MAX = UNLIMITED (재사용 제한 없음)'],
     ['', '관리자가 시간이 지나 OldPass2023으로 되돌려 둠'],
     ['bad', '>> Connected to: Oracle Database 19c'],
     ['bad', '>> 폐기됐어야 할 옛 비밀번호로 접속 성공 — 계정 탈취'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 옛 비밀번호 재사용','desc':'재사용 제한이 없어 과거에 유출된 비밀번호가 다시 유효해져 접속이 허용되었습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 옛 비밀번호로 접속을 시도'],
     ['prompt', 'attacker$ sqlplus SYSTEM/OldPass2023@10.0.0.5'],
     ['good', '>> 관리자는 애초에 옛 번호로 되돌릴 수 없었음'],
     ['warn', '>> ORA-28007: the password cannot be reused'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 재사용 금지','desc':'PASSWORD_REUSE_MAX=10, PASSWORD_REUSE_TIME=365로 최근 비밀번호 복귀가 막혀 유출된 옛 번호가 무효화됩니다.'},
 },
 'D-06': {
   'easy': '회사에서 <b>아르바이트생에게 마스터키</b>를 주면, 그 사람은 사장실 금고까지 다 열 수 있습니다. 응용프로그램용 계정에 DBA(최고관리자) 권한을 주는 것이 바로 그런 상황입니다. 권한은 <b>꼭 필요한 만큼만</b> 줘야 사고와 내부자 위협을 막습니다.',
   'attack_label': '공격자가 탈취한 응용 계정의 DBA 권한으로 전체 DB를 장악한다',
   'attack_vuln': [
     ['cmt', '# 웹앱에서 탈취한 평범한 APPUSER 계정으로 접속'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> SELECT * FROM dba_role_privs WHERE grantee=USER;'],
     ['', 'APPUSER 에게 DBA 롤이 부여되어 있음'],
     ['bad', 'SQL> GRANT DBA TO hacker; CREATE USER hacker ...'],
     ['bad', '>> 모든 스키마 조회/변경 가능 — 전체 DB 장악'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 권한 상승','desc':'응용 계정에 DBA가 부여되어 있어 일반 계정 하나만 털려도 DB 전체가 공격자 손에 넘어갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일 APPUSER 계정으로 권한 상승을 시도'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> SELECT * FROM hr.salary;'],
     ['good', '>> APPUSER 는 app_read 롤만 보유 (DBA 회수됨)'],
     ['warn', '>> ORA-00942: table or view does not exist'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 최소 권한','desc':'DBA를 회수하고 업무 Role만 부여해 계정이 털려도 자기 업무 객체 외에는 접근할 수 없습니다.'},
 },
 'D-07': {
   'easy': '경비실이 <b>"옆 건물에서 왔다"는 말만 믿고</b> 신분증도 안 보고 문을 열어준다면 누구나 들어올 수 있습니다. REMOTE_OS_AUTHENT=TRUE가 바로 그런 설정으로, 원격 PC의 OS 계정 이름만 같으면 비밀번호 없이 DB에 들어옵니다. 이 신뢰를 <b>꺼두어야</b> 합니다.',
   'attack_label': '공격자가 OS 계정 이름만 위조해 비밀번호 없이 접속한다',
   'attack_vuln': [
     ['cmt', '# 원격 OS 인증을 신뢰하는 설정 악용'],
     ['prompt', 'attacker$ useradd ops$oracle   # OS 계정명만 동일하게'],
     ['prompt', 'attacker$ sqlplus /@10.0.0.5   # 비밀번호 없이'],
     ['', 'remote_os_authent = TRUE (원격 OS 계정 신뢰)'],
     ['bad', '>> Connected to: Oracle Database 19c'],
     ['bad', '>> 비밀번호 입력 없이 접속 성공 — 인증 우회'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — OS 인증 우회','desc':'원격 OS 계정을 신뢰하도록 설정되어 공격자가 같은 이름의 OS 계정만 만들면 무인증 접속이 가능합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 무인증 OS 접속을 시도'],
     ['prompt', 'attacker$ sqlplus /@10.0.0.5'],
     ['good', '>> remote_os_authent = FALSE 로 원격 OS 불신뢰'],
     ['warn', '>> ORA-01017: invalid username/password; logon denied'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — OS 인증 비활성','desc':'REMOTE_OS_AUTHENT=FALSE로 원격 OS 계정 신뢰를 끊어 정식 비밀번호 없이는 접속이 거부됩니다.'},
 },
 'D-09': {
   'easy': '현관 비밀번호를 <b>무한정 눌러볼 수 있다면</b> 도둑은 언젠가 맞힙니다. "5번 틀리면 잠김"을 걸어두면, 자동으로 수천 번 눌러보는 공격이 5번 만에 멈춥니다. 그것이 <b>계정 잠금 정책</b>입니다.',
   'attack_label': '공격자가 자동화 도구로 DB 비밀번호를 무차별 대입한다',
   'attack_vuln': [
     ['cmt', '# 계정 잠금이 없어 비밀번호를 무한히 시도 가능'],
     ['prompt', 'attacker$ hydra -l SYSTEM -P rockyou.txt oracle://10.0.0.5'],
     ['', '[try] SYSTEM : 123456 ... 실패'],
     ['', '[try] SYSTEM : password ... 실패'],
     ['bad', '[try] SYSTEM : Summer2024 ... 성공!'],
     ['bad', '>> 12,438회 시도 끝에 비밀번호 획득 — 계정 탈취'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 비밀번호 크랙','desc':'잠금 정책이 없어 자동화 도구가 수천 번 시도 끝에 비밀번호를 알아냈습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 무차별 대입을 시도'],
     ['prompt', 'attacker$ hydra -l SYSTEM -P rockyou.txt oracle://10.0.0.5'],
     ['', '[try] ... 실패 (1/5) ... (4/5) ... (5/5)'],
     ['good', '>> ORA-28000: the account is locked'],
     ['warn', '>> 5회 실패로 계정 잠김 — 더 이상 시도 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 계정 잠금','desc':'FAILED_LOGIN_ATTEMPTS=5로 5회 실패 시 계정이 잠겨 무차별 대입이 무력화됩니다.'},
 },
 'D-13': {
   'easy': '도서관에 <b>모든 회원의 비밀 명부</b>가 있는데, 평범한 열람증만 있어도 그 명부를 펼쳐볼 수 있다면 큰일입니다. O7_DICTIONARY_ACCESSIBILITY=TRUE는 "ANY" 권한만 있으면 SYS의 비밀 사전(딕셔너리)을 들여다보게 합니다. 이 문을 <b>닫아두어야</b> 합니다.',
   'attack_label': '공격자가 ANY 권한으로 SYS.USER$의 비밀번호 해시를 덤프한다',
   'attack_vuln': [
     ['cmt', '# O7_DICTIONARY_ACCESSIBILITY=TRUE 라 SYS 객체 노출'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> SELECT name, spare4 FROM SYS.USER$;'],
     ['', 'APPUSER 는 SELECT ANY TABLE 만 보유'],
     ['bad', '>> SYS  S:A1B2...  H:9F8E...  (전 계정 해시 덤프)'],
     ['bad', '>> 해시 오프라인 크랙 → SYS 비밀번호 획득'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 해시 탈취','desc':'딕셔너리 접근이 열려 있어 ANY 권한만으로 SYS.USER$의 비밀번호 해시 전체를 빼냈습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 딕셔너리 테이블 덤프를 시도'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> SELECT name, spare4 FROM SYS.USER$;'],
     ['good', '>> O7_DICTIONARY_ACCESSIBILITY=FALSE 로 SYS 보호'],
     ['warn', '>> ORA-00942: table or view does not exist'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 딕셔너리 보호','desc':'O7_DICTIONARY_ACCESSIBILITY=FALSE로 ANY 권한이 SYS 소유 객체에는 미치지 않아 해시 덤프가 거부됩니다.'},
 },
 'D-14': {
   'easy': '아파트 <b>중앙 방송실 문이 잠겨 있지 않으면</b>, 외부인이 들어와 방송을 끊거나 가짜 안내를 내보낼 수 있습니다. 리스너에 비밀번호가 없으면 원격에서 누구나 DB 접속 관문을 정지시킬 수 있습니다. 이 관문에 <b>잠금장치(비밀번호)</b>를 걸어야 합니다.',
   'attack_label': '공격자가 비밀번호 없는 리스너를 원격에서 정지시킨다',
   'attack_vuln': [
     ['cmt', '# 리스너에 비밀번호가 없어 원격 제어 가능'],
     ['prompt', 'attacker$ lsnrctl'],
     ['prompt', 'LSNRCTL> SET CURRENT_LISTENER 10.0.0.5'],
     ['prompt', 'LSNRCTL> STOP'],
     ['bad', '>> The command completed successfully'],
     ['bad', '>> 리스너 정지 — 전 사용자 DB 접속 차단(서비스 거부)'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 리스너 정지','desc':'리스너 인증이 없어 원격에서 STOP 명령이 통해 데이터베이스 접속 관문이 마비되었습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 원격에서 리스너 정지를 시도'],
     ['prompt', 'LSNRCTL> SET CURRENT_LISTENER 10.0.0.5'],
     ['prompt', 'LSNRCTL> STOP'],
     ['good', '>> ADMIN_RESTRICTIONS=ON / 비밀번호 설정됨'],
     ['warn', '>> TNS-01169: The listener has not recognized the password'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 리스너 인증','desc':'리스너 비밀번호와 ADMIN_RESTRICTIONS=ON으로 원격 제어가 거부되어 정지 공격이 막힙니다.'},
 },
 'D-15': {
   'easy': 'CCTV가 <b>꺼져 있으면</b> 도둑이 들어와도 누가 언제 왔는지 알 수 없습니다. 리스너 로깅이 꺼지면 누가 DB에 접속을 시도하고 공격했는지 기록이 남지 않습니다. 그래서 <b>로깅을 켜고</b> 그 기록을 지키는 것이 중요합니다.',
   'attack_label': '공격자가 로깅이 꺼진 틈에 흔적 없이 리스너를 정찰한다',
   'attack_vuln': [
     ['cmt', '# 리스너 로깅 OFF — 접속 시도가 기록되지 않음'],
     ['prompt', 'attacker$ nmap -p 1521 --script oracle-sid-brute 10.0.0.5'],
     ['', 'Listener Log File   OFF'],
     ['bad', '>> SID 수백 회 추측 시도 — 로그에 한 줄도 안 남음'],
     ['bad', '>> 관리자는 정찰 사실 자체를 인지하지 못함'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 흔적 없는 정찰','desc':'리스너 로깅이 꺼져 있어 SID 추측 등 공격 정찰이 아무 기록도 남기지 않고 진행됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 SID 추측 정찰을 시도'],
     ['prompt', 'attacker$ nmap -p 1521 --script oracle-sid-brute 10.0.0.5'],
     ['good', '>> Listener Log File   ON (LOGGING_LISTENER=ON)'],
     ['warn', '>> listener.log 에 다수 실패 시도 기록 → 탐지/대응'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 로깅 활성','desc':'리스너 로깅을 켜두면 정찰 시도가 로그에 남아 침해를 조기에 탐지하고 추적할 수 있습니다.'},
 },
 'D-16': {
   'easy': '우리 집에서 <b>옆집 현관까지 바로 통하는 비밀 통로</b>가 있고, 그 통로에 옆집 열쇠까지 걸려 있다면 위험합니다. 안 쓰는 DB 링크는 인접 DB의 자격증명을 품은 그런 통로입니다. 필요 없는 통로는 <b>막아두어야</b> 합니다.',
   'attack_label': '공격자가 남아 있는 DB 링크를 타고 인접 DB로 측면 이동한다',
   'attack_vuln': [
     ['cmt', '# 미사용 DB 링크에 인접 DB 자격증명이 잔존'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> SELECT db_link, host FROM dba_db_links;'],
     ['', 'OLD_LINK  ->  legacy-db (자격증명 내장)'],
     ['bad', 'SQL> SELECT * FROM hr.payroll@OLD_LINK;'],
     ['bad', '>> 링크 통해 legacy-db 급여 데이터 조회 — 측면 이동'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 측면 이동','desc':'남아 있던 DB 링크의 저장된 자격증명을 이용해 공격자가 인접 DB까지 침투했습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 링크를 통한 측면 이동을 시도'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> SELECT * FROM hr.payroll@OLD_LINK;'],
     ['good', '>> 불필요 링크는 DROP DATABASE LINK 로 제거됨'],
     ['warn', '>> ORA-02019: connection description for remote db not found'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 링크 제거','desc':'미사용 DB 링크를 제거해 인접 DB로 통하는 통로와 저장된 자격증명이 사라져 측면 이동이 차단됩니다.'},
 },
 'D-17': {
   'easy': '은행에 <b>거래 기록이 전혀 안 남는다면</b>, 내부 직원이 몰래 돈을 빼가도 추적할 수 없습니다. 감사(Audit) 기능이 꺼지면 권한 변경이나 중요 데이터 접근이 기록되지 않습니다. 그래서 <b>감사를 켜두는 것</b>이 사고 추적의 핵심입니다.',
   'attack_label': '공격자가 감사가 꺼진 상태에서 흔적 없이 데이터를 빼낸다',
   'attack_vuln': [
     ['cmt', '# audit_trail=NONE — 모든 행위가 기록되지 않음'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> GRANT SELECT ANY TABLE TO APPUSER;'],
     ['', 'SQL> SELECT ssn FROM hr.customer;  -- 전 고객 조회'],
     ['bad', '>> 권한 변경·대량 조회가 감사 로그에 안 남음'],
     ['bad', '>> 유출 후에도 누가 무엇을 봤는지 추적 불가'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 흔적 없는 유출','desc':'감사가 꺼져 있어 권한 상승과 대량 데이터 조회가 아무 기록도 남기지 않고 이루어집니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 권한 변경·대량 조회를 시도'],
     ['prompt', 'SQL> GRANT SELECT ANY TABLE TO APPUSER;'],
     ['', 'SQL> SELECT ssn FROM hr.customer;'],
     ['good', '>> audit_trail=DB,EXTENDED 로 모든 행위 기록'],
     ['warn', '>> dba_audit_trail 에 GRANT·SELECT 기록 → 탐지/추적'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 감사 활성','desc':'감사를 켜두면 권한 변경과 중요 데이터 접근이 모두 기록되어 침해를 탐지하고 책임을 추적할 수 있습니다.'},
 },
 'D-20': {
   'easy': '금고에 현금을 <b>그냥 종이봉투에 넣어두면</b>, 금고째 도둑맞는 순간 돈이 그대로 털립니다. 주민번호를 평문으로 저장하면 데이터 파일이나 백업만 훔쳐도 전부 노출됩니다. 그래서 저장할 때부터 <b>암호화(TDE)</b> 해두어야 합니다.',
   'attack_label': '공격자가 데이터파일/백업을 훔쳐 평문 주민번호를 읽는다',
   'attack_vuln': [
     ['cmt', '# 중요정보가 평문 저장 — 파일만 빼내면 노출'],
     ['prompt', 'attacker$ scp 10.0.0.5:/oradata/customer.dbf .'],
     ['prompt', 'attacker$ strings customer.dbf | grep -E "[0-9]{6}-"'],
     ['', 'TDE 미적용 — 데이터파일에 원문 그대로 저장'],
     ['bad', '>> 900101-1234567  900203-2345678  ... (평문 주민번호)'],
     ['bad', '>> 백업 한 개로 전 고객 주민번호 유출'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 평문 유출','desc':'중요정보가 평문으로 저장돼 데이터파일이나 백업만 탈취하면 주민번호가 그대로 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 데이터파일에서 주민번호 추출을 시도'],
     ['prompt', 'attacker$ strings customer.dbf | grep -E "[0-9]{6}-"'],
     ['good', '>> ssn 컬럼은 TDE 로 암호화 저장됨'],
     ['warn', '>> 7F3A 9C01 D5...  (Wallet 없이는 복호화 불가)'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — TDE 암호화','desc':'TDE로 중요 컬럼을 암호화하면 파일이 유출돼도 Wallet 키 없이는 평문을 복원할 수 없습니다.'},
 },
 'D-21': {
   'easy': '소중한 사진을 <b>한 곳에만 저장</b>해 두면, 그 기기가 망가지거나 랜섬웨어에 걸리는 순간 영영 잃습니다. 정기 백업과 복구 연습이 없으면 DB도 마찬가지입니다. 그래서 <b>백업을 자동화하고 복구를 미리 시험</b>해 두어야 합니다.',
   'attack_label': '공격자가 랜섬웨어로 DB를 암호화하는데 백업이 없다',
   'attack_vuln': [
     ['cmt', '# 정기 백업이 없어 복구 수단이 전무'],
     ['prompt', 'attacker$ ransomware --encrypt /oradata/*.dbf'],
     ['prompt', 'DBA> RMAN> LIST BACKUP SUMMARY;'],
     ['', 'specification does not match any backup'],
     ['bad', '>> 전 데이터파일 암호화 — 복구할 백업이 없음'],
     ['bad', '>> 업무 중단·몸값 요구, 데이터 영구 손실 위험'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 복구 불가','desc':'백업이 없어 랜섬웨어로 데이터파일이 암호화되자 복구할 방법이 전혀 없습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 랜섬웨어가 데이터파일을 암호화'],
     ['prompt', 'attacker$ ransomware --encrypt /oradata/*.dbf'],
     ['good', '>> 오프사이트 백업 보관 + 복구 테스트 완료 상태'],
     ['warn', '>> RMAN RESTORE/RECOVER 로 수 시간 내 정상 복구'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 백업 복구','desc':'정기 백업과 분리 보관, 복구 테스트가 갖춰져 있어 랜섬웨어 피해 후에도 데이터를 되살립니다.'},
 },
 'D-22': {
   'easy': '가게 CCTV가 <b>녹화는 되는데 아무도 안 보고 금방 지워진다면</b>, 사고가 나도 화면이 없어 소용없습니다. 로그를 충분히 보관하지 않고 모니터링도 안 하면 침해를 놓칩니다. 그래서 <b>로그를 길게 보관하고 이상 징후를 감시</b>해야 합니다.',
   'attack_label': '공격자가 침입 후 로그가 보관·감시되지 않는 점을 노린다',
   'attack_vuln': [
     ['cmt', '# 로그가 즉시 삭제되고 모니터링이 없음'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> SELECT count(*) FROM dba_audit_trail;'],
     ['', '0  (로그 미보관/즉시 삭제)'],
     ['bad', '>> 야간 대량 조회·반출 — 알람도 보관 기록도 없음'],
     ['bad', '>> 수개월 뒤에도 사고 발생 여부조차 확인 불가'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 탐지 실패','desc':'로그가 보관·모니터링되지 않아 침입과 데이터 반출이 탐지되지도, 사후 분석되지도 못합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 야간 대량 조회·반출을 시도'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['good', '>> 감사 로그 90일+ 보관, SIEM 연계 모니터링'],
     ['warn', '>> 비정상 대량 조회 룰에 즉시 알람 → 차단/조사'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 로그 모니터링','desc':'로그를 충분히 보관하고 SIEM으로 감시하면 이상 접근이 실시간 알람되고 사후 추적도 가능합니다.'},
 },
 'D-23': {
   'easy': '신입에게 회사의 <b>모든 방 만능열쇠</b>를 직접 쥐여주면 관리도 회수도 어렵고 사고도 큽니다. 사용자에게 ANY 권한을 직접 다 주는 것이 그렇습니다. 업무별로 <b>꼭 필요한 권한 꾸러미(Role)</b>만 주는 것이 안전합니다.',
   'attack_label': '공격자가 직접 부여된 ANY 권한으로 모든 스키마를 휘젓는다',
   'attack_vuln': [
     ['cmt', '# APPUSER 에 ANY 권한이 직접 부여됨'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', "SQL> SELECT * FROM dba_sys_privs WHERE grantee='APPUSER';"],
     ['', 'SELECT ANY TABLE / CREATE ANY PROCEDURE'],
     ['bad', 'SQL> SELECT ssn FROM hr.customer;  -- 타 스키마 조회'],
     ['bad', '>> 모든 스키마 열람·악성 프로시저 생성 가능'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 과다 권한 악용','desc':'ANY 권한이 직접 부여돼 있어 계정 하나가 털리면 모든 스키마를 마음대로 조회·변경할 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 타 스키마 조회를 시도'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> SELECT ssn FROM hr.customer;'],
     ['good', '>> ANY 권한 회수, app_read 업무 Role 만 부여'],
     ['warn', '>> ORA-00942: table or view does not exist'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 최소 권한 Role','desc':'ANY 권한을 회수하고 업무 Role로 최소 권한만 부여해 계정이 털려도 영향 범위가 자기 업무로 한정됩니다.'},
 },
 'D-24': {
   'easy': '문 자물쇠에 <b>이미 알려진 따는 법</b>이 있는데도 안 바꾸면, 도둑이 그 방법대로 쉽게 엽니다. 오래된 DBMS는 공개된 취약점이 그대로 남아 있는 자물쇠와 같습니다. 벤더가 내놓는 <b>보안 패치</b>를 제때 적용해 그 구멍을 메워야 합니다.',
   'attack_label': '공격자가 미패치 DBMS의 알려진 취약점으로 권한을 탈취한다',
   'attack_vuln': [
     ['cmt', '# 2년간 패치 미적용 — 공개 익스플로잇 존재'],
     ['prompt', 'attacker$ sqlplus APPUSER/leaked@10.0.0.5'],
     ['', 'SQL> SELECT version FROM v$instance;  -- 19.3.0.0'],
     ['', '해당 버전의 권한상승 CVE 익스플로잇 적용'],
     ['bad', 'SQL> exec sys.evil_priv_esc;  -- 알려진 결함 악용'],
     ['bad', '>> 일반 계정에서 SYS 권한 획득 — DB 장악'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 취약점 악용','desc':'보안 패치가 적용되지 않아 공개된 권한상승 취약점으로 일반 계정이 SYS 권한을 탈취했습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 알려진 취약점 익스플로잇을 시도'],
     ['prompt', 'SQL> SELECT version FROM v$instance;  -- 19.24.x'],
     ['', 'SQL> exec sys.evil_priv_esc;'],
     ['good', '>> 최신 Release Update 적용으로 결함 제거됨'],
     ['warn', '>> ORA-06550 / 익스플로잇 무효 — 권한상승 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 최신 패치','desc':'분기 보안 패치(CPU/RU)를 정기 적용해 알려진 취약점이 제거되어 공개 익스플로잇이 통하지 않습니다.'},
 },
}
