# -*- coding: utf-8 -*-
"""전자금융 보안 특화 시뮬 추가 4종 콘텐츠 명세 (금융보안원 제2026-1호: 취약한 HTTPS/TLS 서버 설정)."""

SPECS = [
{
 'file':'07_fin-tls-protocol.html',
 'title':'취약한 HTTPS 프로토콜 제한',
 'icon':'🔓', 'target':'금융 서비스 HTTPS 웹서버', 'risk':'5', 'item_code':'WEB-SER 취약 HTTPS 프로토콜(034)',
 'attack_panel_title':'TLS 프로토콜 스캔',
 'scenario_html':'웹서버가 <b>SSLv3 / TLS1.0 / TLS1.1</b> 같은 구버전 프로토콜을 계속 허용하면, 공격자는 협상 과정을 가로채 약한 버전으로 <b>다운그레이드</b>시키고 <b>POODLE·BEAST</b> 기법으로 암호화 통신을 <b>복호화</b>할 수 있습니다.',
 'attack_name':'프로토콜 다운그레이드(POODLE/BEAST)', 'attack_sub':'nmap ssl-enum-ciphers로 구버전 허용 확인',
 'normal_req':'nmap --script ssl-enum-ciphers -p 443 bank.example.com\n# 기대: TLSv1.2 / TLSv1.3 만 응답',
 'attack_req':'nmap --script ssl-enum-ciphers -p 443 bank.example.com\n|   SSLv3:    <-- 허용됨 (취약)\n|   TLSv1.0:  <-- 허용됨 (취약)\n|   TLSv1.1:  <-- 허용됨 (취약)\n# 협상 가로채기 → SSLv3 강제 → POODLE 복호화',
 'vuln_logs_js':"addLog('[SCAN] ssl-enum-ciphers 결과 SSLv3/TLS1.0/1.1 허용 확인','warn'); addLog('[MITM] 협상 가로채기 → 프로토콜 다운그레이드 강제','error'); addLog('[POODLE] SSLv3 CBC 패딩 오라클로 평문 추출','error'); addLog('[CRYPTO] 세션 쿠키 복호화 성공','error');",
 'breach_html':'<strong>🚨 다운그레이드 공격 성공</strong><br>구버전 프로토콜 허용으로 통신이 SSLv3로 강제되어 POODLE 기법으로 세션 쿠키가 복호화되었습니다.<table class="data-table"><tr><th>항목</th><th>값</th></tr><tr><td>강제된 프로토콜</td><td style="color:#b71c1c">SSLv3</td></tr><tr><td>복호화 대상</td><td style="color:#b71c1c">세션 쿠키 / 인증 토큰</td></tr></table>',
 'violations':['평가기준 [전자금융] 취약한 HTTPS 프로토콜 제한(위험도 5)',
               '전자금융감독규정 제32조: 전송구간 암호화 강도 미흡',
               'TLS 권고(RFC 8996) SSLv3/TLS1.0/1.1 사용 폐기 위반'],
 'defense_intro':'웹서버는 <strong>TLS 1.2 이상(권장 1.3)</strong>만 허용하고 <strong>SSLv3·TLS1.0·TLS1.1 구버전을 비활성화</strong>해야 합니다. 아래 Nginx 설정을 보완하세요.',
 'vuln_code':'# [취약] 구버전 프로토콜 허용 (Nginx)\nserver {\n    listen 443 ssl;\n    server_name bank.example.com;\n    ssl_protocols SSLv3 TLSv1 TLSv1.1;  # 구버전만 허용\n}',
 'secure_hint':'# [안전] 최신 프로토콜만 허용 (Nginx)\nserver {\n    listen 443 ssl;\n    server_name bank.example.com;\n    ssl_protocols TLSv1.2 TLSv1.3;   # 구버전 비활성화\n    ssl_prefer_server_ciphers on;\n}',
 'checks':[['TLSv1.2','TLSv1.3']],
 'success_msg':'TLS 1.2/1.3만 허용하고 구버전을 비활성화해 다운그레이드 공격이 차단됩니다.',
 'fail_msg':'ssl_protocols를 TLSv1.2/TLSv1.3만 허용하도록 설정하고 구버전을 제거해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>서버 보안 &gt; <b>취약한 HTTPS 프로토콜 제한</b><h4>2. 위험 분석</h4><ul><li>SSLv3/TLS1.0/1.1 허용 시 다운그레이드 공격</li><li>POODLE·BEAST로 암호화 통신 복호화</li></ul><h4>3. 조치 방법</h4><ul><li><b>TLS 1.2 이상</b>(권장 1.3)만 허용</li><li>SSLv3·TLS1.0·TLS1.1 <b>비활성화</b></li><li>다운그레이드 방지 옵션 적용</li></ul>',
 'easy':'낡은 <b>자물쇠 규격</b>을 계속 허용하면 도둑이 일부러 그 낡은 자물쇠로 바꿔 끼워 <b>만능열쇠</b>로 엽니다. 새 규격(TLS 1.2/1.3)만 받도록 하면 낡은 자물쇠 자체를 쓸 수 없습니다.',
},
{
 'file':'07_fin-tls-cipher.html',
 'title':'취약한 HTTPS 암호 알고리즘 제거',
 'icon':'🧮', 'target':'금융 서비스 HTTPS 웹서버', 'risk':'5', 'item_code':'WEB-SER 취약 HTTPS 암호(035)',
 'attack_panel_title':'Cipher Suite 스캔',
 'scenario_html':'서버가 <b>RC4·DES·3DES·NULL·EXPORT·MD5</b> 같은 취약한 cipher suite를 협상에 허용하면, 공격자는 약한 암호로 협상을 유도해 <b>SWEET32</b> 등 기법으로 캡처한 트래픽을 <b>복호화</b>할 수 있습니다.',
 'attack_name':'취약 암호 협상(SWEET32 등)', 'attack_sub':'openssl s_client로 3DES/RC4 협상 확인',
 'normal_req':'openssl s_client -connect bank.example.com:443 -cipher ECDHE\n# 기대: 강한 AEAD cipher만 협상',
 'attack_req':'openssl s_client -connect bank.example.com:443 -cipher RC4-MD5\n# Cipher: RC4-MD5   <-- 협상 성공 (취약)\nopenssl s_client -connect bank.example.com:443 -cipher DES-CBC3-SHA\n# Cipher: DES-CBC3-SHA  <-- 3DES 협상 → SWEET32 복호화',
 'vuln_logs_js':"addLog('[SCAN] s_client 결과 RC4-MD5 / 3DES 협상 가능 확인','warn'); addLog('[MITM] 약한 cipher로 협상 유도','error'); addLog('[SWEET32] 3DES 64비트 블록 충돌로 평문 복원','error'); addLog('[CRYPTO] 트래픽 복호화 성공','error');",
 'breach_html':'<strong>🚨 취약 암호 복호화 성공</strong><br>약한 cipher suite 허용으로 3DES/RC4 협상이 성립되어 캡처한 트래픽이 복호화되었습니다.<table class="data-table"><tr><th>협상 cipher</th><th>위험</th></tr><tr><td style="color:#b71c1c">RC4-MD5</td><td>스트림 편향 / MD5 약점</td></tr><tr><td style="color:#b71c1c">DES-CBC3-SHA</td><td>SWEET32 블록 충돌</td></tr></table>',
 'violations':['평가기준 [전자금융] 취약한 HTTPS 암호 알고리즘 제거(위험도 5)',
               '전자금융감독규정 제32조: 안전하지 않은 암호 알고리즘 사용',
               'TLS 권고(RFC 7465) RC4 금지 / SWEET32 대응 위반'],
 'defense_intro':'서버는 <strong>AEAD·ECDHE 기반의 강한 cipher suite</strong>만 허용하고 <strong>RC4·DES·3DES·NULL·EXPORT·MD5 취약 cipher를 제거</strong>해야 합니다. 아래 Nginx 설정을 보완하세요.',
 'vuln_code':'# [취약] 취약 cipher 허용 (Nginx)\nserver {\n    listen 443 ssl;\n    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_ciphers ALL:RC4:DES-CBC3-SHA:EXPORT:NULL-MD5;  # 약한 암호 포함\n}',
 'secure_hint':'# [안전] 강한 cipher만 허용 (Nginx)\nserver {\n    listen 443 ssl;\n    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_prefer_server_ciphers on;\n    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:HIGH:!aNULL:!MD5:!RC4:!3DES:!DES:!EXPORT;\n}',
 'checks':[['ECDHE'],['GCM','SHA384','HIGH']],
 'success_msg':'AEAD/ECDHE 기반 강한 cipher만 허용하고 취약 cipher를 제거해 복호화가 차단됩니다.',
 'fail_msg':'ssl_ciphers에서 RC4/DES/3DES/NULL/EXPORT/MD5를 제거하고 강한 cipher(ECDHE/AEAD)만 허용해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>서버 보안 &gt; <b>취약한 HTTPS 암호 알고리즘 제거</b><h4>2. 위험 분석</h4><ul><li>RC4·3DES 등 약한 cipher로 트래픽 복호화(SWEET32)</li><li>NULL/EXPORT 사용 시 암호화 무력화</li></ul><h4>3. 조치 방법</h4><ul><li><b>AEAD·ECDHE</b> 기반 강한 cipher만 허용</li><li>RC4·DES·3DES·NULL·EXPORT·MD5 <b>제거</b></li><li>서버 cipher 우선순위 적용</li></ul>',
 'easy':'겉만 잠금장치고 속은 <b>헐거운 약한 자물쇠</b>를 끼워두면 도둑이 굳이 그 약한 것을 골라 따버립니다. 검증된 <b>튼튼한 자물쇠</b>만 쓰도록 약한 규격을 아예 빼야 합니다.',
},
{
 'file':'07_fin-tls-component.html',
 'title':'취약한 HTTPS 컴포넌트 제거',
 'icon':'🩸', 'target':'금융 서버 TLS 라이브러리(OpenSSL)', 'risk':'5', 'item_code':'WEB-SER 취약 HTTPS 컴포넌트(036)',
 'attack_panel_title':'TLS 라이브러리 점검',
 'scenario_html':'서버가 <b>취약한 OpenSSL 버전</b>(예: Heartbleed <b>CVE-2014-0160</b>)을 사용하면, 공격자는 Heartbeat 요청 조작으로 서버 <b>메모리를 누출</b>시켜 <b>개인키·세션·자격증명</b>을 탈취할 수 있습니다.',
 'attack_name':'Heartbleed 메모리 누출', 'attack_sub':'openssl version으로 취약 버전 확인 후 누출',
 'normal_req':'openssl version\n# 기대: OpenSSL 3.x (최신 패치 적용)',
 'attack_req':'openssl version\n# OpenSSL 1.0.1f   <-- Heartbleed 취약 (CVE-2014-0160)\nnmap --script ssl-heartbleed -p 443 bank.example.com\n|   VULNERABLE: The Heartbleed Bug\n# Heartbeat 조작 → 64KB 메모리 반복 누출',
 'vuln_logs_js':"addLog('[CHECK] openssl version=1.0.1f → Heartbleed 취약 확인','warn'); addLog('[HEARTBEAT] payload_length 조작 요청 전송','error'); addLog('[LEAK] 서버 메모리 64KB 누출 반복','error'); addLog('[KEY] 개인키 및 세션 쿠키 탈취','error');",
 'breach_html':'<strong>🚨 Heartbleed 누출 성공</strong><br>패치되지 않은 OpenSSL 사용으로 서버 메모리가 누출되어 개인키와 세션이 탈취되었습니다.<table class="data-table"><tr><th>항목</th><th>값</th></tr><tr><td>취약 버전</td><td style="color:#b71c1c">OpenSSL 1.0.1f</td></tr><tr><td>누출 데이터</td><td style="color:#b71c1c">개인키 / 세션 쿠키 / 자격증명</td></tr></table>',
 'violations':['평가기준 [전자금융] 취약한 HTTPS 컴포넌트 제거(위험도 5)',
               '전자금융감독규정 제21조: 알려진 취약점 패치 관리 미흡',
               '알려진 취약 컴포넌트 사용(CVE-2014-0160) / 패치 관리 위반'],
 'defense_intro':'TLS 라이브러리(OpenSSL 등)는 <strong>알려진 취약점이 제거된 최신 패치 버전</strong>으로 갱신해야 합니다. 아래와 같이 취약 버전을 <strong>패치(patched)</strong>된 버전으로 교체하세요.',
 'vuln_code':'# [취약] Heartbleed 취약 OpenSSL 사용\n$ openssl version\nOpenSSL 1.0.1f 6 Jan 2014   # CVE-2014-0160 취약\n# Dockerfile\nRUN apt-get install -y openssl=1.0.1f',
 'secure_hint':'# [안전] 최신 패치 버전으로 갱신 (patched)\n$ openssl version\nOpenSSL 1.0.1g 7 Apr 2014   # Heartbleed 패치 최신 버전\n# Dockerfile\nRUN apt-get update && apt-get install -y openssl=1.0.1g  # 패치 적용',
 'checks':[['1.0.1g','patched','최신']],
 'success_msg':'OpenSSL을 패치된 최신 버전으로 갱신해 Heartbleed 메모리 누출이 차단됩니다.',
 'fail_msg':'취약 OpenSSL을 제거하고 패치된 최신 버전(예: 1.0.1g 이상)으로 갱신해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>서버 보안 &gt; <b>취약한 HTTPS 컴포넌트 제거</b><h4>2. 위험 분석</h4><ul><li>취약 OpenSSL(Heartbleed)로 서버 메모리 누출</li><li>개인키·세션·자격증명 탈취</li></ul><h4>3. 조치 방법</h4><ul><li>TLS 라이브러리 <b>최신 패치 버전</b>으로 갱신</li><li>알려진 취약점(CVE) <b>지속 점검·패치</b></li><li>유출 의심 시 <b>인증서·키 재발급</b></li></ul>',
 'easy':'금고 자체에 알려진 <b>제조 결함</b>이 있으면 자물쇠가 멀쩡해도 옆구리로 내용물이 새어 나갑니다. 결함이 고쳐진 <b>최신 버전</b>으로 금고를 바꿔야 누출이 막힙니다.',
},
{
 'file':'07_fin-tls-renegotiation.html',
 'title':'HTTPS 재협상 차단',
 'icon':'🔁', 'target':'금융 서비스 HTTPS 웹서버', 'risk':'5', 'item_code':'WEB-SER HTTPS 재협상(037)',
 'attack_panel_title':'TLS 재협상 점검',
 'scenario_html':'서버가 <b>안전하지 않은 클라이언트 개시 TLS 재협상</b>을 허용하면, 공격자는 재협상 경계를 악용해 <b>평문 요청 주입</b>이나 반복 재협상으로 자원을 고갈시키는 <b>DoS</b>를 유발할 수 있습니다.',
 'attack_name':'클라이언트 재협상 악용', 'attack_sub':'openssl s_client로 재협상(R) 허용 확인',
 'normal_req':'openssl s_client -connect bank.example.com:443\n# 콘솔에서 R 입력 → 재협상 시도\n# 기대: 재협상 거부됨',
 'attack_req':'openssl s_client -connect bank.example.com:443\nR                              <-- 클라이언트 재협상 요청\nRENEGOTIATING                  <-- 허용됨 (취약)\n# 재협상 경계로 평문 주입 / R 반복 입력 → DoS',
 'vuln_logs_js':"addLog('[SCAN] s_client 재협상 R 입력 → RENEGOTIATING 허용 확인','warn'); addLog('[INJECT] 재협상 경계 악용 평문 요청 주입','error'); addLog('[DOS] 재협상 반복 요청으로 서버 자원 고갈','error'); addLog('[SERVER] 응답 지연 및 서비스 거부 발생','error');",
 'breach_html':'<strong>🚨 재협상 악용 성공</strong><br>클라이언트 개시 재협상 허용으로 평문 주입과 반복 재협상 DoS가 발생했습니다.<table class="data-table"><tr><th>항목</th><th>결과</th></tr><tr><td>재협상 상태</td><td style="color:#b71c1c">RENEGOTIATING 허용</td></tr><tr><td>영향</td><td style="color:#b71c1c">평문 주입 / 자원 고갈 DoS</td></tr></table>',
 'violations':['평가기준 [전자금융] HTTPS 재협상 차단(위험도 5)',
               '전자금융감독규정 제32조: 안전하지 않은 재협상 통제 미흡',
               'TLS 권고(RFC 5746) 안전하지 않은 재협상 / CVE-2009-3555 위반'],
 'defense_intro':'서버는 <strong>안전하지 않은 재협상을 비활성화</strong>하고 <strong>클라이언트 개시 재협상을 차단</strong>해야 합니다. 아래 Nginx/OpenSSL 설정을 보완하세요.',
 'vuln_code':'# [취약] 클라이언트 재협상 허용 (Nginx/OpenSSL)\nserver {\n    listen 443 ssl;\n    ssl_protocols TLSv1.2 TLSv1.3;\n    # 재협상 제한 없음 → 클라이언트 개시 재협상 허용\n}',
 'secure_hint':'# [안전] 안전하지 않은 재협상 차단 (Nginx/OpenSSL)\nserver {\n    listen 443 ssl;\n    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_conf_command Options SSL_OP_NO_RENEGOTIATION;  # 재협상 disable\n    # OpenSSL 빌드 옵션: no-renegotiation\n}',
 'checks':[['SSL_OP_NO_RENEGOTIATION','no-renegotiation','disable']],
 'success_msg':'안전하지 않은 재협상을 비활성화해 평문 주입과 재협상 DoS가 차단됩니다.',
 'fail_msg':'SSL_OP_NO_RENEGOTIATION 등으로 클라이언트 개시 재협상을 비활성화(disable)해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>서버 보안 &gt; <b>HTTPS 재협상 차단</b><h4>2. 위험 분석</h4><ul><li>안전하지 않은 재협상으로 평문 요청 주입</li><li>재협상 반복으로 자원 고갈 DoS</li></ul><h4>3. 조치 방법</h4><ul><li>안전하지 않은 재협상 <b>비활성화</b></li><li>클라이언트 개시 재협상 <b>차단</b>(SSL_OP_NO_RENEGOTIATION)</li><li>필요 시 재협상 횟수·속도 제한</li></ul>',
 'easy':'통화 도중 상대가 마음대로 <b>회선을 계속 다시 연결</b>하게 두면, 끼어들어 가짜 말을 넣거나 전화기를 마비시킵니다. <b>중간 재연결을 막아두면</b> 한 번 연결된 안전한 통화만 유지됩니다.',
},
]
