# -*- coding: utf-8 -*-
"""주요정보통신기반시설 UNIX 서비스 관리 점검 항목 18종 (메뉴 u-34~u-61 대응)."""

SVC = '서비스 관리'


def U(code, title, icon, sev, desc, vt, st, fixes, chk, ref):
    return {'file': '05_linux-%s.html' % code.lower().replace('u-', 'u'),
            'code': code, 'title': title, 'icon': icon, 'category': SVC, 'severity': sev,
            'description': desc, 'vuln_term': vt, 'secure_term': st,
            'fix_steps': fixes, 'checklist': chk, 'kisa_ref': ref}


SPECS = [
U('U-34', 'Finger 서비스 비활성화', '🖐️', '상',
  'Finger 서비스는 시스템 사용자 정보(로그인명, 홈디렉터리, 최종 로그인 등)를 원격에 노출하여 계정 수집·사회공학 공격에 악용됩니다. 사용하지 않으면 비활성화해야 합니다.',
  [('cmt', '# finger 서비스 활성화 여부 확인'), ('prompt', '# '), ('', 'grep finger /etc/inetd.conf'),
   ('bad', 'finger  stream  tcp  nowait  nobody  /usr/sbin/in.fingerd'), ('warn', '→ 원격에서 사용자 정보 조회 가능 (취약)')],
  [('cmt', '# finger 라인 주석 처리 후 inetd 재시작'), ('prompt', '# '), ('', 'grep finger /etc/inetd.conf'),
   ('good', '#finger  stream  tcp  nowait  nobody  /usr/sbin/in.fingerd'), ('good', '→ 서비스 비활성화 완료 (양호)')],
  ['<code>/etc/inetd.conf</code>에서 finger 라인을 주석(#) 처리합니다.',
   'xinetd 사용 시 <code>/etc/xinetd.d/finger</code>에서 <code>disable = yes</code> 설정.',
   '<code>kill -HUP `cat /var/run/inetd.pid`</code> 로 inetd를 재시작합니다.'],
  ['finger 서비스가 비활성화되어 있는가', 'inetd/xinetd 설정에 finger 항목이 없거나 주석 처리됨'],
  '서비스 관리 > Finger 서비스 비활성화 (불필요 시 제거)'),

U('U-35', '익명 FTP(Anonymous FTP) 비활성화', '📂', '상',
  '익명 FTP를 허용하면 인증 없이 누구나 파일을 업로드/다운로드할 수 있어 정보 유출 및 악성파일 유포 경로가 됩니다. 불필요 시 익명 접속을 제거해야 합니다.',
  [('cmt', '# 익명 ftp 계정 존재 확인'), ('prompt', '# '), ('', 'grep ftp /etc/passwd'),
   ('bad', 'ftp:x:14:50:Anonymous FTP:/var/ftp:/sbin/nologin'), ('warn', '→ 익명 FTP 접속 허용 상태 (취약)')],
  [('cmt', '# 익명 계정 제거 / anonymous 차단'), ('prompt', '# '), ('', 'userdel ftp'),
   ('good', 'vsftpd.conf: anonymous_enable=NO'), ('good', '→ 익명 접속 차단 완료 (양호)')],
  ['<code>vsftpd.conf</code>에서 <code>anonymous_enable=NO</code> 설정.',
   '불필요한 <code>ftp</code> 익명 계정을 <code>userdel ftp</code>로 제거합니다.',
   'FTP 자체가 불필요하면 서비스를 중지/제거하고 SFTP를 사용합니다.'],
  ['익명 FTP 접속이 차단되어 있는가', 'ftp 익명 계정이 제거 또는 비활성화됨'],
  '서비스 관리 > Anonymous FTP 비활성화'),

U('U-36', 'r 계열 서비스(rsh/rlogin/rexec) 비활성화', '🔗', '상',
  'rsh, rlogin, rexec 등 r-command는 평문 통신과 .rhosts 신뢰 기반 인증으로 인증 우회·스니핑에 취약합니다. SSH로 대체하고 비활성화해야 합니다.',
  [('cmt', '# r 계열 서비스 확인'), ('prompt', '# '), ('', 'grep -E "shell|login|exec" /etc/inetd.conf'),
   ('bad', 'shell  stream tcp nowait root /usr/sbin/in.rshd'), ('bad', 'login  stream tcp nowait root /usr/sbin/in.rlogind'),
   ('warn', '→ 평문/신뢰기반 인증 사용 (취약)')],
  [('cmt', '# r 계열 라인 주석 처리'), ('prompt', '# '), ('', 'grep -E "shell|login|exec" /etc/inetd.conf'),
   ('good', '#shell ... / #login ... / #exec ...'), ('good', '→ SSH로 대체, r 서비스 차단 (양호)')],
  ['<code>inetd.conf</code>의 shell/login/exec 라인을 주석 처리합니다.',
   'xinetd 사용 시 rsh/rlogin/rexec를 <code>disable = yes</code> 처리.',
   '원격 접속은 <code>SSH</code>로 대체하고 <code>.rhosts</code>, <code>/etc/hosts.equiv</code>를 제거합니다.'],
  ['rsh/rlogin/rexec가 모두 비활성화되어 있는가', 'SSH로 원격 접속을 대체하였는가', '.rhosts/hosts.equiv 신뢰 설정이 제거됨'],
  '서비스 관리 > r 계열 서비스 비활성화'),

U('U-37', 'cron 접근 제어 (crontab 권한)', '⏰', '중',
  'cron 사용 권한이 통제되지 않으면 일반 사용자가 예약 작업으로 권한 상승·악성 스크립트를 실행할 수 있습니다. cron.allow/deny로 사용을 제한해야 합니다.',
  [('cmt', '# cron 접근제어 파일 확인'), ('prompt', '# '), ('', 'ls -l /etc/cron.allow /etc/cron.deny'),
   ('bad', 'ls: /etc/cron.allow: No such file'), ('warn', '→ 모든 사용자가 cron 사용 가능 (취약)')],
  [('cmt', '# 허용 사용자만 등록'), ('prompt', '# '), ('', 'cat /etc/cron.allow'),
   ('good', 'root'), ('good', '→ cron.allow로 허용 계정만 사용 (양호)')],
  ['<code>/etc/cron.allow</code>를 생성하고 허용할 계정만 등록합니다.',
   '<code>chmod 640 /etc/cron.allow</code> 등 접근권한을 제한합니다.',
   'crontab 파일 권한을 <code>640</code> 이하로 설정합니다.'],
  ['cron.allow/deny로 사용자가 통제되는가', 'crontab 관련 파일 권한이 적절한가(640 이하)'],
  '서비스 관리 > cron 접근 제어'),

U('U-38', 'DoS 취약 서비스(echo/discard/daytime/chargen) 비활성화', '💥', '상',
  'echo, discard, daytime, chargen 등 단순 서비스는 트래픽 증폭·반사 공격(DoS)에 악용됩니다. 불필요하므로 비활성화해야 합니다.',
  [('cmt', '# 단순 서비스 활성화 확인'), ('prompt', '# '), ('', 'grep -E "echo|discard|daytime|chargen" /etc/inetd.conf'),
   ('bad', 'echo    stream tcp nowait root internal'), ('bad', 'chargen dgram  udp wait   root internal'),
   ('warn', '→ 증폭/반사 DoS에 악용 가능 (취약)')],
  [('cmt', '# 모두 주석 처리'), ('prompt', '# '), ('', 'grep -E "echo|discard|daytime|chargen" /etc/inetd.conf'),
   ('good', '(출력 없음 또는 모두 #)'), ('good', '→ 단순 서비스 비활성화 (양호)')],
  ['<code>inetd.conf</code>에서 echo/discard/daytime/chargen 라인을 모두 주석 처리합니다.',
   'xinetd 환경에서는 각 서비스를 <code>disable = yes</code>로 설정합니다.',
   'inetd를 재시작하여 적용합니다.'],
  ['echo/discard/daytime/chargen이 모두 비활성화됨', 'TCP/UDP 양쪽 모두 차단되었는가'],
  '서비스 관리 > DoS 취약 서비스 비활성화'),

U('U-39', 'NFS 서비스 비활성화', '🗄️', '상',
  'NFS(Network File System)가 불필요하게 구동되면 원격에서 파일시스템에 접근·변조할 수 있습니다. 사용하지 않으면 데몬을 중지해야 합니다.',
  [('cmt', '# NFS 관련 데몬 확인'), ('prompt', '# '), ('', 'ps -ef | grep -E "nfsd|statd|lockd"'),
   ('bad', 'root  1123  ... /usr/sbin/rpc.nfsd'), ('warn', '→ 불필요한 NFS 데몬 구동 중 (취약)')],
  [('cmt', '# NFS 서비스 중지/비활성화'), ('prompt', '# '), ('', 'systemctl status nfs-server'),
   ('good', 'inactive (dead)'), ('good', '→ NFS 데몬 중지 완료 (양호)')],
  ['NFS가 불필요하면 <code>systemctl stop nfs-server && systemctl disable nfs-server</code>.',
   'rpc.nfsd, rpc.statd, rpc.lockd 등 관련 데몬을 중지합니다.',
   '필요 시에만 구동하고 <code>U-40</code> 접근통제를 함께 적용합니다.'],
  ['불필요한 NFS 데몬이 모두 중지되었는가', '부팅 시 자동 실행이 비활성화됨'],
  '서비스 관리 > NFS 서비스 비활성화'),

U('U-40', 'NFS 접근통제 (everyone 공유 제한)', '🔐', '상',
  'NFS 공유가 모든 호스트(everyone, *)에 허용되면 누구나 마운트하여 데이터를 탈취할 수 있습니다. 특정 호스트로 제한하고 권한을 최소화해야 합니다.',
  [('cmt', '# 공유 설정 확인'), ('prompt', '# '), ('', 'cat /etc/exports'),
   ('bad', '/data   *(rw,no_root_squash)'), ('warn', '→ 모든 호스트에 rw + root 권한 허용 (취약)')],
  [('cmt', '# 특정 호스트 + 옵션 제한'), ('prompt', '# '), ('', 'cat /etc/exports'),
   ('good', '/data   10.0.0.5(ro,root_squash)'), ('good', '→ 허용 호스트/권한 제한 (양호)')],
  ['<code>/etc/exports</code>에서 <code>*</code>/everyone 공유를 제거하고 허용 호스트를 명시합니다.',
   '<code>root_squash</code>, 필요 시 <code>ro</code> 옵션으로 권한을 최소화합니다.',
   '<code>exportfs -ra</code>로 설정을 적용합니다.'],
  ['everyone(*) 공유가 제거되었는가', 'root_squash 등 권한 최소화 옵션 적용', '읽기 전용 등 최소 권한 부여'],
  '서비스 관리 > NFS 접근통제'),

U('U-41', 'automountd 제거', '🔄',  '중',
  'automountd(autofs)는 RPC 기반으로 동작하며 취약점이 다수 보고되어 권한 상승에 악용될 수 있습니다. 불필요하면 제거해야 합니다.',
  [('cmt', '# automount 데몬 확인'), ('prompt', '# '), ('', 'ps -ef | grep automount'),
   ('bad', 'root ... /usr/sbin/automount'), ('warn', '→ 불필요한 automountd 구동 (취약)')],
  [('cmt', '# autofs 중지/비활성화'), ('prompt', '# '), ('', 'systemctl status autofs'),
   ('good', 'inactive (dead)'), ('good', '→ automountd 비활성화 (양호)')],
  ['<code>systemctl stop autofs && systemctl disable autofs</code>로 중지합니다.',
   'RPC 기반 서비스이므로 함께 불필요한 RPC도 점검(U-42)합니다.'],
  ['automountd/autofs가 비활성화됨', '자동 마운트가 필요한 경우에만 제한적으로 사용'],
  '서비스 관리 > automountd 제거'),

U('U-42', '불필요한 RPC 서비스 비활성화', '📡', '상',
  'rpc.cmsd, rpc.ttdbserverd, rusersd 등 다수 RPC 서비스는 버퍼 오버플로우 등 원격 취약점이 알려져 있습니다. 불필요한 RPC를 비활성화해야 합니다.',
  [('cmt', '# RPC 서비스 확인'), ('prompt', '# '), ('', 'rpcinfo -p | head'),
   ('bad', '100083  ... rpc.ttdbserverd'), ('bad', '100068 ... rpc.cmsd'), ('warn', '→ 취약 RPC 서비스 구동 (취약)')],
  [('cmt', '# 불필요 RPC 주석/중지'), ('prompt', '# '), ('', 'grep -E "cmsd|ttdb|rusers|sprayd|walld" /etc/inetd.conf'),
   ('good', '(모두 # 처리)'), ('good', '→ 취약 RPC 제거 (양호)')],
  ['<code>inetd.conf</code>/xinetd에서 rpc.cmsd, rpc.ttdbserverd, rusersd, sprayd, walld 등을 비활성화합니다.',
   '꼭 필요한 RPC만 남기고 inetd를 재시작합니다.'],
  ['취약한 RPC 서비스가 비활성화됨', '필요한 RPC만 최소로 유지'],
  '서비스 관리 > 불필요한 RPC 서비스 제거'),

U('U-43', 'NIS/NIS+ 비활성화', '🌐', '상',
  'NIS는 인증정보를 평문으로 전송하고 맵 정보 노출 위험이 있습니다. 불필요하면 비활성화하고, 필요 시 보안성이 높은 NIS+ 또는 LDAP을 사용합니다.',
  [('cmt', '# NIS 데몬 확인'), ('prompt', '# '), ('', 'ps -ef | grep -E "ypserv|ypbind|ypxfrd"'),
   ('bad', 'root ... ypserv'), ('warn', '→ 평문 인증 NIS 구동 (취약)')],
  [('cmt', '# NIS 중지/비활성화'), ('prompt', '# '), ('', 'systemctl status ypserv ypbind'),
   ('good', 'inactive (dead)'), ('good', '→ NIS 비활성화 (양호)')],
  ['ypserv, ypbind, ypxfrd, yppasswdd 등 NIS 데몬을 중지/비활성화합니다.',
   '디렉터리 서비스가 필요하면 <code>LDAP(LDAPS)</code> 등 보안 프로토콜로 대체합니다.'],
  ['NIS 관련 데몬이 모두 중지됨', '필요 시 보안 대체 프로토콜 사용'],
  '서비스 관리 > NIS/NIS+ 비활성화'),

U('U-44', 'tftp/talk/ntalk 비활성화', '💬', '상',
  'tftp는 인증 없는 파일 전송, talk/ntalk는 불필요한 대화 서비스로 정보 노출·악용 위험이 있습니다. 비활성화해야 합니다.',
  [('cmt', '# 서비스 확인'), ('prompt', '# '), ('', 'grep -E "tftp|talk" /etc/inetd.conf'),
   ('bad', 'tftp dgram udp wait root /usr/sbin/in.tftpd'), ('bad', 'talk dgram udp wait root /usr/sbin/in.talkd'),
   ('warn', '→ 인증 없는 전송/대화 서비스 (취약)')],
  [('cmt', '# 주석 처리'), ('prompt', '# '), ('', 'grep -E "tftp|talk" /etc/inetd.conf'),
   ('good', '(모두 # 처리)'), ('good', '→ tftp/talk/ntalk 비활성화 (양호)')],
  ['<code>inetd.conf</code>/xinetd에서 tftp, talk, ntalk를 비활성화합니다.',
   'PXE 등으로 tftp가 꼭 필요하면 접근 IP를 제한하고 디렉터리 권한을 최소화합니다.'],
  ['tftp/talk/ntalk가 비활성화됨', 'tftp 필요 시 접근통제 적용'],
  '서비스 관리 > tftp/talk 서비스 비활성화'),

U('U-45', 'Sendmail 버전 최신 유지', '📧', '중',
  '오래된 Sendmail은 다수의 원격 취약점(릴레이, 버퍼 오버플로우)이 존재합니다. 최신 보안 버전으로 유지해야 합니다.',
  [('cmt', '# Sendmail 버전 확인'), ('prompt', '# '), ('', 'echo \\\\$Z | sendmail -bt -d0 | head -1'),
   ('bad', 'Version 8.12.8'), ('warn', '→ 알려진 취약점 다수의 구버전 (취약)')],
  [('cmt', '# 최신 버전 확인'), ('prompt', '# '), ('', 'sendmail -d0.1 -bt < /dev/null | grep Version'),
   ('good', 'Version 8.17.x (latest)'), ('good', '→ 최신 보안 버전 유지 (양호)')],
  ['벤더 패치를 적용해 Sendmail을 최신 보안 버전으로 업데이트합니다.',
   '메일 서버가 불필요하면 데몬 모드를 중지하고 로컬 전송만 허용합니다.'],
  ['Sendmail이 최신 보안 버전인가', '불필요 시 데몬 모드 비활성화'],
  '서비스 관리 > Sendmail 버전 점검'),

U('U-46', '일반 사용자의 Sendmail 실행 방지', '🚫', '중',
  'Sendmail의 큐 처리(-q) 등을 일반 사용자가 실행할 수 있으면 메일 시스템 오용·정보 노출이 가능합니다. restrictqrun 옵션으로 제한해야 합니다.',
  [('cmt', '# 옵션 확인'), ('prompt', '# '), ('', 'grep PrivacyOptions /etc/mail/sendmail.cf'),
   ('bad', 'O PrivacyOptions=authwarnings'), ('warn', '→ 일반 사용자 큐 실행 제한 없음 (취약)')],
  [('cmt', '# restrictqrun 추가'), ('prompt', '# '), ('', 'grep PrivacyOptions /etc/mail/sendmail.cf'),
   ('good', 'O PrivacyOptions=authwarnings,restrictqrun'), ('good', '→ 일반 사용자 실행 제한 (양호)')],
  ['<code>sendmail.cf</code>의 <code>PrivacyOptions</code>에 <code>restrictqrun</code>을 추가합니다.',
   'Sendmail 재시작 후 적용 상태를 확인합니다.'],
  ['restrictqrun 옵션이 적용됨', '일반 사용자가 큐를 실행할 수 없음'],
  '서비스 관리 > 일반 사용자 Sendmail 실행 방지'),

U('U-47', '스팸 메일 릴레이 제한', '🛑', '상',
  '메일 서버가 임의 발신자의 릴레이를 허용하면 스팸 발송 경유지로 악용됩니다. 허용 도메인/네트워크만 릴레이하도록 제한해야 합니다.',
  [('cmt', '# 릴레이 설정 확인'), ('prompt', '# '), ('', 'grep -i relay /etc/mail/sendmail.cf'),
   ('bad', 'R$* $#relay (모든 발신 릴레이 허용)'), ('warn', '→ 오픈 릴레이 상태 (취약)')],
  [('cmt', '# access DB로 허용 대상만'), ('prompt', '# '), ('', 'cat /etc/mail/access'),
   ('good', 'Connect:10.0.0 RELAY'), ('good', '→ 지정 네트워크만 릴레이 (양호)')],
  ['<code>/etc/mail/access</code>에서 허용 네트워크만 <code>RELAY</code>로 지정합니다.',
   '기본 정책은 거부(REJECT)로 두고 <code>makemap hash access < access</code>로 반영합니다.',
   '오픈 릴레이 테스트로 외부 발신이 차단되는지 확인합니다.'],
  ['오픈 릴레이가 차단되었는가', '허용 네트워크만 RELAY로 등록됨'],
  '서비스 관리 > 스팸 메일 릴레이 제한'),

U('U-49', 'DNS 보안 버전(BIND) 패치', '🧭', '상',
  '구버전 BIND는 캐시 포이즈닝·버퍼 오버플로우 등 원격 취약점이 존재합니다. 최신 보안 버전으로 유지해야 합니다.',
  [('cmt', '# BIND 버전 확인'), ('prompt', '# '), ('', 'named -v'),
   ('bad', 'BIND 9.4.1'), ('warn', '→ 알려진 취약점 다수의 구버전 (취약)')],
  [('cmt', '# 최신 버전 확인'), ('prompt', '# '), ('', 'named -v'),
   ('good', 'BIND 9.18.x (latest)'), ('good', '→ 최신 보안 버전 (양호)')],
  ['BIND를 벤더 패치로 최신 보안 버전으로 업데이트합니다.',
   'DNS가 불필요하면 named 데몬을 중지/비활성화합니다.',
   'version.bind 응답을 숨겨 버전 노출을 막습니다.'],
  ['BIND가 최신 보안 버전인가', '버전 정보 노출이 차단됨'],
  '서비스 관리 > DNS 보안 버전 패치'),

U('U-50', 'DNS Zone Transfer 제한', '📤', '상',
  'Zone Transfer가 임의 호스트에 허용되면 전체 도메인 정보(호스트/IP 매핑)가 노출되어 정찰에 악용됩니다. 허가된 보조 DNS로만 제한해야 합니다.',
  [('cmt', '# zone transfer 허용 확인'), ('prompt', '# '), ('', 'grep allow-transfer /etc/named.conf'),
   ('bad', '(설정 없음 → any 허용)'), ('warn', '→ 누구나 axfr 가능 (취약)')],
  [('cmt', '# 보조 DNS만 허용'), ('prompt', '# '), ('', 'grep allow-transfer /etc/named.conf'),
   ('good', 'allow-transfer { 10.0.0.2; };'), ('good', '→ 지정 서버만 전송 허용 (양호)')],
  ['<code>named.conf</code>에 <code>allow-transfer { 보조DNS_IP; };</code>를 설정합니다.',
   'options 블록에 기본 <code>allow-transfer { none; };</code>를 두고 필요한 zone만 허용합니다.',
   '<code>dig @서버 도메인 axfr</code>로 외부 전송이 거부되는지 확인합니다.'],
  ['Zone Transfer가 허가된 서버로만 제한됨', '외부에서 axfr 시도가 거부됨'],
  '서비스 관리 > DNS Zone Transfer 제한'),

U('U-59', 'SNMP 서비스 구동 점검', '📶', '중',
  '불필요한 SNMP 서비스가 구동되면 시스템 정보가 외부에 노출될 수 있습니다. 사용하지 않으면 중지해야 합니다.',
  [('cmt', '# snmp 데몬 확인'), ('prompt', '# '), ('', 'ps -ef | grep snmpd'),
   ('bad', 'root ... /usr/sbin/snmpd'), ('warn', '→ 불필요한 SNMP 구동 (취약)')],
  [('cmt', '# SNMP 중지/비활성화'), ('prompt', '# '), ('', 'systemctl status snmpd'),
   ('good', 'inactive (dead)'), ('good', '→ SNMP 비활성화 (양호)')],
  ['SNMP가 불필요하면 <code>systemctl stop snmpd && systemctl disable snmpd</code>.',
   '필요 시 <code>U-61</code> community string 보안설정을 함께 적용합니다.'],
  ['불필요한 SNMP 데몬이 중지됨', '필요 시에만 제한적으로 사용'],
  '서비스 관리 > SNMP 서비스 구동 점검'),

U('U-61', 'SNMP Community String 복잡도', '🔑', '상',
  'SNMP community string이 기본값(public/private)이면 누구나 시스템 정보를 조회·변조할 수 있습니다. 추측 어려운 값으로 변경하고 접근을 제한해야 합니다.',
  [('cmt', '# community string 확인'), ('prompt', '# '), ('', 'grep -i community /etc/snmp/snmpd.conf'),
   ('bad', 'rocommunity public'), ('bad', 'rwcommunity private'), ('warn', '→ 기본 커뮤니티 사용 (취약)')],
  [('cmt', '# 복잡한 값 + 접근제한'), ('prompt', '# '), ('', 'grep -i community /etc/snmp/snmpd.conf'),
   ('good', 'rocommunity Str0ng#Comm 10.0.0.0/24'), ('good', '→ 복잡도+소스 제한, SNMPv3 권장 (양호)')],
  ['public/private 등 기본 community string을 추측 어려운 값으로 변경합니다.',
   'community 뒤에 접근 허용 네트워크를 지정해 소스를 제한합니다.',
   '가능하면 인증·암호화를 지원하는 <code>SNMPv3</code>를 사용합니다.'],
  ['기본 community string(public/private)이 변경됨', '접근 소스가 제한되었는가', 'SNMPv3 사용 검토'],
  '서비스 관리 > SNMP Community String 복잡도'),
]
