# -*- coding: utf-8 -*-
# 금융보안원 제2026-1호 — 추가 시뮬레이터 스펙 4종
SPECS = [
    {
        'file': '07_fin-file-exposure.html', 'title': '불필요한 파일 노출 방지', 'icon': '🗄️',
        'target': '웹 서버 웹루트', 'risk': '4', 'item_code': 'WEB-SER 불필요 파일 노출(040)',
        'attack_panel_title': '백업·버전관리 파일 요청',
        'scenario_html': '배포 과정에서 남은 <b>백업/버전관리 파일</b>(.bak, .zip, .git)이 웹루트에 노출되면 소스코드와 <b>DB 접속정보·키</b>가 그대로 유출됩니다.',
        'attack_name': '노출 파일 직접 다운로드', 'attack_sub': '백업·.git 디렉터리를 추측해 직접 요청',
        'normal_req': 'GET /index.html HTTP/1.1\nHost: bank.example.com',
        'attack_req': 'GET /.git/config HTTP/1.1\nHost: bank.example.com\n\nGET /backup.zip HTTP/1.1\nHost: bank.example.com\n\nGET /web.config.old HTTP/1.1\nHost: bank.example.com',
        'vuln_logs_js': "addLog('[SCAN] 백업 파일 추측 요청','warn'); addLog('[HIT] /backup.zip 200 OK','warn'); addLog('[HIT] /.git/config 200 OK','warn'); addLog('[LEAK] DB 접속정보 및 비밀키 유출','error');",
        'breach_html': '<strong>🚨 소스코드 유출</strong><br><b>/backup.zip</b>와 <b>/.git</b>가 다운로드되어 DB 비밀번호와 비밀키가 노출되었습니다.',
        'violations': ['평가기준 [전자금융] 불필요 파일 노출(040)(위험도 4)', '소스코드·인증정보 노출 방지 위반', '전자금융감독규정 제15조 미흡'],
        'defense_intro': '웹 서버는 백업·버전관리 파일에 대한 접근을 <strong>차단(deny)</strong>해야 합니다. 아래 설정을 보완하세요.',
        'vuln_code': '# [취약] 모든 파일을 그대로 제공\nserver {\n    root /var/www/bank;\n    location / {\n        try_files $uri $uri/ =404;\n    }\n}',
        'secure_hint': '# [안전] 불필요 파일 접근 차단\nserver {\n    root /var/www/bank;\n    location ~ (.git|.svn|.bak|.old|.zip)$ {\n        deny all;\n        return 404;\n    }\n    location / {\n        try_files $uri $uri/ =404;\n    }\n}',
        'checks': [['deny all', 'deny']],
        'success_msg': '백업·버전관리 파일 접근이 차단됩니다.', 'fail_msg': '불필요 파일에 대한 deny 규칙을 추가해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>서버 설정 점검 &gt; <b>불필요한 파일 노출 방지</b><h4>2. 위험 분석</h4><ul><li>백업·임시·버전관리 파일로 소스코드 유출</li><li>DB 접속정보·비밀키 노출</li></ul><h4>3. 조치 방법</h4><ul><li>노출된 파일 <b>제거</b></li><li>접근 <b>차단(deny)</b> 규칙 적용</li><li>배포 시 불필요 파일 <b>제외</b></li></ul>',
        'easy': '이사하고 남긴 <b>예전 서류 박스</b>를 현관 앞에 그대로 둔 셈입니다. 쓸모없는 사본은 <b>버리거나 잠가</b> 둬야 합니다.',
    },
    {
        'file': '07_fin-background-screen.html', 'title': '백그라운드 화면 보호', 'icon': '📱',
        'target': '모바일 뱅킹 앱', 'risk': '3', 'item_code': 'MOB-SER 백그라운드 화면 보호(043)',
        'attack_panel_title': '최근 앱 미리보기 캡처',
        'scenario_html': '앱이 백그라운드로 전환될 때 OS가 <b>최근 앱(task) 미리보기</b>로 화면을 저장하면, 잔액·계좌가 담긴 스냅샷이 <b>단말 탈취·화면 캡처</b>로 노출됩니다.',
        'attack_name': '백그라운드 스냅샷 탈취', 'attack_sub': '홈 버튼 전환 시 저장된 미리보기 추출',
        'normal_req': '[홈 화면] 계좌 잔액 1,250,000원 표시\n[사용자] 앱을 그대로 사용 중',
        'attack_req': '[사용자] 홈 버튼으로 앱 백그라운드 전환\n[OS] 최근 앱 미리보기 스냅샷 저장\n[공격자] 단말 탈취 후 미리보기에서 잔액·계좌 확인',
        'vuln_logs_js': "addLog('[APP] 백그라운드 전환 감지','warn'); addLog('[OS] 최근 앱 미리보기 스냅샷 저장','warn'); addLog('[ATTACK] 미리보기에서 잔액 노출','error');",
        'breach_html': '<strong>🚨 화면 스냅샷 유출</strong><br>최근 앱 미리보기에 <b>잔액·계좌번호</b>가 그대로 캡처되었습니다.',
        'violations': ['평가기준 [전자금융] 백그라운드 화면 보호(043)(위험도 3)', '단말 화면정보 보호 위반', '전자금융감독규정 제13조 미흡'],
        'defense_intro': '앱은 백그라운드 전환 시 화면을 가리고 <strong>FLAG_SECURE</strong>로 스냅샷을 막아야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 백그라운드 화면 보호 없음\noverride fun onCreate(savedInstanceState: Bundle?) {\n    super.onCreate(savedInstanceState)\n    setContentView(R.layout.activity_main)\n}',
        'secure_hint': '// [안전] 스냅샷 방지 + 백그라운드 가림\noverride fun onCreate(savedInstanceState: Bundle?) {\n    super.onCreate(savedInstanceState)\n    window.setFlags(FLAG_SECURE, FLAG_SECURE)\n    setContentView(R.layout.activity_main)\n}\noverride fun onPause() {\n    super.onPause()\n    blurOnBackground()\n}',
        'checks': [['FLAG_SECURE'], ['blurOnBackground']],
        'success_msg': 'FLAG_SECURE와 화면 가림으로 스냅샷이 차단됩니다.', 'fail_msg': 'FLAG_SECURE와 백그라운드 가림 처리를 추가해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>모바일 단말 보호 &gt; <b>백그라운드 화면 보호</b><h4>2. 위험 분석</h4><ul><li>최근 앱 미리보기로 잔액·계좌 노출</li><li>단말 탈취 시 화면정보 유출</li></ul><h4>3. 조치 방법</h4><ul><li>백그라운드 전환 시 <b>블러/스플래시</b>로 가림</li><li><b>FLAG_SECURE</b> 설정으로 스냅샷 차단</li></ul>',
        'easy': '카드를 보다가 잠깐 책상에 둘 때 <b>덮지 않아 사진이 찍히는</b> 셈입니다. 자리를 비울 땐 화면을 <b>가려</b> 둬야 합니다.',
    },
    {
        'file': '07_fin-session-reuse.html', 'title': '세션정보 재사용 제한', 'icon': '🪪',
        'target': '인터넷 뱅킹 세션', 'risk': '5', 'item_code': 'WEB-SER 세션정보 재사용(048)',
        'attack_panel_title': '만료된 세션으로 거래 요청',
        'scenario_html': '로그아웃·만료 후에도 서버 <b>세션ID·토큰</b>이 유효하면, 탈취된 세션을 <b>재사용</b>해 거래를 일으킬 수 있습니다.',
        'attack_name': '폐기된 세션 재사용', 'attack_sub': '로그아웃 후 옛 세션 쿠키로 이체 요청',
        'normal_req': 'POST /transfer HTTP/1.1\nCookie: JSESSIONID=ACTIVE-9F31\n\namount=10000&to=111-222',
        'attack_req': 'POST /transfer HTTP/1.1\nCookie: JSESSIONID=OLD-7A20-LOGGEDOUT\n\namount=10000&to=999-888',
        'vuln_logs_js': "addLog('[AUTH] 사용자 로그아웃 처리','warn'); addLog('[ATTACK] 폐기된 세션 쿠키 재사용','warn'); addLog('[SESSION] 옛 세션이 여전히 유효함','warn'); addLog('[DB] 탈취 세션으로 이체 실행','error');",
        'breach_html': '<strong>🚨 세션 재사용 성공</strong><br>로그아웃된 세션으로 <b>이체가 실행</b>되었습니다.',
        'violations': ['평가기준 [전자금융] 세션정보 재사용(048)(위험도 5)', '세션 무효화·재사용 방지 위반', '전자금융감독규정 제34조 미흡'],
        'defense_intro': '서버는 로그아웃·만료 시 세션을 <strong>무효화(invalidate)</strong>해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 로그아웃해도 서버 세션이 살아있음\npublic void logout(HttpServletRequest req) {\n    req.getSession().setAttribute("user", null);\n}',
        'secure_hint': '// [안전] 서버 세션 무효화 및 토큰 폐기\npublic void logout(HttpServletRequest req) {\n    HttpSession session = req.getSession(false);\n    if (session != null)\n        session.invalidate();\n    tokenBlacklist.add(currentToken());\n}',
        'checks': [['session.invalidate', 'invalidate']],
        'success_msg': '세션 무효화로 폐기된 세션 재사용이 차단됩니다.', 'fail_msg': '로그아웃 시 세션 invalidate 처리를 추가해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>세션 관리 &gt; <b>세션정보 재사용 제한</b><h4>2. 위험 분석</h4><ul><li>로그아웃·만료 후 세션 유효로 재사용 거래</li><li>탈취 세션으로 부정 이체</li></ul><h4>3. 조치 방법</h4><ul><li>로그아웃 시 서버 세션 <b>무효화(invalidate)</b></li><li>세션 <b>만료·재발급</b> 적용</li><li>토큰 <b>블랙리스트</b> 관리</li></ul>',
        'easy': '로그아웃했는데 옛 <b>출입증이 계속 통하는</b> 셈입니다. 반납한 출입증은 즉시 <b>정지</b>시켜야 합니다.',
    },
    {
        'file': '07_fin-authmeans-owner.html', 'title': '인증수단 소유자 검증', 'icon': '🔐',
        'target': '이체 인증 API', 'risk': '5', 'item_code': 'WEB-SER 인증수단 소유자 검증(049)',
        'attack_panel_title': '타인 인증수단으로 거래',
        'scenario_html': 'OTP·보안카드·인증서가 <b>거래 요청자 본인 소유</b>인지 서버가 확인하지 않으면, 타인의(혹은 공유된) 인증수단으로 거래가 가능합니다.',
        'attack_name': '소유자 미검증 인증', 'attack_sub': '다른 사람 OTP 시리얼로 본인 거래 승인',
        'normal_req': 'POST /transfer/auth HTTP/1.1\n\naccount=A-1001\notpSerial=OTP-A-1001\notp=482913',
        'attack_req': 'POST /transfer/auth HTTP/1.1\n\naccount=A-1001\notpSerial=OTP-B-2002\notp=771204',
        'vuln_logs_js': "addLog('[AUTH] OTP 값 검증 요청','warn'); addLog('[ATTACK] 타인 OTP 시리얼 사용','warn'); addLog('[SERVER] 소유자 매핑 미검증','warn'); addLog('[DB] 타인 인증수단으로 이체 승인','error');",
        'breach_html': '<strong>🚨 소유자 검증 누락</strong><br>타인의 <b>OTP 시리얼</b>로 거래가 승인되었습니다.',
        'violations': ['평가기준 [전자금융] 인증수단 소유자 검증(049)(위험도 5)', '인증수단 소유 매핑 검증 위반', '전자금융감독규정 제34조 미흡'],
        'defense_intro': '서버는 인증수단이 거래 주체의 소유인지 <strong>소유 매핑</strong>을 검증해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] OTP 값만 검증하고 소유자는 확인 안 함\npublic void auth(AuthReq req) {\n    if (otpEngine.verify(req.getOtpSerial(), req.getOtp()))\n        approve(req.getAccount());\n}',
        'secure_hint': '// [안전] 인증수단 소유자 매핑 검증\npublic void auth(AuthReq req) {\n    if (!ownsAuthMeans(req.getAccount(), req.getOtpSerial()))\n        throw new SecurityException("소유자 불일치");\n    if (otpEngine.verify(req.getOtpSerial(), req.getOtp()))\n        approve(req.getAccount());\n}',
        'checks': [['ownsAuthMeans', 'isOwnerOf']],
        'success_msg': '소유자 매핑 검증으로 타인 인증수단 거래가 차단됩니다.', 'fail_msg': '인증수단 소유자 매핑 검증을 추가해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>인증 처리 &gt; <b>인증수단 소유자 검증</b><h4>2. 위험 분석</h4><ul><li>소유자 미검증으로 타인 인증수단 거래</li><li>공유 인증수단 악용</li></ul><h4>3. 조치 방법</h4><ul><li>인증수단과 거래 주체(<b>계정·CI</b>)의 소유 매핑 검증</li><li>불일치 시 거래 <b>차단</b></li></ul>',
        'easy': '내 이름표를 보지 않고 <b>아무 도장</b>이나 찍어 주는 셈입니다. 도장이 <b>내 것인지</b> 먼저 확인해야 합니다.',
    },
]
