# -*- coding: utf-8 -*-
"""전자금융 보안 특화 시뮬 추가 4종 콘텐츠 명세 (금융보안원 제2026-1호 항목 개념 재구성)."""

SPECS = [
{
 'file':'07_fin-transport-encryption.html',
 'title':'통신구간 암호화 적용',
 'icon':'🔒', 'target':'모바일/웹 거래 통신 채널', 'risk':'5', 'item_code':'WEB-SER 통신구간 암호화',
 'attack_panel_title':'거래 통신 전송',
 'scenario_html':'거래 통신이 <b>평문(HTTP)</b>이거나 <b>약한 TLS·인증서 미검증</b>으로 연결되면, 동일 네트워크의 공격자가 <b>중간자(MITM)</b>로 끼어들어 거래정보·자격증명을 <b>탈취·변조</b>할 수 있습니다.',
 'attack_name':'중간자(MITM) 평문 가로채기', 'attack_sub':'mitmproxy로 HTTP 트래픽 열람·변조',
 'normal_req':'POST https://bank.example.com/transfer\nAuthorization: Bearer eyJhbGciOi...\n{\n  "to": "220-771-559010",\n  "amount": 10000\n}',
 'attack_req':'POST http://bank.example.com/transfer        <-- 평문(HTTP)\n# mitmproxy 가로채기 후 변조\nAuthorization: Bearer eyJhbGciOi...   (자격증명 탈취)\n{\n  "to": "999-000-HACKER",\n  "amount": 50000000\n}',
 'vuln_logs_js':"addLog('[NET] 평문 HTTP 연결 감지 → 인증서 미검증','warn'); addLog('[MITM] mitmproxy로 거래 전문 열람 → Bearer 토큰 탈취','error'); addLog('[MITM] 수취계좌/금액 변조 후 서버로 전달','error'); addLog('[SERVER] 변조 거래 그대로 승인','error');",
 'breach_html':'<strong>🚨 중간자 공격 성공</strong><br>평문 통신과 인증서 미검증으로 거래정보와 자격증명이 그대로 노출·변조되었습니다.<table class="data-table"><tr><th>항목</th><th>원거래</th><th>변조 후</th></tr><tr><td>수취계좌</td><td>220-771-559010</td><td style="color:#b71c1c">999-000-HACKER</td></tr><tr><td>금액</td><td class="amount">10,000</td><td class="amount" style="color:#b71c1c">50,000,000</td></tr></table>',
 'violations':['평가기준 [전자금융] 통신구간 암호화 적용(위험도 5)',
               '전자금융감독규정 제32조: 정보처리시스템 전송구간 암호화 미흡',
               '중요정보 평문 전송 / 서버 인증서 검증 부재'],
 'defense_intro':'모든 거래 통신은 <strong>HTTPS(TLS 1.2 이상)</strong>로 강제하고, 클라이언트는 <strong>서버 인증서·호스트명을 검증</strong>(필요 시 인증서 고정)해야 합니다. 아래 통신 설정을 안전하게 보완하세요.',
 'vuln_code':'// [취약] 평문 통신 + 인증서 검증 무력화\nval url = "http://bank.example.com/transfer"   // 평문 HTTP\nval client = OkHttpClient.Builder()\n    .hostnameVerifier { _, _ -> true }         // 호스트명 검증 무시\n    .build()',
 'secure_hint':'// [안전] HTTPS 강제 + 인증서/호스트명 검증 + 핀닝\nval url = "https://bank.example.com/transfer"  // TLS 강제\nval pinner = CertificatePinner.Builder()\n    .add("bank.example.com", "sha256/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")\n    .build()\nval client = OkHttpClient.Builder()\n    .certificatePinner(pinner)                 // 인증서 고정\n    .connectionSpecs(listOf(ConnectionSpec.MODERN_TLS)) // 약한 프로토콜 차단\n    .build()                                   // 호스트명 기본 검증 유지',
 'checks':[['https'],['CertificatePinner','certificatePinner','MODERN_TLS']],
 'success_msg':'HTTPS 강제와 인증서 고정·호스트명 검증으로 중간자 공격이 차단됩니다.',
 'fail_msg':'평문 HTTP 대신 HTTPS를 사용하고 인증서/호스트명 검증(핀닝)을 적용해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>통신 보안 &gt; <b>통신구간 암호화 적용</b><h4>2. 위험 분석</h4><ul><li>평문 통신으로 거래정보·자격증명 탈취</li><li>인증서 미검증 시 중간자 변조 공격</li></ul><h4>3. 조치 방법</h4><ul><li>모든 거래 통신 <b>HTTPS(TLS 1.2 이상)</b> 적용</li><li>서버 <b>인증서·호스트명 검증</b> 및 인증서 고정</li><li>약한 암호스위트·구버전 프로토콜 <b>차단</b></li></ul>',
 'easy':'평문 통신은 내용이 보이는 <b>우편엽서</b>를 보내는 것과 같아, 배달부가 다 읽고 고칠 수 있습니다. HTTPS는 <b>밀봉된 봉투</b>를 쓰고 보내는 사람이 진짜인지 도장까지 확인하는 것입니다.',
},
{
 'file':'07_fin-auth-step-bypass.html',
 'title':'화면 강제실행 인증단계 우회',
 'icon':'🚪', 'target':'모바일뱅킹 내부 화면', 'risk':'5', 'item_code':'MOB-SER 인증단계 우회',
 'attack_panel_title':'화면 강제 호출',
 'scenario_html':'로그인·추가인증을 거치지 않고 <b>내부 화면 URL/액티비티를 직접 강제 호출</b>하면, 각 화면이 자체적으로 인증 상태를 확인하지 않을 경우 <b>인증 단계를 통째로 건너뛰고</b> 잔액·이체 화면에 진입할 수 있습니다.',
 'attack_name':'내부 액티비티 강제 호출', 'attack_sub':'adb로 잔액/이체 화면 직접 실행',
 'normal_req':'LoginActivity → OtpActivity → BalanceActivity\n(정상: 인증 단계 순차 통과 후 진입)',
 'attack_req':'# 로그인/추가인증 생략하고 화면 직접 호출\nadb shell am start -n com.bank.app/.BalanceActivity\n# 또는 deeplink로 내부 화면 강제 진입\nbankapp://internal/transfer',
 'vuln_logs_js':"addLog('[ADB] BalanceActivity 직접 실행 요청','warn'); addLog('[APP] 화면 진입 시 인증 상태(isLoggedIn) 확인 없음','error'); addLog('[FLOW] LoginActivity/OtpActivity 건너뜀','error'); addLog('[SCREEN] 잔액/이체 화면 노출 → 인증 우회 성공','error');",
 'breach_html':'<strong>🚨 인증단계 우회 성공</strong><br>화면별 인증 검증이 없어 로그인·추가인증을 거치지 않고 잔액·이체 화면이 그대로 표시되었습니다.',
 'violations':['평가기준 [전자금융] 인증단계 우회 방지(위험도 5)',
               '불충분한 인증 / 부적절한 접근통제(IN)',
               '전자금융감독규정 제37조 추가인증 의무 우회'],
 'defense_intro':'각 보호 화면은 진입 시 반드시 <strong>인증 상태(로그인·추가인증 완료)</strong>를 서버 세션 기준으로 확인하고, 미충족 시 <strong>로그인 화면으로 강제 이동</strong>해야 합니다. 화면 진입 로직을 보완하세요.',
 'vuln_code':'// [취약] 화면 진입 시 인증 확인 없음\noverride fun onCreate(savedInstanceState: Bundle?) {\n    super.onCreate(savedInstanceState)\n    setContentView(R.layout.activity_balance)\n    showBalance()   // 무조건 표시\n}',
 'secure_hint':'// [안전] 화면 진입 시 인증 단계 강제 검증\noverride fun onCreate(savedInstanceState: Bundle?) {\n    super.onCreate(savedInstanceState)\n    if (!session.isLoggedIn() || !session.isStepUpVerified()) {\n        requireAuth()   // 로그인/추가인증 화면으로 강제 이동\n        finish()\n        return\n    }\n    setContentView(R.layout.activity_balance)\n    showBalance()\n}',
 'checks':[['isLoggedIn','requireAuth'],['isStepUpVerified','추가인증','StepUp']],
 'success_msg':'화면 진입 시 로그인·추가인증 상태 검증으로 강제실행 우회가 차단됩니다.',
 'fail_msg':'각 보호 화면 진입 시 인증 상태(isLoggedIn/추가인증)를 검증해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>이용자 인증/인가 &gt; <b>인증단계 우회 방지</b><h4>2. 위험 분석</h4><ul><li>내부 화면 강제 호출로 로그인·추가인증 생략</li><li>잔액·이체 등 보호 화면 무단 진입</li></ul><h4>3. 조치 방법</h4><ul><li>모든 보호 화면 진입 시 <b>인증 상태 검증</b></li><li>미인증 시 <b>로그인 화면 강제 이동</b></li><li>인증 상태는 <b>서버 세션</b> 기준으로 판단</li></ul>',
 'easy':'은행 건물에 입구 검문을 안 하면, 옆문으로 들어가 곧장 <b>금고방</b>까지 가버립니다. 모든 방 앞에서 <b>출입증을 확인</b>하면 검문을 건너뛸 수 없습니다.',
},
{
 'file':'07_fin-deeplink.html',
 'title':'모바일 DeepLink 도용',
 'icon':'🔗', 'target':'모바일 앱 DeepLink/커스텀 스킴', 'risk':'5', 'item_code':'MOB-SER DeepLink 도용',
 'attack_panel_title':'DeepLink 수신 처리',
 'scenario_html':'검증 없는 <b>DeepLink/커스텀 스킴(예: bankapp://)</b>을 외부에서 그대로 수신·실행하면, 공격자가 만든 악성 링크가 앱을 호출해 <b>피싱 화면 표시·세션 탈취·이체 화면 자동 실행</b> 등 임의 동작을 유발할 수 있습니다.',
 'attack_name':'악성 DeepLink 유도', 'attack_sub':'문자/웹의 위조 링크로 이체 화면 자동 호출',
 'normal_req':'bankapp://open/notice?id=2026-1\n(정상: 공지 화면만 표시)',
 'attack_req':'<!-- 피싱 문자/웹페이지에 삽입된 위조 링크 -->\nbankapp://transfer?to=999-000-HACKER&amount=2000000&auto=1\n<!-- 출처/파라미터 검증 없이 이체 화면 자동 실행 -->',
 'vuln_logs_js':"addLog('[LINK] 외부 위조 DeepLink 수신: bankapp://transfer','warn'); addLog('[APP] 링크 출처/파라미터 검증 없음','error'); addLog('[FLOW] 이체 화면 자동 실행 + 수취계좌 자동 입력','error'); addLog('[SESSION] 콜백 토큰 탈취 시도','error');",
 'breach_html':'<strong>🚨 DeepLink 도용 성공</strong><br>출처·파라미터 검증이 없어 위조 링크가 이체 화면을 자동 실행하고 공격자 계좌가 자동 입력되었습니다.<table class="data-table"><tr><th>파라미터</th><th>값</th></tr><tr><td>수취계좌</td><td style="color:#b71c1c">999-000-HACKER</td></tr><tr><td>금액</td><td class="amount" style="color:#b71c1c">2,000,000</td></tr></table>',
 'violations':['평가기준 [전자금융] DeepLink 도용 방지(위험도 5)',
               '부적절한 인텐트 처리 / 출처 검증 부재(IN)',
               '검증되지 않은 리다이렉트 및 임의 동작 유발'],
 'defense_intro':'DeepLink 수신 시 <strong>허용된 경로·파라미터만 허용목록(allowlist)으로 검증</strong>하고, 민감 동작(이체 등)은 링크만으로 실행하지 말고 <strong>인증·사용자 확인</strong>을 강제해야 합니다. 수신 처리 로직을 보완하세요.',
 'vuln_code':'// [취약] DeepLink를 검증 없이 그대로 실행\noverride fun onNewIntent(intent: Intent) {\n    val data = intent.data ?: return\n    val path = data.host    // 예: "transfer"\n    navigate(path, data.query)   // 출처/값 검증 없이 화면 이동\n}',
 'secure_hint':'// [안전] 경로 허용목록 검증 + 민감동작 인증 강제\nprivate val allowlist = setOf("open", "notice")  // 안전한 경로만 허용\noverride fun onNewIntent(intent: Intent) {\n    val data = intent.data ?: return\n    val path = data.host ?: return\n    if (path !in allowlist) {                    // 허용목록 외 차단\n        blockAndExit("허용되지 않은 링크")\n        return\n    }\n    if (!session.isLoggedIn()) { requireAuth(); return }\n    navigate(path, data.query)\n}',
 'checks':[['allowlist','허용목록'],['requireAuth','isLoggedIn','blockAndExit']],
 'success_msg':'경로 허용목록 검증과 민감동작 인증 강제로 DeepLink 도용이 차단됩니다.',
 'fail_msg':'DeepLink 경로를 허용목록으로 검증하고 민감 동작에 인증을 강제해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>모바일 보안 &gt; <b>DeepLink 도용 방지</b><h4>2. 위험 분석</h4><ul><li>위조 링크로 피싱 화면·세션 탈취</li><li>이체 등 민감 화면 자동 실행(임의 동작)</li></ul><h4>3. 조치 방법</h4><ul><li>수신 경로·파라미터 <b>허용목록(allowlist)</b> 검증</li><li>민감 동작은 <b>인증·사용자 확인</b> 강제</li><li>커스텀 스킴 대신 <b>검증된 App Link</b> 사용 권장</li></ul>',
 'easy':'아무 <b>택배 운송장</b>이나 붙이면 그대로 배달되듯, 검증 없는 링크는 위조해 보내면 앱이 시키는 대로 합니다. 정해진 <b>허용 목록</b>의 링크만 받고 돈 나가는 일은 본인 확인을 또 받아야 합니다.',
},
{
 'file':'07_fin-ssti.html',
 'title':'서버 사이드 템플릿 인젝션(SSTI)',
 'icon':'🧨', 'target':'템플릿 기반 화면/메일 생성', 'risk':'5', 'item_code':'WEB-SER SSTI',
 'attack_panel_title':'템플릿 입력 처리',
 'scenario_html':'사용자 입력이 <b>서버 템플릿 엔진</b>에 그대로 합쳐져 평가되면, 공격자가 <b>{{7*7}}</b> 같은 표현식을 주입했을 때 서버가 이를 <b>49</b>로 계산합니다. 이를 발판으로 <b>원격 코드 실행(RCE)·내부 정보 노출</b>까지 이어집니다.',
 'attack_name':'템플릿 표현식 주입(SSTI)', 'attack_sub':'{{7*7}}→49 확인 후 RCE 페이로드',
 'normal_req':'POST /greeting\n{\n  "name": "홍길동"\n}\n# 출력: 안녕하세요, 홍길동님',
 'attack_req':'POST /greeting\n{\n  "name": "{{7*7}}"\n}\n# 출력: 안녕하세요, 49님   <-- 서버가 표현식 평가\n# 이어서 RCE 시도:\n# {{T(java.lang.Runtime).getRuntime().exec(\'calc\')}}',
 'vuln_logs_js':"addLog('[INPUT] name={{7*7}} 주입','warn'); addLog('[ENGINE] 사용자 입력을 템플릿 소스로 직접 평가 → 49 반환','error'); addLog('[SSTI] 표현식 평가 확인 → RCE 페이로드 주입','error'); addLog('[RCE] Runtime.exec 호출 → 시스템 명령 실행','error');",
 'breach_html':'<strong>🚨 SSTI → RCE 성공</strong><br>사용자 입력이 템플릿으로 평가되어 <b>{{7*7}} → 49</b>가 확인되었고, 이어진 페이로드로 서버 명령이 실행되었습니다.',
 'violations':['평가기준 [전자금융] 서버 사이드 템플릿 인젝션 방지(위험도 5)',
               '입력값 검증 부재 / 코드 인젝션(IN)',
               '신뢰할 수 없는 데이터의 동적 코드 평가'],
 'defense_intro':'사용자 입력을 <strong>템플릿 소스로 합치지 말고</strong>, 미리 정의된 템플릿에 <strong>데이터 모델(변수)로만 바인딩</strong>하고 <strong>샌드박스/이스케이프</strong>를 적용해야 합니다. 템플릿 처리 로직을 보완하세요.',
 'vuln_code':'// [취약] 사용자 입력을 템플릿 소스로 직접 평가\npublic String render(String name) {\n    // 입력이 그대로 템플릿 문법으로 해석됨\n    Template t = engine.parse("안녕하세요, " + name + "님");\n    return t.evaluate();\n}',
 'secure_hint':'// [안전] 고정 템플릿 + 데이터 바인딩 + 샌드박스/이스케이프\nprivate final Template TPL = engine.parse("안녕하세요, ${name}님");\npublic String render(String name) {\n    Map<String, Object> model = new HashMap<>();\n    model.put("name", escape(name));   // 값으로만 주입, 표현식 평가 안함\n    return TPL.evaluateSandboxed(model); // 제한된 샌드박스 평가\n}',
 'checks':[['escape'],['evaluateSandboxed','sandbox','Sandboxed']],
 'success_msg':'고정 템플릿에 값만 바인딩하고 이스케이프·샌드박스를 적용해 SSTI가 차단됩니다.',
 'fail_msg':'사용자 입력을 템플릿 소스로 합치지 말고 데이터 바인딩과 이스케이프/샌드박스를 적용해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>입력값 검증 &gt; <b>서버 사이드 템플릿 인젝션(SSTI) 방지</b><h4>2. 위험 분석</h4><ul><li>표현식 평가로 원격 코드 실행(RCE)</li><li>서버 내부 객체·환경변수 등 정보 노출</li></ul><h4>3. 조치 방법</h4><ul><li>사용자 입력을 <b>템플릿 소스로 결합 금지</b></li><li>고정 템플릿에 <b>데이터 모델 바인딩</b>만 사용</li><li>템플릿 <b>샌드박스·이스케이프</b> 적용</li></ul>',
 'easy':'빈칸에 적은 글이 그대로 출력될 줄 알았는데, 서버가 <b>{{7*7}}</b>을 보고 진짜로 <b>49</b>를 계산해 버립니다. 입력은 항상 <b>글자(값)</b>로만 다루고 수식으로 계산하지 못하게 막아야 합니다.',
},
]
