# -*- coding: utf-8 -*-
"""KISA 49 보안약점 중 사이트에 없던 16개(시간/상태·에러처리·코드오류·캡슐화·API오용) 명세."""


def J(**k):
    return k


SPECS = [
# ===== 시간 및 상태 =====
{
 'file':'03_code_race_condition.html', 'title':'경쟁조건 (TOCTOU)', 'icon':'⏱️',
 'cwe':'CWE-367: Time-of-check Time-of-use (TOCTOU) Race Condition', 'category':'시간 및 상태',
 'java':J(subtitle='검사-사용 사이 원자성 확보', filename='FileWriter.java',
   toolbar_hint='검사와 생성을 원자적으로 처리하세요(CREATE_NEW).',
   vuln='// [취약] 존재검사(exists) 후 생성(write) 사이 시간차 → TOCTOU\nFile f = new File("/tmp/session.dat");\nif (!f.exists()) {\n    FileWriter w = new FileWriter(f);\n    w.write(secret);\n    w.close();\n}',
   checks=[['CREATE_NEW','createNewFile','synchronized']],
   diag='검사 시점과 사용 시점 사이에 다른 프로세스가 개입하여 파일을 바꿔치기할 수 있습니다.',
   success='존재검사와 생성을 원자적으로 처리하여 경쟁조건을 제거했습니다.',
   fail='CREATE_NEW 옵션 또는 createNewFile() 등 원자적 연산을 사용하세요.',
   safe_desc='검사-사용이 단일 원자 연산으로 처리되어 TOCTOU가 제거되었습니다.',
   hint_title='1. 원자적 파일 생성', hint_desc='존재 확인과 생성을 하나의 원자적 연산으로 수행합니다.',
   hint_code='Path p = Paths.get("/tmp/session.dat");\ntry (var ch = Files.newByteChannel(p,\n        StandardOpenOption.CREATE_NEW,   // 없을 때만 원자적 생성\n        StandardOpenOption.WRITE)) {\n    ch.write(ByteBuffer.wrap(secret.getBytes()));\n}',
   goal='파일의 존재 검사와 생성/사용을 원자적으로 처리하여 경쟁조건을 제거해야 합니다.',
   vuln_name='TOCTOU Race Condition', vuln_desc='검사 후 사용 사이의 시간차를 악용해 심볼릭 링크 공격 등이 가능합니다.',
   checklist=['진단 시작','경쟁조건 식별','원자적 연산 적용']),
 'python':J(subtitle="배타적 생성 모드('x')", filename='file_util.py',
   toolbar_hint="open()의 'x'(배타적 생성) 모드를 사용하세요.",
   vuln='import os\n# [취약] exists 검사 후 open 사이 경쟁조건(TOCTOU)\nif not os.path.exists(path):\n    with open(path, "w") as f:\n        f.write(secret)',
   checks=[['"x"',"'x'",'O_EXCL']],
   diag='os.path.exists()와 open() 사이에 파일이 교체될 수 있습니다.',
   success="'x' 모드로 파일이 없을 때만 원자적으로 생성하도록 수정했습니다.",
   fail="open(path, 'x') 배타적 생성 모드를 사용하세요.",
   safe_desc="'x' 모드가 존재검사+생성을 원자적으로 처리합니다.",
   hint_title="1. 배타적 생성 모드", hint_desc="'x' 모드는 파일이 이미 있으면 예외를 던집니다.",
   hint_code='# 파일이 없을 때만 원자적으로 생성\ntry:\n    with open(path, "x") as f:\n        f.write(secret)\nexcept FileExistsError:\n    pass',
   goal='파일 생성 시 검사-사용 경쟁조건을 배타적 생성으로 제거합니다.',
   vuln_name='TOCTOU Race Condition', vuln_desc='검사와 사용 사이 시간차로 인한 파일 교체/링크 공격이 가능합니다.',
   checklist=['진단 시작','경쟁조건 식별','배타적 생성 적용']),
},
{
 'file':'03_code_infinite_loop.html', 'title':'종료되지 않는 반복문·재귀', 'icon':'♾️',
 'cwe':'CWE-835: Loop with Unreachable Exit Condition', 'category':'시간 및 상태',
 'java':J(subtitle='재귀 기저 조건 추가', filename='Calc.java',
   toolbar_hint='재귀에 종료(기저) 조건을 추가하세요.',
   vuln='// [취약] 종료 조건이 없는 재귀 → StackOverflow / DoS\nint factorial(int n) {\n    return n * factorial(n - 1);\n}',
   checks=[['<= 1','< 1','== 0','<=1','<1','==0']],
   diag='기저 조건이 없어 재귀가 무한히 호출되어 스택 오버플로우/서비스 거부가 발생합니다.',
   success='기저 조건을 추가하여 재귀가 정상 종료됩니다.',
   fail='n이 1 이하일 때 종료하는 기저 조건(if (n <= 1) return 1;)을 추가하세요.',
   safe_desc='종료 조건이 있어 무한 재귀가 방지되었습니다.',
   hint_title='1. 기저 조건', hint_desc='재귀 종료 조건을 가장 먼저 검사합니다.',
   hint_code='int factorial(int n) {\n    if (n <= 1) return 1;   // 기저 조건\n    return n * factorial(n - 1);\n}',
   goal='반복/재귀에 도달 가능한 종료 조건을 두어 무한 실행을 방지합니다.',
   vuln_name='Unbounded Recursion', vuln_desc='종료 조건 부재로 자원 고갈 및 DoS가 발생합니다.',
   checklist=['진단 시작','무한 재귀 식별','기저 조건 추가']),
 'python':J(subtitle='루프 종료/한계 추가', filename='worker.py',
   toolbar_hint='break 또는 횟수/타임아웃 한계를 추가하세요.',
   vuln='# [취약] 종료 조건 없는 while True → 무한 루프(DoS)\ndef poll(queue):\n    while True:\n        item = queue.get()\n        process(item)',
   checks=[['break','timeout','max_attempts','for _ in range','range(']],
   diag='탈출 조건이나 타임아웃이 없어 스레드가 영구히 점유됩니다.',
   success='종료 조건/한계를 추가하여 루프가 안전하게 끝납니다.',
   fail='break 조건이나 최대 반복 횟수/타임아웃을 추가하세요.',
   safe_desc='유한한 반복으로 자원 고갈이 방지되었습니다.',
   hint_title='1. 루프 한계', hint_desc='종료 신호 또는 최대 반복 횟수를 둡니다.',
   hint_code='def poll(queue, max_attempts=1000):\n    for _ in range(max_attempts):\n        item = queue.get(timeout=5)\n        if item is None:\n            break\n        process(item)',
   goal='반복문에 종료 조건이나 상한을 두어 무한 루프를 방지합니다.',
   vuln_name='Infinite Loop', vuln_desc='탈출 불가능한 루프로 CPU/스레드 자원이 고갈됩니다.',
   checklist=['진단 시작','무한 루프 식별','종료 조건 추가']),
},
# ===== 에러처리 =====
{
 'file':'03_code_error_message.html', 'title':'오류메시지 정보노출', 'icon':'📢',
 'cwe':'CWE-209: Generation of Error Message Containing Sensitive Information', 'category':'에러처리',
 'java':J(subtitle='상세 예외는 로그로만', filename='PaymentController.java',
   toolbar_hint='스택트레이스를 노출하지 말고 로그에 기록 후 일반 메시지를 반환하세요.',
   vuln='try {\n    processPayment(req);\n} catch (Exception e) {\n    // [취약] 내부 예외/스택트레이스를 사용자에게 노출\n    response.getWriter().println("Error: " + e.getMessage());\n    e.printStackTrace(response.getWriter());\n}',
   checks=[['logger','log.error','LOG.error'],['요청을 처리할 수 없습니다','처리 중 오류','일시적인 오류','오류가 발생']],
   diag='예외 메시지·스택트레이스에 내부 경로/쿼리/버전 등이 노출되어 후속 공격에 활용됩니다.',
   success='상세 내용은 서버 로그에만 남기고 사용자에겐 일반 메시지를 반환하도록 수정했습니다.',
   fail='logger로 내부 기록 후, 사용자에게는 일반화된 메시지를 반환하세요.',
   safe_desc='민감한 내부 정보가 응답에서 제거되었습니다.',
   hint_title='1. 로그 분리 + 일반 메시지', hint_desc='상세는 로그, 사용자에겐 일반 안내만.',
   hint_code='} catch (Exception e) {\n    logger.error("결제 처리 실패", e);   // 상세는 서버 로그에만\n    response.getWriter().println("요청을 처리할 수 없습니다.");\n}',
   goal='예외의 상세 정보를 사용자에게 노출하지 않고 서버 로그로만 기록합니다.',
   vuln_name='Sensitive Error Disclosure', vuln_desc='스택트레이스/예외 메시지로 시스템 내부 구조가 노출됩니다.',
   checklist=['진단 시작','정보노출 식별','로그 분리+일반화']),
 'python':J(subtitle='traceback 비노출', filename='views.py',
   toolbar_hint='traceback을 응답에 넣지 말고 logging으로 기록하세요.',
   vuln='try:\n    process_payment(req)\nexcept Exception as e:\n    # [취약] 예외 상세/트레이스백을 응답에 노출\n    return f"Error: {e}\\n{traceback.format_exc()}"',
   checks=[['logging','logger','log.'],['요청을 처리할 수 없습니다','처리 중 오류','일시적인 오류','오류가 발생']],
   diag='traceback.format_exc()가 응답에 포함되어 소스 경로·변수가 노출됩니다.',
   success='logging으로 기록하고 일반 메시지를 반환하도록 수정했습니다.',
   fail='logging.exception()으로 기록 후 일반화된 메시지를 반환하세요.',
   safe_desc='트레이스백이 응답에서 제거되었습니다.',
   hint_title='1. logging + 일반 메시지', hint_desc='상세는 로그로, 응답은 일반 안내.',
   hint_code='except Exception:\n    logging.exception("결제 처리 실패")  # 서버 로그에만 상세 기록\n    return "요청을 처리할 수 없습니다."',
   goal='예외 상세를 사용자 응답에서 제거하고 로그로만 남깁니다.',
   vuln_name='Sensitive Error Disclosure', vuln_desc='트레이스백 노출로 내부 구현이 드러납니다.',
   checklist=['진단 시작','정보노출 식별','로그 분리+일반화']),
},
{
 'file':'03_code_error_handling_missing.html', 'title':'오류상황 대응 부재', 'icon':'🕳️',
 'cwe':'CWE-391: Unchecked Error Condition', 'category':'에러처리',
 'java':J(subtitle='빈 catch 제거', filename='Transfer.java',
   toolbar_hint='예외를 무시하지 말고 로깅/재시도/예외전파로 대응하세요.',
   vuln='try {\n    int amount = Integer.parseInt(input);\n    transfer(amount);\n} catch (NumberFormatException e) {\n    // [취약] 예외를 잡고도 아무 대응이 없음(빈 catch)\n}',
   checks=[['logger','log.error','throw new','return']],
   diag='오류를 삼켜버려 실패가 드러나지 않고 잘못된 상태로 진행됩니다.',
   success='예외 상황에 대해 로깅/전파 등 대응 로직을 추가했습니다.',
   fail='catch 블록에서 logger 기록 또는 throw/return 등 대응을 추가하세요.',
   safe_desc='오류 상황이 적절히 처리/전파됩니다.',
   hint_title='1. 명시적 대응', hint_desc='로깅 후 사용자 안내 또는 예외 전파.',
   hint_code='} catch (NumberFormatException e) {\n    logger.warn("잘못된 금액 입력: {}", input, e);\n    throw new InvalidInputException("금액 형식이 올바르지 않습니다.");\n}',
   goal='발생한 오류를 무시하지 않고 적절히 처리·전파해야 합니다.',
   vuln_name='Unchecked Error', vuln_desc='빈 catch로 인해 실패가 은폐되어 데이터 무결성이 깨집니다.',
   checklist=['진단 시작','빈 catch 식별','대응 로직 추가']),
 'python':J(subtitle='except pass 제거', filename='transfer.py',
   toolbar_hint='except: pass 대신 logging/raise로 대응하세요.',
   vuln='try:\n    amount = int(user_input)\n    transfer(amount)\nexcept ValueError:\n    pass   # [취약] 예외를 무시(대응 부재)',
   checks=[['logging','logger','raise']],
   diag='예외를 pass로 삼켜 오류가 보고되지 않습니다.',
   success='logging/raise로 오류에 대응하도록 수정했습니다.',
   fail='except 블록에 logging 기록 또는 raise를 추가하세요.',
   safe_desc='오류가 적절히 처리/전파됩니다.',
   hint_title='1. 명시적 대응', hint_desc='로깅 후 예외 전파 또는 복구.',
   hint_code='except ValueError:\n    logging.warning("잘못된 금액 입력: %s", user_input)\n    raise InvalidInput("금액 형식 오류")',
   goal='오류 상황을 무시하지 않고 처리·전파합니다.',
   vuln_name='Unchecked Error', vuln_desc='예외 무시로 실패가 은폐됩니다.',
   checklist=['진단 시작','예외 무시 식별','대응 로직 추가']),
},
{
 'file':'03_code_improper_exception.html', 'title':'부적절한 예외처리', 'icon':'🎭',
 'cwe':'CWE-396: Declaration of Catch for Generic Exception', 'category':'에러처리',
 'java':J(subtitle='구체적 예외 분리', filename='DbService.java',
   toolbar_hint='포괄 Exception 대신 구체적 예외 타입을 처리하세요.',
   vuln='// [취약] 모든 예외를 포괄(Exception)하여 동일 취급 → 원인 구분 불가\ntry {\n    conn = pool.get();\n    conn.query(sql);\n} catch (Exception e) {\n    retry();\n}',
   checks=[['catch (SQLException','catch (TimeoutException','catch (IOException','catch(SQLException']],
   diag='모든 예외를 한꺼번에 잡아 복구 불가능한 오류까지 재시도하는 등 부적절하게 처리됩니다.',
   success='예외 유형별로 구분하여 처리하도록 수정했습니다.',
   fail='SQLException, TimeoutException 등 구체적 예외를 분리해서 처리하세요.',
   safe_desc='예외 유형별로 적절한 대응이 이뤄집니다.',
   hint_title='1. 구체적 예외', hint_desc='유형별로 catch를 나눕니다.',
   hint_code='} catch (SQLTransientException e) {\n    retry();                // 일시적 오류만 재시도\n} catch (SQLException e) {\n    logger.error("DB 오류", e);\n    throw new ServiceException(e);\n}',
   goal='포괄적 예외 처리 대신 구체적 예외 유형에 맞는 처리를 합니다.',
   vuln_name='Generic Exception Catch', vuln_desc='원인 구분 없는 처리로 심각한 오류가 은폐됩니다.',
   checklist=['진단 시작','포괄 예외 식별','구체적 예외 분리']),
 'python':J(subtitle='구체적 예외 분리', filename='db_service.py',
   toolbar_hint='except Exception 대신 구체적 예외를 처리하세요.',
   vuln='# [취약] 광범위한 except로 모든 예외를 동일 처리\ntry:\n    conn = pool.get()\n    conn.query(sql)\nexcept Exception:\n    retry()',
   checks=[['except OperationalError','except TimeoutError','except ConnectionError','except (']],
   diag='모든 예외를 같이 처리해 복구 불가 오류까지 재시도합니다.',
   success='구체적 예외 유형별로 처리하도록 수정했습니다.',
   fail='OperationalError, TimeoutError 등 구체적 예외를 분리하세요.',
   safe_desc='예외 유형별 대응이 이뤄집니다.',
   hint_title='1. 구체적 예외', hint_desc='유형별로 except를 나눕니다.',
   hint_code='except OperationalError:\n    retry()                # 일시적 DB 오류만 재시도\nexcept ConnectionError as e:\n    logging.error("연결 오류: %s", e)\n    raise',
   goal='포괄 except 대신 구체적 예외별 처리를 합니다.',
   vuln_name='Generic Exception Catch', vuln_desc='원인 미구분 처리로 오류가 은폐됩니다.',
   checklist=['진단 시작','포괄 예외 식별','구체적 예외 분리']),
},
# ===== 코드오류 =====
{
 'file':'03_code_null_pointer.html', 'title':'Null Pointer 역참조', 'icon':'🚫',
 'cwe':'CWE-476: NULL Pointer Dereference', 'category':'코드오류',
 'java':J(subtitle='null 검사/Optional', filename='UserService.java',
   toolbar_hint='역참조 전에 null 검사 또는 Optional을 사용하세요.',
   vuln='// [취약] null 가능 객체를 검사 없이 역참조\nUser u = repository.findById(id);   // 없으면 null\nString name = u.getName().trim();',
   checks=[['!= null','== null','Optional','requireNonNull']],
   diag='findById가 null을 반환하면 getName() 호출 시 NullPointerException이 발생합니다.',
   success='null 검사/Optional로 안전하게 역참조하도록 수정했습니다.',
   fail='u != null 검사 또는 Optional 처리를 추가하세요.',
   safe_desc='null 역참조가 방지되었습니다.',
   hint_title='1. null 방어', hint_desc='역참조 전 검사 또는 Optional.',
   hint_code='User u = repository.findById(id);\nif (u == null) throw new NotFoundException("사용자 없음");\nString name = u.getName().trim();\n// 또는: Optional.ofNullable(u).map(User::getName)...',
   goal='null 가능 값을 검사한 뒤에만 역참조해야 합니다.',
   vuln_name='NULL Dereference', vuln_desc='검사 없는 역참조로 NPE 및 서비스 중단이 발생합니다.',
   checklist=['진단 시작','null 역참조 식별','null 방어 추가']),
 'python':J(subtitle='None 검사', filename='user_service.py',
   toolbar_hint='None 여부를 검사한 뒤 속성에 접근하세요.',
   vuln='# [취약] None 가능 값을 검사 없이 사용\nuser = repository.find_by_id(id)   # 없으면 None\nname = user.name.strip()',
   checks=[['is not None','is None']],
   diag='find_by_id가 None을 반환하면 .name 접근 시 AttributeError가 발생합니다.',
   success='None 검사를 추가하여 안전하게 접근하도록 수정했습니다.',
   fail='user is not None(또는 is None 가드)로 검사하세요.',
   safe_desc='None 역참조가 방지되었습니다.',
   hint_title='1. None 가드', hint_desc='접근 전 None 검사.',
   hint_code='user = repository.find_by_id(id)\nif user is None:\n    raise NotFound("사용자 없음")\nname = user.name.strip()',
   goal='None 가능 값을 검사한 뒤 속성에 접근합니다.',
   vuln_name='None Dereference', vuln_desc='검사 없는 접근으로 AttributeError가 발생합니다.',
   checklist=['진단 시작','None 접근 식별','None 가드 추가']),
},
{
 'file':'03_code_improper_resource_release.html', 'title':'부적절한 자원 해제', 'icon':'💧',
 'cwe':'CWE-404: Improper Resource Shutdown or Release', 'category':'코드오류',
 'java':J(subtitle='try-with-resources', filename='FileReader.java',
   toolbar_hint='try-with-resources 또는 finally로 자원을 반드시 해제하세요.',
   vuln='// [취약] 예외 발생 시 close가 호출되지 않아 자원 누수\nFileInputStream in = new FileInputStream(path);\nbyte[] data = in.readAllBytes();\nprocess(data);\nin.close();',
   checks=[['try (','try(','finally']],
   diag='process() 중 예외가 나면 close()에 도달하지 못해 파일 핸들이 누수됩니다.',
   success='try-with-resources로 예외와 무관하게 자원이 해제됩니다.',
   fail='try-with-resources 또는 finally 블록에서 close를 보장하세요.',
   safe_desc='자원이 항상 해제됩니다.',
   hint_title='1. 자동 해제', hint_desc='try-with-resources 사용.',
   hint_code='try (FileInputStream in = new FileInputStream(path)) {\n    byte[] data = in.readAllBytes();\n    process(data);\n} // 블록 종료 시 자동 close',
   goal='예외 발생 여부와 무관하게 자원을 반드시 해제해야 합니다.',
   vuln_name='Resource Leak', vuln_desc='해제 누락으로 핸들/메모리 누수가 누적됩니다.',
   checklist=['진단 시작','자원 누수 식별','자동 해제 적용']),
 'python':J(subtitle='with 컨텍스트', filename='file_reader.py',
   toolbar_hint='with 문으로 파일을 자동 해제하세요.',
   vuln='# [취약] 예외 시 close 누락 → 파일 핸들 누수\nf = open(path, "rb")\ndata = f.read()\nprocess(data)\nf.close()',
   checks=[['with open','with ']],
   diag='process() 예외 시 close()에 도달하지 못해 핸들이 누수됩니다.',
   success='with 문으로 예외와 무관하게 파일이 닫힙니다.',
   fail='with open(...) 컨텍스트 매니저를 사용하세요.',
   safe_desc='파일 자원이 항상 해제됩니다.',
   hint_title='1. with 문', hint_desc='컨텍스트 매니저로 자동 해제.',
   hint_code='with open(path, "rb") as f:\n    data = f.read()\n    process(data)\n# 블록 종료 시 자동 close',
   goal='파일/소켓 등 자원을 컨텍스트 매니저로 안전하게 해제합니다.',
   vuln_name='Resource Leak', vuln_desc='해제 누락으로 핸들이 누수됩니다.',
   checklist=['진단 시작','자원 누수 식별','with 적용']),
},
{
 'file':'03_code_use_after_free.html', 'title':'해제된 자원 사용 (Use-After-Free)', 'icon':'♻️',
 'cwe':'CWE-416: Use After Free / Use of Released Resource', 'category':'코드오류',
 'java':J(subtitle='해제 후 사용 금지', filename='Reader.java',
   toolbar_hint='close 후 자원을 다시 사용하지 말고 사용 범위를 try 안으로 옮기세요.',
   vuln='// [취약] close 후 스트림을 다시 사용\nBufferedReader r = new BufferedReader(new FileReader(path));\nString first = r.readLine();\nr.close();\nString second = r.readLine();   // 닫힌 자원 사용 → IOException',
   checks=[['try (','try(']],
   diag='닫힌 스트림을 다시 사용하여 IOException 또는 예측 불가 동작이 발생합니다.',
   success='try-with-resources로 사용 범위를 한정하여 해제 후 사용을 차단했습니다.',
   fail='모든 사용을 try-with-resources 블록 안에서 끝내세요.',
   safe_desc='자원이 유효한 범위에서만 사용됩니다.',
   hint_title='1. 사용 범위 한정', hint_desc='모든 읽기를 try 블록 안에서 수행.',
   hint_code='try (BufferedReader r = new BufferedReader(new FileReader(path))) {\n    String first = r.readLine();\n    String second = r.readLine();   // 닫히기 전에 모두 사용\n}',
   goal='해제된 자원을 다시 사용하지 않도록 사용 범위를 관리합니다.',
   vuln_name='Use After Free/Close', vuln_desc='해제된 자원 접근으로 예외/정의되지 않은 동작이 발생합니다.',
   checklist=['진단 시작','해제 후 사용 식별','사용 범위 한정']),
 'python':J(subtitle='close 후 사용 금지', filename='reader.py',
   toolbar_hint='close 후 파일을 다시 쓰지 말고 with 블록 안에서 사용하세요.',
   vuln='# [취약] close 후 파일 객체를 다시 사용\nf = open(path)\nfirst = f.readline()\nf.close()\nsecond = f.readline()   # ValueError: I/O operation on closed file',
   checks=[['with open','with ']],
   diag='닫힌 파일을 다시 읽어 ValueError가 발생합니다.',
   success='with 블록으로 사용 범위를 한정하여 해제 후 사용을 차단했습니다.',
   fail='모든 읽기를 with open(...) 블록 안에서 수행하세요.',
   safe_desc='자원이 유효 범위에서만 사용됩니다.',
   hint_title='1. with 범위', hint_desc='읽기를 with 블록 안에서 수행.',
   hint_code='with open(path) as f:\n    first = f.readline()\n    second = f.readline()   # 닫히기 전에 모두 사용',
   goal='닫힌 파일/자원을 재사용하지 않습니다.',
   vuln_name='Use After Close', vuln_desc='닫힌 자원 사용으로 예외가 발생합니다.',
   checklist=['진단 시작','해제 후 사용 식별','with 범위 한정']),
},
{
 'file':'03_code_uninitialized_variable.html', 'title':'초기화되지 않은 변수 사용', 'icon':'🆕',
 'cwe':'CWE-457: Use of Uninitialized Variable', 'category':'코드오류',
 'java':J(subtitle='선언 시 초기화', filename='Score.java',
   toolbar_hint='변수를 선언 시 초기화하거나 else로 모든 경로를 처리하세요.',
   vuln='// [취약] 분기에 따라 초기화되지 않은 채 사용될 수 있음\nint result;\nif (cond) { result = compute(); }\nlog(result);   // cond=false면 미초기화',
   checks=[['int result = ','int result=','= 0','else']],
   diag='cond가 false면 result가 초기화되지 않아 컴파일 오류 또는 잘못된 값이 사용됩니다.',
   success='선언 시 초기화(또는 else 처리)하여 항상 정의된 값을 보장합니다.',
   fail='int result = 0; 처럼 초기화하거나 else 분기를 추가하세요.',
   safe_desc='변수가 항상 정의된 값을 가집니다.',
   hint_title='1. 기본값 초기화', hint_desc='선언과 동시에 안전한 기본값 부여.',
   hint_code='int result = 0;          // 기본값 초기화\nif (cond) { result = compute(); }\nlog(result);',
   goal='변수를 사용 전에 항상 초기화되도록 보장합니다.',
   vuln_name='Uninitialized Variable', vuln_desc='미초기화 변수 사용으로 비결정적 동작이 발생합니다.',
   checklist=['진단 시작','미초기화 식별','기본값 초기화']),
 'python':J(subtitle='사전 정의', filename='score.py',
   toolbar_hint='변수를 if 이전에 정의하거나 else를 추가하세요.',
   vuln='# [취약] 조건에 따라 정의되지 않을 수 있는 변수 사용\nif cond:\n    total = compute()\nprint(total)   # cond=False면 NameError',
   checks=[['total = 0','total=0','else']],
   diag='cond가 False면 total이 정의되지 않아 NameError가 발생합니다.',
   success='변수를 사전 정의(또는 else 처리)하여 항상 정의되도록 했습니다.',
   fail='total = 0 을 if 이전에 두거나 else 분기를 추가하세요.',
   safe_desc='변수가 항상 정의됩니다.',
   hint_title='1. 사전 정의', hint_desc='조건문 이전에 기본값 설정.',
   hint_code='total = 0          # 사전 정의\nif cond:\n    total = compute()\nprint(total)',
   goal='변수가 모든 실행 경로에서 정의되도록 합니다.',
   vuln_name='Undefined Variable', vuln_desc='미정의 변수 참조로 NameError가 발생합니다.',
   checklist=['진단 시작','미정의 식별','사전 정의']),
},
{
 'file':'03_code_deserialization.html', 'title':'신뢰할 수 없는 데이터의 역직렬화', 'icon':'📦',
 'cwe':'CWE-502: Deserialization of Untrusted Data', 'category':'코드오류',
 'java':J(subtitle='ObjectInputFilter 화이트리스트', filename='Receiver.java',
   toolbar_hint='역직렬화 허용 클래스를 화이트리스트로 제한하세요.',
   vuln='// [취약] 신뢰할 수 없는 입력을 그대로 역직렬화 → RCE 위험\nObjectInputStream ois = new ObjectInputStream(socket.getInputStream());\nObject obj = ois.readObject();',
   checks=[['ObjectInputFilter','setObjectInputFilter','createFilter']],
   diag='악의적 직렬화 객체로 가젯 체인을 통한 원격 코드 실행이 가능합니다.',
   success='ObjectInputFilter로 허용 클래스만 역직렬화하도록 제한했습니다.',
   fail='ObjectInputFilter(allowlist)를 설정하거나 JSON 등 데이터 포맷을 사용하세요.',
   safe_desc='허용된 클래스만 역직렬화되어 가젯 공격이 차단됩니다.',
   hint_title='1. 역직렬화 필터', hint_desc='허용 클래스 화이트리스트 적용.',
   hint_code='ObjectInputStream ois = new ObjectInputStream(in);\nois.setObjectInputFilter(ObjectInputFilter.Config\n    .createFilter("com.bank.dto.*;!*"));   // 허용 클래스만\nObject obj = ois.readObject();',
   goal='신뢰할 수 없는 데이터 역직렬화 시 허용 클래스를 제한하거나 안전한 포맷을 씁니다.',
   vuln_name='Untrusted Deserialization', vuln_desc='임의 객체 역직렬화로 RCE가 가능합니다.',
   checklist=['진단 시작','역직렬화 위험 식별','입력 필터 적용']),
 'python':J(subtitle='pickle 대신 JSON', filename='receiver.py',
   toolbar_hint='pickle.loads 대신 json.loads를 사용하세요.',
   vuln='import pickle\n# [취약] 신뢰할 수 없는 데이터를 pickle로 역직렬화 → 임의 코드 실행\nobj = pickle.loads(request.body)',
   checks=[['json.loads','json.load']],
   diag='pickle.loads는 임의 객체를 복원하며 __reduce__를 통해 코드가 실행됩니다.',
   success='데이터 전용 포맷(JSON)으로 교체하여 코드 실행 위험을 제거했습니다.',
   fail='pickle 대신 json.loads 등 데이터 전용 역직렬화를 사용하세요.',
   safe_desc='코드 실행 가능한 역직렬화가 제거되었습니다.',
   hint_title='1. 안전한 포맷', hint_desc='실행 위험 없는 JSON 사용.',
   hint_code='import json\n# pickle 대신 데이터 전용 포맷\nobj = json.loads(request.body)',
   goal='신뢰할 수 없는 입력에는 코드 실행 위험이 없는 직렬화 포맷을 사용합니다.',
   vuln_name='Insecure Deserialization', vuln_desc='pickle 역직렬화로 임의 코드가 실행됩니다.',
   checklist=['진단 시작','pickle 위험 식별','JSON 전환']),
},
# ===== 캡슐화 =====
{
 'file':'03_code_session_data_exposure.html', 'title':'잘못된 세션에 의한 데이터 정보 노출', 'icon':'🧷',
 'cwe':'CWE-488: Exposure of Data Element to Wrong Session', 'category':'캡슐화',
 'java':J(subtitle='요청지역변수/세션', filename='AccountServlet.java',
   toolbar_hint='상태를 인스턴스 필드가 아닌 지역변수/HttpSession에 저장하세요.',
   vuln='public class AccountServlet extends HttpServlet {\n    // [취약] 인스턴스 필드는 모든 요청/사용자가 공유 → 타 사용자 정보 노출\n    private String currentUser;\n    protected void doGet(HttpServletRequest req, HttpServletResponse res) {\n        currentUser = req.getParameter("user");\n        res.getWriter().println(loadBalance(currentUser));\n    }\n}',
   checks=[['getSession','HttpSession','String user = req']],
   diag='서블릿 인스턴스는 모든 요청이 공유하므로 동시 요청 간 사용자 데이터가 뒤섞입니다.',
   success='상태를 요청 지역변수/세션에 저장하여 사용자 간 격리했습니다.',
   fail='currentUser 필드 대신 지역변수 또는 HttpSession을 사용하세요.',
   safe_desc='요청/세션별로 데이터가 격리됩니다.',
   hint_title='1. 상태 격리', hint_desc='공유 필드 제거, 세션 사용.',
   hint_code='protected void doGet(HttpServletRequest req, HttpServletResponse res) {\n    String user = req.getParameter("user");      // 요청 지역변수\n    req.getSession().setAttribute("user", user);  // 사용자별 세션\n    res.getWriter().println(loadBalance(user));\n}',
   goal='멀티스레드 환경에서 사용자별 데이터를 공유 필드가 아닌 세션/지역변수에 보관합니다.',
   vuln_name='Wrong-Session Data Exposure', vuln_desc='공유 인스턴스 필드로 동시 사용자 정보가 교차 노출됩니다.',
   checklist=['진단 시작','공유 상태 식별','세션/지역변수 격리']),
 'python':J(subtitle='전역 대신 세션', filename='app.py',
   toolbar_hint='모듈 전역 변수 대신 요청별 session을 사용하세요.',
   vuln='# [취약] 모듈 전역 변수에 사용자 상태 저장 → 동시요청 교차 노출\ncurrent_user = None\n@app.route("/balance")\ndef balance():\n    global current_user\n    current_user = request.args.get("user")\n    return load_balance(current_user)',
   checks=[['session[','session.get']],
   diag='전역 변수는 모든 요청이 공유하여 동시 요청 시 사용자 정보가 섞입니다.',
   success='요청별 session/지역변수로 사용자 데이터를 격리했습니다.',
   fail='전역 변수 대신 session 또는 요청 지역변수를 사용하세요.',
   safe_desc='요청별로 데이터가 격리됩니다.',
   hint_title='1. 상태 격리', hint_desc='전역 제거, 세션 사용.',
   hint_code='@app.route("/balance")\ndef balance():\n    user = request.args.get("user")   # 요청 지역변수\n    session["user"] = user            # 사용자별 세션\n    return load_balance(user)',
   goal='사용자별 상태를 전역이 아닌 세션/지역변수에 보관합니다.',
   vuln_name='Wrong-Session Data Exposure', vuln_desc='전역 상태로 동시 사용자 정보가 교차 노출됩니다.',
   checklist=['진단 시작','전역 상태 식별','세션 격리']),
},
{
 'file':'03_code_debug_code.html', 'title':'제거되지 않은 디버그 코드', 'icon':'🐞',
 'cwe':'CWE-489: Active Debug Code', 'category':'캡슐화',
 'java':J(subtitle='디버그/백도어 제거', filename='LoginService.java',
   toolbar_hint='디버그 출력과 테스트 백도어를 제거하세요.',
   vuln='public boolean login(String id, String pw) {\n    // [취약] 운영에 남은 디버그 출력 + 테스트 백도어\n    System.out.println("DEBUG pw=" + pw);\n    if (id.equals("test") && pw.equals("test")) return true;\n    return authService.verify(id, pw);\n}',
   checks=[['NOT:System.out.println'],['NOT:"test"']],
   diag='디버그 출력으로 비밀번호가 로그에 남고, 테스트 백도어로 인증이 우회됩니다.',
   success='디버그 출력과 백도어 분기를 제거했습니다.',
   fail='System.out.println 디버그 출력과 "test" 백도어 분기를 모두 제거하세요.',
   safe_desc='운영 코드에서 디버그/백도어가 제거되었습니다.',
   hint_title='1. 정리', hint_desc='디버그 출력·백도어 삭제.',
   hint_code='public boolean login(String id, String pw) {\n    return authService.verify(id, pw);\n}',
   goal='운영 배포 전 디버그 코드와 백도어를 모두 제거해야 합니다.',
   vuln_name='Active Debug Code', vuln_desc='디버그 출력/백도어로 정보 노출과 인증 우회가 발생합니다.',
   checklist=['진단 시작','디버그/백도어 식별','코드 제거']),
 'python':J(subtitle='디버그/백도어 제거', filename='login.py',
   toolbar_hint='print 디버그와 테스트 백도어를 제거하세요.',
   vuln='def login(uid, pw):\n    # [취약] 디버그 출력 + 테스트 백도어 잔존\n    print("DEBUG pw=", pw)\n    if uid == "test" and pw == "test":\n        return True\n    return auth.verify(uid, pw)',
   checks=[['NOT:print("DEBUG'],['NOT:== "test"']],
   diag='print 디버그로 비밀번호가 노출되고, 백도어로 인증이 우회됩니다.',
   success='디버그 출력과 백도어 분기를 제거했습니다.',
   fail='print("DEBUG...) 와 == "test" 백도어를 모두 제거하세요.',
   safe_desc='디버그/백도어가 제거되었습니다.',
   hint_title='1. 정리', hint_desc='디버그 출력·백도어 삭제.',
   hint_code='def login(uid, pw):\n    return auth.verify(uid, pw)',
   goal='운영 코드에서 디버그/백도어를 제거합니다.',
   vuln_name='Active Debug Code', vuln_desc='디버그 출력/백도어로 정보 노출·인증 우회가 발생합니다.',
   checklist=['진단 시작','디버그/백도어 식별','코드 제거']),
},
{
 'file':'03_code_private_array_return.html', 'title':'Public 메서드의 Private 배열 반환', 'icon':'📤',
 'cwe':'CWE-495: Private Data Structure Returned From a Public Method', 'category':'캡슐화',
 'java':J(subtitle='방어적 복사 반환', filename='Account.java',
   toolbar_hint='내부 배열은 clone()/복사본으로 반환하세요.',
   vuln='public class Account {\n    private int[] transactions;\n    // [취약] 내부 배열 참조를 그대로 반환 → 외부에서 내부 상태 변경 가능\n    public int[] getTransactions() {\n        return transactions;\n    }\n}',
   checks=[['.clone()','Arrays.copyOf','copyOf']],
   diag='반환된 내부 배열을 호출자가 수정하면 객체 내부 상태가 깨집니다.',
   success='clone()/복사본을 반환하여 내부 상태를 보호했습니다.',
   fail='return transactions.clone(); 처럼 복사본을 반환하세요.',
   safe_desc='내부 배열이 외부 변경으로부터 보호됩니다.',
   hint_title='1. 방어적 복사', hint_desc='복사본을 반환.',
   hint_code='public int[] getTransactions() {\n    return transactions.clone();   // 방어적 복사\n}',
   goal='내부 가변 배열은 복사본으로 반환하여 캡슐화를 지킵니다.',
   vuln_name='Private Array Exposure', vuln_desc='내부 참조 반환으로 외부에서 상태를 변경할 수 있습니다.',
   checklist=['진단 시작','내부 참조 반환 식별','방어적 복사']),
 'python':J(subtitle='복사본 반환', filename='account.py',
   toolbar_hint='내부 리스트는 복사본(list()/[:])으로 반환하세요.',
   vuln='class Account:\n    def __init__(self):\n        self._transactions = []\n    # [취약] 내부 리스트 참조를 그대로 반환 → 외부에서 직접 수정 가능\n    def get_transactions(self):\n        return self._transactions',
   checks=[['list(self._transactions)','.copy()','[:]']],
   diag='반환된 내부 리스트를 호출자가 수정하면 객체 상태가 깨집니다.',
   success='복사본을 반환하여 내부 상태를 보호했습니다.',
   fail='return list(self._transactions) 등 복사본을 반환하세요.',
   safe_desc='내부 리스트가 외부 변경으로부터 보호됩니다.',
   hint_title='1. 방어적 복사', hint_desc='복사본 반환.',
   hint_code='def get_transactions(self):\n    return list(self._transactions)   # 복사본',
   goal='내부 가변 컬렉션은 복사본으로 반환합니다.',
   vuln_name='Private List Exposure', vuln_desc='내부 참조 반환으로 외부에서 상태가 변경됩니다.',
   checklist=['진단 시작','내부 참조 반환 식별','복사본 반환']),
},
{
 'file':'03_code_public_to_private_array.html', 'title':'Private 배열에 Public 데이터 할당', 'icon':'📥',
 'cwe':'CWE-496: Public Data Assigned to Private Array-Typed Field', 'category':'캡슐화',
 'java':J(subtitle='입력 방어적 복사', filename='Config.java',
   toolbar_hint='외부 배열은 clone()/복사 후 내부 필드에 저장하세요.',
   vuln='public class Config {\n    private String[] roles;\n    // [취약] 외부 배열 참조를 내부 필드에 그대로 저장 → 외부 변경에 노출\n    public Config(String[] roles) {\n        this.roles = roles;\n    }\n}',
   checks=[['.clone()','Arrays.copyOf','copyOf']],
   diag='호출자가 보관 중인 배열을 나중에 수정하면 내부 상태가 함께 바뀝니다.',
   success='입력 배열을 복사하여 내부 필드에 저장하도록 수정했습니다.',
   fail='this.roles = roles.clone(); 처럼 복사본을 저장하세요.',
   safe_desc='내부 필드가 외부 참조와 분리되었습니다.',
   hint_title='1. 방어적 복사', hint_desc='입력을 복사 후 저장.',
   hint_code='public Config(String[] roles) {\n    this.roles = roles.clone();   // 입력 방어적 복사\n}',
   goal='외부에서 받은 가변 배열은 복사하여 내부에 저장합니다.',
   vuln_name='External Reference Stored', vuln_desc='외부 참조 저장으로 내부 상태가 외부 변경에 노출됩니다.',
   checklist=['진단 시작','외부 참조 저장 식별','입력 복사']),
 'python':J(subtitle='입력 복사', filename='config.py',
   toolbar_hint='외부 리스트는 list()/[:]로 복사 후 저장하세요.',
   vuln='class Config:\n    # [취약] 외부 리스트를 그대로 참조 저장 → 호출측 변경에 노출\n    def __init__(self, roles):\n        self._roles = roles',
   checks=[['list(roles)','roles.copy()','roles[:]']],
   diag='호출자가 전달한 리스트를 나중에 수정하면 내부 상태가 함께 바뀝니다.',
   success='입력 리스트를 복사하여 저장하도록 수정했습니다.',
   fail='self._roles = list(roles) 처럼 복사본을 저장하세요.',
   safe_desc='내부 상태가 외부 참조와 분리되었습니다.',
   hint_title='1. 입력 복사', hint_desc='복사 후 저장.',
   hint_code='def __init__(self, roles):\n    self._roles = list(roles)   # 입력 복사',
   goal='외부 가변 컬렉션은 복사하여 내부에 저장합니다.',
   vuln_name='External Reference Stored', vuln_desc='외부 참조 저장으로 내부 상태가 노출됩니다.',
   checklist=['진단 시작','외부 참조 저장 식별','입력 복사']),
},
# ===== API 오용 =====
{
 'file':'03_code_dns_security_decision.html', 'title':'DNS lookup에 의존한 보안결정', 'icon':'🌐',
 'cwe':'CWE-350: Reliance on Reverse DNS Resolution for Security Decision', 'category':'API 오용',
 'java':J(subtitle='DNS 대신 인증 기반', filename='AccessControl.java',
   toolbar_hint='역DNS 이름 대신 인증 토큰/검증으로 인가하세요.',
   vuln='// [취약] 역DNS 이름으로 인가 결정 → DNS 스푸핑으로 우회 가능\nString host = request.getRemoteHost();   // 역DNS 조회 결과\nif (host.endsWith(".trusted.com")) {\n    grantAdmin();\n}',
   checks=[['verifyToken','token','인증서','mTLS','verify(']],
   diag='역DNS는 공격자가 위조할 수 있어 호스트명 기반 인가는 신뢰할 수 없습니다.',
   success='DNS 이름이 아닌 인증 토큰/암호학적 검증으로 인가하도록 수정했습니다.',
   fail='호스트명 대신 인증 토큰 검증(verifyToken 등)이나 mTLS로 판단하세요.',
   safe_desc='인가 결정이 위조 불가능한 자격증명에 기반합니다.',
   hint_title='1. 신뢰 기반 변경', hint_desc='DNS 대신 인증된 자격증명.',
   hint_code='// 호스트명 대신 서명된 토큰/상호TLS로 신원 검증\nif (auth.verifyToken(request.getHeader("Authorization"))\n        && auth.hasRole("ADMIN")) {\n    grantAdmin();\n}',
   goal='보안 결정을 위조 가능한 역DNS가 아닌 인증/암호 검증에 기반해야 합니다.',
   vuln_name='Reverse DNS Trust', vuln_desc='DNS 스푸핑으로 호스트명 기반 인가가 우회됩니다.',
   checklist=['진단 시작','DNS 의존 식별','인증 기반 전환']),
 'python':J(subtitle='DNS 대신 검증', filename='access_control.py',
   toolbar_hint='역DNS(PTR) 대신 토큰/HMAC 검증으로 신뢰를 판단하세요.',
   vuln='import socket\n# [취약] 역DNS(PTR) 이름으로 신뢰 판단 → 스푸핑 우회 가능\nname = socket.gethostbyaddr(client_ip)[0]\nif name.endswith(".trusted.com"):\n    grant_admin()',
   checks=[['verify_token','hmac','token','인증']],
   diag='PTR 레코드는 위조 가능하여 신뢰 판단 근거가 될 수 없습니다.',
   success='DNS 이름 대신 토큰/HMAC 검증으로 신뢰를 판단하도록 수정했습니다.',
   fail='gethostbyaddr 대신 verify_token/HMAC 등 검증을 사용하세요.',
   safe_desc='신뢰 판단이 위조 불가능한 검증에 기반합니다.',
   hint_title='1. 검증 기반', hint_desc='DNS 대신 토큰/HMAC.',
   hint_code='# PTR 이름 대신 서명 토큰 검증\nif verify_token(request.headers.get("Authorization")):\n    grant_admin()',
   goal='보안 결정을 DNS가 아닌 암호학적 검증에 기반합니다.',
   vuln_name='Reverse DNS Trust', vuln_desc='PTR 스푸핑으로 인가가 우회됩니다.',
   checklist=['진단 시작','DNS 의존 식별','검증 기반 전환']),
},
{
 'file':'03_code_vulnerable_api.html', 'title':'취약한 API 사용', 'icon':'⚠️',
 'cwe':'CWE-477/676: Use of Obsolete/Dangerous Function', 'category':'API 오용',
 'java':J(subtitle='SecureRandom·ProcessBuilder', filename='Util.java',
   toolbar_hint='예측가능 Random/문자열 exec 대신 SecureRandom과 ProcessBuilder를 쓰세요.',
   vuln='// [취약] 보안에 부적합한 API: 예측가능 Random, 문자열 exec(셸 인젝션)\nRandom rnd = new Random();\nString token = Long.toHexString(rnd.nextLong());\nRuntime.getRuntime().exec("sh -c \'backup " + name + "\'");',
   checks=[['SecureRandom'],['ProcessBuilder']],
   diag='Random은 예측 가능하고, 문자열 exec는 셸 인젝션에 취약합니다.',
   success='SecureRandom과 ProcessBuilder(인자 분리)로 교체했습니다.',
   fail='SecureRandom과 ProcessBuilder를 사용하세요.',
   safe_desc='안전한 난수와 인자 분리 실행으로 위험 API가 제거되었습니다.',
   hint_title='1. 안전한 API', hint_desc='SecureRandom + ProcessBuilder.',
   hint_code='SecureRandom rnd = new SecureRandom();\nString token = Long.toHexString(rnd.nextLong());\nnew ProcessBuilder("backup", name).start();  // 인자 분리(셸 미경유)',
   goal='보안에 부적합한 오래된/위험한 API를 안전한 대체 API로 교체합니다.',
   vuln_name='Dangerous API Use', vuln_desc='예측가능 난수/문자열 exec로 토큰 예측·명령 주입이 가능합니다.',
   checklist=['진단 시작','위험 API 식별','안전 API 전환']),
 'python':J(subtitle='secrets·subprocess.run', filename='util.py',
   toolbar_hint='random/os.system 대신 secrets와 subprocess.run(리스트)을 쓰세요.',
   vuln='import random, os\n# [취약] 보안 부적합 API: random(예측가능), os.system(셸 인젝션)\ntoken = str(random.random())\nos.system("backup " + name)',
   checks=[['secrets.'],['subprocess.run','subprocess.call']],
   diag='random은 예측 가능하고, os.system 문자열 결합은 셸 인젝션에 취약합니다.',
   success='secrets와 subprocess.run(인자 리스트)로 교체했습니다.',
   fail='secrets 모듈과 subprocess.run([...]) 인자 리스트를 사용하세요.',
   safe_desc='안전한 난수와 셸 미경유 실행으로 위험 API가 제거되었습니다.',
   hint_title='1. 안전한 API', hint_desc='secrets + subprocess.run 리스트.',
   hint_code='import secrets, subprocess\ntoken = secrets.token_hex(16)\nsubprocess.run(["backup", name], check=True)  # 인자 리스트(셸 미경유)',
   goal='위험한 표준 API를 보안에 적합한 대체 API로 교체합니다.',
   vuln_name='Dangerous API Use', vuln_desc='예측가능 난수/os.system으로 토큰 예측·명령 주입이 가능합니다.',
   checklist=['진단 시작','위험 API 식별','안전 API 전환']),
},
]
