# -*- coding: utf-8 -*-
"""주요정보통신기반시설 DBMS(Oracle 기준) 점검 항목 — 사이트 미보유 14종(D-05~D-24)."""

CAT = '데이터베이스 보안'


def D(code, title, icon, sev, desc, vt, st, fixes, chk, ref):
    return {'file': '06_db-%s.html' % code.lower().replace('-', ''),  # D-05 -> 06_db-d05.html
            'code': code, 'title': title, 'icon': icon, 'category': CAT, 'severity': sev,
            'description': desc, 'vuln_term': vt, 'secure_term': st,
            'fix_steps': fixes, 'checklist': chk, 'kisa_ref': ref}


SPECS = [
D('D-05', '패스워드 재사용 금지', '🔁', '중',
  '이전 비밀번호를 반복 사용하면 유출된 과거 비밀번호로 계정이 탈취될 수 있습니다. 프로파일의 PASSWORD_REUSE_TIME/MAX로 재사용을 제한해야 합니다.',
  [('cmt', '-- 재사용 제한 확인'), ('prompt', 'SQL> '), ('', "SELECT limit FROM dba_profiles WHERE resource_name='PASSWORD_REUSE_MAX';"),
   ('bad', 'UNLIMITED'), ('warn', '→ 과거 비밀번호 재사용 가능 (취약)')],
  [('cmt', '-- 재사용 제한 설정'), ('prompt', 'SQL> '), ('', 'ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_MAX 10 PASSWORD_REUSE_TIME 365;'),
   ('good', 'Profile altered.'), ('good', '→ 최근 비밀번호 재사용 차단 (양호)')],
  ['<code>PASSWORD_REUSE_MAX</code>(횟수)와 <code>PASSWORD_REUSE_TIME</code>(기간)을 함께 설정합니다.',
   '모든 사용자 프로파일에 정책이 적용되는지 확인합니다.'],
  ['PASSWORD_REUSE_MAX/TIME이 UNLIMITED가 아닌가', '전 계정 프로파일에 정책 적용'],
  '데이터베이스 > 패스워드 재사용 제한'),

D('D-06', 'DBA/SYSDBA 권한 최소화', '👑', '상',
  '과도한 DBA·SYSDBA 권한 부여는 권한 오남용·내부자 위협을 키웁니다. 관리자 권한은 꼭 필요한 계정에만 최소 부여해야 합니다.',
  [('cmt', '-- DBA 권한 보유자 확인'), ('prompt', 'SQL> '), ('', "SELECT grantee FROM dba_role_privs WHERE granted_role='DBA';"),
   ('bad', 'APPUSER  / BATCH / DEV1 ...'), ('warn', '→ 응용/개발 계정에 DBA 부여 (취약)')],
  [('cmt', '-- 불필요 DBA 회수'), ('prompt', 'SQL> '), ('', 'REVOKE DBA FROM APPUSER;'),
   ('good', 'Revoke succeeded.'), ('good', '→ 관리자 권한 최소화 (양호)')],
  ['응용/개발 계정에서 불필요한 <code>DBA</code> 권한을 회수합니다.',
   '업무에 필요한 최소 권한만 Role로 부여합니다(최소 권한 원칙).',
   'SYSDBA 접속 가능 계정을 주기적으로 점검합니다.'],
  ['DBA 권한이 관리자 계정에만 부여됨', '응용/개발 계정에 과도 권한이 없는가'],
  '데이터베이스 > 관리자 권한 최소화'),

D('D-07', '원격 OS 인증 제한', '🚪', '상',
  'REMOTE_OS_AUTHENT가 TRUE이면 원격 OS 계정을 신뢰하여 인증 없이 DB 접속이 가능합니다. FALSE로 설정해 OS 인증 우회를 차단해야 합니다.',
  [('cmt', '-- 파라미터 확인'), ('prompt', 'SQL> '), ('', "SHOW PARAMETER remote_os_authent"),
   ('bad', 'remote_os_authent  boolean  TRUE'), ('warn', '→ 원격 OS 계정 신뢰로 인증 우회 (취약)')],
  [('cmt', '-- FALSE 설정 후 재기동'), ('prompt', 'SQL> '), ('', "ALTER SYSTEM SET remote_os_authent=FALSE SCOPE=SPFILE;"),
   ('good', 'System altered.'), ('good', '→ 원격 OS 인증 차단 (양호)')],
  ['<code>REMOTE_OS_AUTHENT=FALSE</code>로 설정(SPFILE) 후 인스턴스를 재기동합니다.',
   'OPS$ 계정 등 OS 인증 계정의 필요성을 재검토합니다.'],
  ['REMOTE_OS_AUTHENT가 FALSE인가', 'OS 인증 계정이 최소화됨'],
  '데이터베이스 > 원격 OS 인증 제한'),

D('D-09', '로그인 실패 횟수 제한', '🔒', '상',
  'FAILED_LOGIN_ATTEMPTS가 무제한이면 무차별 대입(brute force)으로 비밀번호가 탈취될 수 있습니다. 실패 임계값과 잠금을 설정해야 합니다.',
  [('cmt', '-- 실패 임계값 확인'), ('prompt', 'SQL> '), ('', "SELECT limit FROM dba_profiles WHERE resource_name='FAILED_LOGIN_ATTEMPTS';"),
   ('bad', 'UNLIMITED'), ('warn', '→ 무차별 대입 가능 (취약)')],
  [('cmt', '-- 임계값/잠금 설정'), ('prompt', 'SQL> '), ('', 'ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 1;'),
   ('good', 'Profile altered.'), ('good', '→ 5회 실패 시 계정 잠금 (양호)')],
  ['<code>FAILED_LOGIN_ATTEMPTS</code>를 5회 이하로 설정합니다.',
   '<code>PASSWORD_LOCK_TIME</code>으로 잠금 시간을 설정합니다.'],
  ['FAILED_LOGIN_ATTEMPTS가 제한되어 있는가', '잠금 시간이 설정됨'],
  '데이터베이스 > 로그인 실패 횟수 제한'),

D('D-13', '데이터 딕셔너리 접근 제한', '📖', '상',
  'O7_DICTIONARY_ACCESSIBILITY가 TRUE이면 ANY 시스템 권한으로 데이터 딕셔너리(SYS 소유 객체)에 접근해 권한 상승이 가능합니다. FALSE로 설정해야 합니다.',
  [('cmt', '-- 파라미터 확인'), ('prompt', 'SQL> '), ('', "SHOW PARAMETER O7_DICTIONARY_ACCESSIBILITY"),
   ('bad', 'O7_DICTIONARY_ACCESSIBILITY  boolean  TRUE'), ('warn', '→ 딕셔너리 접근으로 권한상승 (취약)')],
  [('cmt', '-- FALSE 설정'), ('prompt', 'SQL> '), ('', "ALTER SYSTEM SET O7_DICTIONARY_ACCESSIBILITY=FALSE SCOPE=SPFILE;"),
   ('good', 'System altered.'), ('good', '→ 딕셔너리 보호 (양호)')],
  ['<code>O7_DICTIONARY_ACCESSIBILITY=FALSE</code>로 설정 후 재기동합니다.',
   'SELECT ANY TABLE 등 ANY 권한 보유 계정을 점검합니다.'],
  ['O7_DICTIONARY_ACCESSIBILITY가 FALSE인가', 'ANY 권한 보유 계정이 최소화됨'],
  '데이터베이스 > 데이터 딕셔너리 접근 제한'),

D('D-14', '리스너 비밀번호 설정', '🎧', '상',
  '리스너에 비밀번호가 없으면 원격에서 리스너를 정지(STOP)하거나 설정을 변경하는 서비스 거부·정보 노출이 가능합니다. 비밀번호를 설정해야 합니다.',
  [('cmt', '-- 리스너 상태'), ('prompt', '# '), ('', 'lsnrctl status'),
   ('bad', 'Security        ON: Local OS Authentication 없음'), ('warn', '→ 원격에서 리스너 제어 가능 (취약)')],
  [('cmt', '-- 비밀번호 설정'), ('prompt', '# '), ('', 'LSNRCTL> CHANGE_PASSWORD'),
   ('good', 'listener.ora: PASSWORDS_LISTENER 설정됨'), ('good', '→ 인증 없이는 제어 불가 (양호)')],
  ['<code>listener.ora</code>에 리스너 비밀번호를 설정합니다.',
   '최신 버전은 로컬 OS 인증을 사용하고 원격 관리(ADMIN_RESTRICTIONS=ON)를 제한합니다.'],
  ['리스너 비밀번호/관리 제한이 설정됨', '원격 리스너 제어가 차단됨'],
  '데이터베이스 > 리스너 보안 설정'),

D('D-15', '리스너 로깅 활성화', '📝', '중',
  '리스너 로깅이 비활성화되면 접속 시도·공격 흔적을 추적할 수 없습니다. 로깅을 활성화하고 로그를 보호해야 합니다.',
  [('cmt', '-- 로깅 설정 확인'), ('prompt', '# '), ('', 'lsnrctl status | grep "Listener Log"'),
   ('bad', 'Listener Log File   OFF'), ('warn', '→ 접속/공격 흔적 미기록 (취약)')],
  [('cmt', '-- 로깅 ON'), ('prompt', '# '), ('', 'LSNRCTL> SET LOG_STATUS ON'),
   ('good', 'Listener Log File   ON'), ('good', '→ 리스너 로깅 활성화 (양호)')],
  ['<code>listener.ora</code>에서 <code>LOGGING_LISTENER=ON</code>으로 설정합니다.',
   '로그 파일 권한을 제한하고 정기적으로 검토합니다.'],
  ['리스너 로깅이 활성화됨', '로그 접근 권한이 보호됨'],
  '데이터베이스 > 리스너 로깅'),

D('D-16', '불필요한 DB 링크 제거', '🔗', '중',
  '사용하지 않는 데이터베이스 링크(DB Link)는 자격증명이 저장되어 있어 인접 DB로의 측면 이동 경로가 됩니다. 불필요한 링크는 제거해야 합니다.',
  [('cmt', '-- DB 링크 목록'), ('prompt', 'SQL> '), ('', 'SELECT db_link, username, host FROM dba_db_links;'),
   ('bad', 'OLD_LINK  APPUSER  legacy-db'), ('warn', '→ 미사용 링크에 자격증명 잔존 (취약)')],
  [('cmt', '-- 불필요 링크 삭제'), ('prompt', 'SQL> '), ('', 'DROP DATABASE LINK OLD_LINK;'),
   ('good', 'Database link dropped.'), ('good', '→ 미사용 링크 제거 (양호)')],
  ['사용하지 않는 DB 링크를 <code>DROP DATABASE LINK</code>로 제거합니다.',
   '필요한 링크는 최소 권한 계정으로 생성하고 주기적으로 점검합니다.'],
  ['불필요한 DB 링크가 제거됨', '잔존 링크가 최소 권한으로 구성됨'],
  '데이터베이스 > 불필요한 DB 링크 제거'),

D('D-17', '감사(Audit) 기능 활성화', '🔍', '상',
  '감사 기능이 비활성화되면 권한 변경·중요 데이터 접근 등 보안 이벤트를 추적할 수 없습니다. 감사를 활성화하고 로그를 보호해야 합니다.',
  [('cmt', '-- 감사 설정 확인'), ('prompt', 'SQL> '), ('', "SHOW PARAMETER audit_trail"),
   ('bad', 'audit_trail   string   NONE'), ('warn', '→ 보안 이벤트 미기록 (취약)')],
  [('cmt', '-- 감사 활성화'), ('prompt', 'SQL> '), ('', "ALTER SYSTEM SET audit_trail=DB,EXTENDED SCOPE=SPFILE;"),
   ('good', 'AUDIT CREATE SESSION; AUDIT ALTER USER;'), ('good', '→ 감사 기능 활성화 (양호)')],
  ['<code>AUDIT_TRAIL</code>을 DB(또는 OS)로 설정 후 재기동합니다.',
   '접속, 권한 변경, 중요 객체 접근 등에 대해 AUDIT을 설정합니다.',
   '최신 버전은 <code>Unified Auditing</code> 정책을 사용합니다.'],
  ['AUDIT_TRAIL이 활성화됨', '중요 이벤트에 감사 정책이 설정됨'],
  '데이터베이스 > 감사 기능 활성화'),

D('D-20', '중요정보 컬럼 암호화 (TDE)', '🔐', '상',
  '주민번호·계좌번호 등 중요정보가 평문으로 저장되면 파일 유출·백업 탈취 시 그대로 노출됩니다. TDE 등으로 저장 데이터를 암호화해야 합니다.',
  [('cmt', '-- 평문 저장 예시'), ('prompt', 'SQL> '), ('', 'SELECT ssn FROM customer WHERE rownum=1;'),
   ('bad', '900101-1234567 (평문)'), ('warn', '→ 중요정보 평문 저장 (취약)')],
  [('cmt', '-- 컬럼 암호화(TDE)'), ('prompt', 'SQL> '), ('', 'ALTER TABLE customer MODIFY (ssn ENCRYPT);'),
   ('good', 'Table altered.  SELECT ssn → (암호문)'), ('good', '→ 저장 데이터 암호화 (양호)')],
  ['TDE(Transparent Data Encryption)로 중요 컬럼/테이블스페이스를 암호화합니다.',
   '암호키(Wallet)를 안전하게 보관하고 접근을 제한합니다.',
   '백업 데이터도 암호화되도록 구성합니다.'],
  ['중요정보 컬럼이 암호화 저장됨', '암호키(Wallet)가 안전하게 보호됨'],
  '데이터베이스 > 중요정보 암호화 저장'),

D('D-21', '백업 및 복구 절차', '💾', '중',
  '정기 백업과 복구 절차가 없으면 장애·랜섬웨어 시 데이터를 복구할 수 없습니다. 백업을 자동화하고 복구 테스트를 수행해야 합니다.',
  [('cmt', '-- 백업 이력 확인'), ('prompt', 'RMAN> '), ('', 'LIST BACKUP SUMMARY;'),
   ('bad', 'specification does not match any backup'), ('warn', '→ 백업 미수행 (취약)')],
  [('cmt', '-- 정기 백업 수행'), ('prompt', 'RMAN> '), ('', 'BACKUP DATABASE PLUS ARCHIVELOG;'),
   ('good', 'Finished backup at ...'), ('good', '→ 정기 백업/복구 절차 운영 (양호)')],
  ['RMAN 등으로 전체/증분 백업을 자동화하고 보관 주기를 정의합니다.',
   '백업본을 분리 저장(오프사이트)하고 접근을 제한합니다.',
   '정기적으로 복구 테스트를 수행합니다.'],
  ['정기 백업이 수행되는가', '복구 절차/테스트가 마련됨', '백업본이 분리 보관됨'],
  '데이터베이스 > 백업 및 복구'),

D('D-22', '로그 보관 및 모니터링', '📊', '중',
  '감사·접속 로그를 보관·모니터링하지 않으면 침해 사고를 탐지·분석할 수 없습니다. 로그를 충분히 보관하고 이상 징후를 모니터링해야 합니다.',
  [('cmt', '-- 감사 로그량 확인'), ('prompt', 'SQL> '), ('', 'SELECT count(*) FROM dba_audit_trail;'),
   ('bad', '0 (또는 즉시 삭제됨)'), ('warn', '→ 로그 미보관/미점검 (취약)')],
  [('cmt', '-- 보관/연계'), ('prompt', 'SQL> '), ('', 'aud$ → SIEM 전송, 보관 90일+'),
   ('good', 'audit log retained & monitored'), ('good', '→ 로그 보관·모니터링 (양호)')],
  ['감사/접속 로그를 법규 요건에 맞게 충분히 보관합니다.',
   'SIEM 등과 연계해 이상 접근을 모니터링/알람합니다.',
   '로그 위변조 방지를 위해 접근 권한을 제한합니다.'],
  ['로그가 충분히 보관되는가', '이상 징후 모니터링이 운영됨'],
  '데이터베이스 > 로그 보관 및 모니터링'),

D('D-23', '최소 권한 원칙(Role)', '🎚️', '상',
  '사용자에게 권한을 직접·과다 부여하면 권한 관리가 어렵고 오남용 위험이 큽니다. 업무별 Role을 정의하고 최소 권한만 부여해야 합니다.',
  [('cmt', '-- 과다 권한 예시'), ('prompt', 'SQL> '), ('', "SELECT * FROM dba_sys_privs WHERE grantee='APPUSER';"),
   ('bad', 'SELECT ANY TABLE / CREATE ANY PROCEDURE'), ('warn', '→ ANY 권한 직접 부여 (취약)')],
  [('cmt', '-- Role 기반 최소 권한'), ('prompt', 'SQL> '), ('', 'GRANT app_read TO APPUSER;'),
   ('good', 'ANY 권한 회수, 업무 Role만 부여'), ('good', '→ 최소 권한 적용 (양호)')],
  ['업무 단위 <code>Role</code>을 정의하고 필요한 객체 권한만 부여합니다.',
   'SELECT ANY/CREATE ANY 등 ANY 권한을 회수합니다.',
   '권한 부여 현황을 주기적으로 검토합니다.'],
  ['ANY 등 과다 권한이 회수됨', '업무 Role로 최소 권한이 부여됨'],
  '데이터베이스 > 최소 권한 원칙'),

D('D-24', '보안 패치 적용 주기', '🩹', '상',
  '오래된 DBMS는 알려진 취약점(권한상승·RCE)에 노출됩니다. 벤더 분기 보안 패치(CPU/RU)를 정기적으로 적용해야 합니다.',
  [('cmt', '-- 패치 수준 확인'), ('prompt', 'SQL> '), ('', "SELECT version FROM v$instance;"),
   ('bad', '19.3.0.0  (패치 미적용, 2년 경과)'), ('warn', '→ 알려진 취약점 노출 (취약)')],
  [('cmt', '-- 최신 RU 적용'), ('prompt', '# '), ('', 'opatch apply  (latest Release Update)'),
   ('good', 'Patch applied. version 19.24.x'), ('good', '→ 최신 보안 패치 적용 (양호)')],
  ['Oracle CPU/RU 등 벤더 보안 패치를 정기적으로 적용합니다.',
   '패치 전 영향도 평가와 백업을 수행합니다.',
   '패치 적용 이력을 관리합니다.'],
  ['최신 보안 패치가 적용됨', '정기 패치 주기/이력이 관리됨'],
  '데이터베이스 > 보안 패치 적용'),
]
