# -*- coding: utf-8 -*-
"""주요정보통신기반시설 DBMS(Oracle 기준) 점검 항목 19종 (D-01~D-26)."""

CAT = '데이터베이스 보안'


def D(code, title, icon, sev, desc, vt, st, fixes, chk, ref, f=None):
    return {'file': f or '06_db-%s.html' % code.lower().replace('-', ''),  # D-05 -> 06_db-d05.html
            'code': code, 'title': title, 'icon': icon, 'category': CAT, 'severity': sev,
            'description': desc, 'vuln_term': vt, 'secure_term': st,
            'fix_steps': fixes, 'checklist': chk, 'kisa_ref': ref}


SPECS = [
D('D-05', '패스워드 재사용 금지', '🔁', '중',
  '이전 비밀번호를 반복 사용하면 유출된 과거 비밀번호로 계정이 탈취될 수 있습니다. 프로파일의 PASSWORD_REUSE_TIME/MAX로 재사용을 제한해야 합니다.',
  [('cmt', '-- 재사용 제한 확인'), ('prompt', 'SQL> '), ('', "SELECT limit FROM dba_profiles WHERE resource_name='PASSWORD_REUSE_MAX';"),
   ('bad', 'UNLIMITED'), ('warn', '→ 과거 비밀번호 재사용 가능 (취약)')],
  [('cmt', '-- 재사용 제한 설정'), ('prompt', 'SQL> '), ('', 'ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_MAX 10 PASSWORD_REUSE_TIME 365;'),
   ('good', 'Profile altered.'), ('good', '→ 최근 비밀번호 재사용 차단 (양호)')],
  ['<code>PASSWORD_REUSE_MAX</code>(횟수)와 <code>PASSWORD_REUSE_TIME</code>(기간)을 함께 설정합니다.',
   '모든 사용자 프로파일에 정책이 적용되는지 확인합니다.'],
  ['PASSWORD_REUSE_MAX/TIME이 UNLIMITED가 아닌가', '전 계정 프로파일에 정책 적용'],
  '데이터베이스 > 패스워드 재사용 제한'),

D('D-06', 'DBA/SYSDBA 권한 최소화', '👑', '상',
  '과도한 DBA·SYSDBA 권한 부여는 권한 오남용·내부자 위협을 키웁니다. 관리자 권한은 꼭 필요한 계정에만 최소 부여해야 합니다.',
  [('cmt', '-- DBA 권한 보유자 확인'), ('prompt', 'SQL> '), ('', "SELECT grantee FROM dba_role_privs WHERE granted_role='DBA';"),
   ('bad', 'APPUSER  / BATCH / DEV1 ...'), ('warn', '→ 응용/개발 계정에 DBA 부여 (취약)')],
  [('cmt', '-- 불필요 DBA 회수'), ('prompt', 'SQL> '), ('', 'REVOKE DBA FROM APPUSER;'),
   ('good', 'Revoke succeeded.'), ('good', '→ 관리자 권한 최소화 (양호)')],
  ['응용/개발 계정에서 불필요한 <code>DBA</code> 권한을 회수합니다.',
   '업무에 필요한 최소 권한만 Role로 부여합니다(최소 권한 원칙).',
   'SYSDBA 접속 가능 계정을 주기적으로 점검합니다.'],
  ['DBA 권한이 관리자 계정에만 부여됨', '응용/개발 계정에 과도 권한이 없는가'],
  '데이터베이스 > 관리자 권한 최소화'),

D('D-07', '원격 OS 인증 제한', '🚪', '상',
  'REMOTE_OS_AUTHENT가 TRUE이면 원격 OS 계정을 신뢰하여 인증 없이 DB 접속이 가능합니다. FALSE로 설정해 OS 인증 우회를 차단해야 합니다.',
  [('cmt', '-- 파라미터 확인'), ('prompt', 'SQL> '), ('', "SHOW PARAMETER remote_os_authent"),
   ('bad', 'remote_os_authent  boolean  TRUE'), ('warn', '→ 원격 OS 계정 신뢰로 인증 우회 (취약)')],
  [('cmt', '-- FALSE 설정 후 재기동'), ('prompt', 'SQL> '), ('', "ALTER SYSTEM SET remote_os_authent=FALSE SCOPE=SPFILE;"),
   ('good', 'System altered.'), ('good', '→ 원격 OS 인증 차단 (양호)')],
  ['<code>REMOTE_OS_AUTHENT=FALSE</code>로 설정(SPFILE) 후 인스턴스를 재기동합니다.',
   'OPS$ 계정 등 OS 인증 계정의 필요성을 재검토합니다.'],
  ['REMOTE_OS_AUTHENT가 FALSE인가', 'OS 인증 계정이 최소화됨'],
  '데이터베이스 > 원격 OS 인증 제한'),

D('D-09', '로그인 실패 횟수 제한', '🔒', '상',
  'FAILED_LOGIN_ATTEMPTS가 무제한이면 무차별 대입(brute force)으로 비밀번호가 탈취될 수 있습니다. 실패 임계값과 잠금을 설정해야 합니다.',
  [('cmt', '-- 실패 임계값 확인'), ('prompt', 'SQL> '), ('', "SELECT limit FROM dba_profiles WHERE resource_name='FAILED_LOGIN_ATTEMPTS';"),
   ('bad', 'UNLIMITED'), ('warn', '→ 무차별 대입 가능 (취약)')],
  [('cmt', '-- 임계값/잠금 설정'), ('prompt', 'SQL> '), ('', 'ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 1;'),
   ('good', 'Profile altered.'), ('good', '→ 5회 실패 시 계정 잠금 (양호)')],
  ['<code>FAILED_LOGIN_ATTEMPTS</code>를 5회 이하로 설정합니다.',
   '<code>PASSWORD_LOCK_TIME</code>으로 잠금 시간을 설정합니다.'],
  ['FAILED_LOGIN_ATTEMPTS가 제한되어 있는가', '잠금 시간이 설정됨'],
  '데이터베이스 > 로그인 실패 횟수 제한'),

D('D-13', '데이터 딕셔너리 접근 제한', '📖', '상',
  'O7_DICTIONARY_ACCESSIBILITY가 TRUE이면 ANY 시스템 권한으로 데이터 딕셔너리(SYS 소유 객체)에 접근해 권한 상승이 가능합니다. FALSE로 설정해야 합니다.',
  [('cmt', '-- 파라미터 확인'), ('prompt', 'SQL> '), ('', "SHOW PARAMETER O7_DICTIONARY_ACCESSIBILITY"),
   ('bad', 'O7_DICTIONARY_ACCESSIBILITY  boolean  TRUE'), ('warn', '→ 딕셔너리 접근으로 권한상승 (취약)')],
  [('cmt', '-- FALSE 설정'), ('prompt', 'SQL> '), ('', "ALTER SYSTEM SET O7_DICTIONARY_ACCESSIBILITY=FALSE SCOPE=SPFILE;"),
   ('good', 'System altered.'), ('good', '→ 딕셔너리 보호 (양호)')],
  ['<code>O7_DICTIONARY_ACCESSIBILITY=FALSE</code>로 설정 후 재기동합니다.',
   'SELECT ANY TABLE 등 ANY 권한 보유 계정을 점검합니다.'],
  ['O7_DICTIONARY_ACCESSIBILITY가 FALSE인가', 'ANY 권한 보유 계정이 최소화됨'],
  '데이터베이스 > 데이터 딕셔너리 접근 제한'),

D('D-14', '리스너 비밀번호 설정', '🎧', '상',
  '리스너에 비밀번호가 없으면 원격에서 리스너를 정지(STOP)하거나 설정을 변경하는 서비스 거부·정보 노출이 가능합니다. 비밀번호를 설정해야 합니다.',
  [('cmt', '-- 리스너 상태'), ('prompt', '# '), ('', 'lsnrctl status'),
   ('bad', 'Security        ON: Local OS Authentication 없음'), ('warn', '→ 원격에서 리스너 제어 가능 (취약)')],
  [('cmt', '-- 비밀번호 설정'), ('prompt', '# '), ('', 'LSNRCTL> CHANGE_PASSWORD'),
   ('good', 'listener.ora: PASSWORDS_LISTENER 설정됨'), ('good', '→ 인증 없이는 제어 불가 (양호)')],
  ['<code>listener.ora</code>에 리스너 비밀번호를 설정합니다.',
   '최신 버전은 로컬 OS 인증을 사용하고 원격 관리(ADMIN_RESTRICTIONS=ON)를 제한합니다.'],
  ['리스너 비밀번호/관리 제한이 설정됨', '원격 리스너 제어가 차단됨'],
  '데이터베이스 > 리스너 보안 설정'),

D('D-15', '리스너 로깅 활성화', '📝', '중',
  '리스너 로깅이 비활성화되면 접속 시도·공격 흔적을 추적할 수 없습니다. 로깅을 활성화하고 로그를 보호해야 합니다.',
  [('cmt', '-- 로깅 설정 확인'), ('prompt', '# '), ('', 'lsnrctl status | grep "Listener Log"'),
   ('bad', 'Listener Log File   OFF'), ('warn', '→ 접속/공격 흔적 미기록 (취약)')],
  [('cmt', '-- 로깅 ON'), ('prompt', '# '), ('', 'LSNRCTL> SET LOG_STATUS ON'),
   ('good', 'Listener Log File   ON'), ('good', '→ 리스너 로깅 활성화 (양호)')],
  ['<code>listener.ora</code>에서 <code>LOGGING_LISTENER=ON</code>으로 설정합니다.',
   '로그 파일 권한을 제한하고 정기적으로 검토합니다.'],
  ['리스너 로깅이 활성화됨', '로그 접근 권한이 보호됨'],
  '데이터베이스 > 리스너 로깅'),

D('D-16', '불필요한 DB 링크 제거', '🔗', '중',
  '사용하지 않는 데이터베이스 링크(DB Link)는 자격증명이 저장되어 있어 인접 DB로의 측면 이동 경로가 됩니다. 불필요한 링크는 제거해야 합니다.',
  [('cmt', '-- DB 링크 목록'), ('prompt', 'SQL> '), ('', 'SELECT db_link, username, host FROM dba_db_links;'),
   ('bad', 'OLD_LINK  APPUSER  legacy-db'), ('warn', '→ 미사용 링크에 자격증명 잔존 (취약)')],
  [('cmt', '-- 불필요 링크 삭제'), ('prompt', 'SQL> '), ('', 'DROP DATABASE LINK OLD_LINK;'),
   ('good', 'Database link dropped.'), ('good', '→ 미사용 링크 제거 (양호)')],
  ['사용하지 않는 DB 링크를 <code>DROP DATABASE LINK</code>로 제거합니다.',
   '필요한 링크는 최소 권한 계정으로 생성하고 주기적으로 점검합니다.'],
  ['불필요한 DB 링크가 제거됨', '잔존 링크가 최소 권한으로 구성됨'],
  '데이터베이스 > 불필요한 DB 링크 제거'),

D('D-17', '감사(Audit) 기능 활성화', '🔍', '상',
  '감사 기능이 비활성화되면 권한 변경·중요 데이터 접근 등 보안 이벤트를 추적할 수 없습니다. 감사를 활성화하고 로그를 보호해야 합니다.',
  [('cmt', '-- 감사 설정 확인'), ('prompt', 'SQL> '), ('', "SHOW PARAMETER audit_trail"),
   ('bad', 'audit_trail   string   NONE'), ('warn', '→ 보안 이벤트 미기록 (취약)')],
  [('cmt', '-- 감사 활성화'), ('prompt', 'SQL> '), ('', "ALTER SYSTEM SET audit_trail=DB,EXTENDED SCOPE=SPFILE;"),
   ('good', 'AUDIT CREATE SESSION; AUDIT ALTER USER;'), ('good', '→ 감사 기능 활성화 (양호)')],
  ['<code>AUDIT_TRAIL</code>을 DB(또는 OS)로 설정 후 재기동합니다.',
   '접속, 권한 변경, 중요 객체 접근 등에 대해 AUDIT을 설정합니다.',
   '최신 버전은 <code>Unified Auditing</code> 정책을 사용합니다.'],
  ['AUDIT_TRAIL이 활성화됨', '중요 이벤트에 감사 정책이 설정됨'],
  '데이터베이스 > 감사 기능 활성화'),

D('D-20', '중요정보 컬럼 암호화 (TDE)', '🔐', '상',
  '주민번호·계좌번호 등 중요정보가 평문으로 저장되면 파일 유출·백업 탈취 시 그대로 노출됩니다. TDE 등으로 저장 데이터를 암호화해야 합니다.',
  [('cmt', '-- 평문 저장 예시'), ('prompt', 'SQL> '), ('', 'SELECT ssn FROM customer WHERE rownum=1;'),
   ('bad', '900101-1234567 (평문)'), ('warn', '→ 중요정보 평문 저장 (취약)')],
  [('cmt', '-- 컬럼 암호화(TDE)'), ('prompt', 'SQL> '), ('', 'ALTER TABLE customer MODIFY (ssn ENCRYPT);'),
   ('good', 'Table altered.  SELECT ssn → (암호문)'), ('good', '→ 저장 데이터 암호화 (양호)')],
  ['TDE(Transparent Data Encryption)로 중요 컬럼/테이블스페이스를 암호화합니다.',
   '암호키(Wallet)를 안전하게 보관하고 접근을 제한합니다.',
   '백업 데이터도 암호화되도록 구성합니다.'],
  ['중요정보 컬럼이 암호화 저장됨', '암호키(Wallet)가 안전하게 보호됨'],
  '데이터베이스 > 중요정보 암호화 저장'),

D('D-21', '백업 및 복구 절차', '💾', '중',
  '정기 백업과 복구 절차가 없으면 장애·랜섬웨어 시 데이터를 복구할 수 없습니다. 백업을 자동화하고 복구 테스트를 수행해야 합니다.',
  [('cmt', '-- 백업 이력 확인'), ('prompt', 'RMAN> '), ('', 'LIST BACKUP SUMMARY;'),
   ('bad', 'specification does not match any backup'), ('warn', '→ 백업 미수행 (취약)')],
  [('cmt', '-- 정기 백업 수행'), ('prompt', 'RMAN> '), ('', 'BACKUP DATABASE PLUS ARCHIVELOG;'),
   ('good', 'Finished backup at ...'), ('good', '→ 정기 백업/복구 절차 운영 (양호)')],
  ['RMAN 등으로 전체/증분 백업을 자동화하고 보관 주기를 정의합니다.',
   '백업본을 분리 저장(오프사이트)하고 접근을 제한합니다.',
   '정기적으로 복구 테스트를 수행합니다.'],
  ['정기 백업이 수행되는가', '복구 절차/테스트가 마련됨', '백업본이 분리 보관됨'],
  '데이터베이스 > 백업 및 복구'),

D('D-22', '로그 보관 및 모니터링', '📊', '중',
  '감사·접속 로그를 보관·모니터링하지 않으면 침해 사고를 탐지·분석할 수 없습니다. 로그를 충분히 보관하고 이상 징후를 모니터링해야 합니다.',
  [('cmt', '-- 감사 로그량 확인'), ('prompt', 'SQL> '), ('', 'SELECT count(*) FROM dba_audit_trail;'),
   ('bad', '0 (또는 즉시 삭제됨)'), ('warn', '→ 로그 미보관/미점검 (취약)')],
  [('cmt', '-- 보관/연계'), ('prompt', 'SQL> '), ('', 'aud$ → SIEM 전송, 보관 90일+'),
   ('good', 'audit log retained & monitored'), ('good', '→ 로그 보관·모니터링 (양호)')],
  ['감사/접속 로그를 법규 요건에 맞게 충분히 보관합니다.',
   'SIEM 등과 연계해 이상 접근을 모니터링/알람합니다.',
   '로그 위변조 방지를 위해 접근 권한을 제한합니다.'],
  ['로그가 충분히 보관되는가', '이상 징후 모니터링이 운영됨'],
  '데이터베이스 > 로그 보관 및 모니터링'),

D('D-23', '최소 권한 원칙(Role)', '🎚️', '상',
  '사용자에게 권한을 직접·과다 부여하면 권한 관리가 어렵고 오남용 위험이 큽니다. 업무별 Role을 정의하고 최소 권한만 부여해야 합니다.',
  [('cmt', '-- 과다 권한 예시'), ('prompt', 'SQL> '), ('', "SELECT * FROM dba_sys_privs WHERE grantee='APPUSER';"),
   ('bad', 'SELECT ANY TABLE / CREATE ANY PROCEDURE'), ('warn', '→ ANY 권한 직접 부여 (취약)')],
  [('cmt', '-- Role 기반 최소 권한'), ('prompt', 'SQL> '), ('', 'GRANT app_read TO APPUSER;'),
   ('good', 'ANY 권한 회수, 업무 Role만 부여'), ('good', '→ 최소 권한 적용 (양호)')],
  ['업무 단위 <code>Role</code>을 정의하고 필요한 객체 권한만 부여합니다.',
   'SELECT ANY/CREATE ANY 등 ANY 권한을 회수합니다.',
   '권한 부여 현황을 주기적으로 검토합니다.'],
  ['ANY 등 과다 권한이 회수됨', '업무 Role로 최소 권한이 부여됨'],
  '데이터베이스 > 최소 권한 원칙'),

D('D-24', '보안 패치 적용 주기', '🩹', '상',
  '오래된 DBMS는 알려진 취약점(권한상승·RCE)에 노출됩니다. 벤더 분기 보안 패치(CPU/RU)를 정기적으로 적용해야 합니다.',
  [('cmt', '-- 패치 수준 확인'), ('prompt', 'SQL> '), ('', "SELECT version FROM v$instance;"),
   ('bad', '19.3.0.0  (패치 미적용, 2년 경과)'), ('warn', '→ 알려진 취약점 노출 (취약)')],
  [('cmt', '-- 최신 RU 적용'), ('prompt', '# '), ('', 'opatch apply  (latest Release Update)'),
   ('good', 'Patch applied. version 19.24.x'), ('good', '→ 최신 보안 패치 적용 (양호)')],
  ['Oracle CPU/RU 등 벤더 보안 패치를 정기적으로 적용합니다.',
   '패치 전 영향도 평가와 백업을 수행합니다.',
   '패치 적용 이력을 관리합니다.'],
  ['최신 보안 패치가 적용됨', '정기 패치 주기/이력이 관리됨'],
  '데이터베이스 > 보안 패치 적용'),
]

# ===== D-01~D-26 보강 (기본계정·타임아웃·불필요권한·접근통제·감사/패치) =====
SPECS += [
D('D-01', '기본 계정 관리 (기본 계정 잠금·비밀번호 변경)', '👤', '상',
  'Oracle 설치 시 생성되는 기본 계정(SCOTT, OUTLN, XS$NULL 등)이 잠금 없이 남아 있으면 널리 알려진 기본 비밀번호로 바로 접속됩니다. 사용하지 않는 기본 계정은 잠그거나 삭제해야 합니다.',
  [('cmt', '-- 기본 계정 상태 확인'), ('prompt', 'SQL> '), ('', "SELECT username, account_status FROM dba_users WHERE username IN ('SCOTT','OUTLN','HR');"),
   ('bad', 'SCOTT   OPEN'), ('bad', 'OUTLN   OPEN'),
   ('warn', '→ 기본 계정이 잠금 없이 열려 있음 (취약)')],
  [('cmt', '-- 기본 계정 잠금·삭제'), ('prompt', 'SQL> '), ('', 'ALTER USER SCOTT ACCOUNT LOCK; DROP USER OUTLN CASCADE;'),
   ('good', 'User altered. / User dropped.'),
   ('good', '→ 미사용 기본 계정 제거 (양호)')],
  ['사용하지 않는 기본 계정은 <code>ACCOUNT LOCK</code> 또는 삭제합니다.',
   '유지하는 계정은 기본 비밀번호를 즉시 변경합니다.',
   '신규 설치 후 기본 계정 목록·상태를 점검표로 관리합니다.'],
  ['미사용 기본 계정이 잠금/삭제되었는가', '기본 비밀번호가 모두 변경되었는가'],
  '데이터베이스 > 기본 계정 관리'),

D('D-08', '세션 타임아웃 설정 (유휴 세션 종료)', '⌛', '중',
  'DB 세션이 오랫동안 방치되면 자리 비운 동안 계정 도용·화면 캡처·무단 쿼리의 기회가 됩니다. IDLE_TIME으로 유휴 세션을 자동 종료해야 합니다.',
  [('cmt', '-- 유휴 세션 제한 확인'), ('prompt', 'SQL> '), ('', "SELECT limit FROM dba_profiles WHERE resource_name='IDLE_TIME';"),
   ('bad', 'UNLIMITED'), ('warn', '→ 방치 세션이 무제한 유지 (취약)')],
  [('cmt', '-- 유휴 세션 자동 종료 설정'), ('prompt', 'SQL> '), ('', 'ALTER PROFILE DEFAULT LIMIT IDLE_TIME 15;  -- 15분'),
   ('good', 'Profile altered.'),
   ('good', '>> 15분 유휴 시 세션 자동 종료 (양호)')],
  ['프로파일에 <code>IDLE_TIME</code>(예: 15분)을 설정합니다.',
   '종료된 세션의 리소스 회수를 위해 <code>RESOURCE_LIMIT=TRUE</code>를 확인합니다.',
   '장기 배치 작업은 별도 프로파일로 예외 관리합니다.'],
  ['IDLE_TIME이 제한(예: 15분)되어 있는가', '예외 작업 프로파일이 문서화되어 있는가'],
  '데이터베이스 > 세션 타임아웃'),

D('D-10~12', '불필요한 계정·권한 제거 (PUBLIC 권한 회수)', '🧹', '상',
  '사용하지 않는 계정이 남아 있거나, 모든 사용자(PUBLIC)에 과도한 권한이 부여되면 최소 권한 원칙이 무너집니다. 미사용 계정 잠금과 PUBLIC 권한 회수가 필요합니다.',
  [('cmt', '-- PUBLIC 부여 권한·미사용 계정 확인'), ('prompt', 'SQL> '), ('', "SELECT table_name, privilege FROM dba_tab_privs WHERE grantee='PUBLIC' AND table_name LIKE 'UTL%';"),
   ('bad', 'UTL_FILE    EXECUTE'), ('bad', 'UTL_HTTP    EXECUTE'),
   ('bad', 'TEST_USER   (90일 미접속, OPEN)'),
   ('warn', '→ 전 계정에 강력 패키지 실행 권한 + 유령 계정 (취약)')],
  [('cmt', '-- PUBLIC 권한 회수·계정 잠금'), ('prompt', 'SQL> '), ('', 'REVOKE EXECUTE ON UTL_FILE FROM PUBLIC; REVOKE EXECUTE ON UTL_HTTP FROM PUBLIC;'),
   ('good', 'Revoke succeeded.  /  ALTER USER TEST_USER ACCOUNT LOCK;'),
   ('good', '→ 필요한 사용자에게만 권한 부여 (양호)')],
  ['<code>UTL_FILE</code>, <code>UTL_HTTP</code>, <code>UTL_TCP</code> 등 강력 패키지의 PUBLIC 권한을 회수합니다.',
   '90일 미접속 계정 등 미사용 계정은 잠금·삭제합니다.',
   '부여 권한은 Role로 묶어 최소한으로 관리합니다.'],
  ['PUBLIC에 과도한 권한이 없는가', '미사용 계정이 잠금/삭제되었는가', '권한 부여 이력이 관리되는가'],
  '데이터베이스 > 불필요한 계정·권한 제거', '06_db-d10-d12.html'),

D('D-18~19', 'DB 접근 통제·네트워크 암호화', '📡', '상',
  'DB가 모든 IP의 접속을 받고 통신이 평문이면, 내부망 스니핑으로 계정·데이터가 그대로 노출됩니다. 허용 호스트 제한(TCP.VALIDNODE_CHECKING)과 네이티브 암호화가 필요합니다.',
  [('cmt', '-- sqlnet 접근 제한·암호화 확인'), ('prompt', 'SQL> '), ('', 'cat $ORACLE_HOME/network/admin/sqlnet.ora'),
   ('bad', '(TCP.VALIDNODE_CHECKING 항목 없음 — 전 IP 허용)'),
   ('bad', '(암호화 설정 없음 — 평문 통신)'),
   ('warn', '→ 스니핑·외부 접속 노출 (취약)')],
  [('cmt', '-- 허용 호스트·암호화 설정'), ('prompt', 'SQL> '), ('', 'TCP.VALIDNODE_CHECKING=YES / TCP.INVITED_NODES=(app10, was20)'),
   ('good', 'SQLNET.ENCRYPTION_SERVER=REQUIRED / SQLNET.CRYPTO_CHECKSUM_SERVER=REQUIRED'),
   ('good', '→ 허용 호스트만 + 통신 암호화 (양호)')],
  ['<code>sqlnet.ora</code>에 <code>TCP.VALIDNODE_CHECKING=YES</code>와 허용 노드 목록을 설정합니다.',
   '<code>SQLNET.ENCRYPTION_SERVER=REQUIRED</code> 등 네이티브 암호화·무결성을 강제합니다.',
   '방화벽 정책과 함께 이중으로 WAS·관리망만 접속을 허용합니다.'],
  ['접속 가능 호스트가 제한되어 있는가', '통신 구간이 암호화되어 있는가'],
  '데이터베이스 > 접근 통제·네트워크 암호화', '06_db-d18-d19.html'),

D('D-25~26', '감사 로그 관리·보안 패치 적용', '🛠️', '상',
  '감사(Audit) 기능이 꺼져 있으면 사고 추적이 불가능하고, 최신 보안 패치(CPU/RU) 미적용 DB는 공개된 취약점으로 그대로 뚫립니다. 감사 정책과 정기 패치가 함께 운영되어야 합니다.',
  [('cmt', '-- 감사 기능·버전 확인'), ('prompt', 'SQL> '), ('', 'SHOW PARAMETER audit_trail'),
   ('bad', 'audit_trail  FALSE (감사 비활성)'),
   ('bad', 'BANNER: 19.3.0.0  (최신 RU 미적용 — 2년 경과)'),
   ('warn', '→ 침해 추적 불가 + 알려진 취약점 방치 (취약)')],
  [('cmt', '-- 감사 활성화·패치 적용'), ('prompt', 'SQL> '), ('', 'ALTER SYSTEM SET audit_trail=DB,EXTENDED SCOPE=SPFILE;'),
   ('good', '>> 권한 변경·로그인 실패 감사 기록 시작'),
   ('good', '>> 최신 Release Update 적용 완료 (분기 CPU 주기)'),
   ('good', '→ 추적 가능 + 알려진 구멍 제거 (양호)')],
  ['<code>audit_trail</code>을 활성화하고 로그인·권한 변경·민감 테이블 접근을 감사합니다.',
   '분기별 CPU/RU 패치를 변경관리 절차에 따라 적용합니다.',
   '감사 로그는 별도 저장소로 이관·보관하여 변조를 방지합니다.'],
  ['감사 기능이 활성화되어 있는가', '감사 로그가 안전하게 보관되는가', '최신 보안 패치가 적용되어 있는가'],
  '데이터베이스 > 감사 로그·패치 관리', '06_db-d25-d26.html'),
]
