# -*- coding: utf-8 -*-
"""전자금융 보안 추가 시뮬 5종 콘텐츠 명세 (금융보안원 제2026-1호 항목 개념 재구성)."""

SPECS = [
{
 'file':'07_fin-password-change.html',
 'title':'거래 비밀번호 변경 보안',
 'icon':'🔑', 'target':'거래 비밀번호 변경 API', 'risk':'4', 'item_code':'WEB-FIN 비밀번호 변경',
 'attack_panel_title':'거래 비밀번호 변경 요청',
 'scenario_html':'거래 비밀번호 변경 시 <b>본인확인 절차(현재 비밀번호 재입력 등)</b>가 생략되거나, 변경 시 <b>이전 비밀번호 재사용</b>이 허용되면, 세션 탈취 공격자가 본인 인증 없이 비밀번호를 바꾸거나 사실상 동일한 값으로 되돌려 계정을 장악할 수 있습니다.',
 'attack_name':'본인확인 생략 + 이전 비밀번호 재사용', 'attack_sub':'currentPassword 미검증, 직전 값 그대로 재설정',
 'normal_req':'POST /user/password/change\n{\n  "currentPassword": "Old!2025",\n  "newPassword": "New!2026",\n  "confirm": "New!2026"\n}',
 'attack_req':'POST /user/password/change   (탈취 세션)\n{\n  "currentPassword": "",          // 본인확인 생략\n  "newPassword": "Old!2025",      // 직전 비밀번호 재사용\n  "confirm": "Old!2025"\n}',
 'vuln_logs_js':"addLog('[SESSION] 탈취 세션으로 변경 요청','warn'); addLog('[WAS] currentPassword 검증 절차 없음 → 본인확인 생략','error'); addLog('[WAS] 이전 비밀번호 재사용 차단 없음','error'); addLog('[DB] 비밀번호가 직전 값으로 재설정됨 → 계정 장악','error');",
 'breach_html':'<strong>🚨 비밀번호 변경 보안 우회</strong><br>본인확인이 생략되고 이전 비밀번호 재사용이 허용되어 공격자가 임의로 비밀번호를 변경했습니다.<table class="data-table"><tr><th>점검</th><th>기대</th><th>실제</th></tr><tr><td>현재 비밀번호 검증</td><td>필수</td><td style="color:#b71c1c">미수행</td></tr><tr><td>이전 비밀번호 재사용</td><td>차단</td><td style="color:#b71c1c">허용</td></tr></table>',
 'violations':['평가기준 WEB-FIN [전자금융] 비밀번호 변경 시 본인확인(위험도 4)',
               '비밀번호 변경 시 이전 비밀번호 재사용 방지 미흡',
               '전자금융감독규정 제34조: 이용자 인증정보 관리대책 미흡'],
 'defense_intro':'서버는 비밀번호 변경 시 <strong>현재 비밀번호로 본인확인</strong>을 강제하고, 새 비밀번호가 <strong>이전 비밀번호와 동일/유사하지 않은지</strong> 검증해야 합니다. 아래 코드를 보완하세요.',
 'vuln_code':'// [취약] 본인확인 없이, 이전 비밀번호 재사용 허용\npublic void changePassword(String userId, ChangeReq req) {\n    // 현재 비밀번호 검증 없음\n    // 이전 비밀번호 재사용 검증 없음\n    userRepo.updatePassword(userId, hash(req.getNewPassword()));\n}',
 'secure_hint':'// [안전] 본인확인 + 이전 비밀번호 재사용 차단\npublic void changePassword(String userId, ChangeReq req) {\n    User u = userRepo.find(userId);\n    // 1) 현재 비밀번호로 본인확인\n    if (!verifyCurrentPassword(u, req.getCurrentPassword()))\n        throw new SecurityException("본인확인 실패");\n    // 2) 이전 비밀번호(및 최근 N개) 재사용 차단\n    if (isPasswordReused(u, req.getNewPassword()))\n        throw new SecurityException("이전 비밀번호는 재사용할 수 없습니다");\n    userRepo.updatePassword(userId, hash(req.getNewPassword()));\n    userRepo.pushPasswordHistory(userId, hash(req.getNewPassword()));\n}',
 'checks':[['verifyCurrentPassword','본인확인','getCurrentPassword'],['isPasswordReused','재사용','PasswordHistory','pushPasswordHistory']],
 'success_msg':'현재 비밀번호 본인확인과 이전 비밀번호 재사용 차단으로 비밀번호 변경이 보호됩니다.',
 'fail_msg':'변경 전 현재 비밀번호로 본인확인하고, 이전 비밀번호 재사용을 차단해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>이용자 인증정보 관리 &gt; <b>비밀번호 변경 보안</b><h4>2. 위험 분석</h4><ul><li>본인확인 생략 시 세션 탈취만으로 비밀번호 변경 가능</li><li>이전 비밀번호 재사용 시 사실상 비밀번호 변경 효과 무력화</li></ul><h4>3. 조치 방법</h4><ul><li>변경 시 <b>현재 비밀번호 재입력</b> 등 본인확인 절차 수행</li><li><b>이전 비밀번호(최근 N개) 재사용 방지</b> 정책 적용</li><li>변경 이력·실패횟수 모니터링</li></ul>',
 'easy':'현관 비밀번호를 바꾸려면 먼저 <b>지금 비밀번호를 한 번 더 눌러 본인임을 증명</b>해야 합니다. 또 새 번호를 <b>예전과 똑같이</b> 설정하면 바꾼 의미가 없으니 막아야 합니다.',
},
{
 'file':'07_fin-realname.html',
 'title':'접근매체 발급 실명확인',
 'icon':'🪪', 'target':'접근매체(보안카드/OTP/인증서) 발급', 'risk':'5', 'item_code':'WEB-FIN 실명확인',
 'attack_panel_title':'접근매체 발급 신청',
 'scenario_html':'보안카드·OTP·공동인증서 등 <b>접근매체 발급</b> 시 <b>실명확인(본인확인기관 대조)</b>이 미흡하면, 공격자가 타인 명의 정보만으로 접근매체를 <b>비인가 발급</b>받아 전자금융거래를 도용할 수 있습니다.',
 'attack_name':'타인 명의 접근매체 비인가 발급', 'attack_sub':'실명확인 없이 name/RRN만으로 OTP 발급',
 'normal_req':'POST /access-media/issue\n{\n  "type": "OTP",\n  "name": "홍길동",\n  "rrn": "900101-1******",\n  "verifiedCI": "본인확인기관 검증토큰"\n}',
 'attack_req':'POST /access-media/issue\n{\n  "type": "OTP",\n  "name": "김피해",          // 타인 명의\n  "rrn": "850515-2******",   // 도용 정보\n  "verifiedCI": ""             // 실명확인 토큰 없음\n}',
 'vuln_logs_js':"addLog('[REQUEST] 타인 명의 OTP 발급 신청','warn'); addLog('[WAS] 본인확인기관(CI) 실명확인 절차 없음','error'); addLog('[WAS] 명의자 일치 검증 누락 → 비인가 발급','error'); addLog('[ISSUE] 공격자에게 접근매체 발급 완료','error');",
 'breach_html':'<strong>🚨 접근매체 비인가 발급</strong><br>실명확인 절차가 미흡하여 타인 명의 접근매체가 공격자에게 발급되었습니다.<table class="data-table"><tr><th>항목</th><th>기대</th><th>실제</th></tr><tr><td>본인확인기관 검증(CI)</td><td>필수</td><td style="color:#b71c1c">미수행</td></tr><tr><td>명의자 일치</td><td>일치 검증</td><td style="color:#b71c1c">미검증</td></tr></table>',
 'violations':['평가기준 WEB-FIN [전자금융] 접근매체 발급 시 실명확인(위험도 5)',
               '전자금융거래법 제6조: 접근매체 발급 시 본인 확인 의무 위반',
               '전자금융감독규정 제34조: 접근매체 관리대책 미흡'],
 'defense_intro':'서버는 접근매체 발급 전 <strong>본인확인기관을 통한 실명확인(CI/DI 대조)</strong>을 수행하고, <strong>신청 명의자와 실명확인 결과의 일치</strong>를 검증해야 합니다. 아래 코드를 보완하세요.',
 'vuln_code':'// [취약] 실명확인 없이 입력 명의만으로 발급\npublic AccessMedia issue(IssueReq req) {\n    // 본인확인기관 실명확인 절차 없음\n    return mediaService.create(req.getType(), req.getName(), req.getRrn());\n}',
 'secure_hint':'// [안전] 본인확인기관 실명확인 + 명의자 일치 검증\npublic AccessMedia issue(IssueReq req) {\n    // 1) 본인확인기관(CI) 통한 실명확인\n    IdentityResult id = verifyRealName(req.getName(), req.getRrn(), req.getVerifiedCI());\n    if (!id.isVerified())\n        throw new SecurityException("실명확인 실패");\n    // 2) 신청 명의자와 실명확인 결과 일치 확인\n    if (!id.matchesApplicant(req.getName(), req.getRrn()))\n        throw new SecurityException("명의자 불일치");\n    return mediaService.create(req.getType(), id.getCi());\n}',
 'checks':[['verifyRealName','실명확인','isVerified'],['matchesApplicant','명의자','getCi']],
 'success_msg':'본인확인기관 실명확인과 명의자 일치 검증으로 비인가 발급이 차단됩니다.',
 'fail_msg':'접근매체 발급 전 본인확인기관 실명확인과 명의자 일치 검증이 필요합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>접근매체 관리 &gt; <b>발급 시 실명확인</b><h4>2. 위험 분석</h4><ul><li>실명확인 미흡 시 타인 명의 접근매체 비인가 발급</li><li>발급된 접근매체로 명의도용·부정거래 확대</li></ul><h4>3. 조치 방법</h4><ul><li>발급 시 <b>본인확인기관(CI/DI)</b> 통한 실명확인 수행</li><li><b>신청 명의자와 실명확인 결과 일치</b> 검증</li><li>발급 이력·다중 발급 이상징후 모니터링</li></ul>',
 'easy':'은행 카드를 새로 만들 때 <b>신분증으로 진짜 본인인지</b> 반드시 확인해야 합니다. 이 절차를 건너뛰면 남의 이름으로 카드를 만들어 도용할 수 있습니다.',
},
{
 'file':'07_fin-input-protection.html',
 'title':'이용자 입력정보 보호 (키보드 보안)',
 'icon':'⌨️', 'target':'거래 입력 폼(비밀번호 등)', 'risk':'4', 'item_code':'WEB-FIN 입력정보 보호',
 'attack_panel_title':'거래 비밀번호 입력',
 'scenario_html':'거래 입력값(계좌 비밀번호·OTP 등)이 <b>키보드 보안(보안 키패드)·종단 암호화</b> 없이 평문으로 처리되면, 단말에 설치된 <b>키로깅/메모리 후킹 악성코드</b>가 입력 즉시 평문을 탈취할 수 있습니다.',
 'attack_name':'키로깅 + 메모리 후킹', 'attack_sub':'평문 입력값을 입력 시점/메모리에서 탈취',
 'normal_req':'입력 폼 → 서버 전송\n{\n  "account": "110-392-102931",\n  "password": "[보안키패드 암호화 블록]",\n  "encrypted": true\n}',
 'attack_req':'키로깅/후킹 캡처 결과\n{\n  "account": "110-392-102931",\n  "password": "8417",       // 평문 입력값 탈취\n  "encrypted": false        // 보안 키패드/암호화 미적용\n}',
 'vuln_logs_js':"addLog('[MALWARE] 키로깅 드라이버 적재','warn'); addLog('[INPUT] 보안 키패드 미적용 → 키 입력 평문 캡처','error'); addLog('[HOOK] 폼 메모리 후킹으로 password 평문 추출','error'); addLog('[EXFIL] 거래 비밀번호 8417 외부 유출','error');",
 'breach_html':'<strong>🚨 입력정보 탈취</strong><br>키보드 보안·종단 암호화가 없어 거래 비밀번호 평문이 키로깅과 메모리 후킹으로 탈취되었습니다.<table class="data-table"><tr><th>보호장치</th><th>기대</th><th>실제</th></tr><tr><td>보안 키패드</td><td>적용</td><td style="color:#b71c1c">미적용</td></tr><tr><td>종단 암호화(E2E)</td><td>적용</td><td style="color:#b71c1c">평문 처리</td></tr></table>',
 'violations':['평가기준 WEB-FIN [전자금융] 이용자 입력정보 보호(위험도 4)',
               '키보드 보안·종단 암호화 미적용으로 입력정보 노출',
               '전자금융감독규정 제34조: 이용자 정보 보호대책 미흡'],
 'defense_intro':'클라이언트는 <strong>보안 키패드</strong>로 입력을 받고, 입력 즉시 <strong>종단 암호화(E2E)</strong>하여 평문이 메모리/전송 구간에 노출되지 않도록 해야 합니다. 아래 코드를 보완하세요.',
 'vuln_code':'// [취약] 일반 입력 + 평문 처리 (키로깅/후킹에 노출)\npublic TxnInput collect(InputForm form) {\n    String pw = form.getPlainPassword();   // 평문 입력\n    return new TxnInput(form.getAccount(), pw);   // 종단 암호화 없음\n}',
 'secure_hint':'// [안전] 보안 키패드 입력 + 종단 암호화\npublic TxnInput collect(InputForm form) {\n    // 1) 보안 키패드로 입력(가상 키패드, 키 순서 난수화)\n    SecureKeypad keypad = SecureKeypad.bind(form);\n    // 2) 입력 즉시 종단 암호화(E2E) → 평문 메모리 잔존 방지\n    byte[] cipher = keypad.encryptEndToEnd(form.getSessionKey());\n    keypad.wipePlainBuffer();\n    return new TxnInput(form.getAccount(), cipher);\n}',
 'checks':[['SecureKeypad','보안 키패드','keypad'],['encryptEndToEnd','종단','wipePlainBuffer']],
 'success_msg':'보안 키패드 입력과 종단 암호화로 키로깅·메모리 후킹에 의한 탈취가 차단됩니다.',
 'fail_msg':'보안 키패드 입력과 입력 즉시 종단 암호화(평문 버퍼 제거)가 필요합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>이용자 정보 보호 &gt; <b>입력정보 보호(키보드 보안)</b><h4>2. 위험 분석</h4><ul><li>키로깅으로 키 입력 평문 탈취</li><li>메모리 후킹으로 폼 내 평문 추출</li></ul><h4>3. 조치 방법</h4><ul><li><b>보안 키패드(가상·난수 배열)</b> 적용</li><li>입력 즉시 <b>종단 암호화(E2E)</b> 후 처리</li><li>평문 <b>메모리 버퍼 즉시 제거</b></li></ul>',
 'easy':'비밀번호를 누를 때 누군가 <b>어깨너머로 키보드를 그대로 베껴 적는</b> 상황입니다. 화면에 뒤죽박죽 섞인 <b>보안 키패드</b>로 누르고 곧바로 암호로 잠가야 베껴도 소용이 없습니다.',
},
{
 'file':'07_fin-malware-protection.html',
 'title':'악성코드 방지',
 'icon':'🦠', 'target':'모바일 금융앱', 'risk':'5', 'item_code':'MOB-FIN 악성코드 방지',
 'attack_panel_title':'모바일 이체 실행',
 'scenario_html':'모바일 금융앱이 <b>악성코드 탐지/차단 프로세스</b> 없이 구동되면, <b>접근성 서비스를 악용한 악성앱</b>이 화면·입력을 가로채 거래정보를 변조하거나 인증정보를 탈취합니다.',
 'attack_name':'접근성 악용 + 화면/입력 탈취', 'attack_sub':'악성앱이 오버레이로 이체 수취계좌 변조',
 'normal_req':'모바일 이체 요청\n{\n  "to": "220-771-559010",\n  "amount": 200000,\n  "device": "정상 단말"\n}',
 'attack_req':'악성앱 개입 후 전송\n{\n  "to": "999-000-HACKER",   // 오버레이로 수취계좌 변조\n  "amount": 200000,\n  "device": "악성코드 감염 단말"\n}',
 'vuln_logs_js':"addLog('[APP] 악성코드 탐지/차단 프로세스 없음','error'); addLog('[A11Y] 악성앱이 접근성 서비스로 화면/입력 가로채기','warn'); addLog('[OVERLAY] 이체 수취계좌 220-771 → 999-000 변조','error'); addLog('[EXFIL] 인증정보 탈취 → 변조 거래 승인','error');",
 'breach_html':'<strong>🚨 악성코드에 의한 거래 변조</strong><br>악성코드 탐지/차단이 없어 접근성 악용 악성앱이 화면·입력을 가로채 거래를 변조했습니다.<table class="data-table"><tr><th>점검</th><th>기대</th><th>실제</th></tr><tr><td>악성코드 탐지</td><td>구동 시 수행</td><td style="color:#b71c1c">미수행</td></tr><tr><td>접근성 악용 차단</td><td>차단</td><td style="color:#b71c1c">허용</td></tr></table>',
 'violations':['평가기준 MOB-FIN [전자금융] 악성코드 방지(위험도 5)',
               '접근성 서비스 악용·화면 오버레이 탐지 부재',
               '전자금융감독규정 제34조: 단말기 보안대책(악성코드 방지) 미흡'],
 'defense_intro':'앱은 구동·거래 시점에 <strong>악성코드/접근성 악용/화면 오버레이</strong>를 탐지하고, 위협 발견 시 거래를 <strong>차단</strong>해야 합니다. 아래 Kotlin 코드를 보완하세요.',
 'vuln_code':'// [취약] 악성코드 탐지/차단 없이 거래 진행 (Kotlin)\nfun startTransfer(req: TransferReq) {\n    // 악성코드/접근성/오버레이 점검 없음\n    api.submit(req)\n}',
 'secure_hint':'// [안전] 악성코드/접근성/오버레이 탐지 후 차단 (Kotlin)\nfun startTransfer(req: TransferReq) {\n    // 1) 악성코드/위협 스캔\n    if (malwareScanner.detectMalware())\n        throw SecurityException("악성코드가 탐지되어 거래를 차단합니다")\n    // 2) 접근성 서비스 악용 탐지\n    if (isAccessibilityAbused())\n        throw SecurityException("비정상 접근성 서비스 탐지")\n    // 3) 화면 오버레이 탐지\n    if (isScreenOverlayDetected())\n        throw SecurityException("화면 오버레이 탐지")\n    api.submit(req)\n}',
 'checks':[['detectMalware','악성코드','malwareScanner'],['isAccessibilityAbused','접근성','isScreenOverlayDetected','오버레이']],
 'success_msg':'악성코드·접근성 악용·화면 오버레이 탐지 후 차단으로 거래 변조가 방지됩니다.',
 'fail_msg':'구동·거래 시 악성코드/접근성 악용/화면 오버레이를 탐지하고 차단해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>단말기 보안 &gt; <b>악성코드 방지</b><h4>2. 위험 분석</h4><ul><li>접근성 서비스 악용으로 화면·입력 탈취</li><li>화면 오버레이로 거래정보(수취계좌·금액) 변조</li></ul><h4>3. 조치 방법</h4><ul><li>구동/거래 시 <b>악성코드 탐지·차단</b> 프로세스 적용</li><li><b>접근성 악용·화면 오버레이</b> 탐지 및 거래 차단</li><li>위협 탐지 시 거래 중단 및 사용자 경고</li></ul>',
 'easy':'금고를 열 때 <b>방 안에 도둑이 숨어 있는지 먼저 확인</b>하지 않으면, 도둑이 몰래 손을 바꿔치기합니다. 앱은 실행할 때마다 <b>악성코드가 있는지 검사</b>하고 있으면 거래를 멈춰야 합니다.',
},
{
 'file':'07_fin-security-program.html',
 'title':'보안프로그램 동작·임의해제 방지',
 'icon':'🛡️', 'target':'HTS/PC 보안프로그램', 'risk':'5', 'item_code':'HTS-FIN 보안프로그램',
 'attack_panel_title':'HTS 보안프로그램 상태',
 'scenario_html':'HTS/PC 보안프로그램이 <b>미동작</b>하거나, <b>강제종료(taskkill)·레지스트리 변조</b>로 임의 해제 가능하고 <b>최신 업데이트가 미수행</b>되면, 키로깅·전문 변조 등 공격에 그대로 노출됩니다.',
 'attack_name':'보안모듈 강제종료 + 레지스트리 변조', 'attack_sub':'taskkill로 종료 후 키로깅, 자동시작 레지스트리 무력화',
 'normal_req':'보안프로그램 상태 점검\n{\n  "process": "running",\n  "autoStart": "HKLM\\\\...\\\\Run 등록",\n  "version": "latest"\n}',
 'attack_req':'공격자 조작 후 상태\n{\n  "process": "killed (taskkill /f)",\n  "autoStart": "레지스트리 키 삭제",\n  "version": "outdated"\n}',
 'vuln_logs_js':"addLog('[ATTACK] taskkill /f 로 보안모듈 강제종료','error'); addLog('[REG] 자동시작 레지스트리 키 삭제 → 임의 해제','error'); addLog('[STATE] 보안프로그램 미동작 + 최신 업데이트 미수행','warn'); addLog('[KEYLOG] 보호 해제 상태에서 키로깅 활성화','error');",
 'breach_html':'<strong>🚨 보안프로그램 임의 해제</strong><br>강제종료와 레지스트리 변조로 보안프로그램이 무력화되고 업데이트도 미수행되어 키로깅이 활성화되었습니다.<table class="data-table"><tr><th>점검</th><th>기대</th><th>실제</th></tr><tr><td>프로세스 동작</td><td>상시 동작</td><td style="color:#b71c1c">강제종료</td></tr><tr><td>임의 해제 방지</td><td>차단/재기동</td><td style="color:#b71c1c">해제 성공</td></tr><tr><td>최신 업데이트</td><td>최신</td><td style="color:#b71c1c">미수행</td></tr></table>',
 'violations':['평가기준 HTS-FIN [전자금융] 보안프로그램 정상 동작(위험도 5)',
               '보안프로그램 임의 해제 방지 및 최신 업데이트 미수행',
               '전자금융감독규정 제34조: 해킹방지 보안프로그램 운영대책 미흡'],
 'defense_intro':'클라이언트는 거래 전 <strong>보안프로그램의 정상 동작</strong>을 확인하고, <strong>강제종료/레지스트리 변조에 의한 임의 해제를 탐지·재기동</strong>하며 <strong>최신 버전 업데이트</strong>를 강제해야 합니다. 아래 코드를 보완하세요.',
 'vuln_code':'// [취약] 보안프로그램 상태 확인 없이 거래 허용\npublic void startTrading(TradeReq req) {\n    // 보안프로그램 동작/무결성/버전 점검 없음\n    hts.execute(req);\n}',
 'secure_hint':'// [안전] 동작 확인 + 임의해제 방지 + 최신 업데이트 강제\npublic void startTrading(TradeReq req) {\n    // 1) 보안프로그램 정상 동작 확인\n    if (!securityAgent.isRunning())\n        throw new SecurityException("보안프로그램 미동작");\n    // 2) 강제종료/레지스트리 변조 등 임의해제 탐지 → 재기동\n    if (securityAgent.isTampered()) {\n        securityAgent.restartProtected();\n        throw new SecurityException("보안프로그램 임의해제 탐지");\n    }\n    // 3) 최신 버전 업데이트 강제\n    if (!securityAgent.isLatestVersion())\n        throw new SecurityException("보안프로그램 업데이트 필요");\n    hts.execute(req);\n}',
 'checks':[['isRunning','동작','securityAgent'],['isTampered','임의해제','restartProtected'],['isLatestVersion','업데이트','최신']],
 'success_msg':'동작 확인·임의해제 탐지/재기동·최신 업데이트 강제로 보안프로그램이 보호됩니다.',
 'fail_msg':'보안프로그램 동작 확인, 임의해제(강제종료/레지스트리) 탐지·재기동, 최신 업데이트 강제가 필요합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>단말기 보안 &gt; <b>보안프로그램 동작·임의해제 방지</b><h4>2. 위험 분석</h4><ul><li>강제종료(taskkill)·레지스트리 변조로 보호 무력화</li><li>보안프로그램 미동작·미업데이트 상태에서 키로깅·전문변조 노출</li></ul><h4>3. 조치 방법</h4><ul><li>거래 전 <b>보안프로그램 정상 동작</b> 확인</li><li><b>강제종료/레지스트리 변조 탐지 및 재기동(자기보호)</b></li><li><b>최신 버전 자동 업데이트</b> 강제</li></ul>',
 'easy':'금고 옆 <b>경비원이 자리를 지키고 있는지</b> 확인하지 않으면, 도둑이 경비원을 잠시 쫓아내고 금고를 텁니다. 보안프로그램이 꺼지거나 낡았는지 매번 확인하고 <b>다시 켜고 최신으로</b> 유지해야 합니다.',
},
]
