# -*- coding: utf-8 -*-
DYN = {
 'N-01': {
   'easy': 'enable secret이 없으면 특권 모드는 <b>잠금장치 없는 금고</b>와 같습니다 — 손잡이만 돌리면 열립니다. 누구든 장비 콘솔이나 원격 세션에 들어와 그냥 enable만 입력하면 모든 설정을 바꿀 수 있는 관리자 권한을 얻습니다.',
   'attack_label': '공격자가 비밀번호 없이 특권(enable) 모드로 들어간다',
   'attack_vuln': [
     ['cmt', '# 공격자가 장비에 접속해 특권 모드를 시도'],
     ['prompt', 'attacker$ telnet 10.0.0.1'],
     ['', 'Router> enable'],
     ['bad', '>> 비밀번호를 묻지 않고 Router# 프롬프트로 전환!'],
     ['bad', '>> configure terminal 으로 설정 변경 가능'],
     ['bad', '>> 장비 전체 장악 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 특권 모드 무단 진입', 'desc': 'enable secret이 없으면 enable 입력만으로 관리자 권한을 얻어 설정을 마음대로 바꿀 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일 공격을 안전한 설정에서'],
     ['prompt', 'attacker$ telnet 10.0.0.1'],
     ['', 'Router> enable'],
     ['good', '>> Password: ____  (해시된 비밀번호 요구)'],
     ['warn', '>> 값을 모르면 특권 모드 진입 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 특권 진입 실패', 'desc': 'enable secret이 설정되면 해시된 비밀번호를 모르는 한 특권 모드로 들어갈 수 없습니다.'},
 },
 'N-02': {
   'easy': '단순한 비밀번호는 <b>현관 비밀번호를 1234로 해둔 것</b>과 같습니다 — 몇 번만 눌러보면 열립니다. 공격자는 자동화 도구로 흔한 비밀번호를 초당 수백 번 시도하므로, 짧고 단순한 값은 순식간에 뚫립니다.',
   'attack_label': '공격자가 단순 비밀번호를 무차별 대입으로 알아낸다',
   'attack_vuln': [
     ['cmt', '# 공격자가 흔한 비밀번호 목록으로 대입'],
     ['prompt', 'attacker$ hydra -l admin -P top100.txt 10.0.0.1 ssh'],
     ['', 'trying admin:123456 ... admin:password ...'],
     ['bad', '>> [22][ssh] login: admin  password: admin'],
     ['bad', '>> 단순 비밀번호가 7번째 시도에서 일치!'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 비밀번호 추측', 'desc': '길이와 복잡도 정책이 없으면 흔한 비밀번호가 자동 대입으로 쉽게 맞춰집니다.'},
   'attack_secure': [
     ['cmt', '# 동일 공격을 복잡도 정책이 적용된 장비에'],
     ['prompt', 'attacker$ hydra -l admin -P top100.txt 10.0.0.1 ssh'],
     ['good', '>> 목록의 단순 비밀번호가 모두 불일치'],
     ['warn', '>> 8자 이상 복잡 비밀번호는 목록에 없어 실패'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 추측 실패', 'desc': '최소 길이와 복잡도가 강제되면 흔한 비밀번호 사전으로는 맞출 수 없습니다.'},
 },
 'N-03': {
   'easy': '공용 계정 하나로 모두가 쓰는 것은 <b>사무실 열쇠를 한 개만 두고 돌려쓰는 것</b>과 같습니다 — 누가 무엇을 했는지 알 수 없죠. 비밀번호가 새면 그 하나로 모든 권한이 넘어가고, 사고가 나도 책임 추적이 불가능합니다.',
   'attack_label': '공격자가 공용 계정 하나로 전권을 장악한다',
   'attack_vuln': [
     ['cmt', '# 공용 admin 계정 하나가 모든 권한을 가짐'],
     ['prompt', 'attacker$ ssh admin@10.0.0.1'],
     ['', 'Password: (유출된 공용 비밀번호 입력)'],
     ['bad', '>> privilege 15 — 최고 권한 즉시 획득'],
     ['bad', '>> 로그에 admin 으로만 남아 추적 불가'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 전권 탈취 + 추적 불가', 'desc': '공용 고권한 계정 하나가 유출되면 전체 권한이 넘어가고 행위 추적도 불가능합니다.'},
   'attack_secure': [
     ['cmt', '# 사용자별 계정 + 최소 권한이 적용된 장비에'],
     ['prompt', 'attacker$ ssh op1@10.0.0.1'],
     ['good', '>> op1 은 privilege 7 — 제한된 명령만 가능'],
     ['warn', '>> 모든 행위가 op1 이름으로 로그에 기록됨'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 권한 분리 + 추적 가능', 'desc': '사용자별 계정과 최소 권한을 부여하면 피해 범위가 줄고 행위가 추적됩니다.'},
 },
 'N-04': {
   'easy': '설정 파일 속 평문 비밀번호는 <b>다이어리에 비밀번호를 적어둔 것</b>과 같습니다 — 그 페이지를 보는 사람은 누구나 알게 됩니다. 설정을 화면 캡처하거나 백업 파일을 입수한 공격자는 비밀번호를 그대로 읽어냅니다.',
   'attack_label': '공격자가 설정 파일에서 평문 비밀번호를 읽어낸다',
   'attack_vuln': [
     ['cmt', '# 공격자가 백업된 설정 파일을 입수'],
     ['prompt', 'attacker$ grep password router-config.txt'],
     ['', 'line vty 0 4'],
     ['bad', '>>  password cisco123   ← 평문 그대로!'],
     ['bad', '>> 비밀번호를 즉시 재사용해 로그인'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 설정에서 평문 유출', 'desc': '암호화가 없으면 설정 백업이나 화면 한 장만으로 비밀번호가 그대로 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# service password-encryption 적용된 설정에서'],
     ['prompt', 'attacker$ grep password router-config.txt'],
     ['good', '>>  password 7 0822455D0A16   (암호화됨)'],
     ['warn', '>> 평문이 보이지 않아 바로 쓸 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 평문 미노출', 'desc': 'service password-encryption을 적용하면 설정 파일에서 평문 비밀번호가 사라집니다.'},
 },
 'N-05': {
   'easy': 'VTY 접근 ACL이 없으면 원격 관리 문이 <b>인터넷 전체에 활짝 열린 것</b>과 같습니다. 관리자만 들어와야 할 문에 전 세계 누구나 접속을 시도할 수 있어, 비밀번호 대입 공격의 표적이 됩니다.',
   'attack_label': '외부 인터넷의 공격자가 관리 포트에 직접 접속한다',
   'attack_vuln': [
     ['cmt', '# 인터넷의 공격자가 VTY 포트로 바로 접속'],
     ['prompt', 'attacker$ ssh admin@203.0.113.5   (외부 IP)'],
     ['', 'connecting to vty ...'],
     ['bad', '>> 접속 허용됨 — 로그인 프롬프트 표시'],
     ['bad', '>> 외부에서 무차별 대입 공격 시작 가능'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 외부에서 관리 접근', 'desc': 'VTY에 접근 ACL이 없으면 인터넷 어디서나 관리 인터페이스에 접속을 시도할 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# access-class 10 in 으로 관리 대역만 허용'],
     ['prompt', 'attacker$ ssh admin@203.0.113.5   (외부 IP)'],
     ['good', '>> Connection refused (ACL이 차단)'],
     ['warn', '>> 허용된 관리 대역 밖이라 접속 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 접근 거부', 'desc': 'access-class로 관리 대역만 허용하면 외부 IP의 접속 시도는 연결 단계에서 거부됩니다.'},
 },
 'N-06': {
   'easy': 'Telnet은 비밀번호를 <b>엽서</b>에 적어 보내는 것과 같습니다 — 배달 도중 누구나 읽을 수 있죠. SSH는 <b>밀봉된 금고</b>에 넣어 보내는 방식입니다. 같은 네트워크의 공격자가 통신을 "엿들을" 때, 엽서(Telnet)는 비밀번호가 그대로 보이지만 금고(SSH)는 열 수 없습니다.',
   'attack_label': '같은 네트워크의 공격자가 관리자 접속을 도청한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 스위치 미러 포트에서 트래픽을 도청'],
     ['prompt', 'attacker$ tcpdump -i eth0 port 23 -A   (Telnet=23)'],
     ['', 'listening on eth0 ... 관리자가 접속을 시작함'],
     ['bad', '>> Username: admin'],
     ['bad', '>> Password: P@ssw0rd!   ← 평문 그대로 노출!'],
     ['bad', '>> 탈취한 계정으로 장비 장악 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 관리자 계정 탈취', 'desc': 'Telnet은 비밀번호를 평문으로 전송하므로, 도청만으로 자격증명이 그대로 유출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게, 이번엔 SSH(22) 트래픽을 도청 시도'],
     ['prompt', 'attacker$ tcpdump -i eth0 port 22 -A   (SSH=22)'],
     ['good', '>> 8f a1 3e c2 9d ...  (암호문, 해독 불가)'],
     ['warn', '>> 비밀번호를 가로챌 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 도청 실패', 'desc': 'SSH는 통신을 암호화하므로 트래픽을 가로채도 비밀번호를 알아낼 수 없습니다.'},
 },
 'N-07': {
   'easy': '세션 타임아웃이 없으면 <b>현관문을 열어둔 채 자리를 비우는 것</b>과 같습니다. 관리자가 로그인한 채 잠시 자리를 비우면, 그 틈에 다른 사람이 이미 열려 있는 세션을 그대로 이어받아 명령을 내릴 수 있습니다.',
   'attack_label': '공격자가 방치된 관리자 세션을 가로챈다',
   'attack_vuln': [
     ['cmt', '# 관리자가 로그인한 채 자리를 비움 (timeout 0 0)'],
     ['prompt', 'attacker$ (관리자 PC 앞 또는 열린 세션 접근)'],
     ['', 'Router# (세션이 종료되지 않고 계속 열려 있음)'],
     ['bad', '>> 그대로 configure terminal 입력 가능'],
     ['bad', '>> 인증 없이 특권 명령 실행 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 세션 탈취', 'desc': 'exec-timeout이 무제한이면 방치된 세션이 살아 있어 누구든 이어받아 명령을 실행합니다.'},
   'attack_secure': [
     ['cmt', '# exec-timeout 5 0 이 적용된 장비에서'],
     ['prompt', 'attacker$ (5분 뒤 방치된 세션에 접근 시도)'],
     ['good', '>> 세션이 자동으로 종료되어 로그아웃됨'],
     ['warn', '>> 다시 로그인해야 하므로 이어받기 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 세션 자동 종료', 'desc': 'exec-timeout을 설정하면 유휴 세션이 자동 종료되어 방치된 세션을 노릴 수 없습니다.'},
 },
 'N-08': {
   'easy': '로그인 실패 제한이 없으면 <b>비밀번호를 무한정 찍어볼 수 있는 자물쇠</b>와 같습니다. 공격자는 자동 도구로 끝없이 비밀번호를 시도할 수 있어, 시간만 충분하면 결국 맞는 값을 찾아냅니다.',
   'attack_label': '공격자가 횟수 제한 없이 비밀번호를 계속 시도한다',
   'attack_vuln': [
     ['cmt', '# 실패 제한이 없어 무한 대입 가능'],
     ['prompt', 'attacker$ hydra -l admin -P bigwordlist.txt 10.0.0.1 ssh'],
     ['', 'attempt 1 ... 500 ... 5000 (차단 없음)'],
     ['bad', '>> 계속 시도 허용 — 속도 제한 없음'],
     ['bad', '>> 충분한 시도 끝에 비밀번호 일치'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무제한 대입 돌파', 'desc': '실패 제한과 차단이 없으면 공격자가 끝없이 시도하여 결국 비밀번호를 찾아냅니다.'},
   'attack_secure': [
     ['cmt', '# login block-for 60 attempts 5 within 60 적용'],
     ['prompt', 'attacker$ hydra -l admin -P bigwordlist.txt 10.0.0.1 ssh'],
     ['good', '>> 5회 실패 후 60초간 로그인 차단됨'],
     ['warn', '>> 시도 속도가 막혀 대입이 사실상 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 대입 속도 제한', 'desc': 'login block-for로 실패 임계 초과 시 차단되어 무차별 대입이 무력화됩니다.'},
 },
 'N-09': {
   'easy': 'SNMP community가 기본값 public이면 <b>모두가 아는 마스터키</b>를 문에 붙여둔 것과 같습니다. 공격자는 이 흔한 키 하나로 장비의 인터페이스, 라우팅, 설정 정보를 통째로 읽어낼 수 있습니다.',
   'attack_label': '공격자가 기본 community로 장비 정보를 통째로 덤프한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 기본 community public 으로 조회'],
     ['prompt', 'attacker$ snmpwalk -v2c -c public 10.0.0.1'],
     ['', 'iso.3.6.1.2.1 ... 응답이 쏟아짐'],
     ['bad', '>> 인터페이스, IP, 라우팅 테이블 모두 노출'],
     ['bad', '>> 내부 네트워크 구조를 통째로 수집 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 장비 정보 덤프', 'desc': '기본 community public과 ACL 부재로 장비의 상세 정보가 그대로 조회됩니다.'},
   'attack_secure': [
     ['cmt', '# 복잡 community + access-list 20 적용'],
     ['prompt', 'attacker$ snmpwalk -v2c -c public 10.0.0.1'],
     ['good', '>> Timeout: No Response (community 불일치)'],
     ['warn', '>> 추측 어려운 값 + 소스 ACL로 조회 차단'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 조회 실패', 'desc': '복잡한 community와 접근 ACL을 적용하면 기본값 추측과 외부 조회가 모두 막힙니다.'},
 },
 'N-10': {
   'easy': 'SNMP 쓰기(RW) community는 <b>설정을 원격으로 고칠 수 있는 만능 리모컨</b>입니다. 기본값 private이 열려 있으면, 공격자는 장비에 직접 로그인하지 않고도 설정을 바꾸거나 설정 파일을 통째로 빼낼 수 있습니다.',
   'attack_label': '공격자가 SNMP RW로 설정을 변경하고 설정을 빼낸다',
   'attack_vuln': [
     ['cmt', '# 공격자가 RW community private 로 설정 변경'],
     ['prompt', 'attacker$ snmpset -v2c -c private 10.0.0.1 ...'],
     ['', '설정 변경 OID 전송 ...'],
     ['bad', '>> 원격에서 running-config 를 TFTP로 추출'],
     ['bad', '>> 비밀번호 포함 전체 설정 탈취 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 원격 설정 변조/유출', 'desc': 'RW community가 열려 있으면 로그인 없이 설정을 바꾸거나 설정 전체를 빼낼 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# no snmp-server community private RW (RW 제거)'],
     ['prompt', 'attacker$ snmpset -v2c -c private 10.0.0.1 ...'],
     ['good', '>> Error: No Response (RW community 없음)'],
     ['warn', '>> 쓰기 권한이 없어 설정 변경 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 쓰기 거부', 'desc': 'RW community를 제거하면 SNMP로 설정을 변경하거나 추출할 수 없습니다.'},
 },
 'N-11': {
   'easy': 'CDP는 장비가 <b>자기 명함(모델, IOS 버전, IP)을 옆 장비에 자동으로 돌리는 것</b>과 같습니다. 네트워크에 끼어든 공격자는 명령 한 줄로 이 명함을 모아, 어떤 취약점을 노릴지 손쉽게 정찰합니다.',
   'attack_label': '공격자가 CDP로 장비 모델과 IOS 버전을 정찰한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 CDP 광고를 수집해 정찰'],
     ['prompt', 'attacker$ show cdp neighbors detail'],
     ['', 'collecting CDP advertisements ...'],
     ['bad', '>> Platform: Cisco 2960, IOS 12.2'],
     ['bad', '>> Mgmt IP: 10.0.0.1  ← 표적 정보 확보'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 장비 정보 정찰', 'desc': 'CDP가 켜져 있으면 모델과 IOS 버전, 관리 IP가 노출되어 표적 공격의 단서가 됩니다.'},
   'attack_secure': [
     ['cmt', '# no cdp run (또는 인터페이스별 no cdp enable)'],
     ['prompt', 'attacker$ show cdp neighbors detail'],
     ['good', '>> (광고 없음 — 수집되는 정보 없음)'],
     ['warn', '>> 장비 모델/버전을 알아낼 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 정찰 실패', 'desc': '불필요한 CDP를 끄면 장비 정보가 광고되지 않아 정찰 단서가 사라집니다.'},
 },
 'N-12': {
   'easy': '평문 HTTP 관리 페이지는 <b>유리로 된 관리실 문</b>과 같습니다 — 비밀번호를 입력하는 순간 밖에서 다 들여다보입니다. 공격자는 이 통신을 엿보거나 웹 취약점을 노려 관리 화면을 장악합니다.',
   'attack_label': '공격자가 평문 HTTP 관리 통신을 가로챈다',
   'attack_vuln': [
     ['cmt', '# 평문 HTTP 관리(80) 통신을 도청'],
     ['prompt', 'attacker$ tcpdump -i eth0 port 80 -A'],
     ['', '관리자가 웹 관리 페이지에 로그인 ...'],
     ['bad', '>> Authorization: Basic YWRtaW46Y2lzY28='],
     ['bad', '>> 디코딩 시 admin:cisco — 자격증명 노출'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 웹 관리 자격증명 유출', 'desc': '평문 HTTP 관리 서버는 로그인 정보를 그대로 전송해 도청만으로 탈취됩니다.'},
   'attack_secure': [
     ['cmt', '# no ip http server + HTTPS + access-class'],
     ['prompt', 'attacker$ tcpdump -i eth0 port 80 -A'],
     ['good', '>> (포트 80 응답 없음 — HTTP 비활성)'],
     ['warn', '>> HTTPS는 암호화되어 자격증명 보이지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 도청 무력화', 'desc': '평문 HTTP를 끄고 HTTPS+ACL만 허용하면 관리 통신을 가로채도 내용을 알 수 없습니다.'},
 },
 'N-13': {
   'easy': '불필요한 서비스(finger 등)는 <b>안 쓰는데 켜둔 옆문들</b>과 같습니다 — 많을수록 침입 경로가 늘어납니다. 공격자는 이런 옛 서비스로 사용자 정보를 캐거나 경로 우회 공격의 발판을 만듭니다.',
   'attack_label': '공격자가 finger 서비스로 사용자 정보를 캔다',
   'attack_vuln': [
     ['cmt', '# 켜진 finger 서비스(79)로 사용자 조회'],
     ['prompt', 'attacker$ finger @10.0.0.1'],
     ['', 'querying finger service ...'],
     ['bad', '>> Login: admin   On since ...'],
     ['bad', '>> 접속 중인 계정명 노출 — 표적 확보'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 사용자 정보 노출', 'desc': 'finger 등 불필요 서비스가 켜져 있으면 계정명 같은 정찰 정보가 새어 나갑니다.'},
   'attack_secure': [
     ['cmt', '# no service finger ; no ip source-route 등 적용'],
     ['prompt', 'attacker$ finger @10.0.0.1'],
     ['good', '>> Connection refused (서비스 비활성)'],
     ['warn', '>> 캐낼 수 있는 정보가 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 서비스 응답 없음', 'desc': '불필요 서비스를 끄면 공격 표면이 줄어 정찰과 우회 공격의 발판이 사라집니다.'},
 },
 'N-14': {
   'easy': 'directed broadcast가 켜진 장비는 <b>확성기처럼 신호를 증폭해주는 중계기</b>가 됩니다. 공격자는 피해자 주소를 사칭해 작은 요청을 보내고, 장비가 이를 수많은 응답으로 부풀려 피해자를 마비시키는 Smurf DoS에 악용합니다.',
   'attack_label': '공격자가 directed broadcast를 Smurf 증폭 DoS에 악용한다',
   'attack_vuln': [
     ['cmt', '# 피해자 IP로 위장해 브로드캐스트로 ping 폭주'],
     ['prompt', 'attacker$ hping3 --icmp -a 피해자IP 10.0.0.255'],
     ['', '브로드캐스트 ping 전송 ...'],
     ['bad', '>> 대역 내 모든 호스트가 피해자에게 응답'],
     ['bad', '>> 트래픽 증폭으로 피해자 회선 마비 (DoS)'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 증폭 DoS 중계', 'desc': 'ip directed-broadcast가 켜져 있으면 장비가 Smurf 공격의 증폭 중계지로 악용됩니다.'},
   'attack_secure': [
     ['cmt', '# no ip directed-broadcast 적용'],
     ['prompt', 'attacker$ hping3 --icmp -a 피해자IP 10.0.0.255'],
     ['good', '>> 브로드캐스트 ping이 호스트로 전달 안 됨'],
     ['warn', '>> 증폭이 일어나지 않아 DoS 중계 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 증폭 차단', 'desc': 'no ip directed-broadcast를 적용하면 브로드캐스트가 호스트로 퍼지지 않아 증폭 DoS를 막습니다.'},
 },
 'N-15': {
   'easy': 'ICMP redirect를 무분별하게 허용하면 <b>가짜 도로 표지판을 믿고 길을 바꾸는 것</b>과 같습니다. 공격자는 조작된 redirect로 트래픽 경로를 자기 쪽으로 틀거나, unreachable 응답으로 내부 망 구조를 정찰합니다.',
   'attack_label': '공격자가 ICMP로 경로를 조작하고 망을 정찰한다',
   'attack_vuln': [
     ['cmt', '# 위조 ICMP redirect로 경로 조작 + 정찰'],
     ['prompt', 'attacker$ nmap -sn -PE 10.0.0.0/24'],
     ['', 'ICMP unreachable 응답을 분석 ...'],
     ['bad', '>> 살아있는 호스트와 차단 규칙 추정 성공'],
     ['bad', '>> redirect 위조로 트래픽 가로채기 시도'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 경로 조작/정찰', 'desc': 'redirect/unreachable이 열려 있으면 라우팅 조작과 내부 망 정찰에 악용됩니다.'},
   'attack_secure': [
     ['cmt', '# no ip redirects ; no ip unreachables (외부 IF)'],
     ['prompt', 'attacker$ nmap -sn -PE 10.0.0.0/24'],
     ['good', '>> ICMP 응답이 억제되어 정보 수집 실패'],
     ['warn', '>> 위조 redirect도 수용되지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 정보 억제', 'desc': '외부 인터페이스에서 redirect/unreachable을 끄면 정찰 정보와 경로 조작이 차단됩니다.'},
 },
 'N-16': {
   'easy': 'Proxy ARP는 장비가 <b>남의 우편물을 대신 받아주겠다고 나서는 것</b>과 같습니다. 공격자는 이를 악용해 자신이 다른 호스트인 척 끼어들어 통신을 가로채는 중간자(MITM) 공격을 펼칠 수 있습니다.',
   'attack_label': '공격자가 Proxy ARP를 악용해 중간자 위치를 차지한다',
   'attack_vuln': [
     ['cmt', '# Proxy ARP 활성 상태에서 호스트 위장'],
     ['prompt', 'attacker$ arpspoof -t 피해자 게이트웨이'],
     ['', '위조 ARP 응답 전송 ...'],
     ['bad', '>> 장비가 위장을 보조해 경로가 공격자로 향함'],
     ['bad', '>> 피해자 트래픽을 중간에서 가로채기 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 중간자 가로채기', 'desc': 'Proxy ARP가 켜져 있으면 호스트 위장이 쉬워져 MITM 공격에 악용됩니다.'},
   'attack_secure': [
     ['cmt', '# no ip proxy-arp 적용'],
     ['prompt', 'attacker$ arpspoof -t 피해자 게이트웨이'],
     ['good', '>> 장비가 위장 응답을 대리하지 않음'],
     ['warn', '>> 중간자 경로를 만들기 어려움'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 위장 차단', 'desc': 'no ip proxy-arp를 적용하면 장비가 호스트 위장을 돕지 않아 MITM 위험이 줄어듭니다.'},
 },
 'N-17': {
   'easy': 'TFTP는 <b>인증도 봉인도 없는 택배 상자</b>로 설정 파일을 주고받는 것과 같습니다 — 누구나 집어 들고 열어볼 수 있죠. 공격자는 인증 없이 설정 파일을 내려받거나 바꿔치기할 수 있습니다.',
   'attack_label': '공격자가 TFTP로 설정 파일을 인증 없이 가져간다',
   'attack_vuln': [
     ['cmt', '# 인증 없는 TFTP 서버에서 설정 파일 요청'],
     ['prompt', 'attacker$ tftp 10.0.0.1 -c get config'],
     ['', 'requesting file over TFTP (인증 없음) ...'],
     ['bad', '>> config 파일 다운로드 성공'],
     ['bad', '>> 비밀번호 포함 설정 전체 입수'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 설정 파일 탈취', 'desc': 'TFTP는 인증 없는 평문 전송이라 설정 파일을 누구나 내려받거나 변조할 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# no tftp-server + ip scp server enable (SCP 사용)'],
     ['prompt', 'attacker$ tftp 10.0.0.1 -c get config'],
     ['good', '>> Transfer timed out (TFTP 비활성)'],
     ['warn', '>> SCP는 SSH 인증이 필요해 무단 접근 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 전송 거부', 'desc': '불필요한 TFTP를 끄고 SCP를 쓰면 인증 없이는 설정 파일을 가져갈 수 없습니다.'},
 },
 'N-18': {
   'easy': '구버전 IOS는 <b>이미 도둑들이 따는 법을 다 아는 옛날 자물쇠</b>와 같습니다. 공개된 취약점 정보가 돌아다니므로, 공격자는 맞는 공격 도구를 골라 쓰기만 하면 원격으로 장비를 장악할 수 있습니다.',
   'attack_label': '공격자가 알려진 취약점으로 구버전 IOS를 공격한다',
   'attack_vuln': [
     ['cmt', '# 버전 확인 후 공개 취약점(exploit) 적용'],
     ['prompt', 'attacker$ nmap -sV 10.0.0.1   (버전 식별)'],
     ['', 'IOS 12.2 (EOL) — 알려진 CVE 다수'],
     ['bad', '>> 공개된 익스플로잇으로 원격 코드 실행'],
     ['bad', '>> 패치되지 않은 취약점으로 장비 장악'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 알려진 취약점 악용', 'desc': 'EOL 구버전 IOS는 공개된 취약점이 많아 공격 도구만으로 원격 장악됩니다.'},
   'attack_secure': [
     ['cmt', '# 권고 보안 버전으로 업그레이드된 장비에'],
     ['prompt', 'attacker$ nmap -sV 10.0.0.1   (버전 식별)'],
     ['good', '>> 최신 권고 버전 — 해당 CVE 이미 패치됨'],
     ['warn', '>> 공개 익스플로잇이 동작하지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 취약점 부재', 'desc': '최신 보안 버전으로 유지하면 알려진 취약점이 패치되어 공개 공격이 통하지 않습니다.'},
 },
 'N-19': {
   'easy': '중앙 로그 수집이 없으면 <b>CCTV 영상을 침입자가 들어온 방에만 두는 것</b>과 같습니다 — 침입자가 지워버리면 끝입니다. 공격자는 장비에만 남은 로그를 손쉽게 삭제해 흔적을 지웁니다.',
   'attack_label': '공격자가 장비에만 남은 로그를 지워 흔적을 없앤다',
   'attack_vuln': [
     ['cmt', '# 로그가 장비 내부에만 저장됨 (원격 미전송)'],
     ['prompt', 'attacker$ (장악 후) clear logging'],
     ['', 'local buffer 로그 삭제 ...'],
     ['bad', '>> 침입 기록이 모두 사라짐'],
     ['bad', '>> 사후 분석/추적 불가능'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 흔적 삭제', 'desc': '로그가 장비에만 있으면 공격자가 장악 후 로그를 지워 침해 흔적을 없앨 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# logging host 10.0.0.20 (중앙 Syslog 전송)'],
     ['prompt', 'attacker$ (장악 후) clear logging'],
     ['good', '>> 로컬 로그는 지워져도 원격 서버에 이미 전송됨'],
     ['warn', '>> 중앙 Syslog의 기록은 삭제 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 원격 보존', 'desc': '중앙 Syslog로 실시간 전송하면 장비 로그를 지워도 침해 기록이 서버에 남습니다.'},
 },
 'N-20': {
   'easy': '시각 동기화가 없으면 각 장비의 로그 시계가 제멋대로라 <b>사건 순서를 맞출 수 없는 증언들</b>처럼 됩니다. 공격자의 침입 경로를 시간순으로 엮어 분석해야 하는데, 시각이 어긋나면 상관분석이 불가능해집니다.',
   'attack_label': '시각 불일치로 공격 추적의 시간선이 무너진다',
   'attack_vuln': [
     ['cmt', '# 장비 시각이 동기화되지 않아 로그 시간이 제각각'],
     ['prompt', 'attacker$ (여러 장비를 거쳐 침입)'],
     ['', 'A장비 로그 14:00, B장비 로그 09:12 ...'],
     ['bad', '>> 장비별 시각이 어긋나 사건 순서 추정 불가'],
     ['bad', '>> 침입 경로 상관분석 실패'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 추적 시간선 붕괴', 'desc': '시각이 동기화되지 않으면 로그 시간이 어긋나 침입 경로의 상관분석이 어렵습니다.'},
   'attack_secure': [
     ['cmt', '# ntp server 10.0.0.30 ; ntp authenticate 적용'],
     ['prompt', 'attacker$ (여러 장비를 거쳐 침입)'],
     ['good', '>> 모든 장비 시각이 동일 기준으로 일치'],
     ['warn', '>> 로그를 시간순으로 엮어 경로 재구성 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 정확한 추적', 'desc': 'NTP로 시각을 동기화하면 로그 시간이 일치해 침입 경로를 정확히 분석할 수 있습니다.'},
 },
 'N-21': {
   'easy': '미사용 포트가 켜져 있는 것은 <b>건물에 잠그지 않은 빈 콘센트 문</b>을 둔 것과 같습니다. 공격자가 사무실에 몰래 들어와 빈 포트에 노트북이나 무선 AP를 꽂으면, 곧바로 내부 네트워크에 합류해 버립니다.',
   'attack_label': '공격자가 활성 상태인 빈 포트에 무단 장비를 연결한다',
   'attack_vuln': [
     ['cmt', '# 미사용인데 up 상태인 포트에 장비를 연결'],
     ['prompt', 'attacker$ (빈 포트 Gi0/10에 노트북 연결)'],
     ['', 'link up — DHCP 주소 요청 ...'],
     ['bad', '>> 내부 IP를 즉시 할당받아 망에 합류'],
     ['bad', '>> 내부 네트워크 스캔/공격 발판 확보'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무단 네트워크 합류', 'desc': '미사용 포트가 활성 상태면 비인가 단말을 꽂는 즉시 내부 네트워크에 연결됩니다.'},
   'attack_secure': [
     ['cmt', '# interface Gi0/10 ; shutdown (미사용 포트 차단)'],
     ['prompt', 'attacker$ (빈 포트 Gi0/10에 노트북 연결)'],
     ['good', '>> 포트가 administratively down — link 안 올라옴'],
     ['warn', '>> 주소를 받지 못해 네트워크 합류 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 포트 비활성', 'desc': '미사용 포트를 shutdown하면 단말을 꽂아도 링크가 올라오지 않아 무단 연결이 막힙니다.'},
 },
}
