# -*- coding: utf-8 -*-
# 금융보안원 제2026-1호 평가기준 — 전자금융 특화(FIN) 단말보안 누락분 3종
# 020 소스코드 난독화 / 021 디버깅 탐지 / 022 보안프로그램 최신 업데이트

SPECS = [
    {
        'file': '07_fin-obfuscation.html',
        'title': '소스코드 난독화 적용',
        'icon': '🧬',
        'target': '모바일/HTS 실행파일 (APK·IPA·EXE)',
        'risk': '4',
        'item_code': 'MOB/HTS-FIN 소스코드 난독화(020)',
        'attack_panel_title': '앱 디컴파일 분석',
        'scenario_html': '실행파일이 <b>난독화 없이</b> 배포되면 공격자가 디컴파일러(jadx, apktool)로 <b>원본에 가까운 소스코드</b>를 복원합니다. 하드코딩된 <b>API 키·암호화 키·거래 로직</b>이 그대로 노출됩니다.',
        'attack_name': '정적 역공학(디컴파일)',
        'attack_sub': 'jadx / apktool 로 평문 로직·하드코딩 키 추출',
        'normal_req': '$ jadx app-release.apk -d out/   # 난독화된 앱',
        'attack_req': '$ jadx app-release.apk -d out/\n$ grep -R "API_KEY\\|AES_KEY" out/\nPayClient.java:  API_KEY = "AKIA-LIVE-9F3K-22XQ"\nPayClient.java:  AES_KEY = "0123456789abcdef"',
        'vuln_logs_js': "addLog('[ATTACKER] jadx 로 APK 디컴파일','warn'); addLog('[ANALYZE] 클래스/메서드명이 평문 → 거래 로직 즉시 파악','error'); addLog('[LEAK] 하드코딩 API_KEY/AES_KEY 추출 성공','error');",
        'breach_html': '<strong>🚨 핵심 로직·키 탈취</strong><br>난독화가 없어 디컴파일된 소스에서 <b>암호화 키와 API 키</b>가 평문으로 노출되었습니다.<table class="data-table"><tr><th>점검</th><th>기대</th><th>실제</th></tr><tr><td>난독화(minify)</td><td>적용</td><td style="color:#b71c1c">미적용</td></tr><tr><td>키 하드코딩</td><td>금지</td><td style="color:#b71c1c">평문 노출</td></tr></table>',
        'violations': [
            '금융보안원 평가기준 [전자금융] 소스코드 난독화 적용(020) (위험도 4)',
            '중요정보(키) 하드코딩 금지 위반',
            '디컴파일 대응(난독화) 미적용',
        ],
        'defense_intro': '빌드 시 <strong>난독화(R8/ProGuard/DexGuard)</strong>를 적용하고, <strong>키·시크릿은 코드에서 분리</strong>하여 안전저장소(KeyStore)나 서버에서 주입해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 난독화 미적용 + 키 하드코딩\npublic class PayClient {\n    // build.gradle: minifyEnabled false  (난독화 꺼짐)\n    static final String API_KEY = "AKIA-LIVE-9F3K-22XQ"; // 디컴파일 시 노출\n    static final String AES_KEY = "0123456789abcdef";     // 평문 키\n}',
        'secure_hint': '// [안전] 난독화 적용 + 시크릿 외부화\npublic class PayClient {\n    // build.gradle: minifyEnabled true  (R8/ProGuard 난독화)\n    // 키는 코드가 아닌 안전저장소/서버에서 주입\n    String apiKey = KeyStoreProvider.get("api_key"); // AndroidKeyStore\n    String aesKey = fetchKeyFromServer();            // 서버 발급\n}',
        # 난독화(minifyEnabled/R8 등)는 build.gradle 빌드설정이라 코드 에디터에선 주석으로만 표현되어
        # 자동 검증 대상에서 제외(힌트·해설로 학습). 코드에서 검증 가능한 '키 외부화 + 하드코딩 키 제거'를 채점한다.
        'checks': [
            ['KeyStoreProvider', 'fetchKeyFromServer', 'AndroidKeyStore'],
            ['!AKIA-LIVE', '!0123456789abcdef'],
        ],
        'success_msg': '키를 KeyStore/서버로 외부화하고 하드코딩 키를 제거했습니다. (배포 시 빌드에서 R8/ProGuard 난독화도 함께 적용하세요)',
        'fail_msg': '하드코딩된 키를 제거하고 KeyStore/서버 주입으로 바꾸세요. (난독화 minifyEnabled true 는 build.gradle에서 별도 적용)',
        'kisa_ref': '<h4>1. 점검 항목</h4>단말 보안 &gt; <b>소스코드 난독화 적용</b><h4>2. 위험 분석</h4><ul><li>디컴파일(jadx/apktool)로 평문에 가까운 소스 복원</li><li>하드코딩된 키·로직 노출 → 위·변조, 키 탈취</li></ul><h4>3. 조치 방법</h4><ul><li>R8/ProGuard/DexGuard 등 <b>난독화 적용</b></li><li>키·시크릿 <b>코드 분리</b>(KeyStore/서버 발급)</li></ul>',
        'easy': '난독화는 설계도를 <b>외계어로 바꿔 놓는 것</b>입니다. 안 하면 누구나 앱을 뜯어 도면을 그대로 읽고 <b>숨겨둔 열쇠(키)</b>까지 주워 갑니다. 열쇠는 도면이 아니라 <b>따로 금고</b>에 둬야 합니다.',
    },
    {
        'file': '07_fin-debug-detection.html',
        'title': '디버깅 탐지기능 적용',
        'icon': '🐞',
        'target': '모바일/HTS 실행 중 프로세스',
        'risk': '4',
        'item_code': 'MOB/HTS-FIN 디버깅 탐지(021)',
        'attack_panel_title': '동적 디버깅·후킹',
        'scenario_html': '실행 중인 앱에 <b>디버거(gdb/lldb)나 후킹 도구(Frida)</b>를 붙이면, 인증 분기 함수를 가로채 <b>우회</b>하거나 <b>메모리에서 평문 정보</b>를 꺼낼 수 있습니다. 안티디버깅이 없으면 그대로 통합니다.',
        'attack_name': 'Frida 후킹으로 인증 우회',
        'attack_sub': 'frida attach → 인증함수 return true 강제',
        'normal_req': '$ frida -U -f com.bank.app  # 디버거 부착 시도',
        'attack_req': "$ frida -U -f com.bank.app\n> Interceptor.attach(checkAuth, {\n>   onLeave(r){ r.replace(1); }   // 인증 결과 강제 true\n> })\n>> 인증 우회 + 메모리 덤프 성공",
        'vuln_logs_js': "addLog('[ATTACKER] Frida 로 프로세스 부착','warn'); addLog('[HOOK] checkAuth() 후킹 → 반환값 강제 변조','error'); addLog('[BYPASS] 인증 우회, 메모리 내 평문 추출 성공','error');",
        'breach_html': '<strong>🚨 런타임 조작 성공</strong><br>안티디버깅이 없어 디버거·후킹 도구가 부착되고 <b>인증 분기가 우회</b>되었습니다.<table class="data-table"><tr><th>점검</th><th>기대</th><th>실제</th></tr><tr><td>디버거 탐지</td><td>탐지·종료</td><td style="color:#b71c1c">탐지 안 됨</td></tr><tr><td>후킹(Frida) 탐지</td><td>차단</td><td style="color:#b71c1c">허용</td></tr></table>',
        'violations': [
            '금융보안원 평가기준 [전자금융] 디버깅 탐지기능 적용(021) (위험도 4)',
            '역분석(동적 디버깅) 대응 미흡',
            '런타임 무결성·후킹 탐지 부재',
        ],
        'defense_intro': '앱 구동·주요 거래 시 <strong>디버거 연결·ptrace·Frida 후킹을 탐지</strong>하고, 탐지되면 <strong>즉시 서비스를 종료</strong>해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 디버깅/후킹 탐지 없음\npublic void startSession() {\n    authenticateAndTrade();   // 디버거가 분기 후킹 가능\n}',
        'secure_hint': '// [안전] 디버거/후킹 탐지 후 즉시 종료\npublic void startSession() {\n    if (Debug.isDebuggerConnected() || isFridaDetected() || isPtraceAttached()) {\n        terminate("디버깅 탐지");   // 안티디버깅\n        return;\n    }\n    authenticateAndTrade();\n}',
        'checks': [
            ['isDebuggerConnected', 'isFridaDetected', 'isPtraceAttached', '안티디버깅'],
            ['terminate', 'System.exit', 'finishAndRemoveTask'],
        ],
        'success_msg': '디버거·후킹을 탐지해 즉시 종료하므로 런타임 조작이 차단됩니다.',
        'fail_msg': '디버거/Frida 탐지 호출과 탐지 시 종료(terminate 등) 처리를 추가해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>단말 보안 &gt; <b>디버깅 탐지기능 적용</b><h4>2. 위험 분석</h4><ul><li>gdb/lldb/Frida 부착으로 인증 분기 우회·메모리 덤프</li></ul><h4>3. 조치 방법</h4><ul><li>디버거 연결·ptrace·후킹 <b>탐지 루틴</b> 적용</li><li>탐지 시 <b>즉시 종료</b> 및 이벤트 보고</li></ul>',
        'easy': '디버깅은 <b>시계 뒷판을 열고 톱니를 멈춰가며</b> 들여다보는 것입니다. 안티디버깅은 <b>"뒷판이 열리면 작동을 멈추는"</b> 장치라, 공격자가 멈춰 세워 분석·조작하지 못하게 합니다.',
    },
    {
        'file': '07_fin-secprog-update.html',
        'title': '보안프로그램 구동 시 최신 업데이트 수행',
        'icon': '⬆️',
        'target': 'HTS/PC 보안모듈 (키보드보안·백신)',
        'risk': '4',
        'item_code': 'HTS-FIN 보안프로그램 최신 업데이트(022)',
        'attack_panel_title': '보안모듈 버전 점검',
        'scenario_html': '보안프로그램이 <b>구버전 그대로 구동</b>되면, 이미 공개된 <b>알려진 취약점(CVE)</b>으로 키보드보안·백신 모듈이 무력화됩니다. 구동 시 최신 버전 확인·강제 업데이트가 없으면 그대로 노출됩니다.',
        'attack_name': '구버전 모듈 취약점 악용',
        'attack_sub': '공개된 CVE 로 키보드보안 우회·후킹',
        'normal_req': 'launch security-module v2.1.0   # 최신 여부 점검 안 함',
        'attack_req': 'launch security-module v2.1.0\n# v2.1.0 = 공개 CVE-XXXX 존재 (키로깅 우회)\n>> 구버전 모듈에 알려진 익스플로잇 적용 → 입력값 탈취',
        'vuln_logs_js': "addLog('[LAUNCH] 보안모듈 v2.1.0 그대로 구동','warn'); addLog('[VULN] 해당 버전에 공개된 취약점 존재','error'); addLog('[BYPASS] 구버전 키보드보안 우회 → 입력값 탈취','error');",
        'breach_html': '<strong>🚨 구버전 보안모듈 무력화</strong><br>최신 버전 확인·강제 업데이트가 없어 <b>알려진 취약점</b>으로 보안모듈이 우회되었습니다.<table class="data-table"><tr><th>점검</th><th>기대</th><th>실제</th></tr><tr><td>구동 시 버전 확인</td><td>수행</td><td style="color:#b71c1c">미수행</td></tr><tr><td>강제 업데이트</td><td>적용</td><td style="color:#b71c1c">없음</td></tr></table>',
        'violations': [
            '금융보안원 평가기준 [전자금융] 보안프로그램 구동시 최신 업데이트 수행(022) (위험도 4)',
            '알려진 취약점(구버전) 방치',
            '보안모듈 무결성·최신성 관리 미흡',
        ],
        'defense_intro': '보안프로그램 구동 시 <strong>서버의 최신 버전과 비교</strong>하고, 최신이 아니면 <strong>강제 업데이트 후</strong> 서비스를 시작해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 버전 점검 없이 구버전 모듈 바로 실행\npublic void launchSecurityModule() {\n    securityModule.start();   // 최신 여부 검증 없음\n}',
        'secure_hint': '// [안전] 구동 시 최신 버전 확인 후 강제 업데이트\npublic void launchSecurityModule() {\n    String latest = updateServer.getLatestVersion();\n    if (compareVersion(securityModule.version(), latest) < 0) {\n        forceUpdate(latest);          // 최신 아니면 강제 업데이트\n        if (!isUpToDate()) { blockService("보안모듈 업데이트 필요"); return; }\n    }\n    securityModule.start();\n}',
        'checks': [
            ['getLatestVersion', 'compareVersion', 'isUpToDate', '최신'],
            ['forceUpdate', 'blockService'],
        ],
        'success_msg': '구동 시 최신 버전을 확인하고 강제 업데이트하므로 구버전 취약점이 차단됩니다.',
        'fail_msg': '최신 버전 비교(getLatestVersion/compareVersion)와 강제 업데이트(forceUpdate) 처리를 추가해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>단말 보안 &gt; <b>보안프로그램 구동 시 최신 업데이트</b><h4>2. 위험 분석</h4><ul><li>구버전 보안모듈의 공개 취약점으로 키보드보안·백신 무력화</li></ul><h4>3. 조치 방법</h4><ul><li>구동 시 <b>서버 최신 버전과 비교</b></li><li>최신이 아니면 <b>강제 업데이트</b> 후 서비스 시작</li></ul>',
        'easy': '보안프로그램이 <b>옛날 자물쇠</b>라면 따는 법이 이미 인터넷에 다 퍼져 있습니다. 켤 때마다 <b>최신 자물쇠로 바뀌었는지 확인</b>하고, 아니면 먼저 교체(업데이트)한 뒤 문을 열어야 합니다.',
    },
]
