# -*- coding: utf-8 -*-
"""전자금융 보안 특화 시뮬 추가 4종 콘텐츠 명세 (금융보안원 제2026-1호 WEB-SER 서버보안 항목)."""

SPECS = [
{
 'file':'07_fin-cert-integrity.html',
 'title':'서버 인증서 무결성 검증',
 'icon':'🪪', 'target':'모바일/클라이언트 TLS 연결', 'risk':'5', 'item_code':'WEB-SER 서버 인증서 무결성(030)',
 'attack_panel_title':'서버 TLS 연결 검증',
 'scenario_html':'앱/클라이언트가 서버 TLS 인증서의 <b>유효성·신뢰체인·핀(pin)</b>을 검증하지 않거나 <b>모든 인증서를 무조건 신뢰</b>하면, 동일 네트워크의 공격자가 <b>MITM 프록시 인증서</b>로 끼어들어 거래 통신을 그대로 가로채고 변조할 수 있습니다.',
 'attack_name':'MITM 프록시 인증서 가로채기', 'attack_sub':'모든 인증서 신뢰 → mitmproxy 인증서로 통신 열람',
 'normal_req':'POST https://bank.example.com/transfer\n# 정상: 신뢰체인 검증 + 인증서 핀 일치\nServer Cert: CN=bank.example.com (DigiCert 발급, pin 일치)\n{\n  "to": "220-771-559010",\n  "amount": 10000\n}',
 'attack_req':'# 공격자 mitmproxy 인증서로 중간자 연결\nServer Cert: CN=bank.example.com (mitmproxy 자체서명)\n--- 클라이언트 TrustManager 무력화 상태 ---\nfun checkServerTrusted(chain, authType) { /* 비어있음: 모두 신뢰 */ }\n# 인증서 검증을 건너뛰어 가짜 인증서 그대로 수용\n{\n  "to": "999-000-HACKER",\n  "amount": 50000000\n}',
 'vuln_logs_js':"addLog('[TLS] 서버 인증서 신뢰체인 검증 생략 → 모든 인증서 신뢰','warn'); addLog('[MITM] mitmproxy 자체서명 인증서 수용됨','error'); addLog('[PROXY] 거래 전문 평문 열람 → 수취계좌 변조','error'); addLog('[SERVER] 변조 거래 그대로 승인','error');",
 'breach_html':'<strong>🚨 서버 인증서 위조 가로채기 성공</strong><br>인증서 검증을 하지 않아 MITM 프록시의 가짜 인증서가 수용되었고 거래정보가 노출·변조되었습니다.<table class="data-table"><tr><th>항목</th><th>원거래</th><th>변조 후</th></tr><tr><td>수취계좌</td><td>220-771-559010</td><td style="color:#b71c1c">999-000-HACKER</td></tr><tr><td>금액</td><td class="amount">10,000</td><td class="amount" style="color:#b71c1c">50,000,000</td></tr></table>',
 'violations':['평가기준 [전자금융] 서버 인증서 무결성 검증(위험도 5)',
               '전자금융감독규정 제32조: 전송구간 서버 인증서 검증 미흡',
               '부적절한 인증서 검증 / TrustManager 무력화(IN)'],
 'defense_intro':'클라이언트는 서버 인증서의 <strong>기본 신뢰체인·호스트명 검증을 유지</strong>하고, 가능하면 <strong>Certificate Pinning</strong>을 적용해야 합니다. <strong>TrustManager를 비우는(모두 신뢰) 무력화는 금지</strong>입니다. 아래 코드를 보완하세요.',
 'vuln_code':'// [취약] TrustManager 무력화 → 모든 인증서 신뢰\nval trustAll = object : X509TrustManager {\n    override fun checkServerTrusted(c: Array<X509Certificate>, a: String) { }\n    override fun checkClientTrusted(c: Array<X509Certificate>, a: String) { }\n    override fun getAcceptedIssuers() = arrayOf<X509Certificate>()\n}\nval client = OkHttpClient.Builder()\n    .sslSocketFactory(buildContext(trustAll), trustAll)\n    .hostnameVerifier { _, _ -> true }   // 호스트명 검증도 무시\n    .build()',
 'secure_hint':'// [안전] 기본 인증서 검증 유지 + Certificate Pinning\nval pinner = CertificatePinner.Builder()\n    .add("bank.example.com", "sha256/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")\n    .build()\nval client = OkHttpClient.Builder()\n    .certificatePinner(pinner)            // 인증서 핀 고정\n    .build()                              // 기본 TrustManager/호스트명 검증 유지',
 'checks':[['CertificatePinner','certificatePinner'],['certificatePinner','pinner','신뢰체인']],
 'success_msg':'기본 신뢰체인 검증을 유지하고 Certificate Pinning을 적용해 MITM 인증서가 차단됩니다.',
 'fail_msg':'TrustManager를 무력화하지 말고 기본 인증서 검증 유지 + Certificate Pinning을 적용해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>통신 보안 &gt; <b>서버 인증서 무결성 검증</b><h4>2. 위험 분석</h4><ul><li>인증서 미검증 시 MITM 프록시 인증서 수용</li><li>거래정보·자격증명 탈취 및 변조</li></ul><h4>3. 조치 방법</h4><ul><li>기본 <b>신뢰체인·호스트명 검증</b> 유지</li><li><b>Certificate Pinning</b>으로 인증서 고정</li><li>모든 인증서를 신뢰하는 <b>TrustManager 무력화 금지</b></li></ul>',
 'easy':'아무 도장이나 찍힌 신분증을 그냥 믿으면, 위조 신분증을 든 사람이 본인 행세를 합니다. 진짜 <b>발급기관의 도장</b>인지 끝까지 확인하고, 미리 받아둔 <b>지문(핀)</b>과 같은지까지 맞춰봐야 합니다.',
},
{
 'file':'07_fin-system-info-leak.html',
 'title':'시스템 운영정보 노출 방지',
 'icon':'🕵️', 'target':'웹 서버 응답/에러 페이지', 'risk':'4', 'item_code':'WEB-SER 시스템 운영정보 노출(031)',
 'attack_panel_title':'서버 응답 정보 수집',
 'scenario_html':'에러 페이지·응답 헤더(<b>Server</b>, <b>X-Powered-By</b>)·<b>스택트레이스</b>로 서버 종류·버전·내부 경로가 그대로 노출되면, 공격자가 해당 버전의 <b>알려진 취약점</b>을 골라 표적 공격에 활용할 수 있습니다.',
 'attack_name':'운영정보 핑거프린팅', 'attack_sub':'헤더·에러페이지로 서버 종류·버전·경로 수집',
 'normal_req':'GET /info HTTP/1.1\nHost: bank.example.com\n# 정상: 운영정보 비노출, 표준 에러만 반환',
 'attack_req':'GET /not-exist HTTP/1.1\nHost: bank.example.com\n\n--- 응답에서 운영정보 노출 ---\nHTTP/1.1 500 Internal Server Error\nServer: Apache/2.4.49 (Unix)\nX-Powered-By: PHP/7.4.3\n\njava.lang.NullPointerException\n    at com.bank.pay.Service.charge(Service.java:88)\n    at /opt/bankapp/WEB-INF/classes/...   <-- 내부 경로 노출',
 'vuln_logs_js':"addLog('[SCAN] 응답 헤더 수집: Server, X-Powered-By','warn'); addLog('[FINGERPRINT] Apache 2.4.49 / PHP 7.4.3 버전 식별','error'); addLog('[ERROR] 스택트레이스에서 내부 경로/클래스 노출','error'); addLog('[ATTACK] 식별 버전 대상 알려진 취약점 표적 공격','error');",
 'breach_html':'<strong>🚨 운영정보 노출 → 표적 공격</strong><br>응답 헤더와 에러 페이지로 서버 종류·버전·내부 경로가 그대로 드러나 공격자가 맞춤형 익스플로잇을 선택했습니다.<table class="data-table"><tr><th>노출 항목</th><th>값</th></tr><tr><td>Server</td><td style="color:#b71c1c">Apache/2.4.49 (Unix)</td></tr><tr><td>X-Powered-By</td><td style="color:#b71c1c">PHP/7.4.3</td></tr><tr><td>내부 경로</td><td style="color:#b71c1c">/opt/bankapp/WEB-INF/...</td></tr></table>',
 'violations':['평가기준 [전자금융] 시스템 운영정보 노출 방지(위험도 4)',
               '정보 노출(Information Exposure) / 불충분한 오류 처리(IN)',
               '전자금융감독규정 제15조: 시스템 정보 보호 미흡'],
 'defense_intro':'서버 종류·버전 헤더를 <strong>숨기고</strong>, 상세 오류를 사용자에게 노출하지 말고 <strong>커스텀 에러 페이지</strong>로 표준 메시지만 반환해야 합니다. 스택트레이스·내부 경로는 <strong>로그에만 기록</strong>합니다. 설정을 보완하세요.',
 'vuln_code':'# [취약] 서버 버전 헤더 노출 + 상세 에러 노출 (nginx)\nserver {\n    # 버전 헤더 숨김 미설정 → Server/X-Powered-By 노출\n    location / {\n        proxy_pass http://app;\n        # 에러 시 스택트레이스 그대로 출력\n    }\n}',
 'secure_hint':'# [안전] 서버 토큰 숨김 + 커스텀 에러페이지 (nginx)\nserver {\n    server_tokens off;              # Server 버전 헤더 숨김\n    proxy_hide_header X-Powered-By; # 프레임워크 헤더 제거\n    error_page 500 502 503 /custom_error.html;  # 표준 에러만 노출\n    location = /custom_error.html { internal; }   # 상세 오류 비노출\n}',
 'checks':[['server_tokens'],['custom_error','error_page','proxy_hide_header']],
 'success_msg':'서버 토큰을 숨기고 커스텀 에러 페이지로 상세 오류를 가려 운영정보 노출이 차단됩니다.',
 'fail_msg':'server_tokens off와 커스텀 에러 페이지로 서버 버전·상세 오류 노출을 막아야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>서버 보안 &gt; <b>시스템 운영정보 노출 방지</b><h4>2. 위험 분석</h4><ul><li>헤더·에러로 서버 종류·버전 식별</li><li>버전 기반 알려진 취약점 표적 공격</li><li>스택트레이스로 내부 경로 노출</li></ul><h4>3. 조치 방법</h4><ul><li>서버/프레임워크 <b>버전 헤더 숨김</b></li><li><b>커스텀 에러 페이지</b>로 표준 메시지만 반환</li><li>스택트레이스·상세 오류는 <b>로그에만 기록</b></li></ul>',
 'easy':'우리 집 현관에 <b>금고 모델명과 비밀번호 힌트</b>를 붙여두면, 도둑이 그 모델 약점만 골라 노려옵니다. 서버도 <b>종류·버전·내부 경로</b>를 숨기고 손님에겐 <b>깔끔한 안내문</b>만 보여줘야 합니다.',
},
{
 'file':'07_fin-web-methods.html',
 'title':'불필요한 웹 메서드 차단',
 'icon':'🚫', 'target':'웹 서버 HTTP 메서드 허용 설정', 'risk':'4', 'item_code':'WEB-SER 불필요 웹 메서드(038)',
 'attack_panel_title':'HTTP 메서드 점검',
 'scenario_html':'서버가 <b>PUT/DELETE/TRACE</b> 등 불필요한 HTTP 메서드를 허용하면, 공격자가 <b>PUT으로 웹셸을 업로드</b>하거나 <b>DELETE로 파일을 삭제</b>하고, <b>TRACE</b>를 악용한 <b>XST(Cross-Site Tracing)</b>로 쿠키를 탈취할 수 있습니다.',
 'attack_name':'위험 메서드 악용(PUT/TRACE)', 'attack_sub':'PUT로 웹셸 업로드 · TRACE로 XST',
 'normal_req':'OPTIONS / HTTP/1.1\nHost: bank.example.com\n\n--- 응답 ---\nHTTP/1.1 200 OK\nAllow: GET, POST, PUT, DELETE, TRACE, OPTIONS   <-- 위험 메서드 허용',
 'attack_req':'# 1) PUT으로 웹셸 업로드\nPUT /shell.jsp HTTP/1.1\nHost: bank.example.com\nContent-Type: application/x-jsp\n\n<% Runtime.getRuntime().exec(request.getParameter("c")); %>\n\n# 2) TRACE로 XST → 요청 헤더(쿠키) 반사\nTRACE / HTTP/1.1\nHost: bank.example.com\nCookie: JSESSIONID=ABC123',
 'vuln_logs_js':"addLog('[OPTIONS] Allow 헤더에 PUT/DELETE/TRACE 노출','warn'); addLog('[PUT] /shell.jsp 업로드 성공 → 웹셸 배치','error'); addLog('[TRACE] 요청 헤더 그대로 반사 → XST로 쿠키 노출','error'); addLog('[RCE] 업로드한 웹셸로 시스템 명령 실행','error');",
 'breach_html':'<strong>🚨 위험 메서드 악용 성공</strong><br>PUT 허용으로 웹셸이 업로드되고 TRACE 허용으로 XST 쿠키 탈취가 가능했습니다.<table class="data-table"><tr><th>메서드</th><th>악용 결과</th></tr><tr><td>PUT</td><td style="color:#b71c1c">/shell.jsp 업로드 → RCE</td></tr><tr><td>DELETE</td><td style="color:#b71c1c">임의 파일 삭제</td></tr><tr><td>TRACE</td><td style="color:#b71c1c">XST 쿠키 반사</td></tr></table>',
 'violations':['평가기준 [전자금융] 불필요한 웹 메서드 차단(위험도 4)',
               '부적절한 HTTP 메서드 허용 / XST 노출(IN)',
               '전자금융감독규정 제15조: 서버 설정 보안 미흡'],
 'defense_intro':'서버는 서비스에 필요한 <strong>GET/POST 메서드만 허용</strong>하고 <strong>TRACE/PUT/DELETE 등 불필요한 메서드는 비활성화</strong>해야 합니다. 메서드 제한 설정을 보완하세요.',
 'vuln_code':'# [취약] 모든 HTTP 메서드 허용 (web.xml)\n<security-constraint>\n    <web-resource-collection>\n        <web-resource-name>all</web-resource-name>\n        <url-pattern>/*</url-pattern>\n        <!-- http-method 제한 없음 → PUT/DELETE/TRACE 허용 -->\n    </web-resource-collection>\n</security-constraint>',
 'secure_hint':'# [안전] 허용 메서드 제한 + TRACE/PUT/DELETE 차단 (web.xml)\n<security-constraint>\n    <web-resource-collection>\n        <web-resource-name>restrict</web-resource-name>\n        <url-pattern>/*</url-pattern>\n        <http-method-omission>GET</http-method-omission>\n        <http-method-omission>POST</http-method-omission>\n    </web-resource-collection>\n    <auth-constraint/>  <!-- GET/POST 외 모든 메서드 차단(TRACE/PUT/DELETE) -->\n</security-constraint>\n<!-- allowedMethods: GET, POST 만 허용 -->',
 'checks':[['allowedMethods','http-method-omission'],['TRACE','auth-constraint']],
 'success_msg':'GET/POST만 허용하고 TRACE/PUT/DELETE를 차단해 위험 메서드 악용이 막힙니다.',
 'fail_msg':'허용 메서드를 GET/POST로 제한하고 TRACE/PUT/DELETE를 비활성화해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>서버 보안 &gt; <b>불필요한 웹 메서드 차단</b><h4>2. 위험 분석</h4><ul><li>PUT으로 웹셸 업로드 → 원격 코드 실행</li><li>DELETE로 임의 파일 삭제</li><li>TRACE 악용 XST로 쿠키 탈취</li></ul><h4>3. 조치 방법</h4><ul><li>서비스 필요한 <b>GET/POST만 허용</b></li><li><b>TRACE/PUT/DELETE</b> 등 비활성화</li><li>OPTIONS <b>Allow 헤더</b> 점검·최소화</li></ul>',
 'easy':'건물에 <b>모든 출입문</b>을 다 열어두면, 짐 넣는 문으로 폭탄을 들여오거나 살림을 통째로 들어낼 수 있습니다. 꼭 필요한 <b>정문(GET/POST)</b>만 열고 나머지 문은 잠가야 합니다.',
},
{
 'file':'07_fin-admin-access.html',
 'title':'관리자 페이지 접근 통제',
 'icon':'🛡️', 'target':'관리자 페이지(/admin)', 'risk':'5', 'item_code':'WEB-SER 관리자 페이지 접근통제(039)',
 'attack_panel_title':'관리자 페이지 접근',
 'scenario_html':'관리자 페이지(<b>/admin</b> 등)가 추측 가능한 경로에 <b>인증·IP 통제 없이</b> 노출되면, 공격자가 <b>기본계정(admin/admin)</b>이나 <b>무차별 대입</b>으로 관리 기능에 그대로 접근할 수 있습니다.',
 'attack_name':'관리자 페이지 무단 접근', 'attack_sub':'추측 경로 + 기본계정/무차별 대입',
 'normal_req':'GET /admin HTTP/1.1\nHost: bank.example.com\n# 정상: 인증·권한·허용 IP 검사 후에만 접근',
 'attack_req':'# 추측 가능한 경로로 직접 접근\nGET /admin HTTP/1.1\nHost: bank.example.com\n\n# 기본계정 로그인 시도\nPOST /admin/login HTTP/1.1\n{\n  "username": "admin",\n  "password": "admin"   <-- 기본계정/무차별 대입\n}',
 'vuln_logs_js':"addLog('[SCAN] 추측 경로 /admin 노출 확인','warn'); addLog('[AUTH] 권한·허용 IP 검사 없음','error'); addLog('[BRUTE] admin/admin 기본계정 로그인 성공','error'); addLog('[ADMIN] 관리 콘솔 진입 → 계정/거래 조작','error');",
 'breach_html':'<strong>🚨 관리자 페이지 탈취</strong><br>경로 추측과 기본계정으로 인증·IP 통제 없는 관리자 페이지에 진입해 관리 기능이 그대로 노출되었습니다.<table class="data-table"><tr><th>항목</th><th>값</th></tr><tr><td>경로</td><td style="color:#b71c1c">/admin (추측 가능)</td></tr><tr><td>계정</td><td style="color:#b71c1c">admin / admin</td></tr><tr><td>접근 IP</td><td style="color:#b71c1c">제한 없음</td></tr></table>',
 'violations':['평가기준 [전자금융] 관리자 페이지 접근통제(위험도 5)',
               '부적절한 접근통제 / 기본계정·인증 부재(IN)',
               '전자금융감독규정 제15조: 관리자 접근통제 미흡'],
 'defense_intro':'관리자 페이지는 진입 시 <strong>인증·권한(관리자 역할) 검사</strong>를 강제하고, <strong>허용 IP 대역으로 접근을 제한</strong>하며, <strong>경로 추측 방지·기본계정 제거</strong>를 적용해야 합니다. 접근통제 설정을 보완하세요.',
 'vuln_code':'// [취약] 인증·권한·IP 검사 없이 관리자 페이지 제공\n@GetMapping("/admin")\npublic String adminConsole(HttpServletRequest req) {\n    // 인증/권한/IP 확인 없음 → 누구나 접근\n    return "admin/console";\n}',
 'secure_hint':'// [안전] 권한 검사 + 허용 IP 제한 + 추측 방지 경로\n@GetMapping("/secure-admin-x91")           // 경로 추측 방지\npublic String adminConsole(HttpServletRequest req, Authentication auth) {\n    if (!auth.hasRole("ADMIN"))             // 관리자 권한 검사\n        throw new AccessDeniedException("권한 없음");\n    if (!ipAllowlist.contains(req.getRemoteAddr())) // 허용 IP 제한\n        throw new AccessDeniedException("허용되지 않은 IP");\n    return "admin/console";\n}',
 'checks':[['hasRole','requireRole'],['ipAllowlist','getRemoteAddr','허용 IP']],
 'success_msg':'관리자 권한 검사와 허용 IP 제한, 추측 방지 경로로 무단 접근이 차단됩니다.',
 'fail_msg':'관리자 페이지에 권한(hasRole) 검사와 허용 IP 제한을 적용해야 합니다.',
 'kisa_ref':'<h4>1. 점검 항목</h4>접근 통제 &gt; <b>관리자 페이지 접근 통제</b><h4>2. 위험 분석</h4><ul><li>추측 가능한 경로로 관리자 페이지 노출</li><li>기본계정·무차별 대입으로 무단 접근</li><li>관리 기능을 통한 계정·거래 조작</li></ul><h4>3. 조치 방법</h4><ul><li>진입 시 <b>인증·관리자 권한 검사</b> 강제</li><li>접근 <b>허용 IP 대역 제한</b></li><li><b>경로 추측 방지</b> 및 기본계정 제거</li></ul>',
 'easy':'은행 <b>관리실 문</b>을 누구나 아는 자리에 두고 잠그지도 않으면, 아무나 들어가 금고를 엽니다. 문 위치를 숨기고 <b>출입증(권한)</b>과 <b>허가된 사람의 위치(IP)</b>까지 확인해야 합니다.',
},
]
