# -*- coding: utf-8 -*-
DYN = {
 'C-01': {
   'easy': '루트 계정은 <b>건물 마스터키</b>입니다. 비밀번호 하나만 알면 모든 문을 엽니다. MFA는 마스터키에 <b>두 번째 잠금</b>을 다는 것이라, 비밀번호가 새도 두 번째 잠금 없이는 못 들어옵니다.',
   'attack_label': '유출된 비밀번호로 루트 콘솔에 로그인한다',
   'attack_vuln': [
     ['cmt', '# 유출 DB에서 구한 루트 비밀번호로 로그인'],
     ['prompt', 'attacker$ 콘솔 로그인 root@company.com'],
     ['', '비밀번호 입력 ...'],
     ['bad', '>> 2차 인증 요구 없음 — 바로 로그인'],
     ['bad', '>> 전체 클라우드 장악 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 전체 장악','desc':'MFA가 없어 비밀번호 유출만으로 루트 권한을 얻습니다.'},
   'attack_secure': [
     ['cmt', '# 동일 비밀번호로 로그인 시도'],
     ['prompt', 'attacker$ 콘솔 로그인 root@company.com'],
     ['good', '>> 비밀번호 통과 후 MFA 코드 요구'],
     ['warn', '>> 2차 인증 없어 로그인 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 2차 인증','desc':'비밀번호가 새도 MFA 기기가 없으면 들어올 수 없습니다.'},
 },
 'C-02': {
   'easy': '관리자 권한은 <b>만능 출입증</b>입니다. 모두에게 만능 출입증을 주면, 한 명만 도둑맞아도 전부 털립니다. 최소 권한은 <b>필요한 방 열쇠만</b> 주는 것이라 피해가 그 방에 그칩니다.',
   'attack_label': '탈취한 개발자 키로 새 관리자 계정을 만든다',
   'attack_vuln': [
     ['cmt', '# 개발자 키 하나를 탈취한 상태'],
     ['prompt', 'attacker$ aws iam create-user --user-name backdoor'],
     ['', '권한이 AdministratorAccess 라 무엇이든 가능'],
     ['bad', '>> aws iam attach-user-policy AdministratorAccess'],
     ['bad', '>> 백도어 관리자 생성 — 전체 탈취'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 권한 확장','desc':'키 하나에 관리자 권한이 있어 무엇이든 만들 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일 키로 사용자 생성 시도'],
     ['prompt', 'attacker$ aws iam create-user --user-name backdoor'],
     ['good', '>> AccessDenied: iam 권한 없음'],
     ['warn', '>> S3 읽기 권한뿐이라 확장 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 최소 권한','desc':'필요한 권한만 있어 키가 새도 피해 범위가 좁습니다.'},
 },
 'C-03': {
   'easy': '액세스 키는 <b>집 열쇠</b>인데, 코드에 적어 깃허브에 올리면 <b>열쇠를 길에 떨어뜨린</b> 셈입니다. 봇이 공개 저장소를 뒤져 줍는 순간 바로 침입합니다. 키는 금고에 넣고 주기적으로 바꿔야 합니다.',
   'attack_label': '공개 깃허브에서 액세스 키를 주워 바로 사용한다',
   'attack_vuln': [
     ['cmt', '# 봇이 공개 저장소에서 AKIA 키를 발견'],
     ['prompt', 'attacker$ git clone 공개저장소 ; grep AKIA'],
     ['bad', '>> AKIAIOSFODNN7EXAMPLE 발견 (700일 미교체)'],
     ['prompt', 'attacker$ aws s3 ls'],
     ['bad', '>> 버킷 목록 노출 — 데이터 탈취 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 키 악용','desc':'노출된 장기 키로 즉시 자원에 접근합니다.'},
   'attack_secure': [
     ['cmt', '# 같은 키를 주웠지만 이미 교체됨'],
     ['prompt', 'attacker$ aws s3 ls'],
     ['good', '>> InvalidAccessKeyId: 키 비활성화됨'],
     ['warn', '>> 90일 교체 + Vault 관리라 무효'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 키 무효','desc':'키가 주기적으로 교체되어 노출돼도 쓸 수 없습니다.'},
 },
 'C-04': {
   'easy': '퇴직자 출입증을 회수하지 않으면 <b>옛 직원이 언제든 들어올</b> 수 있습니다. 미사용 계정과 키는 잊혀진 <b>뒷문 열쇠</b>라, 아무도 안 보는 사이 침입 통로가 됩니다.',
   'attack_label': '방치된 퇴직자 계정 키로 조용히 침입한다',
   'attack_vuln': [
     ['cmt', '# 200일 미사용 계정 키를 입수'],
     ['prompt', 'attacker$ aws sts get-caller-identity'],
     ['bad', '>> user old-dev 유효 — 아무도 안 봄'],
     ['prompt', 'attacker$ aws s3 cp s3://data ./'],
     ['bad', '>> 데이터 반출 성공 (탐지 안 됨)'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 잠입','desc':'방치된 자격증명이 살아 있어 조용히 악용됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일 계정 사용 시도'],
     ['prompt', 'attacker$ aws sts get-caller-identity'],
     ['good', '>> 계정이 비활성화됨 (정리 완료)'],
     ['warn', '>> 미사용 자격증명 삭제로 통로 차단'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 통로 제거','desc':'미사용 계정을 정리해 뒷문이 사라졌습니다.'},
 },
 'C-05': {
   'easy': '퍼블릭 버킷은 <b>비밀번호 없는 공개 사물함</b>입니다. 주소만 알면 누구나 열어 안의 파일을 가져갑니다. 퍼블릭 차단은 사물함에 <b>자물쇠</b>를 채우는 것입니다.',
   'attack_label': '서명 없이 익명으로 버킷 데이터를 내려받는다',
   'attack_vuln': [
     ['cmt', '# 인증 없이 버킷 접근 시도'],
     ['prompt', 'attacker$ aws s3 ls s3://company-data --no-sign-request'],
     ['bad', '>> customers.csv  backups.zip 목록 노출'],
     ['prompt', 'attacker$ aws s3 cp s3://company-data/customers.csv ./ --no-sign-request'],
     ['bad', '>> 익명 다운로드 성공 — 고객정보 유출'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 익명 유출','desc':'퍼블릭 설정이라 인증 없이 데이터를 가져갑니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 익명 접근 시도'],
     ['prompt', 'attacker$ aws s3 ls s3://company-data --no-sign-request'],
     ['good', '>> AccessDenied (퍼블릭 차단됨)'],
     ['warn', '>> 서명된 요청만 허용 — 익명 거부'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 접근 거부','desc':'Block Public Access로 익명 다운로드를 막습니다.'},
 },
 'C-06': {
   'easy': '암호화 없는 저장소는 <b>유리 금고</b>와 같습니다. 디스크나 스냅샷을 훔치면 안의 내용이 그대로 보입니다. 저장 암호화는 내용을 <b>해독 불가 암호문</b>으로 바꿔, 훔쳐도 읽지 못하게 합니다.',
   'attack_label': '백업 스냅샷을 빼내 저장된 평문 데이터를 읽는다',
   'attack_vuln': [
     ['cmt', '# 잘못 공유된 스냅샷을 볼륨으로 복원'],
     ['prompt', 'attacker$ 스냅샷 복원 후 디스크 마운트'],
     ['bad', '>> ServerSideEncryption: none (평문 저장)'],
     ['prompt', 'attacker$ cat 마운트한_디스크/db.dump'],
     ['bad', '>> 평문 그대로 읽힘 — 데이터 유출'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 평문 노출','desc':'암호화가 없어 디스크만 손에 넣으면 다 읽힙니다.'},
   'attack_secure': [
     ['cmt', '# 동일 디스크를 마운트해 읽기 시도'],
     ['prompt', 'attacker$ cat 마운트한_디스크/db.dump'],
     ['good', '>> a3 f1 9c ... (KMS 암호문)'],
     ['warn', '>> KMS 키 없이 해독 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 해독 실패','desc':'SSE-KMS 암호화로 디스크를 훔쳐도 읽을 수 없습니다.'},
 },
 'C-07': {
   'easy': '퍼블릭 스냅샷은 <b>회사 캐비닛 사본을 길거리에 둔</b> 것과 같습니다. 안에 든 데이터와 키까지 통째로 복제됩니다. 공유 범위를 제한하면 필요한 사람만 사본을 받습니다.',
   'attack_label': '퍼블릭 공유된 스냅샷을 복제해 내부 데이터를 캔다',
   'attack_vuln': [
     ['cmt', '# 퍼블릭 스냅샷을 검색해 발견'],
     ['prompt', 'attacker$ aws ec2 describe-snapshots --restorable-by-user-ids all'],
     ['bad', '>> snap-123 createVolumePermission: all'],
     ['prompt', 'attacker$ 스냅샷 복원 후 디스크 탐색'],
     ['bad', '>> 내부 설정과 자격증명 추출 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 디스크 복제','desc':'퍼블릭 공유라 누구나 스냅샷을 복원해 캡니다.'},
   'attack_secure': [
     ['cmt', '# 동일 스냅샷 접근 시도'],
     ['prompt', 'attacker$ aws ec2 describe-snapshots --restorable-by-user-ids all'],
     ['good', '>> 목록에 없음 (private 전환)'],
     ['warn', '>> 허가된 계정만 접근 가능'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 비공개','desc':'스냅샷을 비공개로 돌려 외부 복제를 막습니다.'},
 },
 'C-08': {
   'easy': '0.0.0.0/0 개방은 <b>대문을 활짝 열고 전 세계에 초대장</b>을 돌린 셈입니다. 인터넷 누구나 모든 문을 두드릴 수 있습니다. 출발지 제한은 <b>아는 사람만 들이는</b> 초인종 명단입니다.',
   'attack_label': '인터넷에서 전체 개방된 포트를 스캔해 침투한다',
   'attack_vuln': [
     ['cmt', '# 전체 개방 보안그룹의 서버를 스캔'],
     ['prompt', 'attacker$ nmap -p- 203.0.113.10'],
     ['bad', '>> 0.0.0.0/0 -> ALL ports 열림'],
     ['bad', '>> 노출된 서비스로 침투 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 무차별 침투','desc':'모든 포트가 열려 인터넷 어디서든 들어옵니다.'},
   'attack_secure': [
     ['cmt', '# 동일 서버를 스캔'],
     ['prompt', 'attacker$ nmap -p- 203.0.113.10'],
     ['good', '>> 모든 포트 filtered (응답 없음)'],
     ['warn', '>> 허용 대역 밖이라 접근 거부'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 대역 제한','desc':'필요한 출발지만 허용해 외부 스캔이 막힙니다.'},
 },
 'C-09': {
   'easy': 'SSH/RDP를 인터넷에 열면 <b>현관 비밀번호를 무한히 시도</b>할 수 있는 도둑을 부르는 격입니다. 봇이 흔한 비밀번호를 끝없이 넣습니다. Bastion 경유는 <b>경비실을 거쳐야</b> 현관에 닿게 합니다.',
   'attack_label': '노출된 SSH 포트에 무차별 대입으로 로그인한다',
   'attack_vuln': [
     ['cmt', '# 인터넷에 열린 22번 포트를 공격'],
     ['prompt', 'attacker$ hydra -l root -P rockyou.txt ssh://203.0.113.10'],
     ['bad', '>> 0.0.0.0/0 -> 22 개방 (직접 접근)'],
     ['bad', '>> 비밀번호 적중 — 셸 획득 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 셸 획득','desc':'관리 포트가 노출돼 무차별 대입으로 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일 포트로 대입 시도'],
     ['prompt', 'attacker$ hydra -l root -P rockyou.txt ssh://203.0.113.10'],
     ['good', '>> connection timed out (직접 노출 없음)'],
     ['warn', '>> Bastion/SSM 경유만 허용'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 경유 강제','desc':'관리 포트를 직접 열지 않아 대입 자체가 막힙니다.'},
 },
 'C-10': {
   'easy': '내부 서버에 퍼블릭 IP를 붙이는 건 <b>창고 뒷방에 길가 출입문</b>을 내는 것과 같습니다. 굳이 밖에서 보일 필요 없는 자원이 표적이 됩니다. 프라이빗 전환은 출입문을 <b>건물 안쪽</b>으로만 두는 것입니다.',
   'attack_label': '퍼블릭 IP가 붙은 내부 DB 서버를 직접 노린다',
   'attack_vuln': [
     ['cmt', '# 내부용 DB가 퍼블릭 IP로 노출됨'],
     ['prompt', 'attacker$ nmap 3.12.34.56 -p 3306'],
     ['bad', '>> db-server PublicIp 3.12.34.56 응답'],
     ['bad', '>> 외부에서 DB 포트 직접 도달 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 직접 노출','desc':'내부 자원이 퍼블릭 IP로 인터넷에 드러납니다.'},
   'attack_secure': [
     ['cmt', '# 동일 서버를 찾으려 시도'],
     ['prompt', 'attacker$ nmap 3.12.34.56 -p 3306'],
     ['good', '>> 해당 IP 없음 (프라이빗 전환)'],
     ['warn', '>> 외부에서 도달 경로 없음'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 내부 격리','desc':'퍼블릭 IP를 제거해 외부 표적에서 사라집니다.'},
 },
 'C-11': {
   'easy': '감사 로그가 없으면 <b>CCTV 없는 은행</b>과 같습니다. 도둑이 무엇을 했는지 추적할 수 없습니다. CloudTrail은 모든 출입과 행동을 기록하는 <b>녹화 카메라</b>입니다.',
   'attack_label': '로그가 없는 틈을 타 흔적 없이 자원을 조작한다',
   'attack_vuln': [
     ['cmt', '# 감사 로깅이 꺼진 계정에 침입'],
     ['prompt', 'attacker$ aws cloudtrail describe-trails'],
     ['bad', '>> trail: none (기록 없음)'],
     ['prompt', 'attacker$ aws ec2 run-instances ... (채굴기 가동)'],
     ['bad', '>> 흔적 없이 자원 탈취 — 추적 불가'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 추적 불가','desc':'기록이 없어 침해 행위를 되짚을 수 없습니다.'},
   'attack_secure': [
     ['cmt', '# 동일 조작을 시도'],
     ['prompt', 'attacker$ aws ec2 run-instances ...'],
     ['good', '>> CloudTrail에 호출 전부 기록됨'],
     ['warn', '>> SIEM 경보 발생 — 즉시 탐지'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 행위 추적','desc':'전 리전 로깅으로 모든 조작이 남아 탐지됩니다.'},
 },
 'C-12': {
   'easy': '무결성 없는 로그는 <b>연필로 쓴 출입대장</b>입니다. 침입자가 자기 기록을 지우개로 지울 수 있죠. 무결성 검증과 WORM 보관은 대장을 <b>지울 수 없는 잉크</b>로 봉인합니다.',
   'attack_label': '침입 후 자기 흔적을 로그에서 지운다',
   'attack_vuln': [
     ['cmt', '# 침입자가 로그 위변조를 시도'],
     ['prompt', 'attacker$ aws cloudtrail get-trail-status'],
     ['bad', '>> LogFileValidation: false'],
     ['prompt', 'attacker$ 로그 객체 삭제/수정'],
     ['bad', '>> 흔적 삭제 성공 — 사고 분석 불가'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 증거 인멸','desc':'무결성 보호가 없어 로그를 지우고 수정합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 로그 변조 시도'],
     ['prompt', 'attacker$ 로그 객체 삭제/수정'],
     ['good', '>> 객체 잠금(WORM)으로 삭제 거부'],
     ['warn', '>> 변조 시 validation 불일치 탐지'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 변조 탐지','desc':'무결성 검증과 WORM으로 증거가 보존됩니다.'},
 },
 'C-13': {
   'easy': '특권 컨테이너는 <b>호스트라는 건물 전체 마스터키</b>를 방 안에 둔 격입니다. 방(컨테이너) 안 침입자가 그 키로 건물(호스트)을 통째로 장악합니다. 특권 제거는 방을 건물과 <b>완전히 격리</b>합니다.',
   'attack_label': '특권 컨테이너에서 호스트로 탈출한다',
   'attack_vuln': [
     ['cmt', '# 침해된 특권 파드 안에서'],
     ['prompt', 'attacker$ cat /proc/1/status | grep privileged'],
     ['bad', '>> privileged: true (호스트 장치 접근)'],
     ['prompt', 'attacker$ 호스트 파일시스템 마운트 후 조회'],
     ['bad', '>> 호스트 etc shadow 읽기 — 탈출 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 컨테이너 탈출','desc':'특권 권한으로 호스트 파일시스템까지 장악합니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 탈출 시도'],
     ['prompt', 'attacker$ 호스트 파일시스템 마운트 시도'],
     ['good', '>> Operation not permitted (drop ALL)'],
     ['warn', '>> 비루트 + 권한 격리로 차단'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 권한 격리','desc':'특권을 제거해 컨테이너가 호스트에 닿지 못합니다.'},
 },
 'C-14': {
   'easy': '취약점 스캔 없는 이미지는 <b>유통기한 안 보고 먹는 음식</b>입니다. 상한 라이브러리가 들어 있어도 모르고 배포합니다. 스캔 게이트는 배포 전 <b>위생 검사</b>를 강제합니다.',
   'attack_label': '패치 안 된 라이브러리의 알려진 취약점을 노린다',
   'attack_vuln': [
     ['cmt', '# 배포된 이미지의 CVE를 확인'],
     ['prompt', 'attacker$ trivy image myapp:1.0'],
     ['bad', '>> CRITICAL 14건 (원격 코드 실행 가능)'],
     ['prompt', 'attacker$ 공개 익스플로잇 실행'],
     ['bad', '>> 취약 라이브러리로 침투 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 알려진 CVE','desc':'스캔을 안 해 취약한 이미지가 그대로 노출됩니다.'},
   'attack_secure': [
     ['cmt', '# 배포 단계에서 스캔 게이트 동작'],
     ['prompt', 'cloud$ trivy image --exit-code 1 --severity CRITICAL'],
     ['good', '>> CRITICAL 발견 — 배포 중단'],
     ['warn', '>> 취약 이미지가 운영에 못 나감'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 배포 차단','desc':'스캔 게이트가 취약 이미지를 사전에 막습니다.'},
 },
 'C-15': {
   'easy': '환경변수에 비밀번호를 두는 건 <b>금고 비밀번호를 포스트잇으로 붙인</b> 격입니다. 이미지 한 겹만 들춰도 보입니다. 시크릿 관리도구는 비밀을 <b>잠긴 별도 금고</b>에 넣어 주입합니다.',
   'attack_label': '이미지 레이어와 프로세스에서 DB 비밀번호를 캔다',
   'attack_vuln': [
     ['cmt', '# 공개된 이미지의 레이어를 조사'],
     ['prompt', 'attacker$ docker history myapp:1.0'],
     ['bad', '>> ENV DB_PASSWORD=P@ssw0rd! (평문)'],
     ['prompt', 'attacker$ printenv'],
     ['bad', '>> 비밀번호 추출 — DB 접속 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 시크릿 유출','desc':'평문 환경변수라 이미지만 받아도 비밀번호가 보입니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 레이어/환경변수 조회'],
     ['prompt', 'attacker$ docker history myapp:1.0 ; printenv'],
     ['good', '>> DB_PASSWORD 없음 (Vault 주입)'],
     ['warn', '>> 시크릿은 런타임에만 메모리 존재'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 비밀 은닉','desc':'Secret/Vault로 주입해 이미지에 평문이 남지 않습니다.'},
 },
 'C-16': {
   'easy': 'cluster-admin은 클러스터의 <b>만능 마스터키</b>입니다. 파드 하나가 뚫려 그 키를 쥐면 클러스터 전체가 넘어갑니다. 최소 권한은 <b>자기 방 열쇠만</b> 줘 피해를 가둡니다.',
   'attack_label': '침해된 파드 토큰으로 전체 시크릿을 훔친다',
   'attack_vuln': [
     ['cmt', '# 침해된 파드의 서비스계정 토큰 사용'],
     ['prompt', 'attacker$ kubectl auth can-i get secrets --all-namespaces'],
     ['bad', '>> yes (default SA -> cluster-admin)'],
     ['prompt', 'attacker$ kubectl get secrets --all-namespaces'],
     ['bad', '>> 전체 시크릿 탈취 — 클러스터 장악'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 클러스터 장악','desc':'과도한 RBAC로 파드 하나가 전체를 털 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 동일 토큰으로 시크릿 조회 시도'],
     ['prompt', 'attacker$ kubectl get secrets --all-namespaces'],
     ['good', '>> Forbidden: 권한 없음'],
     ['warn', '>> 네임스페이스 한정 Role만 부여'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 권한 격리','desc':'최소 권한이라 파드가 뚫려도 피해가 한정됩니다.'},
 },
 'C-17': {
   'easy': 'API 서버 익명 접근은 <b>관제실 문을 잠그지 않은</b> 것과 같습니다. 아무나 들어와 클러스터를 조종합니다. 익명 차단과 RBAC는 관제실에 <b>신분증 검사</b>를 세웁니다.',
   'attack_label': '인증 없이 K8s API 서버를 익명으로 조회한다',
   'attack_vuln': [
     ['cmt', '# 인터넷에 노출된 API 서버에 익명 요청'],
     ['prompt', 'attacker$ curl -k https://api:6443/api/v1/pods'],
     ['bad', '>> 200 OK (익명 조회 성공)'],
     ['prompt', 'attacker$ curl -k .../api/v1/secrets'],
     ['bad', '>> 클러스터 정보 노출 — 조작 가능'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 익명 접근','desc':'익명 인증이 켜져 비인가자가 클러스터를 봅니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 익명 요청 시도'],
     ['prompt', 'attacker$ curl -k https://api:6443/api/v1/pods'],
     ['good', '>> 401 Unauthorized'],
     ['warn', '>> anonymous-auth=false + RBAC로 거부'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 인증 강제','desc':'익명 접근을 끄고 RBAC로 신원을 요구합니다.'},
 },
 'C-18': {
   'easy': 'hostPath와 hostPID 공유는 방(컨테이너)에 <b>건물 복도로 통하는 비밀문</b>을 내는 격입니다. 침입자가 그 문으로 호스트 파일과 프로세스에 닿습니다. 공유 제거는 비밀문을 <b>벽으로 막습니다</b>.',
   'attack_label': '호스트 경로 공유를 통해 호스트 자원에 접근한다',
   'attack_vuln': [
     ['cmt', '# 호스트 루트가 마운트된 파드 안에서'],
     ['prompt', 'attacker$ kubectl get pod -o yaml | grep hostPath'],
     ['bad', '>> hostPath: / , hostPID: true'],
     ['prompt', 'attacker$ 마운트된 호스트 경로 탐색'],
     ['bad', '>> 호스트 파일/프로세스 접근 — 탈출 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 호스트 접근','desc':'호스트 공유로 컨테이너가 노드 자원에 닿습니다.'},
   'attack_secure': [
     ['cmt', '# 동일 파드에서 호스트 접근 시도'],
     ['prompt', 'attacker$ 호스트 경로 탐색 시도'],
     ['good', '>> 마운트 없음 (hostPath 제거)'],
     ['warn', '>> hostPID false — 호스트와 격리'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 호스트 격리','desc':'호스트 공유를 제거해 탈출 경로를 끊습니다.'},
 },
 'C-19': {
   'easy': 'latest 태그는 <b>이름표 없는 택배</b>를 받는 것과 같습니다. 안에 무엇이 든지, 누가 바꿔치기했는지 모릅니다. 다이제스트 고정과 서명은 <b>봉인된 정품 인증</b> 택배만 받습니다.',
   'attack_label': '레지스트리의 latest 태그를 악성 이미지로 바꿔치기한다',
   'attack_vuln': [
     ['cmt', '# latest를 쓰는 배포를 노림'],
     ['prompt', 'attacker$ docker push myapp:latest (악성 변조본)'],
     ['bad', '>> image: myapp:latest (미고정)'],
     ['prompt', 'cloud$ 파드 재시작 → latest 재취득'],
     ['bad', '>> 변조 이미지 배포 — 백도어 실행'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 이미지 변조','desc':'태그가 고정되지 않아 바꿔치기한 이미지가 돕니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 변조본을 밀어넣음'],
     ['prompt', 'attacker$ docker push 변조본'],
     ['good', '>> digest 불일치 + cosign 검증 실패'],
     ['warn', '>> 서명 없는 이미지 배포 거부'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 무결성 검증','desc':'다이제스트 고정과 서명으로 변조본을 거부합니다.'},
 },
 'C-20': {
   'easy': '리소스 제한이 없으면 한 컨테이너가 <b>뷔페를 혼자 다 먹어치우는</b> 손님처럼 노드 자원을 독식합니다. 다른 서비스가 굶어 멈춥니다. limits 설정은 <b>1인분씩 접시</b>를 나눠 줍니다.',
   'attack_label': '제한 없는 파드로 노드 자원을 고갈시켜 DoS를 일으킨다',
   'attack_vuln': [
     ['cmt', '# 침해된 파드에 리소스 제한이 없음'],
     ['prompt', 'attacker$ kubectl get pod -o yaml | grep -A2 resources'],
     ['bad', '>> resources: {} (제한 없음)'],
     ['prompt', 'attacker$ 메모리/CPU 무한 소비 유발'],
     ['bad', '>> 노드 자원 고갈 — 전체 서비스 다운'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 자원 고갈','desc':'제한이 없어 파드 하나가 노드를 마비시킵니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 자원 폭주 유발'],
     ['prompt', 'attacker$ 메모리 무한 소비 유발'],
     ['good', '>> limits 초과로 파드만 OOMKilled'],
     ['warn', '>> 노드와 다른 서비스는 정상 유지'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 자원 격리','desc':'limits/requests로 한 파드의 폭주를 가둡니다.'},
 },
}
