# -*- coding: utf-8 -*-
"""자동차 보안 동적 공격 데모 — 비유 + 상태별 결과 (20종).
ISO/SAE 21434 · UN R155/R156 · AUTOSAR SecOC 개념의 교육용 재구성."""

DYN = {
 'AUTO-01': {
  'easy': 'CAN 스푸핑은 <b>아파트 우편함에 남의 이름으로 편지를 넣는</b> 공격입니다. CAN 버스는 보낸 사람을 확인하지 않아서, 내용만 그럴듯하면 ECU가 편지를 진짜로 믿습니다.',
  'attack_label': '위조 CAN 프레임으로 계기판 속도를 바꿔 본다',
  'attack_vuln': [
    ['cmt', '# 진단 포트로 버스에 연결'],
    ['prompt', 'attacker$ cansend can0 0x0D2#0100FF00'],
    ['bad', '>> 계기판: 0 km/h 표시 (실제 100km/h)'],
    ['bad', '>> 운전자, 속도를 믿고 과속 유지'],
  ],
  'outcome_vuln': {'emoji':'🛞','title':'스푸핑 성공 — 계기 기만','desc':'보낸 사람 검증이 없으면 버스 위의 모든 명령이 믿을 수 없어집니다.'},
  'attack_secure': [
    ['cmt', '# 동일 프레임 전송 (SecOC 적용 차량)'],
    ['prompt', 'attacker$ cansend can0 0x0D2#0100FF00'],
    ['good', '>> MAC 불일치 — 프레임 폐기'],
    ['warn', '>> 위조 시도가 게이트웨이에 기록됨'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 메시지 인증','desc':'인증 코드(SecOC)가 있으면 위조 편지는 발송자 확인 전에 버려집니다.'},
 },
 'AUTO-02': {
  'easy': 'CAN DoS는 <b>비상사이렌을 계속 울려서 다른 모든 방송을 묻어버리는</b> 공격입니다. CAN은 번호가 빠른(우선순위 높은) 메시지가 먼저 도착하므로, 최우선 번호를 독점하면 아무것도 전달되지 못합니다.',
  'attack_label': '최우선 CAN ID로 버스를 플러딩해 본다',
  'attack_vuln': [
    ['cmt', '# ID 0x000 (최우선) 연속 발사'],
    ['prompt', 'attacker$ while true; cansend can0 0x000#FF'],
    ['bad', '>> 다른 ECU 프레임 전부 패킷 손실'],
    ['bad', '>> 계기·제어 메시지 마비 — 버스 오프 유발'],
  ],
  'outcome_vuln': {'emoji':'⛔','title':'서비스 마비 — 버스 독점','desc':'가용성 공격 몇 줄로 차량 전체 통신이 멈춥니다.'},
  'attack_secure': [
    ['cmt', '# 침입탐지(IDS) 활성 차량'],
    ['prompt', 'attacker$ while true; cansend can0 0x000#FF'],
    ['good', '>> 플러딩 패턴 감지 — 진단 경로 격리'],
    ['warn', '>> 정상 버스 전달은 별도 경로로 유지'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'완화 — 이상 트래픽 격리','desc':'감지와 격리가 있으면 공격자는 버스를 잡아도 독점하지 못합니다.'},
 },
 'AUTO-03': {
  'easy': '리플레이는 <b>어제 도장 찍힌 승인서를 오늘 다시 제출하는</b> 공격입니다. 서명(명령)은 진짜지만, 오늘 발급된 것이 아니라는 점을 확인하지 않으면 그대로 통과합니다.',
  'attack_label': '녹음해 둔 도어해제 프레임을 재생해 본다',
  'attack_vuln': [
    ['cmt', '# 정상 해제 신호를 미리 녹음'],
    ['prompt', 'attacker$ candump can0 ; replay 0x1F2#01'],
    ['bad', '>> ECU: 과거 카운터의 유효 MAC — 수용'],
    ['bad', '>> 도어 잠금 해제 — 차량 개방'],
  ],
  'outcome_vuln': {'emoji':'🔁','title':'재생 성공 — 시간 검증 없음','desc':'진짜 명령인지 확인해도, 지금 명령인지는 확인하지 않으면 재생을 막을 수 없습니다.'},
  'attack_secure': [
    ['cmt', '# 신선도 카운터 적용 차량'],
    ['prompt', 'attacker$ candump can0 ; replay 0x1F2#01'],
    ['good', '>> 카운터 과거값 — 리플레이 판정 폐기'],
    ['warn', '>> 재사용 시도가 로그에 기록됨'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 신선도 검증','desc':'매번 커지는 카운터가 있으면 어제의 승인서는 오늘 통과하지 못합니다.'},
 },
 'AUTO-04': {
  'easy': 'UDS 약한 인증은 <b>서버실 문이 잠겨 있지만 열쇠가 현관 매트 밑에</b> 있는 상태입니다. 진단 도구만 있으면 아무나 들어가 펌웨어를 다시 쓸 수 있습니다.',
  'attack_label': '인증 없이 ECU 펌웨어 쓰기를 시도한다',
  'attack_vuln': [
    ['cmt', '# UDS 진단 세션 진입'],
    ['prompt', 'tester$ 10 03 ; 34 00 (request download)'],
    ['bad', '>> 보안접근(0x27) 요구 없음 — 쓰기 허용'],
    ['bad', '>> 임의 펌웨어 다운로드 시작 가능'],
  ],
  'outcome_vuln': {'emoji':'🔧','title':'진단 악용 — 재프로그래밍 개방','desc':'진단 기능이 인증 없이 열려 있으면 차량 소프트웨어 전체가 공격 대상입니다.'},
  'attack_secure': [
    ['cmt', '# 인증서 기반 진단 인증(0x29) 적용'],
    ['prompt', 'tester$ 34 00 (request download)'],
    ['good', '>> 미인가 진단기 — 서비스 거부'],
    ['warn', '>> 쓰기는 인가 세션+서비스 모드에서만'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 강한 진단 인증','desc':'인증서를 가진 정품 도구만, 허용된 상태에서만 쓸 수 있습니다.'},
 },
 'AUTO-05': {
  'easy': '게이트웨이 부재는 <b>도서관과 화학실험실 사이에 벽이 없는</b> 건물입니다. 내비게이션(누구나 만질 수 있는 공간)에서 감염되면 그대로 브레이크 실험실로 불이 번집니다.',
  'attack_label': '감염시킨 내비게이션에서 제어 버스로 스캔해 본다',
  'attack_vuln': [
    ['cmt', '# IVI(내비) 앱을 통해 침투'],
    ['prompt', 'attacker$ (compromised IVI) canscan can1'],
    ['bad', '>> powertrain 버스 직접 도달'],
    ['bad', '>> 제어 ECU 명령 열람·위조 준비 완료'],
  ],
  'outcome_vuln': {'emoji':'🚪','title':'횡단 성공 — 도메인 붕괴','desc':'공격면이 넓은 쾌적 구역과 위험한 제어 구역이 통째로 연결돼 있습니다.'},
  'attack_secure': [
    ['cmt', '# 게이트웨이 화이트리스트 적용'],
    ['prompt', 'attacker$ (compromised IVI) canscan can1'],
    ['good', '>> IVI→제어망 전달 규칙 없음 — 차단'],
    ['warn', '>> 비정상 스캔 시도가 감지·기록됨'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 구획 격리','desc':'벽(게이트웨이)이 있으면 내비가 감염돼도 불은 제어망으로 번지지 않습니다.'},
 },
 'AUTO-06': {
  'easy': 'OBD-II 무보호는 <b>건물 현관에 누구나 쓸 수 있는 마스터키 걸이</b>를 두는 것입니다. 주차장 5분이면 차의 모든 신경계(버스)에 케이블을 꽂을 수 있습니다.',
  'attack_label': 'OBD-II 단자로 버스에 직접 연결해 본다',
  'attack_vuln': [
    ['cmt', '# 주차장에서 OBD-II 포트 접근'],
    ['prompt', 'attacker$ plug dongle -> can0 up'],
    ['bad', '>> 전체 차내 버스 접근 성공'],
    ['bad', '>> 진단·제어 명령 자유롭게 발사'],
  ],
  'outcome_vuln': {'emoji':'🔌','title':'진입 성공 — 만능 문 개방','desc':'물리 포트 하나가 차량 전체 공격의 시작점이 됩니다.'},
  'attack_secure': [
    ['cmt', '# 진단 정책 + 이상 알림 적용'],
    ['prompt', 'attacker$ plug dongle -> can0 up'],
    ['good', '>> 미인가 진단기 감지 — 경보·기록'],
    ['warn', '>> 노출 서비스는 조회만 허용됨'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'통제 — 최소 노출 + 감시','desc':'문은 열려 있어도 안에는 잠긴 서랍만, 그리고 문 열림이 기록됩니다.'},
 },
 'AUTO-07': {
  'easy': 'JTAG 잔존은 <b>이사 간 집에 이전 주인의 복사 열쇠가 그대로 남은</b> 것입니다. 개발할 때 쓰던 뒷문이 양산차에 그대로 살아있습니다.',
  'attack_label': 'ECU 보드의 JTAG 포트로 펌웨어를 덤프해 본다',
  'attack_vuln': [
    ['cmt', '# ECU 케이스 개방 후 JTAG 핀 식별'],
    ['prompt', 'attacker$ openocd -f ecu.cfg ; dump flash'],
    ['bad', '>> 플래시 전체 덤프 성공'],
    ['bad', '>> 펌웨어 수정·분석 자유로움'],
  ],
  'outcome_vuln': {'emoji':'🧷','title':'덤프 성공 — 뒷문 잔존','desc':'개발 편의를 위해 남긴 포트가 양산에서는 공격자의 정문이 됩니다.'},
  'attack_secure': [
    ['cmt', '# 양산 빌드: 디버그 퓨즈 차단'],
    ['prompt', 'attacker$ openocd -f ecu.cfg ; dump flash'],
    ['good', '>> 디버그 접근 거부 (locked)'],
    ['warn', '>> 플래시 읽기 보호(RDP) 활성 상태'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 양산 잠금','desc':'양산 물량에서 뒷문을 용접해 버리면(퓨즈 차단) 열쇠는 더 이상 없습니다.'},
 },
 'AUTO-08': {
  'easy': '펌웨어 비밀 추출은 <b>금고 대신 책상 서랍에 도장을 보관한</b> 것입니다. 펌웨어를 덤프하면 서랍째로 훔쳐지고, 공격자는 진짜 도장으로 서류를 발급합니다.',
  'attack_label': '덤프한 펌웨어에서 키를 검색해 본다',
  'attack_vuln': [
    ['cmt', '# 펌웨어 이미지 문자열 분석'],
    ['prompt', 'attacker$ strings fw.bin | grep -i key'],
    ['bad', '>> SECRET_KEY=... · 서버 인증서 발견'],
    ['bad', '>> 위조 진단기·가짜 서버 제작 가능'],
  ],
  'outcome_vuln': {'emoji':'💾','title':'비밀 노출 — 평문 저장','desc':'기기 안의 비밀은 언젠가 읽힌다고 가정해야 합니다.'},
  'attack_secure': [
    ['cmt', '# HSM 보관 + 비추출 키'],
    ['prompt', 'attacker$ strings fw.bin | grep -i key'],
    ['good', '>> 평문 키 없음 — 서랍이 비어 있음'],
    ['warn', '>> 키는 HSM 안에서만 연산에 사용됨'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 비밀 비보관','desc':'금고(HSM) 밖으로 나올 수 없는 키는 덤프해도 집에 없습니다.'},
 },
 'AUTO-09': {
  'easy': '릴레이 공격은 <b>친구와 무전기로 목소리를 이어주는</b> 사기입니다. 차는 "키가 옆에 있다"는 무전기를 듣고, 실제 키는 수십 미터 떨어진 집 안에 있습니다.',
  'attack_label': '중계기 2대로 스마트키 신호를 늘려 본다',
  'attack_vuln': [
    ['cmt', '# 차량 측 + 현관 측 중계기 설치'],
    ['prompt', 'attacker$ relay key-signal <-> car'],
    ['bad', '>> 차량: 키 근접 판정 — 잠금 해제'],
    ['bad', '>> 시동 걸고 그대로 이탈'],
  ],
  'outcome_vuln': {'emoji':'📡','title':'릴레이 성공 — 거리 기만','desc':'"신호가 강하다=가깝다"라는 가정이 공격의 표적입니다.'},
  'attack_secure': [
    ['cmt', '# UWB 도달시간(ToF) 측정 적용'],
    ['prompt', 'attacker$ relay key-signal <-> car'],
    ['good', '>> 중계 지연 감지 — 실제 거리 수십m 판정'],
    ['warn', '>> 유휴 키는 수면 상태 — 응답 자체 없음'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 거리 측정','desc':'도달 시간을 재면 무전기로 늘린 거리는 거짓말이 됩니다.'},
 },
 'AUTO-10': {
  'easy': 'TPMS 스푸핑은 <b>가짜 비상경보 방송을 틀어주는</b> 장난입니다. 타이어 센서의 무선 신호를 위조하면 계기판이 없는 위험을 경고하고, 있는 경고를 묻을 수 있습니다.',
  'attack_label': '위조 TPMS 신호로 허위 경고를 띄워 본다',
  'attack_vuln': [
    ['cmt', '# TPMS 주파수 스니핑 후 위조 전송'],
    ['prompt', 'attacker$ send TPMS id=0xA31 pressure=0'],
    ['bad', '>> 계기판: "타이어 공기압 이상" 점등'],
    ['bad', '>> 주행 중 오경고 — 급정차 유발'],
  ],
  'outcome_vuln': {'emoji':'🛞','title':'기만 성공 — 오경고','desc':'센서 메시지를 믿는 시스템은 센서를 속이는 공격에 무방비입니다.'},
  'attack_secure': [
    ['cmt', '# 비정상 패턴 필터 적용'],
    ['prompt', 'attacker$ send TPMS id=0xA31 pressure=0'],
    ['good', '>> 급변·불연속 값 폐기 — 무시'],
    ['warn', '>> 복수 샘플 일치 시에만 경고 표시'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'완화 — 상식 필터','desc':'한 번의 이상한 측정으로 비상경보가 울리지 않도록 걸러집니다.'},
 },
 'AUTO-11': {
  'easy': 'OTA 서명검증 부재는 <b>택배로 온 프로그램을 보낸 사람도 확인하고 설치하는</b> 것입니다. 조작된 업데이트 한 번이면 온 차량이 공격자의 소프트웨어로 바뀝니다.',
  'attack_label': '위조 OTA 패키지를 차량에 밀어 넣어 본다',
  'attack_vuln': [
    ['cmt', '# 업데이트 서버 흉내 또는 중간 전송'],
    ['prompt', 'attacker$ push evil_firmware.bin via OTA'],
    ['bad', '>> 서명 검증 없음 — 설치 시작'],
    ['bad', '>> 악성 펌웨어 탑재 — 완전 장악'],
  ],
  'outcome_vuln': {'emoji':'⬇️','title':'설치 성공 — 원격 장악','desc':'OTA는 원격 코드 실행의 정문입니다. 문지기가 없으면 열려 있는 문입니다.'},
  'attack_secure': [
    ['cmt', '# 코드서이닝 + 롤백 방지 적용'],
    ['prompt', 'attacker$ push evil_firmware.bin via OTA'],
    ['good', '>> 서명 불일치 — 설치 거부'],
    ['warn', '>> 구버전 다운그레이드 시도도 차단됨'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 서명 검증','desc':'제조사 도장(서명)이 없는 패키지는 문 앞에서 반송됩니다.'},
 },
 'AUTO-12': {
  'easy': 'MISRA 위반은 <b>비행기 부품을 통조림 따개로 조이는</b> 것과 같습니다. 돌아가긴 하지만, 어디서 어떻게 무너질지 아무도 보장하지 못합니다.',
  'attack_label': '정적 분석으로 안전핵심 코드를 점검해 본다',
  'attack_vuln': [
    ['cmt', '# 제어 코드 정적 분석 실행'],
    ['prompt', 'dev$ cppcheck --enable=all control.c'],
    ['bad', '>> buffer overrun 위험 37건'],
    ['bad', '>> 미초기화 변수 12건 — 병합 그대로 통과'],
  ],
  'outcome_vuln': {'emoji':'🧱','title':'기술부채 — 안전 구멍','desc':'경고를 무시한 코드는 언젠가 사고나 취약점의 시작점이 됩니다.'},
  'attack_secure': [
    ['cmt', '# 코딩 표준 게이트 적용'],
    ['prompt', 'dev$ cppcheck --enable=all control.c'],
    ['good', '>> 위반 0 — 병합 승인'],
    ['warn', '>> 퍼즈·단위 테스트도 통과 완료'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'게이트 통과 — 표준 준수','desc':'경고가 있으면 못 들어가는 문이 안전 코드의 기본선을 지킵니다.'},
 },
 'AUTO-13': {
  'easy': 'SecOC 부재는 <b>도장 없는 공문</b>입니다. 서류(메시지) 형식은 완벽해도 발행처를 확인할 수 없으면, 아무나 발행한 가짜 공문이 진짜처럼 시행됩니다.',
  'attack_label': '인증 없는 CAN에 위조 제어 프레임을 쏴 본다',
  'attack_vuln': [
    ['cmt', '# SecOC 미적용 차량'],
    ['prompt', 'attacker$ cansend can0 0x123#AABBCCDD'],
    ['bad', '>> 수신 ECU: 검증 없이 수용'],
    ['bad', '>> 위조 명령 그대로 실행'],
  ],
  'outcome_vuln': {'emoji':'🔐','title':'위조 성공 — 무인증 버스','desc':'CAN은 원래 도장이 없는 통신입니다. 도장(SecOC)은 선택이 아니라 설계입니다.'},
  'attack_secure': [
    ['cmt', '# SecOC 적용 (MAC + 카운터)'],
    ['prompt', 'attacker$ cansend can0 0x123#AABBCCDD'],
    ['good', '>> MAC 불일치 — 프레임 폐기'],
    ['warn', '>> 정당 발신자의 프레임만 수용됨'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 메시지 도장','desc':'모든 제어 메시지에 도장이 찍히면 가짜 공문은 시행되지 못합니다.'},
 },
 'AUTO-14': {
  'easy': 'SBOM 부재는 <b>재료 표시가 없는 식품</b>입니다. "이 과자에 문제가 된 첨가물이 들었나요?"라는 질문에 아무도 대답할 수 없습니다.',
  'attack_label': '새 CVE 발표 후 영향 받는 차량을 찾아 본다',
  'attack_vuln': [
    ['cmt', '# CVE-2026-XXXX 긴급 공지 수신'],
    ['prompt', 'mgr$ 우리 차량에 이 라이브러리 있나?'],
    ['bad', '>> 부품 목록 없음 — 확인 불가'],
    ['bad', '>> 3주 뒤에야 전수 조사 착수 — 사각지대 방치'],
  ],
  'outcome_vuln': {'emoji':'📦','title':'대응 불가 — 목록 부재','desc':'무엇으로 만들었는지 모르면 무엇이 위험한지도 알 수 없습니다.'},
  'attack_secure': [
    ['cmt', '# ECU별 SBOM 대조'],
    ['prompt', 'mgr$ cve-check against SBOM DB'],
    ['good', '>> 3개 ECU 사용 확인 — 패치 우선순위 즉시 산정'],
    ['warn', '>> 해당 차종 OTA 일정 수립 완료'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'즉시 대응 — 재료 표시','desc':'재료표(SBOM)가 있으면 뉴스를 듣자마자 답할 수 있습니다.'},
 },
 'AUTO-15': {
  'easy': 'API 키 하드코딩은 <b>은행 비밀번호를 이마에 적고 다니는</b> 것입니다. 앱을 분해해 보면 누구나 읽을 수 있고, 그 키로 차량 문을 열 수 있습니다.',
  'attack_label': '앱을 분해해서 안에 박힌 키를 꺼내 본다',
  'attack_vuln': [
    ['cmt', '# 앱 스토어 APK 다운로드 후 역분석'],
    ['prompt', 'attacker$ apktool app.apk ; grep api_key'],
    ['bad', '>> api_key=AIza... 추출 성공'],
    ['bad', '>> 차량 제어 API 직접 호출 가능'],
  ],
  'outcome_vuln': {'emoji':'📱','title':'키 유출 — 기기 신뢰 붕괴','desc':'기기에 넣은 비밀은 반드시 꺼낼 수 있다는 것이 공격의 전제입니다.'},
  'attack_secure': [
    ['cmt', '# 단기 토큰 + 서버 프록시 구조'],
    ['prompt', 'attacker$ apktool app.apk ; grep api_key'],
    ['good', '>> 장기 키 없음 — 빈 서랍'],
    ['warn', '>> 명령은 서버에서 계정·권한 재검증됨'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 비밀 비보관','desc':'이마에 적을 비밀 자체가 없으면 읽을 것도 없습니다.'},
 },
 'AUTO-16': {
  'easy': '클라우드 토큰 유출은 <b>집 비밀번호가 적힌 쪽지가 담긴 지갑 분실</b>입니다. 지갑 주인이 누구든, 쪽지를 본 사람은 집에 들어갈 수 있습니다.',
  'attack_label': '유출된 토큰으로 원격 도어 해제를 호출해 본다',
  'attack_vuln': [
    ['cmt', '# 덤프/피싱으로 확보한 클라우드 토큰'],
    ['prompt', 'attacker$ curl /v1/cars/123/unlock -H "auth: ..."'],
    ['bad', '>> 200 OK — 원격 도어 해제'],
    ['bad', '>> 위치 조회·원격 시동까지 가능'],
  ],
  'outcome_vuln': {'emoji':'☁️','title':'원격 장악 — 토큰 만능','desc':'하나의 강력한 토큰이 있으면 차와 관련된 모든 것에 문이 열립니다.'},
  'attack_secure': [
    ['cmt', '# 기기 바인딩 + 이상 감지 적용'],
    ['prompt', 'attacker$ curl /v1/cars/123/unlock -H "auth: ..."'],
    ['good', '>> 등록 기기·위치 불일치 — 요청 차단'],
    ['warn', '>> 소유자 앱으로 확인 알림 발송됨'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'차단 — 스코프+상황 검증','desc':'토큰이 새도 그것이 어떤 기기에서, 어디서 쓰이는지까지 확인합니다.'},
 },
 'AUTO-17': {
  'easy': 'TARA 부재는 <b>설계도 없이 지은 빌딩에 소화기 위치를 묻는</b> 것입니다. 무엇이 위험하고 어디가 뚫릴지 그린 적이 없으니, 막아야 할 곳조차 목록이 없습니다.',
  'attack_label': '보안 분석 없이 개발한 차량을 점검해 본다',
  'attack_vuln': [
    ['cmt', '# TARA 생략하고 양산 임박'],
    ['prompt', 'team$ 일정 급함 → 보안 분석 생략'],
    ['bad', '>> 진단 포트·무선 경로 통제 부재 확인'],
    ['bad', '>> 양산 후 결함 발견 — 대규모 리콜'],
  ],
  'outcome_vuln': {'emoji':'📋','title':'사후 발견 — 비용 폭증','desc':'개발 중 1주일이면 될 분석이 양산 후에는 리콜이 됩니다.'},
  'attack_secure': [
    ['cmt', '# TARA 수행 → 통제 도출'],
    ['prompt', 'sec$ damage scenario -> attack path -> control'],
    ['good', '>> SecOC·도메인 격리·진단 인증 설계 반영'],
    ['warn', '>> 잔여 위험은 문서화·경영 승인 완료'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'사전 설계 — 위험 지도','desc':'위협 지도(TARA)가 있으면 막을 곳을 먼저 알고 설계합니다.'},
 },
 'AUTO-18': {
  'easy': 'CSMS 미인증은 <b>면허 없이 버스를 운행하려는</b> 것과 같습니다. 차가 아무리 좋아도(기능이 있어도) 운행 자격(인증)이 없으면 영업을 못 합니다.',
  'attack_label': '관리체계 없는 상태로 신차 인증을 신청해 본다',
  'attack_vuln': [
    ['cmt', '# CSMS 없이 신차 인증 서류 제출'],
    ['prompt', 'mgr$ type approval 신청'],
    ['bad', '>> 사이버보안 관리체계 미흡 지적'],
    ['bad', '>> 인증 보류 — 출시 일정 전체 지연'],
  ],
  'outcome_vuln': {'emoji':'🏛️','title':'인증 보류 — 판매 불가','desc':'규제는 결과물이 아니라 과정(체계)을 심사합니다.'},
  'attack_secure': [
    ['cmt', '# CSMS 구축 후 심사'],
    ['prompt', 'mgr$ risk-mgmt + monitoring + response 체계'],
    ['good', '>> CSMS 인증 획득'],
    ['warn', '>> 신차 인증 요건 충족 — 일정대로 출시'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'인증 획득 — 체계 입증','desc':'면허(CSMS 인증)는 차를 만드는 방법 자체를 보증합니다.'},
 },
 'AUTO-19': {
  'easy': 'SUMS 부재는 <b>약의 허가 없이 처방 없이 환자에 투약하는</b> 것과 같습니다. 업데이트라는 약을 검증·기록 없이 아무 때나 전 차량에 뿌리면 부작용을 못 막습니다.',
  'attack_label': '검증 없는 긴급 OTA를 전 차량에 배포해 본다',
  'attack_vuln': [
    ['cmt', '# 오늘 발견 → 오늘 전 차량 배포'],
    ['prompt', 'team$ 급하니 검증 생략, 전량 배포'],
    ['bad', '>> 안전 영향 미검증 — 일제 오작동'],
    ['bad', '>> 어느 차가 어떤 버전인지 추적 불가'],
  ],
  'outcome_vuln': {'emoji':'🔄','title':'배포 사고 — 통제 부재','desc':'빠른 업데이트가 미덕이 아니라, 검증된 업데이트가 미덕입니다.'},
  'attack_secure': [
    ['cmt', '# SUMS 절차: 검증→승인→단계 배포'],
    ['prompt', 'ops$ 1% 군집 → 관찰 → 전체 확대'],
    ['good', '>> 무결성·버전(RXSWIN) 추적 완료'],
    ['warn', '>> 이상 징후 즉시 중단·롤백 체계 대기'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'절차 준수 — 단계 확대','desc':'허가받은 약을 소수에게 먼저 써보고, 괜찮으면 늘리는 것이 원칙입니다.'},
 },
 'AUTO-20': {
  'easy': 'VSOC 부재는 <b>화재경보기 없는 아파트</b>입니다. 불이 나도(공격을 받아도) 아무도 알람을 듣지 못해, 타버린 뒤에야 화재를 압니다.',
  'attack_label': '관제 없는 상태에서 차대 공격을 관찰해 본다',
  'attack_vuln': [
    ['cmt', '# 야간에 차대 공격 시도'],
    ['prompt', 'attacker$ exploit fleet vehicles'],
    ['bad', '>> 탐지 없음 — 수개월 은폐'],
    ['bad', '>> 같은 취약점으로 수만 대 감염 확산'],
  ],
  'outcome_vuln': {'emoji':'🖥️','title':'은폐 성공 — 방치 감염','desc':'출고된 차는 관측하지 않으면 공격 중인지조차 모릅니다.'},
  'attack_secure': [
    ['cmt', '# VSOC 상시 감시 체계'],
    ['prompt', 'attacker$ exploit fleet vehicles'],
    ['good', '>> 이상 징후 실시간 탐지 — 경보'],
    ['warn', '>> 분석 후 48시간 내 전 차량 OTA 패치 완료'],
  ],
  'outcome_secure': {'emoji':'🛡️','title':'조기 차단 — 관제 순환','desc':'경보기(VSOC)는 탐지→분석→패치로 이어지는 방어의 마지막 라인입니다.'},
 },
}

# 확장 41종(AUTO-21~61) 동적 데모 병합
from specs_auto_dyn_p2 import DYN2  # noqa: E402

DYN.update(DYN2)
