# -*- coding: utf-8 -*-
"""주요정보통신기반시설 Windows 서버 보안 점검 표준 항목 (KISA 체크리스트 기반)."""

HOST = 'PS C:\\>'


def W(code, title, icon, cat, sev, desc, vt, st, fixes, chk, ref):
    return {'file': '08_win-%s.html' % code.lower().replace('-', ''),
            'code': code, 'title': title, 'icon': icon, 'category': 'Windows 서버 · ' + cat, 'severity': sev,
            'description': desc, 'vuln_term': vt, 'secure_term': st, 'host': HOST,
            'fix_steps': fixes, 'checklist': chk, 'kisa_ref': ref}


SPECS = [
# ===== 계정 관리 =====
W('W-01', 'Administrator 계정 이름 변경', '🪪', '계정 관리', '상',
  '기본 관리자 계정명(Administrator)은 공격자에게 알려져 있어 무차별 대입의 1차 표적이 됩니다. 추측 어려운 이름으로 변경해야 합니다.',
  [('cmt', '# 관리자 계정 확인'), ('prompt', 'PS> '), ('', 'Get-LocalUser | Where SID -like "*-500"'),
   ('bad', 'Administrator   Enabled  True'), ('warn', '→ 기본 관리자명 그대로 사용 (취약)')],
  [('cmt', '# 계정 이름 변경'), ('prompt', 'PS> '), ('', 'Rename-LocalUser -Name "Administrator" -NewName "svc_adm07"'),
   ('good', 'svc_adm07   (SID ...-500)'), ('good', '→ 관리자명 변경 완료 (양호)')],
  ['<code>로컬 보안 정책 &gt; 계정: Administrator 계정 이름 바꾸기</code>에서 변경합니다.',
   '변경 후에도 SID(-500) 기반 공격에 대비해 잠금 정책을 병행합니다.'],
  ['기본 Administrator 계정명이 변경됨', '계정 잠금 정책이 함께 적용됨'],
  'Windows 계정 관리 > Administrator 이름 변경'),

W('W-02', 'Guest 계정 비활성화', '👤', '계정 관리', '상',
  'Guest 계정은 익명 접근 경로가 되어 정보 노출·권한 오용에 악용됩니다. 비활성화해야 합니다.',
  [('cmt', '# Guest 상태 확인'), ('prompt', 'PS> '), ('', 'Get-LocalUser Guest | Select Name,Enabled'),
   ('bad', 'Guest   Enabled  True'), ('warn', '→ Guest 활성화 상태 (취약)')],
  [('cmt', '# Guest 비활성화'), ('prompt', 'PS> '), ('', 'Disable-LocalUser -Name "Guest"'),
   ('good', 'Guest   Enabled  False'), ('good', '→ Guest 비활성화 (양호)')],
  ['<code>Disable-LocalUser Guest</code> 또는 로컬 사용자 관리에서 Guest를 사용 안 함으로 설정합니다.'],
  ['Guest 계정이 비활성화됨'],
  'Windows 계정 관리 > Guest 계정 비활성화'),

W('W-03', '불필요한 계정 제거', '🧹', '계정 관리', '중',
  '퇴직자·테스트·미사용 계정이 남아 있으면 인증 우회·권한 오용 경로가 됩니다. 불필요한 계정은 제거하거나 비활성화해야 합니다.',
  [('cmt', '# 계정 목록'), ('prompt', 'PS> '), ('', 'Get-LocalUser | Select Name,Enabled,LastLogon'),
   ('bad', 'test, temp, olduser ... (Enabled)'), ('warn', '→ 미사용 계정 잔존 (취약)')],
  [('cmt', '# 미사용 계정 제거'), ('prompt', 'PS> '), ('', 'Remove-LocalUser -Name "test"'),
   ('good', '활성 계정 = 운영에 필요한 것만'), ('good', '→ 계정 정리 완료 (양호)')],
  ['장기 미사용·테스트·퇴직자 계정을 제거하거나 비활성화합니다.',
   '계정 현황을 주기적으로 검토하는 절차를 운영합니다.'],
  ['불필요/미사용 계정이 제거되었는가', '계정 점검 주기가 운영됨'],
  'Windows 계정 관리 > 불필요한 계정 제거'),

W('W-04', '계정 잠금 임계값 설정', '🔒', '계정 관리', '상',
  '잠금 임계값이 없으면 무차별 대입으로 비밀번호가 탈취됩니다. 실패 횟수 임계값과 잠금 기간을 설정해야 합니다.',
  [('cmt', '# 잠금 정책 확인'), ('prompt', 'PS> '), ('', 'net accounts | findstr /i lockout'),
   ('bad', 'Lockout threshold:  Never'), ('warn', '→ 무차별 대입 가능 (취약)')],
  [('cmt', '# 임계값 설정'), ('prompt', 'PS> '), ('', 'net accounts /lockoutthreshold:5 /lockoutduration:60'),
   ('good', 'Lockout threshold:  5'), ('good', '→ 5회 실패 시 잠금 (양호)')],
  ['<code>로컬 보안 정책 &gt; 계정 잠금 정책</code>에서 임계값을 5회 이하로 설정합니다.',
   '잠금 기간/카운터 초기화 시간을 함께 설정합니다.'],
  ['계정 잠금 임계값이 설정됨(5회 이하)', '잠금 기간이 설정됨'],
  'Windows 계정 관리 > 계정 잠금 임계값'),

W('W-05', '복구 가능한 암호화로 암호 저장 안 함', '🔓', '계정 관리', '상',
  '"되돌릴 수 있는 암호화로 암호 저장"이 켜져 있으면 비밀번호를 평문에 가깝게 복원할 수 있습니다. 비활성화해야 합니다.',
  [('cmt', '# 정책 확인'), ('prompt', 'PS> '), ('', 'secedit /export /cfg pol.cfg; findstr ClearText pol.cfg'),
   ('bad', 'ClearTextPassword = 1'), ('warn', '→ 복구 가능 암호 저장 (취약)')],
  [('cmt', '# 비활성화'), ('prompt', 'PS> '), ('', 'ClearTextPassword = 0 (정책 적용)'),
   ('good', 'ClearTextPassword = 0'), ('good', '→ 복구 가능 저장 비활성화 (양호)')],
  ['<code>암호 정책 &gt; 되돌릴 수 있는 암호화를 사용하여 암호 저장</code>을 "사용 안 함"으로 설정합니다.'],
  ['되돌릴 수 있는 암호화 저장이 비활성화됨'],
  'Windows 계정 관리 > 복구 가능 암호 저장 금지'),

W('W-06', '암호 복잡성 설정', '🔣', '계정 관리', '상',
  '암호 복잡성이 미적용되면 단순 비밀번호가 허용되어 쉽게 추측됩니다. 복잡성 정책을 활성화해야 합니다.',
  [('cmt', '# 복잡성 확인'), ('prompt', 'PS> '), ('', 'findstr PasswordComplexity pol.cfg'),
   ('bad', 'PasswordComplexity = 0'), ('warn', '→ 단순 비밀번호 허용 (취약)')],
  [('cmt', '# 복잡성 사용'), ('prompt', 'PS> '), ('', 'PasswordComplexity = 1 (정책 적용)'),
   ('good', 'PasswordComplexity = 1'), ('good', '→ 복잡성 요구 (양호)')],
  ['<code>암호 정책 &gt; 암호는 복잡성을 만족해야 함</code>을 "사용"으로 설정합니다.'],
  ['암호 복잡성 정책이 활성화됨'],
  'Windows 계정 관리 > 암호 복잡성'),

W('W-07', '최소 암호 길이', '📏', '계정 관리', '중',
  '최소 길이가 짧으면 무차별 대입에 취약합니다. 8자리 이상으로 설정해야 합니다.',
  [('cmt', '# 최소 길이 확인'), ('prompt', 'PS> '), ('', 'net accounts | findstr /i length'),
   ('bad', 'Minimum password length:  0'), ('warn', '→ 짧은 암호 허용 (취약)')],
  [('cmt', '# 8자리 이상'), ('prompt', 'PS> '), ('', 'net accounts /minpwlen:8'),
   ('good', 'Minimum password length:  8'), ('good', '→ 최소 길이 설정 (양호)')],
  ['<code>암호 정책 &gt; 최소 암호 길이</code>를 8자 이상으로 설정합니다.'],
  ['최소 암호 길이가 8자 이상인가'],
  'Windows 계정 관리 > 최소 암호 길이'),

W('W-08', '암호 사용 기간(최대/최소)', '📆', '계정 관리', '중',
  '암호 최대 사용 기간이 무제한이면 유출된 암호가 장기간 유효합니다. 최대/최소 사용 기간을 설정해야 합니다.',
  [('cmt', '# 사용 기간 확인'), ('prompt', 'PS> '), ('', 'net accounts | findstr /i age'),
   ('bad', 'Maximum password age:  Unlimited'), ('warn', '→ 암호 무기한 사용 (취약)')],
  [('cmt', '# 기간 설정'), ('prompt', 'PS> '), ('', 'net accounts /maxpwage:90 /minpwage:1'),
   ('good', 'Maximum password age:  90'), ('good', '→ 주기적 변경 강제 (양호)')],
  ['최대 암호 사용 기간(예: 90일)과 최소 사용 기간(1일 이상)을 설정합니다.'],
  ['최대 암호 사용 기간이 설정됨', '최소 사용 기간이 설정됨'],
  'Windows 계정 관리 > 암호 사용 기간'),

# ===== 서비스 관리 =====
W('W-09', '공유 권한 및 Everyone 제거', '📁', '서비스 관리', '상',
  '공유에 Everyone 모든 권한이 부여되면 누구나 접근·변조할 수 있습니다. 공유 권한을 최소화하고 Everyone을 제거해야 합니다.',
  [('cmt', '# 공유 권한 확인'), ('prompt', 'PS> '), ('', 'Get-SmbShareAccess -Name "Data"'),
   ('bad', 'Everyone   Allow   Full'), ('warn', '→ 모든 사용자 전체 권한 (취약)')],
  [('cmt', '# Everyone 제거 + 최소권한'), ('prompt', 'PS> '), ('', 'Revoke-SmbShareAccess Data -AccountName Everyone'),
   ('good', 'DOMAIN\\AppGrp   Allow   Read'), ('good', '→ 필요 그룹만 최소 권한 (양호)')],
  ['공유 권한에서 <code>Everyone</code>을 제거하고 필요한 그룹에만 최소 권한을 부여합니다.',
   'NTFS 권한과 공유 권한을 함께 점검합니다.'],
  ['공유에 Everyone 전체권한이 없는가', '필요 그룹만 최소 권한 부여'],
  'Windows 서비스 관리 > 공유 권한 설정'),

W('W-10', '기본 공유(C$, ADMIN$) 제거', '💽', '서비스 관리', '중',
  '관리 목적 기본 공유(C$, ADMIN$, IPC$)는 원격 접근·측면 이동에 악용될 수 있습니다. 불필요하면 비활성화합니다.',
  [('cmt', '# 기본 공유 확인'), ('prompt', 'PS> '), ('', 'Get-SmbShare | Where Name -like "*$"'),
   ('bad', 'C$, ADMIN$, IPC$  (자동 공유)'), ('warn', '→ 관리 공유 활성 (취약)')],
  [('cmt', '# AutoShareServer=0'), ('prompt', 'PS> '), ('', 'reg add ...\\LanmanServer\\Parameters /v AutoShareServer /t REG_DWORD /d 0'),
   ('good', '재부팅 후 기본 공유 비활성'), ('good', '→ 자동 공유 해제 (양호)')],
  ['레지스트리 <code>AutoShareServer/AutoShareWks</code>를 0으로 설정 후 재부팅합니다.',
   '관리 공유가 업무상 필요하면 방화벽으로 접근 IP를 제한합니다.'],
  ['불필요한 기본 공유가 비활성화됨', '필요 시 접근 IP가 제한됨'],
  'Windows 서비스 관리 > 기본 공유 제거'),

W('W-11', '불필요한 서비스 제거', '🧯', '서비스 관리', '상',
  'Telnet, SNMP, Alerter 등 불필요한 서비스는 공격 표면을 넓힙니다. 사용하지 않는 서비스는 중지/비활성화합니다.',
  [('cmt', '# 위험 서비스 확인'), ('prompt', 'PS> '), ('', 'Get-Service Telnet,Browser,RemoteRegistry | Select Name,Status'),
   ('bad', 'Telnet   Running'), ('warn', '→ 불필요/취약 서비스 구동 (취약)')],
  [('cmt', '# 중지+비활성화'), ('prompt', 'PS> '), ('', 'Set-Service Telnet -StartupType Disabled; Stop-Service Telnet'),
   ('good', 'Telnet   Stopped/Disabled'), ('good', '→ 불필요 서비스 제거 (양호)')],
  ['Telnet/SNMP/RemoteRegistry/Alerter 등 불필요 서비스를 중지·비활성화합니다.',
   '원격 접속은 NLA가 적용된 RDP 또는 SSH로 대체합니다.'],
  ['불필요/취약 서비스가 비활성화됨', '원격 접속이 안전한 방식으로 대체됨'],
  'Windows 서비스 관리 > 불필요한 서비스 제거'),

W('W-12', 'IIS 디렉터리 리스팅 제거', '🌐', '서비스 관리', '상',
  'IIS 디렉터리 검색(Directory Browsing)이 켜져 있으면 파일 목록이 노출되어 정보 수집에 악용됩니다. 비활성화해야 합니다.',
  [('cmt', '# 디렉터리 검색 확인'), ('prompt', 'PS> '), ('', 'Get-WebConfigurationProperty //directoryBrowse -Name enabled'),
   ('bad', 'enabled : True'), ('warn', '→ 디렉터리 목록 노출 (취약)')],
  [('cmt', '# 비활성화'), ('prompt', 'PS> '), ('', 'Set-WebConfigurationProperty //directoryBrowse -Name enabled -Value False'),
   ('good', 'enabled : False'), ('good', '→ 디렉터리 검색 차단 (양호)')],
  ['IIS 관리자에서 <code>디렉터리 검색</code>을 사용 안 함으로 설정합니다.',
   '기본 문서(default document)를 지정하고 불필요한 파일을 제거합니다.'],
  ['IIS 디렉터리 검색이 비활성화됨', '기본 문서가 설정됨'],
  'Windows 서비스 관리 > IIS 디렉터리 리스팅'),

W('W-13', 'RDP NLA 및 접속 제한', '🖥️', '서비스 관리', '상',
  'RDP가 NLA(네트워크 수준 인증) 없이 모든 IP에 열려 있으면 무차별 대입·취약점 공격에 노출됩니다. NLA를 적용하고 접근을 제한해야 합니다.',
  [('cmt', '# NLA 설정 확인'), ('prompt', 'PS> '), ('', 'reg query "...\\Terminal Server\\WinStations\\RDP-Tcp" /v UserAuthentication'),
   ('bad', 'UserAuthentication  0x0'), ('warn', '→ NLA 미적용, 전체 개방 (취약)')],
  [('cmt', '# NLA + 방화벽 제한'), ('prompt', 'PS> '), ('', 'Set-ItemProperty ... UserAuthentication 1; 방화벽 소스 IP 제한'),
   ('good', 'UserAuthentication  0x1'), ('good', '→ NLA 적용, 접근 제한 (양호)')],
  ['RDP에 <code>네트워크 수준 인증(NLA)</code>을 적용합니다.',
   '방화벽으로 RDP(3389) 접근 IP를 허용 대역으로 제한합니다.',
   '계정 잠금 정책과 강력한 암호 정책을 병행합니다.'],
  ['RDP에 NLA가 적용됨', 'RDP 접근 IP가 제한됨'],
  'Windows 서비스 관리 > 원격 터미널(RDP) 보안'),

W('W-14', 'SNMP Community String 보안', '📶', '서비스 관리', '상',
  'SNMP community가 기본값(public/private)이면 시스템 정보 조회·변조가 가능합니다. 복잡한 값으로 변경하고 접근을 제한합니다.',
  [('cmt', '# community 확인'), ('prompt', 'PS> '), ('', 'reg query "...\\SNMP\\Parameters\\ValidCommunities"'),
   ('bad', 'public   REG_DWORD   4'), ('warn', '→ 기본 community 사용 (취약)')],
  [('cmt', '# 복잡한 값 + 호스트 제한'), ('prompt', 'PS> '), ('', 'ValidCommunities = Str0ng#Comm ; PermittedManagers 지정'),
   ('good', '기본값 제거 + 소스 제한'), ('good', '→ SNMP 보안 강화 (양호)')],
  ['public/private 등 기본 community를 추측 어려운 값으로 변경합니다.',
   '허용 관리 호스트(PermittedManagers)만 지정합니다.',
   '불필요하면 SNMP 서비스를 비활성화합니다.'],
  ['기본 community string이 변경됨', '허용 관리 호스트가 제한됨'],
  'Windows 서비스 관리 > SNMP Community'),

W('W-15', 'DNS Zone Transfer 제한', '🧭', '서비스 관리', '상',
  'Windows DNS의 영역 전송이 모든 서버에 허용되면 도메인 정보가 노출됩니다. 지정 서버로만 전송을 제한해야 합니다.',
  [('cmt', '# zone transfer 설정'), ('prompt', 'PS> '), ('', 'Get-DnsServerZone | Select ZoneName,SecureSecondaries'),
   ('bad', 'SecureSecondaries : TransferAnyServer'), ('warn', '→ 누구나 영역 전송 가능 (취약)')],
  [('cmt', '# 지정 서버만'), ('prompt', 'PS> '), ('', 'Set-DnsServerPrimaryZone -SecureSecondaries TransferToZoneNameServer'),
   ('good', 'TransferToSecureServers'), ('good', '→ 영역 전송 제한 (양호)')],
  ['DNS 영역 속성에서 영역 전송을 <code>지정된 서버로만</code> 제한합니다.',
   '불필요한 영역 전송을 비활성화합니다.'],
  ['DNS 영역 전송이 지정 서버로 제한됨'],
  'Windows 서비스 관리 > DNS Zone Transfer'),

# ===== 패치 관리 =====
W('W-16', '최신 보안 패치 적용', '🩹', '패치 관리', '상',
  '미적용 보안 패치는 알려진 취약점(권한상승·RCE)에 노출됩니다. 정기적으로 최신 패치를 적용해야 합니다.',
  [('cmt', '# 미적용 업데이트 확인'), ('prompt', 'PS> '), ('', 'Get-HotFix | Sort InstalledOn -Desc | Select -First 1'),
   ('bad', '최종 패치: 18개월 전'), ('warn', '→ 다수 취약점 노출 (취약)')],
  [('cmt', '# 패치 적용'), ('prompt', 'PS> '), ('', 'Install-WindowsUpdate -AcceptAll (WSUS/업데이트)'),
   ('good', '최신 누적 업데이트 적용'), ('good', '→ 패치 최신화 (양호)')],
  ['WSUS 또는 Windows Update로 정기 패치를 적용합니다.',
   '패치 적용 전 영향도 검토와 백업을 수행하고 이력을 관리합니다.'],
  ['최신 보안 패치가 적용됨', '정기 패치 절차가 운영됨'],
  'Windows 패치 관리 > 최신 HotFix 적용'),

# ===== 로그 관리 =====
W('W-17', '감사 정책 설정', '📋', '로그 관리', '상',
  '감사 정책이 미설정이면 로그온·정책 변경·권한 사용 등 보안 이벤트를 추적할 수 없습니다. 주요 이벤트에 대해 감사를 설정해야 합니다.',
  [('cmt', '# 감사 정책 확인'), ('prompt', 'PS> '), ('', 'auditpol /get /category:*'),
   ('bad', 'Logon/Logoff  No Auditing'), ('warn', '→ 보안 이벤트 미기록 (취약)')],
  [('cmt', '# 감사 활성화'), ('prompt', 'PS> '), ('', 'auditpol /set /category:"Logon/Logoff" /success:enable /failure:enable'),
   ('good', 'Success and Failure'), ('good', '→ 감사 정책 설정 (양호)')],
  ['로그온, 계정 관리, 정책 변경, 권한 사용 등에 대해 성공/실패 감사를 설정합니다.',
   '감사 로그를 SIEM과 연계해 모니터링합니다.'],
  ['주요 이벤트 감사 정책이 설정됨', '로그가 모니터링됨'],
  'Windows 로그 관리 > 감사 정책'),

W('W-18', '원격 레지스트리 접근 경로 제한', '🗝️', '로그 관리', '상',
  '원격으로 접근 가능한 레지스트리 경로가 과도하면 시스템 정보 노출·변조가 가능합니다. 허용 경로를 최소화해야 합니다.',
  [('cmt', '# 원격 접근 경로 확인'), ('prompt', 'PS> '), ('', 'reg query "...\\SecurePipeServers\\winreg\\AllowedPaths"'),
   ('bad', '광범위한 경로 허용'), ('warn', '→ 원격 레지스트리 노출 (취약)')],
  [('cmt', '# 경로 최소화'), ('prompt', 'PS> '), ('', 'AllowedPaths 최소화 + RemoteRegistry 비활성화'),
   ('good', '필요한 경로만/서비스 중지'), ('good', '→ 원격 접근 제한 (양호)')],
  ['원격 레지스트리 서비스(RemoteRegistry)를 불필요하면 비활성화합니다.',
   '<code>AllowedPaths/AllowedExactPaths</code>를 최소한으로 유지합니다.'],
  ['원격 레지스트리 접근이 제한됨', 'RemoteRegistry가 불필요 시 비활성화됨'],
  'Windows 로그 관리 > 원격 레지스트리 접근'),

W('W-19', '이벤트 로그 크기·보관 설정', '🧾', '로그 관리', '중',
  '이벤트 로그 크기가 작거나 덮어쓰기되면 침해 분석에 필요한 기록이 소실됩니다. 충분한 크기와 보관 정책을 설정해야 합니다.',
  [('cmt', '# 로그 설정 확인'), ('prompt', 'PS> '), ('', 'Get-WinEvent -ListLog Security | Select MaximumSizeInBytes,LogMode'),
   ('bad', 'MaxSize 512KB / Overwrite'), ('warn', '→ 로그 조기 소실 (취약)')],
  [('cmt', '# 크기/보관 상향'), ('prompt', 'PS> '), ('', 'Limit-EventLog -LogName Security -MaximumSize 200MB -OverflowAction ...'),
   ('good', 'MaxSize 200MB / Archive'), ('good', '→ 로그 보관 강화 (양호)')],
  ['보안/시스템/응용 로그의 최대 크기를 충분히 설정합니다.',
   '보관(Archive) 방식으로 두고 중앙 로그 서버로 전송합니다.'],
  ['이벤트 로그 크기가 충분한가', '로그 보관/전송 정책이 설정됨'],
  'Windows 로그 관리 > 이벤트 로그 설정'),

# ===== 보안 관리 =====
W('W-20', '화면 보호기 잠금 설정', '🖼️', '보안 관리', '하',
  '자리 비움 시 화면 잠금이 없으면 물리적 접근자가 세션을 탈취할 수 있습니다. 일정 시간 후 잠금되는 화면 보호기를 설정합니다.',
  [('cmt', '# 잠금 정책 확인'), ('prompt', 'PS> '), ('', 'reg query "...\\Desktop" /v ScreenSaverIsSecure'),
   ('bad', 'ScreenSaverIsSecure  0 / Timeout 없음'), ('warn', '→ 자동 잠금 미설정 (취약)')],
  [('cmt', '# 잠금 설정'), ('prompt', 'PS> '), ('', 'ScreenSaveActive=1; ScreenSaverIsSecure=1; Timeout=600'),
   ('good', '10분 후 잠금'), ('good', '→ 자동 잠금 적용 (양호)')],
  ['일정 시간(예: 10분) 후 암호로 잠기는 화면 보호기를 설정합니다.',
   'GPO로 조직 전반에 강제 적용합니다.'],
  ['화면 자동 잠금이 설정됨', '재개 시 암호를 요구함'],
  'Windows 보안 관리 > 화면 보호기 잠금'),

W('W-21', '로그온 없이 시스템 종료 금지', '⏻', '보안 관리', '중',
  '로그온하지 않고 시스템 종료가 허용되면 비인가자가 서비스를 중단(DoS)할 수 있습니다. 종료를 인증된 사용자로 제한합니다.',
  [('cmt', '# 정책 확인'), ('prompt', 'PS> '), ('', 'findstr ShutdownWithoutLogon pol.cfg'),
   ('bad', 'ShutdownWithoutLogon = 1'), ('warn', '→ 비인가 종료 가능 (취약)')],
  [('cmt', '# 비활성화'), ('prompt', 'PS> '), ('', 'ShutdownWithoutLogon = 0'),
   ('good', 'ShutdownWithoutLogon = 0'), ('good', '→ 인증 후에만 종료 (양호)')],
  ['<code>보안 옵션 &gt; 로그온하지 않고 시스템 종료 허용</code>을 "사용 안 함"으로 설정합니다.'],
  ['로그온 없이 종료가 금지됨'],
  'Windows 보안 관리 > 로그온 없는 종료 금지'),

W('W-22', '익명 SID/이름 변환 금지', '🕵️', '보안 관리', '상',
  '익명 사용자가 SID↔계정명 변환을 할 수 있으면 계정 열거가 가능합니다. 허용하지 않도록 설정합니다.',
  [('cmt', '# 정책 확인'), ('prompt', 'PS> '), ('', 'findstr LSAAnonymousNameLookup pol.cfg'),
   ('bad', 'LSAAnonymousNameLookup = 1'), ('warn', '→ 익명 계정 열거 가능 (취약)')],
  [('cmt', '# 비활성화'), ('prompt', 'PS> '), ('', 'LSAAnonymousNameLookup = 0'),
   ('good', 'LSAAnonymousNameLookup = 0'), ('good', '→ 익명 변환 차단 (양호)')],
  ['<code>익명 SID/이름 변환 허용</code>을 "사용 안 함"으로 설정합니다.'],
  ['익명 SID/이름 변환이 금지됨'],
  'Windows 보안 관리 > 익명 SID/이름 변환'),

W('W-23', '익명 사용자 Everyone 권한 제외', '🚷', '보안 관리', '상',
  '"Everyone 권한을 익명 사용자에게 적용"이 켜져 있으면 익명 접근자가 공유·리소스에 접근할 수 있습니다. 비활성화해야 합니다.',
  [('cmt', '# 정책 확인'), ('prompt', 'PS> '), ('', 'reg query "...\\Lsa" /v EveryoneIncludesAnonymous'),
   ('bad', 'EveryoneIncludesAnonymous  0x1'), ('warn', '→ 익명에 Everyone 권한 (취약)')],
  [('cmt', '# 비활성화'), ('prompt', 'PS> '), ('', 'EveryoneIncludesAnonymous = 0'),
   ('good', 'EveryoneIncludesAnonymous  0x0'), ('good', '→ 익명 제외 (양호)')],
  ['<code>Everyone 권한을 익명 사용자에게 적용</code>을 "사용 안 함"으로 설정합니다.'],
  ['익명 사용자에 Everyone 권한이 적용되지 않음'],
  'Windows 보안 관리 > 익명 Everyone 권한'),

W('W-24', 'LAN Manager 인증 수준(NTLMv2)', '🔐', '보안 관리', '상',
  'LM/NTLMv1 인증은 크래킹·중계 공격에 취약합니다. NTLMv2만 허용하도록 인증 수준을 상향해야 합니다.',
  [('cmt', '# 인증 수준 확인'), ('prompt', 'PS> '), ('', 'reg query "...\\Lsa" /v LmCompatibilityLevel'),
   ('bad', 'LmCompatibilityLevel  0x0 (LM/NTLM 허용)'), ('warn', '→ 취약 인증 허용 (취약)')],
  [('cmt', '# NTLMv2만 허용'), ('prompt', 'PS> '), ('', 'LmCompatibilityLevel = 5'),
   ('good', 'LmCompatibilityLevel  0x5'), ('good', '→ NTLMv2 강제 (양호)')],
  ['<code>LAN Manager 인증 수준</code>을 "NTLMv2 응답만 보냄, LM/NTLM 거부"로 설정합니다.'],
  ['인증 수준이 NTLMv2로 상향됨', 'LM/NTLMv1이 거부됨'],
  'Windows 보안 관리 > LAN Manager 인증 수준'),

W('W-25', 'SAM 계정 익명 열거 제한', '📇', '보안 관리', '상',
  'RestrictAnonymous 미설정 시 익명 세션으로 계정·공유 목록을 열거할 수 있습니다. 익명 열거를 제한해야 합니다.',
  [('cmt', '# 설정 확인'), ('prompt', 'PS> '), ('', 'reg query "...\\Lsa" /v RestrictAnonymous'),
   ('bad', 'RestrictAnonymous  0x0'), ('warn', '→ 익명 계정/공유 열거 (취약)')],
  [('cmt', '# 익명 열거 제한'), ('prompt', 'PS> '), ('', 'RestrictAnonymous=1; RestrictAnonymousSAM=1'),
   ('good', 'RestrictAnonymous  0x1'), ('good', '→ 익명 열거 차단 (양호)')],
  ['<code>RestrictAnonymous</code>, <code>RestrictAnonymousSAM</code>을 1로 설정합니다.',
   '익명 세션 공유 접근(NullSessionShares)을 제거합니다.'],
  ['익명 SAM 계정 열거가 제한됨', '익명 세션 공유가 제거됨'],
  'Windows 보안 관리 > SAM 익명 열거 제한'),

W('W-26', '자동 로그온 비활성화', '🔁', '보안 관리', '상',
  '자동 로그온(AutoAdminLogon)이 켜져 있으면 레지스트리에 비밀번호가 평문 저장되고 물리 접근 시 즉시 로그인됩니다. 비활성화해야 합니다.',
  [('cmt', '# 자동 로그온 확인'), ('prompt', 'PS> '), ('', 'reg query "...\\Winlogon" /v AutoAdminLogon'),
   ('bad', 'AutoAdminLogon  1 / DefaultPassword 평문'), ('warn', '→ 평문 암호 저장+자동 로그인 (취약)')],
  [('cmt', '# 비활성화 + 평문 제거'), ('prompt', 'PS> '), ('', 'AutoAdminLogon=0; DefaultPassword 삭제'),
   ('good', 'AutoAdminLogon  0'), ('good', '→ 자동 로그온 해제 (양호)')],
  ['<code>AutoAdminLogon</code>을 0으로 설정하고 <code>DefaultPassword</code> 값을 삭제합니다.'],
  ['자동 로그온이 비활성화됨', '레지스트리 평문 암호가 제거됨'],
  'Windows 보안 관리 > 자동 로그온 비활성화'),

W('W-27', '백신·악성코드 보호 설치', '🛡️', '보안 관리', '상',
  '악성코드 보호 솔루션이 없거나 미갱신이면 랜섬웨어·악성코드에 노출됩니다. 백신을 설치·실시간 보호·정기 갱신해야 합니다.',
  [('cmt', '# 보호 상태 확인'), ('prompt', 'PS> '), ('', 'Get-MpComputerStatus | Select RealTimeProtectionEnabled,AntivirusSignatureAge'),
   ('bad', 'RealTimeProtection  False / 시그니처 60일'), ('warn', '→ 보호 미동작/미갱신 (취약)')],
  [('cmt', '# 실시간 보호+갱신'), ('prompt', 'PS> '), ('', 'Set-MpPreference -DisableRealtimeMonitoring $false; Update-MpSignature'),
   ('good', 'RealTimeProtection  True / 최신'), ('good', '→ 악성코드 보호 동작 (양호)')],
  ['백신/EDR을 설치하고 실시간 보호를 활성화합니다.',
   '시그니처를 자동 갱신하고 정기 전체 검사를 수행합니다.'],
  ['악성코드 보호가 실시간 동작함', '시그니처가 최신으로 갱신됨'],
  'Windows 보안 관리 > 악성코드 보호'),

W('W-28', '시스템 로깅(NTP 시각 동기화)', '⏲️', '보안 관리', '중',
  '시스템 시각이 동기화되지 않으면 로그 시각이 어긋나 사고 분석·상관분석이 어렵습니다. NTP로 신뢰 시각원과 동기화해야 합니다.',
  [('cmt', '# 시간 동기화 확인'), ('prompt', 'PS> '), ('', 'w32tm /query /status'),
   ('bad', 'Source: Local CMOS Clock'), ('warn', '→ 시각 미동기화 (취약)')],
  [('cmt', '# NTP 동기화'), ('prompt', 'PS> '), ('', 'w32tm /config /manualpeerlist:"time.bora.net" /syncfromflags:manual /update'),
   ('good', 'Source: time.bora.net (NTP)'), ('good', '→ 시각 동기화 (양호)')],
  ['신뢰할 수 있는 NTP 서버와 시각을 동기화합니다.',
   '로그 시각 일관성을 확보해 사고 분석 정확도를 높입니다.'],
  ['NTP 시각 동기화가 설정됨', '로그 시각이 일관됨'],
  'Windows 보안 관리 > 시각 동기화/로깅'),
]
