# -*- coding: utf-8 -*-
"""주요정보통신기반시설 네트워크 장비(라우터/스위치, Cisco IOS 기준) 보안 점검 항목."""

HOST = 'Router#'


def N(code, title, icon, cat, sev, desc, vt, st, fixes, chk, ref):
    return {'file': '09_net-%s.html' % code.lower().replace('-', ''),
            'code': code, 'title': title, 'icon': icon, 'category': '네트워크 장비 · ' + cat, 'severity': sev,
            'description': desc, 'vuln_term': vt, 'secure_term': st, 'host': HOST,
            'fix_steps': fixes, 'checklist': chk, 'kisa_ref': ref}


SPECS = [
# ===== 계정 관리 =====
N('N-01', 'enable 비밀번호 설정(secret)', '🔑', '계정 관리', '상',
  '특권(enable) 모드에 비밀번호가 없거나 평문 enable password를 쓰면 장비 전체 설정이 탈취됩니다. 단방향 해시 enable secret을 설정해야 합니다.',
  [('cmt', '! 특권 비밀번호 확인'), ('prompt', '# '), ('', 'show running-config | include enable'),
   ('bad', 'enable password cisco'), ('warn', '→ 평문/취약 enable 비밀번호 (취약)')],
  [('cmt', '! enable secret 설정'), ('prompt', '# '), ('', 'enable secret <complex>'),
   ('good', 'enable secret 5 $1$...'), ('good', '→ 해시 특권 비밀번호 (양호)')],
  ['<code>enable secret</code>(MD5 이상 해시)으로 특권 비밀번호를 설정합니다.',
   '평문 <code>enable password</code> 라인을 제거합니다.'],
  ['enable secret이 설정됨', '평문 enable password가 제거됨'],
  '네트워크 계정 관리 > enable 비밀번호'),

N('N-02', '비밀번호 복잡도 정책', '🔣', '계정 관리', '중',
  '단순한 장비 비밀번호는 무차별 대입·추측에 취약합니다. 길이·복잡도 정책을 적용해야 합니다.',
  [('cmt', '! 비밀번호 정책 확인'), ('prompt', '# '), ('', 'show run | include username|security passwords'),
   ('bad', 'username admin password admin'), ('warn', '→ 단순 비밀번호 허용 (취약)')],
  [('cmt', '! 최소 길이/복잡도'), ('prompt', '# '), ('', 'security passwords min-length 8'),
   ('good', 'min-length 8 + 복잡 비밀번호'), ('good', '→ 복잡도 정책 적용 (양호)')],
  ['<code>security passwords min-length 8</code> 등 최소 길이를 강제합니다.',
   '영문 대소문자·숫자·특수문자를 조합한 비밀번호를 사용합니다.'],
  ['비밀번호 최소 길이/복잡도가 적용됨'],
  '네트워크 계정 관리 > 비밀번호 복잡도'),

N('N-03', '사용자별 계정 및 권한', '👥', '계정 관리', '중',
  '공용 계정 하나로 운영하면 행위 추적이 불가하고 권한 분리가 안 됩니다. 사용자별 계정과 권한 수준을 부여해야 합니다.',
  [('cmt', '! 계정 구성 확인'), ('prompt', '# '), ('', 'show run | include username'),
   ('bad', 'username admin privilege 15 (공용)'), ('warn', '→ 공용 계정 단일 사용 (취약)')],
  [('cmt', '! 사용자별 계정/권한'), ('prompt', '# '), ('', 'username op1 privilege 7 secret ...'),
   ('good', '사용자별 계정 + 최소 권한'), ('good', '→ 권한 분리 (양호)')],
  ['운영자별 개별 계정을 생성하고 업무에 맞는 privilege level을 부여합니다.',
   'AAA(TACACS+/RADIUS) 연동으로 중앙 인증·감사를 적용합니다.'],
  ['사용자별 계정이 구성됨', '권한 수준이 최소화됨'],
  '네트워크 계정 관리 > 사용자별 계정/권한'),

N('N-04', '비밀번호 암호화(service password-encryption)', '🔐', '계정 관리', '상',
  '설정 파일에 비밀번호가 평문으로 노출되면 백업·화면 캡처로 유출됩니다. service password-encryption으로 평문 노출을 막아야 합니다.',
  [('cmt', '! 평문 비밀번호 노출 확인'), ('prompt', '# '), ('', 'show run | include password'),
   ('bad', 'line vty 0 4  password cisco123 (평문)'), ('warn', '→ 설정 내 평문 노출 (취약)')],
  [('cmt', '! 암호화 적용'), ('prompt', '# '), ('', 'service password-encryption'),
   ('good', 'password 7 0822455D0A16'), ('good', '→ 평문 노출 제거 (양호)')],
  ['<code>service password-encryption</code>을 적용해 설정 내 평문 비밀번호를 숨깁니다.',
   '가능하면 단방향 해시(secret)를 우선 사용합니다(type 7은 복호화 가능하므로 보조 수단).'],
  ['service password-encryption이 적용됨', '핵심 비밀번호는 secret(해시)로 설정됨'],
  '네트워크 계정 관리 > 비밀번호 암호화'),

# ===== 접근 관리 =====
N('N-05', 'VTY 접근 ACL 제한', '🚪', '접근 관리', '상',
  '원격 관리(VTY) 접근이 모든 IP에 열려 있으면 외부에서 장비 관리 인터페이스에 접근할 수 있습니다. 관리 대역만 허용하는 ACL을 적용해야 합니다.',
  [('cmt', '! VTY 접근제어 확인'), ('prompt', '# '), ('', 'show run | section line vty'),
   ('bad', 'line vty 0 4  (access-class 없음)'), ('warn', '→ 모든 IP에서 관리 접근 (취약)')],
  [('cmt', '! 관리 대역만 허용'), ('prompt', '# '), ('', 'access-class 10 in  (ACL 10 permit mgmt)'),
   ('good', 'access-class 10 in'), ('good', '→ 관리 대역만 접근 (양호)')],
  ['관리 대역만 허용하는 표준 ACL을 만들어 <code>line vty</code>에 <code>access-class in</code>으로 적용합니다.',
   '관리 트래픽을 별도 망/대역으로 분리합니다.'],
  ['VTY에 접근 ACL이 적용됨', '관리 대역으로 접근이 제한됨'],
  '네트워크 접근 관리 > VTY 접근 제한'),

N('N-06', 'SSH 사용 / Telnet 비활성화', '🔒', '접근 관리', '상',
  'Telnet은 평문 통신으로 자격증명이 스니핑됩니다. 암호화된 SSH만 허용하고 Telnet을 비활성화해야 합니다.',
  [('cmt', '! 전송 프로토콜 확인'), ('prompt', '# '), ('', 'show run | section line vty'),
   ('bad', 'transport input telnet'), ('warn', '→ 평문 Telnet 허용 (취약)')],
  [('cmt', '! SSH만 허용'), ('prompt', '# '), ('', 'transport input ssh ; ip ssh version 2'),
   ('good', 'transport input ssh'), ('good', '→ SSHv2만 허용 (양호)')],
  ['<code>transport input ssh</code>로 SSH만 허용하고 Telnet을 차단합니다.',
   '<code>ip ssh version 2</code> 및 RSA 키(2048bit 이상)를 생성합니다.'],
  ['Telnet이 비활성화됨', 'SSHv2만 허용됨'],
  '네트워크 접근 관리 > SSH 사용'),

N('N-07', '세션 타임아웃(exec-timeout)', '⏲️', '접근 관리', '중',
  '유휴 세션이 자동 종료되지 않으면 자리 비움 시 세션이 탈취될 수 있습니다. exec-timeout을 설정해야 합니다.',
  [('cmt', '! 타임아웃 확인'), ('prompt', '# '), ('', 'show run | section line'),
   ('bad', 'exec-timeout 0 0 (무제한)'), ('warn', '→ 세션 무한 유지 (취약)')],
  [('cmt', '! 타임아웃 설정'), ('prompt', '# '), ('', 'exec-timeout 5 0'),
   ('good', 'exec-timeout 5 0'), ('good', '→ 5분 후 자동 종료 (양호)')],
  ['콘솔/VTY에 <code>exec-timeout</code>(예: 5분)을 설정합니다.',
   '<code>service tcp-keepalives-in</code>으로 유휴 세션을 정리합니다.'],
  ['exec-timeout이 설정됨(무제한 아님)'],
  '네트워크 접근 관리 > 세션 타임아웃'),

N('N-08', '로그인 실패 제한 및 경고 배너', '🚧', '접근 관리', '중',
  '로그인 시도 제한과 경고 배너가 없으면 무차별 대입에 취약하고 법적 고지가 미흡합니다. 실패 제한과 배너를 설정해야 합니다.',
  [('cmt', '! 로그인 보호 확인'), ('prompt', '# '), ('', 'show run | include login block|banner'),
   ('bad', '(login block/banner 없음)'), ('warn', '→ 무차별 대입 방어/고지 미흡 (취약)')],
  [('cmt', '! 실패 제한 + 배너'), ('prompt', '# '), ('', 'login block-for 60 attempts 5 within 60 ; banner login ^...^'),
   ('good', 'login block-for + banner'), ('good', '→ 대입 방어/경고 고지 (양호)')],
  ['<code>login block-for</code>로 실패 임계 초과 시 일정 시간 차단합니다.',
   '<code>banner login</code>으로 비인가 접근 경고 문구를 표시합니다.'],
  ['로그인 실패 제한이 설정됨', '접근 경고 배너가 설정됨'],
  '네트워크 접근 관리 > 로그인 실패 제한/배너'),

N('N-09', 'SNMP Community 복잡도 + ACL', '📶', '접근 관리', '상',
  'SNMP community가 기본값(public/private)이거나 ACL이 없으면 장비 정보 조회·변조가 가능합니다. 복잡한 값과 접근 ACL을 적용해야 합니다.',
  [('cmt', '! SNMP 확인'), ('prompt', '# '), ('', 'show run | include snmp-server community'),
   ('bad', 'snmp-server community public RO'), ('warn', '→ 기본 community, ACL 없음 (취약)')],
  [('cmt', '! 복잡 community + ACL'), ('prompt', '# '), ('', 'snmp-server community Str0ng#Ro RO 20'),
   ('good', 'community + access-list 20'), ('good', '→ 복잡도+소스 제한 (양호)')],
  ['public/private 기본값을 제거하고 추측 어려운 community로 변경합니다.',
   'community에 ACL을 결합해 관리 호스트만 허용합니다.',
   '가능하면 인증·암호화를 지원하는 <code>SNMPv3</code>를 사용합니다.'],
  ['기본 community가 변경됨', 'SNMP 접근 ACL이 적용됨', 'SNMPv3 사용 검토'],
  '네트워크 접근 관리 > SNMP Community'),

N('N-10', 'SNMP 쓰기(RW) 권한 제한', '✍️', '접근 관리', '상',
  'SNMP 쓰기(RW) 커뮤니티가 열려 있으면 원격에서 장비 설정을 변경할 수 있습니다. RW를 제거하거나 엄격히 제한해야 합니다.',
  [('cmt', '! RW community 확인'), ('prompt', '# '), ('', 'show run | include community.*RW'),
   ('bad', 'snmp-server community private RW'), ('warn', '→ 원격 설정 변경 가능 (취약)')],
  [('cmt', '! RW 제거/제한'), ('prompt', '# '), ('', 'no snmp-server community private RW'),
   ('good', 'RO만 유지 또는 SNMPv3 write 제한'), ('good', '→ 쓰기 권한 제거 (양호)')],
  ['불필요한 <code>RW</code> community를 제거합니다.',
   '쓰기가 필요하면 SNMPv3 + 엄격한 ACL로 제한합니다.'],
  ['SNMP RW community가 제거/제한됨'],
  '네트워크 접근 관리 > SNMP 쓰기 권한'),

# ===== 기능 관리 =====
N('N-11', '불필요한 CDP 비활성화', '📡', '기능 관리', '중',
  'CDP(Cisco Discovery Protocol)는 장비 정보(모델, IOS, IP)를 인접 장비에 노출해 정찰에 악용됩니다. 불필요한 인터페이스에서 비활성화합니다.',
  [('cmt', '! CDP 상태 확인'), ('prompt', '# '), ('', 'show cdp'),
   ('bad', 'CDP is globally enabled'), ('warn', '→ 장비 정보 노출 (취약)')],
  [('cmt', '! CDP 비활성화'), ('prompt', '# '), ('', 'no cdp run  (또는 인터페이스별 no cdp enable)'),
   ('good', 'CDP disabled on edge'), ('good', '→ 정보 노출 차단 (양호)')],
  ['외부/불필요 인터페이스에서 <code>no cdp enable</code>, 전역 불필요 시 <code>no cdp run</code>.'],
  ['불필요한 CDP가 비활성화됨'],
  '네트워크 기능 관리 > CDP'),

N('N-12', 'HTTP 관리 서비스 제한', '🌐', '기능 관리', '상',
  '평문 HTTP 관리 서버가 켜져 있으면 자격증명 스니핑·웹 취약점 공격에 노출됩니다. HTTP를 끄고 필요 시 HTTPS+ACL을 사용합니다.',
  [('cmt', '! 웹 관리 확인'), ('prompt', '# '), ('', 'show run | include ip http'),
   ('bad', 'ip http server'), ('warn', '→ 평문 HTTP 관리 (취약)')],
  [('cmt', '! HTTP off / HTTPS+ACL'), ('prompt', '# '), ('', 'no ip http server ; ip http secure-server ; ip http access-class 10'),
   ('good', 'HTTPS + access-class'), ('good', '→ 안전한 관리만 허용 (양호)')],
  ['<code>no ip http server</code>로 평문 HTTP를 비활성화합니다.',
   '웹 관리가 필요하면 <code>ip http secure-server</code> + <code>access-class</code>로 제한합니다.'],
  ['평문 HTTP 관리가 비활성화됨', '필요 시 HTTPS+ACL로 제한됨'],
  '네트워크 기능 관리 > HTTP 관리 서비스'),

N('N-13', '불필요 서비스(finger/bootp/source-route)', '🧯', '기능 관리', '중',
  'finger, bootp, IP source routing 등 불필요한 서비스는 정보 노출·우회 공격에 악용됩니다. 비활성화해야 합니다.',
  [('cmt', '! 서비스 확인'), ('prompt', '# '), ('', 'show run | include finger|bootp|source-route'),
   ('bad', 'ip source-route / service finger'), ('warn', '→ 불필요 서비스 활성 (취약)')],
  [('cmt', '! 비활성화'), ('prompt', '# '), ('', 'no ip source-route ; no service finger ; no ip bootp server'),
   ('good', '불필요 서비스 off'), ('good', '→ 공격 표면 축소 (양호)')],
  ['<code>no ip source-route</code>, <code>no service finger</code>, <code>no ip bootp server</code> 등을 적용합니다.'],
  ['불필요 서비스(finger/bootp/source-route)가 비활성화됨'],
  '네트워크 기능 관리 > 불필요 서비스'),

N('N-14', 'Directed Broadcast 차단', '📣', '기능 관리', '상',
  'directed broadcast가 허용되면 Smurf 등 증폭 DoS 공격의 중계지가 됩니다. 인터페이스에서 차단해야 합니다.',
  [('cmt', '! 설정 확인'), ('prompt', '# '), ('', 'show run | include directed-broadcast'),
   ('bad', 'ip directed-broadcast'), ('warn', '→ 증폭 DoS 중계 (취약)')],
  [('cmt', '! 차단'), ('prompt', '# '), ('', 'no ip directed-broadcast'),
   ('good', '(default no directed-broadcast)'), ('good', '→ 증폭 DoS 차단 (양호)')],
  ['모든 인터페이스에서 <code>no ip directed-broadcast</code>를 적용합니다.'],
  ['directed broadcast가 차단됨'],
  '네트워크 기능 관리 > Directed Broadcast'),

N('N-15', 'ICMP redirect/unreachable 제한', '↩️', '기능 관리', '중',
  'ICMP redirect/unreachable이 무분별하게 허용되면 라우팅 조작·정찰에 악용될 수 있습니다. 외부 인터페이스에서 제한합니다.',
  [('cmt', '! 설정 확인'), ('prompt', '# '), ('', 'show run interface | include redirects|unreachables'),
   ('bad', 'ip redirects / ip unreachables'), ('warn', '→ 라우팅 조작/정찰 가능 (취약)')],
  [('cmt', '! 제한'), ('prompt', '# '), ('', 'no ip redirects ; no ip unreachables'),
   ('good', 'redirects/unreachables off (edge)'), ('good', '→ 정보 노출 제한 (양호)')],
  ['외부 인터페이스에서 <code>no ip redirects</code>, <code>no ip unreachables</code>를 적용합니다.'],
  ['ICMP redirect/unreachable이 외부 인터페이스에서 제한됨'],
  '네트워크 기능 관리 > ICMP 제한'),

N('N-16', 'Proxy ARP 비활성화', '🔁', '기능 관리', '중',
  'Proxy ARP는 호스트 위장·중간자 공격에 악용될 수 있습니다. 불필요하면 인터페이스에서 비활성화합니다.',
  [('cmt', '! proxy-arp 확인'), ('prompt', '# '), ('', 'show ip interface | include Proxy ARP'),
   ('bad', 'Proxy ARP is enabled'), ('warn', '→ 호스트 위장 위험 (취약)')],
  [('cmt', '! 비활성화'), ('prompt', '# '), ('', 'no ip proxy-arp'),
   ('good', 'Proxy ARP is disabled'), ('good', '→ MITM 위험 감소 (양호)')],
  ['<code>no ip proxy-arp</code>를 적용합니다(불필요한 인터페이스).'],
  ['Proxy ARP가 비활성화됨'],
  '네트워크 기능 관리 > Proxy ARP'),

N('N-17', 'TFTP/원격 설정 전송 제한', '📦', '기능 관리', '중',
  'TFTP는 인증 없는 평문 전송으로 설정 파일이 탈취·변조될 수 있습니다. 사용을 제한하고 보안 전송(SCP)을 사용합니다.',
  [('cmt', '! 전송 방식 확인'), ('prompt', '# '), ('', 'show run | include tftp'),
   ('bad', 'tftp-server flash:config'), ('warn', '→ 인증 없는 설정 전송 (취약)')],
  [('cmt', '! SCP 사용/TFTP 제한'), ('prompt', '# '), ('', 'no tftp-server ... ; ip scp server enable'),
   ('good', 'SCP(SSH 기반) 사용'), ('good', '→ 보안 전송 (양호)')],
  ['불필요한 <code>tftp-server</code> 설정을 제거합니다.',
   '설정 전송은 <code>SCP</code>(SSH 기반) 등 인증·암호화 방식을 사용합니다.'],
  ['TFTP 설정 전송이 제한됨', '보안 전송(SCP)이 사용됨'],
  '네트워크 기능 관리 > 설정 전송 보안'),

# ===== 패치/로그 관리 =====
N('N-18', '최신 OS(IOS) 패치', '🩹', '패치 관리', '상',
  '구버전 네트워크 OS는 알려진 원격 취약점에 노출됩니다. 벤더 권고 보안 버전으로 유지해야 합니다.',
  [('cmt', '! OS 버전 확인'), ('prompt', '# '), ('', 'show version | include Version'),
   ('bad', 'IOS Version 12.2 (EOL)'), ('warn', '→ 취약점 다수의 EOL 버전 (취약)')],
  [('cmt', '! 권고 버전 적용'), ('prompt', '# '), ('', '(이미지 업그레이드 후) show version'),
   ('good', '권고 보안 버전'), ('good', '→ 최신 패치 (양호)')],
  ['벤더 보안 권고에 따라 IOS/OS 이미지를 최신 안정 버전으로 업그레이드합니다.',
   '업그레이드 전 영향도 검토와 설정 백업을 수행합니다.'],
  ['네트워크 OS가 권고 보안 버전인가', '정기 패치 절차가 운영됨'],
  '네트워크 패치 관리 > OS 패치'),

N('N-19', '로깅(Syslog) 서버 설정', '🧾', '로그 관리', '중',
  '로그가 장비에만 저장되거나 미설정이면 침해 분석이 어렵습니다. 중앙 Syslog 서버로 로그를 전송·보관해야 합니다.',
  [('cmt', '! 로깅 확인'), ('prompt', '# '), ('', 'show run | include logging'),
   ('bad', '(logging host 없음)'), ('warn', '→ 중앙 로그 미수집 (취약)')],
  [('cmt', '! Syslog 전송'), ('prompt', '# '), ('', 'logging host 10.0.0.20 ; logging trap informational'),
   ('good', 'logging host + trap level'), ('good', '→ 중앙 로그 수집 (양호)')],
  ['<code>logging host</code>로 중앙 Syslog 서버에 로그를 전송합니다.',
   '적절한 <code>logging trap</code> 레벨과 타임스탬프를 설정합니다.'],
  ['중앙 Syslog 전송이 설정됨', '로그 레벨/타임스탬프가 적절함'],
  '네트워크 로그 관리 > Syslog'),

N('N-20', 'NTP 시각 동기화', '🕰️', '로그 관리', '중',
  '장비 시각이 동기화되지 않으면 로그 시각이 어긋나 상관분석이 어렵습니다. 신뢰 NTP 서버와 동기화해야 합니다.',
  [('cmt', '! 시간 동기화 확인'), ('prompt', '# '), ('', 'show ntp status'),
   ('bad', 'clock is unsynchronized'), ('warn', '→ 시각 미동기화 (취약)')],
  [('cmt', '! NTP 설정'), ('prompt', '# '), ('', 'ntp server 10.0.0.30 ; ntp authenticate'),
   ('good', 'clock is synchronized'), ('good', '→ 시각 동기화 (양호)')],
  ['<code>ntp server</code>로 신뢰 NTP와 동기화하고 인증(ntp authenticate)을 적용합니다.',
   '로그 타임스탬프를 NTP 기준으로 설정합니다.'],
  ['NTP 시각 동기화가 설정됨', 'NTP 인증이 적용됨'],
  '네트워크 로그 관리 > NTP'),

N('N-21', '미사용 인터페이스 셧다운', '🔌', '기능 관리', '중',
  '미사용 포트가 활성 상태이면 비인가 단말이 네트워크에 무단 연결될 수 있습니다. 사용하지 않는 인터페이스는 shutdown해야 합니다.',
  [('cmt', '! 인터페이스 상태'), ('prompt', '# '), ('', 'show ip interface brief'),
   ('bad', 'Gi0/10  up  up  (미사용인데 활성)'), ('warn', '→ 비인가 단말 연결 가능 (취약)')],
  [('cmt', '! 미사용 포트 차단'), ('prompt', '# '), ('', 'interface Gi0/10 ; shutdown'),
   ('good', 'Gi0/10  administratively down'), ('good', '→ 미사용 포트 차단 (양호)')],
  ['미사용 인터페이스를 <code>shutdown</code>하고 미사용 VLAN에 격리합니다.',
   '스위치 포트에 <code>port-security</code>를 적용해 MAC을 제한합니다.'],
  ['미사용 인터페이스가 shutdown됨', '필요 시 port-security가 적용됨'],
  '네트워크 기능 관리 > 미사용 포트'),
]
