# -*- coding: utf-8 -*-
"""보안장비(방화벽/IPS/IDS/VPN) 점검 항목 동적 공격 시연 데이터."""

DYN = {
 'S-01': {
   'easy': '기본 비밀번호 admin/admin은 <b>새 자물쇠에 붙어 온 공장 열쇠</b>를 그대로 꽂아 둔 것과 같습니다. 그 만능열쇠는 인터넷에 다 공개돼 있어서, 누구나 똑같은 열쇠로 장비를 통째로 열 수 있습니다.',
   'attack_label': '공격자가 기본 자격증명으로 방화벽 관리화면에 로그인한다',
   'attack_vuln': [
     ['cmt', '# 공개된 기본 계정으로 로그인 시도'],
     ['prompt', 'attacker$ curl -k https://secgw/login -d user=admin -d pass=admin'],
     ['bad', '>> 로그인 성공! (admin / admin)'],
     ['bad', '>> 방화벽 정책 전체 수정 권한 획득 — 장비 장악'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 장비 장악','desc':'알려진 기본값 그대로라 추측도 필요 없이 곧장 로그인됩니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 기본 자격증명으로 로그인 시도'],
     ['prompt', 'attacker$ curl -k https://secgw/login -d user=admin -d pass=admin'],
     ['good', '>> 401 Unauthorized (비밀번호 불일치)'],
     ['warn', '>> 기본값이 제거되어 추측 로그인 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 로그인 실패','desc':'기본 비밀번호를 바꿔 두면 공개된 만능열쇠가 통하지 않습니다.'},
 },
 'S-02': {
   'easy': '비밀번호가 4자리 숫자면 <b>자전거 번호 자물쇠</b>처럼 끝까지 돌려보면 열립니다. 길고 복잡하게 만들면, 가능한 조합이 너무 많아 다 돌려보기 전에 포기하게 됩니다.',
   'attack_label': '공격자가 단순 비밀번호를 무차별 대입으로 알아낸다',
   'attack_vuln': [
     ['cmt', '# 짧은 비밀번호라 사전공격으로 빠르게 탐색'],
     ['prompt', 'attacker$ hydra -l admin -P 4digit.txt secgw https-form'],
     ['', '>> 시도: 0000 ... 1234 ...'],
     ['bad', '>> [SUCCESS] password: 1234'],
     ['bad', '>> 단순 비밀번호라 수초 만에 탈취'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 비밀번호 탈취','desc':'길이·복잡도 정책이 없어 약한 비밀번호가 곧장 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 무차별 대입 시도'],
     ['prompt', 'attacker$ hydra -l admin -P 4digit.txt secgw https-form'],
     ['good', '>> 모든 후보 실패 (정책상 8자+복잡도 필요)'],
     ['warn', '>> 조합이 방대해 현실적으로 탐색 불가'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 대입 실패','desc':'길고 복잡한 비밀번호는 가능한 조합이 너무 많아 뚫리지 않습니다.'},
 },
 'S-03': {
   'easy': '잠금 정책이 없으면 도둑이 <b>열쇠를 무한정 바꿔 끼워볼</b> 수 있습니다. 5번 틀리면 잠그도록 하면, 몇 번 시도하다 막혀서 더는 돌려보지 못합니다.',
   'attack_label': '공격자가 잠금 없이 관리 로그인을 무제한 시도한다',
   'attack_vuln': [
     ['cmt', '# 잠금이 없어 끝없이 비밀번호 추측'],
     ['prompt', 'attacker$ hydra -l admin -P rockyou.txt secgw https-form'],
     ['', '>> 시도 1회 ... 5만회 ... 100만회 (차단 없음)'],
     ['bad', '>> [SUCCESS] password: Summer2024!'],
     ['bad', '>> 무제한 대입으로 결국 통과'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 무차별 대입 통과','desc':'실패 잠금이 없어 시간만 들이면 비밀번호가 결국 뚫립니다.'},
   'attack_secure': [
     ['cmt', '# 동일하게 대량 추측 시도'],
     ['prompt', 'attacker$ hydra -l admin -P rockyou.txt secgw https-form'],
     ['good', '>> 5회 실패 후 계정 잠금 (10분 차단)'],
     ['warn', '>> 시도가 막혀 대입 공격 중단'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 계정 잠금','desc':'몇 번 틀리면 잠기므로 무차별 대입을 이어갈 수 없습니다.'},
 },
 'S-04': {
   'easy': '모두가 같은 <b>공용 출입카드</b>를 돌려 쓰면, 사고가 나도 누가 했는지 알 수 없고 모두가 모든 문을 엽니다. 사람마다 카드를 주고 필요한 문만 열리게 하면, 책임도 분명하고 권한도 딱 맞습니다.',
   'attack_label': '공격자가 공용 계정 뒤에 숨어 흔적 없이 설정을 바꾼다',
   'attack_vuln': [
     ['cmt', '# 모두가 공유하는 공용 admin 계정 사용'],
     ['prompt', 'attacker$ ssh admin@secgw  (탈취한 공용 비밀번호)'],
     ['bad', '>> 공용 계정이라 누가 접속했는지 식별 불가'],
     ['bad', '>> 전권 보유 계정으로 정책 변경 후 흔적 은폐'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 추적 불가 변경','desc':'공용 계정 한 개라 행위 추적이 안 되고 권한도 과다합니다.'},
   'attack_secure': [
     ['cmt', '# 사용자별 계정 + 최소 역할 적용 후 동일 시도'],
     ['prompt', 'attacker$ ssh op1@secgw'],
     ['good', '>> op1은 read-only 역할 — 정책 변경 거부'],
     ['warn', '>> 모든 접속이 계정별로 감사 로그에 기록됨'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 권한 분리·추적','desc':'계정이 분리되고 최소 권한이라 변경 시도가 막히고 기록됩니다.'},
 },
 'S-05': {
   'easy': '관리화면이 모든 IP에 열려 있으면 <b>금고 다이얼을 길거리 쪽으로 돌려 둔</b> 셈입니다. 지나가던 누구나 손댈 수 있죠. 관리 대역만 허용하면, 정해진 사람만 그 방에 들어와 만질 수 있습니다.',
   'attack_label': '인터넷의 공격자가 외부에서 방화벽 관리화면에 접근한다',
   'attack_vuln': [
     ['cmt', '# 인터넷에서 관리 포트가 그대로 열려 있음'],
     ['prompt', 'attacker$ curl -k https://1.2.3.4:443/admin/login'],
     ['bad', '>> 관리 로그인 페이지 응답 (외부 접근 허용)'],
     ['bad', '>> 외부에서 곧장 자격증명 공격 개시'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 외부 접근 노출','desc':'permit any라 인터넷 어디서나 관리화면에 닿을 수 있습니다.'},
   'attack_secure': [
     ['cmt', '# 관리 대역만 허용 후 외부에서 동일 접근'],
     ['prompt', 'attacker$ curl -k https://1.2.3.4:443/admin/login'],
     ['good', '>> 연결 거부 (trusted-host 10.0.0.0/24만 허용)'],
     ['warn', '>> 관리 대역 밖이라 관리화면에 닿지 못함'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 접근 거부','desc':'허용 대역으로 제한하면 외부에서는 관리화면이 보이지 않습니다.'},
 },
 'S-06': {
   'easy': 'HTTP·Telnet 관리는 비밀번호를 <b>엽서에 적어 보내는</b> 것과 같아, 같은 네트워크의 누구나 읽을 수 있습니다. HTTPS·SSH는 밀봉된 봉투라 가로채도 속을 볼 수 없습니다.',
   'attack_label': '같은 네트워크의 공격자가 평문 관리 접속을 도청한다',
   'attack_vuln': [
     ['cmt', '# 평문 HTTP 관리 트래픽 도청'],
     ['prompt', 'attacker$ tcpdump -i eth0 port 80 -A'],
     ['bad', '>> POST /login user=admin pass=P@ssw0rd!'],
     ['bad', '>> 평문 그대로 자격증명 탈취 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 자격증명 도청','desc':'HTTP/Telnet은 평문이라 도청만으로 비밀번호가 새어 나갑니다.'},
   'attack_secure': [
     ['cmt', '# HTTPS/SSH만 허용된 상태에서 동일 도청'],
     ['prompt', 'attacker$ tcpdump -i eth0 port 443 -A'],
     ['good', '>> 8f a1 3e ... (암호문, 해독 불가)'],
     ['warn', '>> 평문 관리 차단 — 비밀번호를 읽을 수 없음'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 도청 실패','desc':'암호화 관리만 허용하면 가로채도 자격증명을 알 수 없습니다.'},
 },
 'S-07': {
   'easy': '관리 세션이 안 끊기면, 자리를 비운 사이 <b>열려 있는 PC</b>처럼 누구나 와서 이어서 조작할 수 있습니다. 5분 후 자동 종료되게 하면, 잠깐 비워도 곧 잠겨 안전합니다.',
   'attack_label': '공격자가 자리 비운 관리자의 살아 있는 세션을 가로챈다',
   'attack_vuln': [
     ['cmt', '# 타임아웃이 없어 세션이 계속 살아 있음'],
     ['prompt', 'attacker$ curl -k -b "session=ABC123" https://secgw/admin/policy'],
     ['bad', '>> 200 OK (관리자가 자리 비운 지 2시간, 세션 유효)'],
     ['bad', '>> 남은 세션을 그대로 이어받아 설정 변경'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 세션 탈취','desc':'유휴 타임아웃이 0이라 방치된 세션이 무한히 유효합니다.'},
   'attack_secure': [
     ['cmt', '# 5분 유휴 타임아웃 설정 후 동일 시도'],
     ['prompt', 'attacker$ curl -k -b "session=ABC123" https://secgw/admin/policy'],
     ['good', '>> 440 Session Expired (유휴 5분 초과)'],
     ['warn', '>> 세션이 이미 종료되어 이어받기 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 세션 만료','desc':'유휴 타임아웃이 있으면 방치된 세션이 곧 끊겨 탈취되지 않습니다.'},
 },
 'S-08': {
   'easy': '관리 통로와 서비스 통로가 같으면, <b>손님 출입문으로 금고실까지</b> 이어진 셈이라 손님 중 누군가 관리실을 노릴 수 있습니다. 관리 전용 뒷문(OOB)을 따로 두면, 서비스 쪽에서는 관리실에 닿지 못합니다.',
   'attack_label': '서비스망에 침투한 공격자가 같은 경로로 관리 포트를 노린다',
   'attack_vuln': [
     ['cmt', '# 관리가 서비스 인터페이스를 공유 — 같은 망에서 도달'],
     ['prompt', 'attacker$ nmap -p 22,443 10.0.5.1   (서비스망 내부에서)'],
     ['bad', '>> 22/tcp open, 443/tcp open (관리 포트 노출)'],
     ['bad', '>> 서비스망 발판으로 관리 인터페이스 공격'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 관리 포트 도달','desc':'관리·서비스가 한 경로라 서비스망 침투만으로 관리에 닿습니다.'},
   'attack_secure': [
     ['cmt', '# 전용 OOB 관리 포트로 분리 후 동일 스캔'],
     ['prompt', 'attacker$ nmap -p 22,443 10.0.5.1   (서비스망 내부에서)'],
     ['good', '>> 22/tcp filtered, 443/tcp filtered'],
     ['warn', '>> 관리는 분리된 OOB 망 — 서비스망에서 닿지 못함'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 관리망 분리','desc':'전용 관리망으로 분리하면 서비스망에서는 관리에 접근할 수 없습니다.'},
 },
 'S-09': {
   'easy': 'SNMP community가 public/private 기본값이면 <b>비밀번호가 "비밀번호"인 금고</b>와 같습니다. public으로 안을 다 들여다보고, private(쓰기)로는 설정까지 바꿔 버릴 수 있습니다.',
   'attack_label': '공격자가 기본 community로 장비 정보를 조회·변조한다',
   'attack_vuln': [
     ['cmt', '# 기본 community public(읽기)으로 설정 덤프'],
     ['prompt', 'attacker$ snmpwalk -v2c -c public secgw'],
     ['bad', '>> 인터페이스/라우팅/계정 정보 전부 노출'],
     ['cmt', '# private(쓰기)로 설정 변조'],
     ['prompt', 'attacker$ snmpset -v2c -c private secgw ifAdminStatus.2 = down'],
     ['bad', '>> 포트를 강제 down — 설정 변조 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 조회·변조','desc':'기본 community라 장비 정보가 새고 설정까지 바뀝니다.'},
   'attack_secure': [
     ['cmt', '# SNMPv3(인증·암호화)+ACL 적용 후 동일 시도'],
     ['prompt', 'attacker$ snmpwalk -v2c -c public secgw'],
     ['good', '>> Timeout (기본 community 제거, v2c 거부)'],
     ['warn', '>> v3 인증·ACL이 없어 조회·변조 모두 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 접근 거부','desc':'기본 community를 없애고 SNMPv3+ACL을 쓰면 통하지 않습니다.'},
 },
 'S-10': {
   'easy': 'Any-Any 허용 룰은 <b>모든 문을 활짝 열어 둔</b> 것과 같아 방화벽이 있으나 마나입니다. 출발지·목적지·포트를 콕 집어 허용하면, 정해진 통로 외에는 모두 막힙니다.',
   'attack_label': '공격자가 무력화된 방화벽을 통해 내부 호스트로 자유롭게 이동한다',
   'attack_vuln': [
     ['cmt', '# any->any allow 룰이라 내부로 자유 이동'],
     ['prompt', 'attacker$ nmap -p- 10.0.2.5   (방화벽 너머 내부 서버)'],
     ['bad', '>> 1433/tcp open, 3389/tcp open (전부 통과)'],
     ['bad', '>> 방화벽을 우회하듯 내부 자원에 직접 도달'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 내부 침투','desc':'모든 트래픽을 허용하는 룰이라 방화벽이 사실상 무력화됩니다.'},
   'attack_secure': [
     ['cmt', '# 필요한 출발/목적/포트만 허용 후 동일 스캔'],
     ['prompt', 'attacker$ nmap -p- 10.0.2.5'],
     ['good', '>> 443/tcp open, 그 외 전부 filtered'],
     ['warn', '>> 허용 외 포트는 차단 — 내부 이동 봉쇄'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 최소 허용','desc':'필요한 통신만 구체적으로 허용하면 자유로운 침투가 막힙니다.'},
 },
 'S-11': {
   'easy': '안 쓰는 낡은 룰이 쌓이면, <b>오래전 손님에게 준 출입카드를 회수하지 않은</b> 것과 같습니다. 그 잊힌 카드로 누군가 슬쩍 들어옵니다. 주기적으로 정리하면 그런 빈틈이 사라집니다.',
   'attack_label': '공격자가 방치된 미사용 허용 룰의 경로로 침투한다',
   'attack_vuln': [
     ['cmt', '# 1년 넘게 방치된 미사용 허용 룰(rule 42)'],
     ['prompt', 'attacker$ nc 10.0.3.9 8080   (오래된 룰이 열어 둔 경로)'],
     ['bad', '>> 연결 성공 (잊힌 허용 룰이 아직 살아 있음)'],
     ['bad', '>> 방치된 룰의 빈틈으로 내부 진입'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 잔존 룰 악용','desc':'관리되지 않은 미사용 룰이 의도치 않은 통로로 남아 있습니다.'},
   'attack_secure': [
     ['cmt', '# 미사용 룰 제거(delete policy 42) 후 동일 시도'],
     ['prompt', 'attacker$ nc 10.0.3.9 8080'],
     ['good', '>> 연결 거부 (해당 허용 룰 제거됨)'],
     ['warn', '>> 불필요한 통로가 사라져 진입 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 통로 제거','desc':'미사용 룰을 정리하면 잊혀진 허용 경로가 사라집니다.'},
 },
 'S-12': {
   'easy': '기본 동작이 Allow면 <b>명단에 없는 사람도 일단 들여보내는</b> 안내소와 같습니다. 새 위협이 그냥 통과하죠. 기본을 Deny로 두면, 명단에 적힌 사람만 통과하고 나머지는 다 막힙니다.',
   'attack_label': '공격자가 어떤 룰에도 정의되지 않은 새 공격 트래픽을 흘려보낸다',
   'attack_vuln': [
     ['cmt', '# 명시 룰에 없는 신종 포트로 공격 트래픽 전송'],
     ['prompt', 'attacker$ ./exploit --port 31337 --target 10.0.2.7'],
     ['bad', '>> default ALLOW: 미정의 트래픽 그대로 통과'],
     ['bad', '>> 막는 룰이 없어 신종 공격 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 미정의 통과','desc':'기본 정책이 Allow라 명시 차단이 없는 모든 것이 통과합니다.'},
   'attack_secure': [
     ['cmt', '# 기본 정책 Deny 설정 후 동일 공격'],
     ['prompt', 'attacker$ ./exploit --port 31337 --target 10.0.2.7'],
     ['good', '>> default DENY: 미정의 트래픽 차단 + 로그 기록'],
     ['warn', '>> 명시 허용 외 전부 막혀 공격 실패'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 기본 Deny','desc':'기본을 Deny로 두면 정의되지 않은 새 위협이 곧장 막힙니다.'},
 },
 'S-13': {
   'easy': '시그니처가 오래되면 <b>지명수배 전단이 8개월 전 것</b>이라 새로 등장한 범인을 못 알아봅니다. 자동 업데이트로 전단을 최신으로 유지하면, 신종 공격도 바로 잡아냅니다.',
   'attack_label': '공격자가 알려진 CVE 익스플로잇으로 낡은 IPS를 통과한다',
   'attack_vuln': [
     ['cmt', '# 8개월 전 시그니처 — 최신 CVE 미탐지'],
     ['prompt', 'attacker$ ./exploit-CVE-2024-XXXX --target 10.0.2.10'],
     ['bad', '>> IPS 통과 (해당 시그니처 없음)'],
     ['bad', '>> 알려진 취약점 익스플로잇 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 미탐지 통과','desc':'시그니처가 낡아 이미 알려진 공격조차 탐지하지 못합니다.'},
   'attack_secure': [
     ['cmt', '# 시그니처 자동 업데이트 적용 후 동일 공격'],
     ['prompt', 'attacker$ ./exploit-CVE-2024-XXXX --target 10.0.2.10'],
     ['good', '>> IPS DROP: CVE-2024-XXXX 시그니처 일치'],
     ['warn', '>> 최신 시그니처로 탐지·차단됨'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 시그니처 탐지','desc':'시그니처를 최신으로 유지하면 알려진 공격이 곧장 잡힙니다.'},
 },
 'S-14': {
   'easy': '공격자는 위험한 짐을 <b>여러 봉투에 잘게 나눠</b> 검색대를 통과합니다. 재조합·정규화를 켜면, 장비가 조각을 다시 합쳐 원래 모습으로 검사하므로 우회가 통하지 않습니다.',
   'attack_label': '공격자가 페이로드를 잘게 단편화해 IPS 탐지를 우회한다',
   'attack_vuln': [
     ['cmt', '# 재조합 off — 페이로드를 단편화해 탐지 회피'],
     ['prompt', 'attacker$ fragroute -f frag.conf ./exploit 10.0.2.11'],
     ['bad', '>> 조각난 패킷이라 시그니처 미일치 — 통과'],
     ['bad', '>> 단편화 우회로 공격 페이로드 전달 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 탐지 우회','desc':'재조합이 꺼져 있어 잘게 나눈 페이로드가 검사를 빠져나갑니다.'},
   'attack_secure': [
     ['cmt', '# 재조합/정규화 on 후 동일 단편화 공격'],
     ['prompt', 'attacker$ fragroute -f frag.conf ./exploit 10.0.2.11'],
     ['good', '>> 조각 재조합 후 시그니처 일치 — DROP'],
     ['warn', '>> 정규화로 우회 시도 무력화'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 재조합 탐지','desc':'조각을 다시 합쳐 검사하므로 단편화 우회가 통하지 않습니다.'},
 },
 'S-15': {
   'easy': '장애 시 검사 없이 통과(fail-open)하면, <b>경비원이 쓰러지자 정문을 활짝 열어</b> 두는 셈입니다. 이중화와 안전 차단(fail-secure)을 두면, 한쪽이 멈춰도 다른 경비가 계속 검사하거나 문이 잠긴 채 유지됩니다.',
   'attack_label': '공격자가 장비 장애를 유발해 무검사 통과 상태를 악용한다',
   'attack_vuln': [
     ['cmt', '# 과부하로 인라인 장비를 장애 상태로 유도'],
     ['prompt', 'attacker$ ./flood --target secgw ; ./exploit 10.0.2.12'],
     ['bad', '>> fail-mode OPEN: 장애 중 트래픽 무검사 통과'],
     ['bad', '>> 검사 없이 공격 트래픽 그대로 전달'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 무검사 통과','desc':'fail-open이라 장비가 멈춘 순간 보안 검사가 사라집니다.'},
   'attack_secure': [
     ['cmt', '# HA 이중화 + fail-secure 설정 후 동일 시도'],
     ['prompt', 'attacker$ ./flood --target secgw ; ./exploit 10.0.2.12'],
     ['good', '>> passive 장비로 절체, 검사 지속'],
     ['warn', '>> 장애 시에도 fail-close로 보안 유지'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 보안 유지','desc':'이중화와 fail-secure로 장애 중에도 검사가 끊기지 않습니다.'},
 },
 'S-16': {
   'easy': '구버전 펌웨어는 <b>약점이 신문에 다 난 낡은 자물쇠</b>입니다. 공격자는 공개된 방법대로 따고 들어옵니다. 권고 버전으로 올리면 그 약점이 메워져 같은 수법이 통하지 않습니다.',
   'attack_label': '공격자가 알려진 펌웨어 CVE로 원격 코드를 실행한다',
   'attack_vuln': [
     ['cmt', '# EOL 펌웨어 6.0.1 — 공개된 RCE 취약점 보유'],
     ['prompt', 'attacker$ ./fw-rce --cve 2023-YYYY --target secgw'],
     ['bad', '>> Shell: secgw# (원격 코드 실행 성공)'],
     ['bad', '>> 패치 안 된 펌웨어로 장비 완전 장악'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 원격 코드 실행','desc':'구버전 펌웨어의 알려진 취약점으로 장비가 통째로 장악됩니다.'},
   'attack_secure': [
     ['cmt', '# 권고 버전 7.4.x 업그레이드 후 동일 익스플로잇'],
     ['prompt', 'attacker$ ./fw-rce --cve 2023-YYYY --target secgw'],
     ['good', '>> Exploit failed (해당 취약점 패치됨)'],
     ['warn', '>> 최신 펌웨어라 공개 익스플로잇 무효'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 패치 적용','desc':'권고 보안 버전으로 올리면 알려진 펌웨어 공격이 통하지 않습니다.'},
 },
 'S-17': {
   'easy': '로그가 장비 안에만 있으면, 침입자가 <b>현관 CCTV를 떼어 가</b> 흔적을 지웁니다. 중앙 로그 서버로 즉시 복사해 두면, 장비를 건드려도 사고 기록이 멀리서 안전하게 남습니다.',
   'attack_label': '공격자가 침입 후 장비 로컬 로그를 지워 흔적을 없앤다',
   'attack_vuln': [
     ['cmt', '# 중앙 전송 없음 — 로컬 로그만 존재'],
     ['prompt', 'attacker$ secgw# clear log all'],
     ['bad', '>> 로컬 로그 삭제 완료 (사본 없음)'],
     ['bad', '>> 침해 흔적이 통째로 사라져 분석 불가'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 흔적 삭제','desc':'중앙 전송이 없어 장비 로그를 지우면 증거가 함께 사라집니다.'},
   'attack_secure': [
     ['cmt', '# 중앙 Syslog 전송 설정 후 동일하게 로그 삭제'],
     ['prompt', 'attacker$ secgw# clear log all'],
     ['good', '>> 로컬은 지워도 Syslog 서버에 이미 사본 존재'],
     ['warn', '>> 중앙 로그로 침해 행위 그대로 보존'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 로그 보존','desc':'중앙으로 즉시 전송하면 장비 로그를 지워도 기록이 남습니다.'},
 },
 'S-18': {
   'easy': '장비 시계가 안 맞으면 <b>CCTV마다 시각이 제각각</b>이라 사건 순서를 맞출 수 없습니다. NTP로 시각을 통일하면, 여러 장비 로그를 시간순으로 정확히 꿰어 분석할 수 있습니다.',
   'attack_label': '공격자가 시각 불일치를 틈타 사고 타임라인 분석을 방해한다',
   'attack_vuln': [
     ['cmt', '# NTP 미동기화 — 장비 시각이 제각각'],
     ['prompt', 'analyst$ correlate secgw.log fw.log ids.log'],
     ['bad', '>> 장비별 시각 12분 차이 — 사건 순서 뒤죽박죽'],
     ['bad', '>> 타임라인 재구성 실패로 공격 경로 추적 불가'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 분석 방해','desc':'시각이 어긋나 여러 장비 로그를 시간순으로 맞출 수 없습니다.'},
   'attack_secure': [
     ['cmt', '# NTP 동기화 적용 후 동일 상관분석'],
     ['prompt', 'analyst$ correlate secgw.log fw.log ids.log'],
     ['good', '>> 전 장비 시각 일치 — 사건 순서 정확히 정렬'],
     ['warn', '>> 타임라인 재구성으로 공격 경로 추적 성공'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 정확한 추적','desc':'NTP로 시각을 맞추면 로그 타임라인을 정확히 재구성합니다.'},
 },
 'S-19': {
   'easy': '로그 보관이 7일뿐이고 무결성 보호가 없으면, <b>일주일 만에 지워지는 CCTV에 편집까지 가능한</b> 셈입니다. 길게 보관하고 해시로 봉인하면, 나중에 들춰봐도 위변조가 바로 드러납니다.',
   'attack_label': '공격자가 보관 만료를 노리거나 로그를 위변조한다',
   'attack_vuln': [
     ['cmt', '# 보관 7일 + 무결성 off — 천천히 침투 후 흔적 변조'],
     ['prompt', 'attacker$ edit secgw.log  (자신의 접속 라인 삭제)'],
     ['bad', '>> 무결성 검증 없어 변조 탐지 안 됨'],
     ['bad', '>> 8일 전 침입 로그는 이미 보관 만료로 소실'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 로그 위변조','desc':'보관이 짧고 무결성 보호가 없어 증거가 사라지거나 조작됩니다.'},
   'attack_secure': [
     ['cmt', '# 보관 180일 + 해시 무결성 적용 후 동일 변조'],
     ['prompt', 'attacker$ edit secgw.log'],
     ['good', '>> 해시 불일치 — 위변조 즉시 탐지'],
     ['warn', '>> 180일 보관이라 과거 침입 기록도 보존됨'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 무결성 보장','desc':'충분히 보관하고 해시로 봉인하면 위변조가 곧장 드러납니다.'},
 },
 'S-20': {
   'easy': '관리 접속·설정 변경 감사가 없으면, <b>누가 금고 비밀번호를 바꿨는지 아무도 모르는</b> 상태입니다. 감사·알림을 켜면, 누군가 손대는 순간 기록되고 담당자에게 바로 통보됩니다.',
   'attack_label': '공격자가 감사 없는 틈을 타 몰래 정책을 변경한다',
   'attack_vuln': [
     ['cmt', '# admin-audit off — 변경이 기록도 알림도 안 됨'],
     ['prompt', 'attacker$ secgw# set policy 99 any any allow'],
     ['bad', '>> 변경 적용 (감사 로그 없음, 알림 없음)'],
     ['bad', '>> 백도어 룰을 추가해도 아무도 인지 못함'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 은밀한 변경','desc':'감사·알림이 없어 비인가 설정 변경을 탐지할 수 없습니다.'},
   'attack_secure': [
     ['cmt', '# admin-audit + 변경 알림 설정 후 동일 변경'],
     ['prompt', 'attacker$ secgw# set policy 99 any any allow'],
     ['good', '>> 감사 로그 기록 + SIEM 즉시 알림 발송'],
     ['warn', '>> 비인가 변경이 곧바로 탐지·통보됨'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 변경 탐지','desc':'감사와 알림을 켜면 몰래 한 설정 변경이 바로 드러납니다.'},
 },
 'S-21': {
   'easy': '설정 백업이 없으면 랜섬웨어나 오설정으로 장비가 망가졌을 때 <b>복사본 없는 원본을 잃은</b> 것과 같습니다. 정기 백업을 따로 보관하면, 사고가 나도 마지막 정상 상태로 빠르게 되돌립니다.',
   'attack_label': '공격자가 장비 설정을 파괴해 운영을 마비시킨다',
   'attack_vuln': [
     ['cmt', '# 백업 한 번도 없음 — 설정 파괴 후 복구 불가'],
     ['prompt', 'attacker$ secgw# factory-reset ; corrupt config'],
     ['bad', '>> 전체 설정 소실 (복원할 백업 없음)'],
     ['bad', '>> 정책 재구축까지 장기 마비'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 운영 마비','desc':'백업이 없어 설정이 파괴되면 신속한 복구가 불가능합니다.'},
   'attack_secure': [
     ['cmt', '# 정기 백업 + 분리 보관 상태에서 동일 파괴'],
     ['prompt', 'attacker$ secgw# factory-reset ; corrupt config'],
     ['good', '>> 분리 보관된 백업에서 설정 즉시 복원'],
     ['warn', '>> 마지막 정상 상태로 신속 복구'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 신속 복구','desc':'정기 백업을 분리 보관하면 파괴돼도 곧바로 되돌립니다.'},
 },
 'S-22': {
   'easy': '안 쓰는 서비스를 켜 두면 <b>잠그지 않은 옆문·뒷문</b>이 늘어나는 것과 같아 도둑이 노릴 문이 많아집니다. 필요한 문만 남기고 나머지는 잠그면, 공격할 곳 자체가 줄어듭니다.',
   'attack_label': '공격자가 불필요하게 켜진 데몬을 찾아 공격한다',
   'attack_vuln': [
     ['cmt', '# 불필요한 서비스가 다수 구동 중'],
     ['prompt', 'attacker$ nmap -sV secgw'],
     ['bad', '>> 67/udp dhcp, 161/udp snmp, 80/http ... 노출'],
     ['bad', '>> 쓰지 않는 dhcp 데몬 취약점으로 침투 성공'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 공격면 악용','desc':'불필요한 서비스가 켜져 있어 공격할 진입점이 많습니다.'},
   'attack_secure': [
     ['cmt', '# 불필요 서비스 비활성화 후 동일 스캔'],
     ['prompt', 'attacker$ nmap -sV secgw'],
     ['good', '>> 443/https only (그 외 전부 닫힘)'],
     ['warn', '>> 노출 데몬이 없어 공격 진입점 사라짐'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 공격면 축소','desc':'쓰지 않는 서비스를 끄면 노릴 진입점 자체가 사라집니다.'},
 },
 'S-23': {
   'easy': '경고 배너는 <b>"관계자 외 출입금지" 안내판</b>과 같습니다. 보안을 직접 막진 않지만, 비인가 접근임을 분명히 고지해 법적 대응의 근거가 됩니다. 배너가 없으면 그 고지가 빠진 셈입니다.',
   'attack_label': '공격자가 무단 접속 시 사전 경고 고지 없이 접근한다',
   'attack_vuln': [
     ['cmt', '# 로그인 배너 없음 — 사전 경고 고지 누락'],
     ['prompt', 'attacker$ ssh admin@secgw'],
     ['bad', '>> (경고 문구 없이 곧장 로그인 프롬프트)'],
     ['bad', '>> 비인가 접근 경고 고지가 빠져 법적 근거 미흡'],
   ],
   'outcome_vuln': {'emoji':'🔓','title':'공격 성공 — 고지 누락','desc':'경고 배너가 없어 무단 접근에 대한 사전 고지가 빠집니다.'},
   'attack_secure': [
     ['cmt', '# 경고 배너 설정 후 동일 접속'],
     ['prompt', 'attacker$ ssh admin@secgw'],
     ['good', '>> "Authorized access only" 경고 배너 표시'],
     ['warn', '>> 비인가 접근임을 사전 고지 — 법적 근거 확보'],
   ],
   'outcome_secure': {'emoji':'🛡️','title':'공격 차단 — 경고 고지','desc':'접속 시 경고 배너를 표시하면 비인가 접근을 명확히 고지합니다.'},
 },
}
