# -*- coding: utf-8 -*-
# 금융 단말/모바일 보호 시뮬레이터 스펙 (금융보안원 제2026-1호)
SPECS = [
    {
        'file': '07_fin-device-storage.html',
        'title': '단말기 내 중요정보 저장 방지',
        'icon': '📱',
        'target': '모바일 금융앱 로컬 저장소',
        'risk': '5',
        'item_code': 'MOB-SER 단말 내 중요정보 저장',
        'attack_panel_title': '단말 로컬 저장소 추출',
        'scenario_html': '금융앱이 <b>비밀번호·계좌번호·인증토큰</b>을 평문으로 SharedPreferences/파일/SQLite에 저장하면, 단말 탈취나 백업 추출만으로 중요정보가 그대로 유출됩니다.',
        'attack_name': '단말 백업·run-as 추출',
        'attack_sub': 'adb backup / run-as로 평문 prefs 덤프',
        'normal_req': '// SharedPreferences (auth.xml) 저장 상태\n<map>\n  <string name="user_pw">******</string>\n  <string name="account">****-**-******</string>\n  <string name="token">***</string>\n</map>',
        'attack_req': '$ adb backup -f data.ab com.bank.app\n$ adb shell run-as com.bank.app \\\n    cat shared_prefs/auth.xml\n\n<map>\n  <string name="user_pw">P@ssw0rd!</string>\n  <string name="account">110-23-456789</string>\n  <string name="token">eyJhbGciOi...</string>\n</map>',
        'vuln_logs_js': "addLog('[ADB] run-as com.bank.app 진입','warn'); addLog('[FILE] shared_prefs/auth.xml 평문 읽기','warn'); addLog('[LEAK] 비밀번호·계좌·토큰 평문 추출','error');",
        'breach_html': '<strong>🚨 평문 저장정보 유출</strong><br>백업 추출만으로 <b>비밀번호·계좌번호·인증토큰</b>이 평문 그대로 노출되었습니다.',
        'violations': [
            '평가기준 [전자금융] 단말 내 중요정보 저장(위험도 5) 위반',
            '전자금융감독규정 제37조의2 단말기 정보보호 미흡',
            '개인정보보호법 제29조 안전성 확보조치(암호화 저장) 위반',
        ],
        'defense_intro': '중요정보는 평문 저장을 금지하고 <strong>EncryptedSharedPreferences</strong>와 하드웨어 <strong>Keystore</strong> 기반으로 암호화 저장해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 평문 SharedPreferences 저장\nSharedPreferences prefs =\n    context.getSharedPreferences("auth", MODE_PRIVATE);\nprefs.edit()\n    .putString("user_pw", password)\n    .putString("token", token)\n    .apply();',
        'secure_hint': '// [안전] Keystore 기반 EncryptedSharedPreferences\nMasterKey key = new MasterKey.Builder(context)\n    .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)\n    .build();\nSharedPreferences prefs = EncryptedSharedPreferences.create(\n    context, "auth", key,\n    EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,\n    EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM);\nprefs.edit()\n    .putString("token", token)\n    .apply();\n// 가능하면 비밀번호 자체를 저장하지 않음',
        'checks': [['EncryptedSharedPreferences'], ['MasterKey', 'Keystore', 'KeyScheme']],
        'success_msg': 'EncryptedSharedPreferences와 Keystore 암호화로 평문 추출이 차단됩니다.',
        'fail_msg': 'EncryptedSharedPreferences/Keystore 기반 암호화 저장으로 전환해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>모바일 단말 보호 &gt; <b>단말 내 중요정보 저장 방지</b><h4>2. 위험 분석</h4><ul><li>단말 탈취·백업 추출 시 평문 유출</li><li>run-as·루팅 단말에서 prefs/SQLite 직접 열람</li></ul><h4>3. 조치 방법</h4><ul><li>중요정보 평문 저장 금지, 불필요 시 미저장</li><li><b>EncryptedSharedPreferences</b>·하드웨어 <b>Keystore</b> 암호화 적용</li><li>allowBackup=false 설정</li></ul>',
        'easy': '비밀번호를 <b>금고가 아닌 메모지</b>에 적어 서랍에 둔 격이라, 서랍(단말)을 통째로 가져가면 다 읽힙니다. 반드시 <b>금고(암호화 저장소)</b>에 넣어야 합니다.',
    },
    {
        'file': '07_fin-memory-protection.html',
        'title': '메모리 내 중요정보 노출 방지',
        'icon': '🧠',
        'target': '거래 처리 중 프로세스 메모리',
        'risk': '4',
        'item_code': 'MOB-SER 메모리 노출 방지',
        'attack_panel_title': '런타임 메모리 덤프',
        'scenario_html': '거래 처리 중 <b>비밀번호·세션키</b>를 String으로 두고 사용 후 비우지 않으면, 메모리에 평문 잔존하여 <b>Frida·gdb 덤프</b>로 그대로 추출됩니다.',
        'attack_name': 'Frida 메모리 덤프',
        'attack_sub': '런타임 프로세스 메모리에서 평문 비밀번호 스캔',
        'normal_req': '// 거래 중 메모리 상태 (힙)\npassword = "********"   (String, 잔존)\nsessionKey = "********" (String, 잔존)',
        'attack_req': '$ frida -U -n com.bank.app -e \\\n    "Memory.scan(...)"\n\n[DUMP 0x7f12a0] 70 61 73 73 77 30 72 64\n  -> ascii: "P@ssw0rd!"\n[DUMP 0x7f1340] 73 65 73 73 3a 61 39 66\n  -> ascii: "sess:a9f3c1..."',
        'vuln_logs_js': "addLog('[FRIDA] com.bank.app 프로세스 attach','warn'); addLog('[MEM] 힙 스캔 중 평문 문자열 탐지','warn'); addLog('[LEAK] 비밀번호·세션키 메모리 추출','error');",
        'breach_html': '<strong>🚨 메모리 평문 잔존</strong><br>거래 후에도 <b>비밀번호·세션키</b>가 힙에 남아 메모리 덤프로 추출되었습니다.',
        'violations': [
            '평가기준 [전자금융] 메모리 내 중요정보 노출(위험도 4) 위반',
            '전자금융감독규정 제37조의2 단말기 정보보호 미흡',
            '개인정보보호법 제29조 안전성 확보조치 위반',
        ],
        'defense_intro': '비밀번호·세션키는 불변 String 대신 <strong>char[]</strong>로 다루고, 사용 직후 <strong>fill(</strong>)로 즉시 덮어써 메모리 잔존을 제거해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] String 평문 잔존, 비우지 않음\npublic void login(PinView view) {\n    String password = view.getText();\n    auth.verify(password);\n    // password 그대로 힙에 잔존\n}',
        'secure_hint': '// [안전] char[] 사용 후 즉시 소거\npublic void login(PinView view) {\n    char[] password = view.getCharArray();\n    try {\n        auth.verify(password);\n    } finally {\n        java.util.Arrays.fill(password, \'\\0\');\n    }\n}',
        'checks': [['char[]'], ['fill(']],
        'success_msg': 'char[] 사용 후 fill()로 즉시 소거하여 메모리 잔존이 제거됩니다.',
        'fail_msg': '중요정보를 char[]로 다루고 사용 후 fill()로 소거해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>모바일 단말 보호 &gt; <b>메모리 내 중요정보 노출 방지</b><h4>2. 위험 분석</h4><ul><li>불변 String은 GC 전까지 평문 잔존</li><li>Frida·gdb 메모리 덤프로 비밀번호·세션키 추출</li></ul><h4>3. 조치 방법</h4><ul><li>중요정보를 <b>char[]</b>로 처리</li><li>사용 직후 <b>Arrays.fill()</b>로 소거</li><li>가능 시 보안 키 저장소 활용</li></ul>',
        'easy': '비밀번호를 화이트보드에 썼다가 <b>지우지 않고</b> 자리를 뜨면 누구나 읽습니다. 다 쓰면 <b>즉시 깨끗이 지워야</b> 사진(메모리 덤프)에 안 찍힙니다.',
    },
    {
        'file': '07_fin-screen-protection.html',
        'title': '화면 내 중요정보 평문노출·캡처 방지',
        'icon': '🖼️',
        'target': '거래내역·계좌 표시 화면',
        'risk': '4',
        'item_code': 'MOB-SER 화면 노출 방지',
        'attack_panel_title': '화면 캡처·미리보기 추출',
        'scenario_html': '계좌번호·주민번호가 <b>평문</b>으로 화면에 표시되고 <b>스크린샷·화면녹화·최근앱 미리보기</b>가 허용되면, 캡처 이미지로 중요정보가 그대로 유출됩니다.',
        'attack_name': '스크린샷·최근앱 미리보기 탈취',
        'attack_sub': '스크린샷/화면녹화 및 최근앱 썸네일 캡처',
        'normal_req': '// 화면 표시 상태\n계좌번호: 110-234-567890\n주민번호: 900101-1234567\n[스크린샷 허용=YES, 최근앱 미리보기=노출]',
        'attack_req': '$ adb shell screencap /sdcard/s.png\n$ adb pull /sdcard/s.png\n\n// 최근앱 전환 시 썸네일 캐시\n/data/system_ce/.../recent_images/\n  -> 계좌·주민번호 평문 노출',
        'vuln_logs_js': "addLog('[CAPTURE] screencap 화면 캡처 성공','warn'); addLog('[RECENT] 최근앱 미리보기 썸네일 노출','warn'); addLog('[LEAK] 계좌·주민번호 평문 캡처','error');",
        'breach_html': '<strong>🚨 화면 정보 캡처</strong><br>스크린샷과 최근앱 미리보기로 <b>계좌번호·주민번호</b>가 평문 그대로 유출되었습니다.',
        'violations': [
            '평가기준 [전자금융] 화면 내 중요정보 노출(위험도 4) 위반',
            '전자금융감독규정 제37조의2 단말기 정보보호 미흡',
            '개인정보보호법 제24조의2 주민등록번호 처리 제한 위반',
        ],
        'defense_intro': '중요정보는 마스킹 표시하고, 민감 화면에는 <strong>FLAG_SECURE</strong>를 설정해 스크린샷·화면녹화·최근앱 미리보기 캡처를 차단해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 캡처 차단 없음, 평문 표시\n@Override\nprotected void onCreate(Bundle b) {\n    super.onCreate(b);\n    setContentView(R.layout.account);\n    accountView.setText(account); // 110-234-567890\n}',
        'secure_hint': '// [안전] FLAG_SECURE로 캡처 차단 + 마스킹\n@Override\nprotected void onCreate(Bundle b) {\n    super.onCreate(b);\n    getWindow().setFlags(\n        WindowManager.LayoutParams.FLAG_SECURE,\n        WindowManager.LayoutParams.FLAG_SECURE);\n    setContentView(R.layout.account);\n    accountView.setText(mask(account)); // 110-***-**7890\n}',
        'checks': [['FLAG_SECURE'], ['mask(', 'setFlags']],
        'success_msg': 'FLAG_SECURE로 캡처가 차단되고 마스킹으로 평문 노출이 제거됩니다.',
        'fail_msg': '민감 화면에 FLAG_SECURE를 설정하고 중요정보를 마스킹 표시해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>모바일 단말 보호 &gt; <b>화면 내 중요정보 노출·캡처 방지</b><h4>2. 위험 분석</h4><ul><li>스크린샷·화면녹화로 평문 캡처</li><li>최근앱 미리보기 썸네일 노출</li></ul><h4>3. 조치 방법</h4><ul><li>민감 화면에 <b>FLAG_SECURE</b> 설정</li><li>계좌·주민번호 등 <b>마스킹</b> 표시</li></ul>',
        'easy': '비밀번호를 화면에 띄워두면 옆 사람이 <b>어깨너머로 사진</b>을 찍는 것과 같습니다. 가림막(마스킹)을 치고 <b>사진 촬영 자체를 막아야</b> 합니다.',
    },
    {
        'file': '07_fin-source-info-leak.html',
        'title': '앱 소스/디버그 로그 운영정보 노출',
        'icon': '🔍',
        'target': '배포 APK 및 운영 빌드 로그',
        'risk': '4',
        'item_code': 'MOB-SER 소스/로그 정보 노출',
        'attack_panel_title': 'APK 디컴파일·로그 수집',
        'scenario_html': 'APK를 <b>jadx·apktool</b>로 디컴파일하면 하드코딩된 <b>API키·서버URL·주석</b>이 드러나고, 운영 빌드에 남은 <b>디버그 로그</b>로 중요정보가 단말 로그에 출력됩니다.',
        'attack_name': 'jadx 디컴파일 + logcat 수집',
        'attack_sub': '소스 내 비밀정보 추출 및 운영 디버그 로그 수집',
        'normal_req': '// 배포 APK 내부 (디컴파일 전)\napp-release.apk\n  classes.dex / resources.arsc\n  (난독화·로그 제거 여부 점검 대상)',
        'attack_req': '$ jadx -d out app-release.apk\n$ grep -r "API_KEY\\|http" out/\n\nString API_KEY = "sk_live_9af3c1...";\nString BASE = "https://prod-pay.bank.kr";\n// TODO: 운영 DB 계정 admin/pw1234\n\n$ adb logcat | grep BankApp\nD/BankApp: login token=eyJhbGci...',
        'vuln_logs_js': "addLog('[JADX] app-release.apk 디컴파일 성공','warn'); addLog('[SRC] API키·서버URL·주석 하드코딩 노출','warn'); addLog('[LOGCAT] 운영 디버그 로그에서 토큰 추출','error');",
        'breach_html': '<strong>🚨 소스·로그 정보 노출</strong><br>디컴파일로 <b>API키·서버URL</b>이, 운영 로그로 <b>인증토큰</b>이 그대로 노출되었습니다.',
        'violations': [
            '평가기준 [전자금융] 앱 소스/로그 운영정보 노출(위험도 4) 위반',
            '전자금융감독규정 제37조의2 단말기 정보보호 미흡',
            '개인정보보호법 제29조 안전성 확보조치(로그 노출 방지) 위반',
        ],
        'defense_intro': '비밀정보 하드코딩과 운영 로그 출력을 제거하고, <strong>BuildConfig.DEBUG</strong>·<strong>isLoggable</strong> 가드로 운영 빌드에서 디버그 로그를 차단해야 합니다. 아래 코드를 보완하세요.',
        'vuln_code': '// [취약] 하드코딩 + 무조건 로그 출력\nString apiKey = "sk_live_9af3c1...";\nString token = login(apiKey);\nLog.d("BankApp", "login token=" + token);',
        'secure_hint': '// [안전] 보안 저장소 사용 + 운영 로그 차단\nString apiKey = secureConfig.getApiKey(); // 하드코딩 제거\nString token = login(apiKey);\nif (BuildConfig.DEBUG && Log.isLoggable("BankApp", Log.DEBUG)) {\n    Log.d("BankApp", "login ok"); // 중요정보 미출력\n}',
        'checks': [['BuildConfig.DEBUG'], ['isLoggable']],
        'success_msg': 'BuildConfig.DEBUG·isLoggable 가드로 운영 빌드 로그가 차단되고 비밀정보가 제거됩니다.',
        'fail_msg': 'BuildConfig.DEBUG와 isLoggable 가드로 운영 로그를 차단하고 하드코딩을 제거해야 합니다.',
        'kisa_ref': '<h4>1. 점검 항목</h4>모바일 단말 보호 &gt; <b>앱 소스/디버그 로그 운영정보 노출</b><h4>2. 위험 분석</h4><ul><li>jadx·apktool 디컴파일로 API키·서버URL·주석 노출</li><li>운영 빌드 디버그 로그로 토큰 유출</li></ul><h4>3. 조치 방법</h4><ul><li>비밀정보 하드코딩 금지, 보안 저장소 사용</li><li><b>BuildConfig.DEBUG</b>·<b>isLoggable</b> 로그 가드</li><li>코드 난독화 및 주석 제거</li></ul>',
        'easy': '앱 설치파일은 <b>분해되는 장난감</b>이라, 안에 적어둔 열쇠(API키)와 메모(주석)가 다 보입니다. 비밀은 <b>겉에 적지 말고</b> 운영용에선 일기(로그)도 남기지 말아야 합니다.',
    },
]
